export type SaleActorKind="HUMAN"|"SYSTEM"|"AI"|"EXTERNAL_PROVIDER";
export interface SaleActor {kind:SaleActorKind;id?:string;roles?:string[]}
export interface SaleCommand<E extends string>{event:E;actor:SaleActor;idempotencyKey:string;guards?:Record<string,boolean>;occurredAt?:string}
export interface SaleEdge<S extends string,E extends string>{from:S;event:E;to:S;humanOnly?:boolean;guard?:string}
export interface SaleMachine<S extends string,E extends string>{name:string;initial:S;terminal:S[];edges:SaleEdge<S,E>[]}
export function applySaleTransition<S extends string,E extends string>(machine:SaleMachine<S,E>,state:S,command:SaleCommand<E>){const audit={machine:machine.name,event:command.event,actorKind:command.actor.kind,actorId:command.actor.id,idempotencyKey:command.idempotencyKey,occurredAt:command.occurredAt??new Date().toISOString()};if(!command.idempotencyKey.trim())return{allowed:false,state,previousState:state,reasonCodes:["IDEMPOTENCY_KEY_REQUIRED"],audit};const edge=machine.edges.find(x=>x.from===state&&x.event===command.event);if(!edge)return{allowed:false,state,previousState:state,reasonCodes:["ILLEGAL_STATE_TRANSITION"],audit};if(edge.humanOnly&&(command.actor.kind!=="HUMAN"||!command.actor.id?.trim()))return{allowed:false,state,previousState:state,reasonCodes:["HUMAN_ACTOR_REQUIRED"],audit};if(edge.guard&&command.guards?.[edge.guard]!==true)return{allowed:false,state,previousState:state,reasonCodes:["GUARD_NOT_SATISFIED:"+edge.guard],audit};return{allowed:true,state:edge.to,previousState:state,reasonCodes:[],audit}}
export type SaleListingState="DRAFT"|"IN_REVIEW"|"READY"|"PUBLISHED"|"PAUSED"|"ARCHIVED";export type SaleListingEvent="SUBMIT"|"APPROVE"|"PUBLISH"|"PAUSE"|"RESUME"|"INVALIDATE"|"ARCHIVE";
export const saleListingMachine:SaleMachine<SaleListingState,SaleListingEvent>={name:"SALE_LISTING",initial:"DRAFT",terminal:["ARCHIVED"],edges:[{from:"DRAFT",event:"SUBMIT",to:"IN_REVIEW"},{from:"IN_REVIEW",event:"APPROVE",to:"READY",humanOnly:true,guard:"UPSTREAM_CURRENT"},{from:"READY",event:"PUBLISH",to:"PUBLISHED",humanOnly:true,guard:"PUBLICATION_GATE_READY"},{from:"PUBLISHED",event:"PAUSE",to:"PAUSED",humanOnly:true},{from:"PAUSED",event:"RESUME",to:"PUBLISHED",humanOnly:true,guard:"PUBLICATION_GATE_READY"},{from:"PUBLISHED",event:"INVALIDATE",to:"IN_REVIEW"},{from:"PAUSED",event:"ARCHIVE",to:"ARCHIVED",humanOnly:true}]};
export type SaleLeadState="NEW"|"CONSENTED"|"QUALIFIED"|"VISIT_READY"|"CLOSED";export type SaleLeadEvent="CONSENT"|"QUALIFY"|"READY_VISIT"|"CLOSE";
export const saleLeadMachine:SaleMachine<SaleLeadState,SaleLeadEvent>={name:"SALE_LEAD",initial:"NEW",terminal:["CLOSED"],edges:[{from:"NEW",event:"CONSENT",to:"CONSENTED",guard:"CONSENT_VALID"},{from:"CONSENTED",event:"QUALIFY",to:"QUALIFIED",humanOnly:true},{from:"QUALIFIED",event:"READY_VISIT",to:"VISIT_READY",humanOnly:true},{from:"NEW",event:"CLOSE",to:"CLOSED",humanOnly:true},{from:"CONSENTED",event:"CLOSE",to:"CLOSED",humanOnly:true},{from:"QUALIFIED",event:"CLOSE",to:"CLOSED",humanOnly:true},{from:"VISIT_READY",event:"CLOSE",to:"CLOSED",humanOnly:true}]};
export type SaleVisitState="PLANNED"|"CONFIRMED"|"COMPLETED"|"FOLLOWED_UP"|"CANCELLED";export type SaleVisitEvent="CONFIRM"|"COMPLETE"|"FOLLOW_UP"|"CANCEL";
export const saleVisitMachine:SaleMachine<SaleVisitState,SaleVisitEvent>={name:"SALE_VISIT",initial:"PLANNED",terminal:["FOLLOWED_UP","CANCELLED"],edges:[{from:"PLANNED",event:"CONFIRM",to:"CONFIRMED",guard:"ACCESS_AUTHORIZED"},{from:"CONFIRMED",event:"COMPLETE",to:"COMPLETED",humanOnly:true},{from:"COMPLETED",event:"FOLLOW_UP",to:"FOLLOWED_UP",humanOnly:true},{from:"PLANNED",event:"CANCEL",to:"CANCELLED"},{from:"CONFIRMED",event:"CANCEL",to:"CANCELLED"}]};
export type SaleNegotiationState="OPEN"|"SCENARIO_READY"|"HUMAN_DECISION"|"OFFER_READY"|"CLOSED";export type SaleNegotiationEvent="PREPARE"|"DECIDE"|"READY_OFFER"|"CLOSE";
export const saleNegotiationMachine:SaleMachine<SaleNegotiationState,SaleNegotiationEvent>={name:"SALE_NEGOTIATION",initial:"OPEN",terminal:["CLOSED"],edges:[{from:"OPEN",event:"PREPARE",to:"SCENARIO_READY"},{from:"SCENARIO_READY",event:"DECIDE",to:"HUMAN_DECISION",humanOnly:true},{from:"HUMAN_DECISION",event:"READY_OFFER",to:"OFFER_READY",humanOnly:true,guard:"OWNER_LIMITS_RESPECTED"},{from:"OFFER_READY",event:"CLOSE",to:"CLOSED",humanOnly:true}]};
export type SaleOfferState="DRAFT"|"REVIEWED"|"SUBMITTED"|"ACCEPTED"|"REJECTED"|"EXPIRED"|"WITHDRAWN";export type SaleOfferEvent="REVIEW"|"SUBMIT"|"ACCEPT"|"REJECT"|"EXPIRE"|"WITHDRAW";
export const saleOfferMachine:SaleMachine<SaleOfferState,SaleOfferEvent>={name:"SALE_OFFER",initial:"DRAFT",terminal:["ACCEPTED","REJECTED","EXPIRED","WITHDRAWN"],edges:[{from:"DRAFT",event:"REVIEW",to:"REVIEWED",humanOnly:true,guard:"OFFER_PREFLIGHT_READY"},{from:"REVIEWED",event:"SUBMIT",to:"SUBMITTED",humanOnly:true},{from:"SUBMITTED",event:"ACCEPT",to:"ACCEPTED",humanOnly:true,guard:"ACCEPTANCE_EVIDENCE_READY"},{from:"SUBMITTED",event:"REJECT",to:"REJECTED",humanOnly:true},{from:"SUBMITTED",event:"EXPIRE",to:"EXPIRED"},{from:"DRAFT",event:"WITHDRAW",to:"WITHDRAWN",humanOnly:true},{from:"REVIEWED",event:"WITHDRAW",to:"WITHDRAWN",humanOnly:true},{from:"SUBMITTED",event:"WITHDRAW",to:"WITHDRAWN",humanOnly:true}]};
export type SalePreliminaryState="NOT_REQUIRED"|"DRAFT"|"PROFESSIONAL_REVIEW"|"READY"|"SIGNED"|"COMPLETED";export type SalePreliminaryEvent="MARK_NOT_REQUIRED"|"START_REVIEW"|"APPROVE"|"SIGN"|"COMPLETE";
export const salePreliminaryMachine:SaleMachine<SalePreliminaryState,SalePreliminaryEvent>={name:"SALE_PRELIMINARY",initial:"DRAFT",terminal:["NOT_REQUIRED","COMPLETED"],edges:[{from:"DRAFT",event:"MARK_NOT_REQUIRED",to:"NOT_REQUIRED",humanOnly:true,guard:"NOT_REQUIRED_APPROVED"},{from:"DRAFT",event:"START_REVIEW",to:"PROFESSIONAL_REVIEW"},{from:"PROFESSIONAL_REVIEW",event:"APPROVE",to:"READY",humanOnly:true,guard:"PROFESSIONAL_REVIEW_CURRENT"},{from:"READY",event:"SIGN",to:"SIGNED",humanOnly:true,guard:"SIGNATURES_COMPLETE"},{from:"SIGNED",event:"COMPLETE",to:"COMPLETED",humanOnly:true,guard:"REGISTRATION_TRACKED"}]};
export type SaleClosingState="PREPARING"|"NOTARY_REVIEW"|"READY"|"SIGNED"|"COMPLETED";export type SaleClosingEvent="SEND_NOTARY"|"APPROVE"|"SIGN"|"COMPLETE";
export const saleClosingMachine:SaleMachine<SaleClosingState,SaleClosingEvent>={name:"SALE_CLOSING",initial:"PREPARING",terminal:["COMPLETED"],edges:[{from:"PREPARING",event:"SEND_NOTARY",to:"NOTARY_REVIEW"},{from:"NOTARY_REVIEW",event:"APPROVE",to:"READY",humanOnly:true,guard:"NOTARY_CHECKLIST_READY"},{from:"READY",event:"SIGN",to:"SIGNED",humanOnly:true,guard:"CLOSING_GATE_READY"},{from:"SIGNED",event:"COMPLETE",to:"COMPLETED",humanOnly:true,guard:"FINAL_EVIDENCE_READY"}]};
export type SaleArchiveState="OPEN"|"RECONCILING"|"READY"|"ARCHIVED";export type SaleArchiveEvent="RECONCILE"|"APPROVE"|"ARCHIVE";
export const saleArchiveMachine:SaleMachine<SaleArchiveState,SaleArchiveEvent>={name:"SALE_ARCHIVE",initial:"OPEN",terminal:["ARCHIVED"],edges:[{from:"OPEN",event:"RECONCILE",to:"RECONCILING"},{from:"RECONCILING",event:"APPROVE",to:"READY",humanOnly:true,guard:"AUDIT_COMPLETE"},{from:"READY",event:"ARCHIVE",to:"ARCHIVED",humanOnly:true,guard:"RETENTION_PLAN_READY"}]};
