import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R07_CANDIDATES";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR07Rules: BrainRule[] = [
  { id: "R07_LISTING_NOT_ACTIVE", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Annuncio non attivo", description: "Annuncio non attivo", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.status","value":"PUBLISHED"}, outcome: {"code":"ACTIVE_LISTING_REQUIRED","message":"La pipeline candidati richiede un annuncio pubblicato e corrente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_INQUIRY_CONSENT_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Consenso della richiesta non registrato", description: "Consenso della richiesta non registrato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.inquiry.consentStatus","value":"VALID"}, outcome: {"code":"INQUIRY_CONSENT_REQUIRED","message":"Registrare informativa, finalità e consenso/base applicabile prima di trattare i dati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_CONTACT_INVALID", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Recapito del richiedente non verificato", description: "Recapito del richiedente non verificato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.inquiry.contactStatus","value":"VERIFIED"}, outcome: {"code":"INQUIRY_CONTACT_REQUIRED","message":"Verificare almeno un recapito operativo senza raccogliere dati eccedenti.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_DUPLICATE_UNRESOLVED", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Richiesta duplicata non riconciliata", description: "Richiesta duplicata non riconciliata", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"gt","path":"rental.inquiry.possibleDuplicateCount","value":0}, outcome: {"code":"INQUIRY_DEDUP_REQUIRED","message":"Riconciliare i duplicati senza perdere cronologia o consensi.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_VIEWING_PRIVACY_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Privacy della visita non preparata", description: "Privacy della visita non preparata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.viewing.privacyStatus","value":"READY"}, outcome: {"code":"VIEWING_PRIVACY_REQUIRED","message":"Proteggere dati del locatore, dell'occupante e degli altri candidati durante la visita.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_VIEWING_CONFLICT", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Conflitto nell'agenda visite", description: "Conflitto nell'agenda visite", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.viewing.scheduleConflictCount","value":0}, outcome: {"code":"VIEWING_SCHEDULE_CONFLICT","message":"Risolvare sovrapposizioni e vincoli di accesso prima della conferma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_EXCESSIVE_DATA", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Dati della candidatura eccedenti", description: "Dati della candidatura eccedenti", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.application.excessiveFieldCount","value":0}, outcome: {"code":"DATA_MINIMIZATION_BLOCK","message":"Rimuovere i campi non necessari alla finalità dichiarata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_IDENTITY_EVIDENCE_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Evidenza identità candidato mancante", description: "Evidenza identità candidato mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.application.identityEvidenceStatus","value":"VERIFIED"}, outcome: {"code":"CANDIDATE_IDENTITY_EVIDENCE_REQUIRED","message":"Acquisire evidenza proporzionata e verificata dell'identità.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], evidencePolicy: {requiredFactPaths:["rental.application.identityEvidenceStatus"],requireVerifiedEvidence:true,acceptedProvenance:["DOCUMENT","OFFICIAL_SOURCE","AGENT","PROFESSIONAL","SYSTEM"]}, active: true, version: 1 },
  { id: "R07_ECONOMIC_EVIDENCE_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Evidenze economiche non verificabili", description: "Evidenze economiche non verificabili", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.application.economicEvidenceStatus","value":"VERIFIED"}, outcome: {"code":"CANDIDATE_ECONOMIC_EVIDENCE_REQUIRED","message":"Raccogliere soltanto evidenze economiche ammesse, pertinenti e verificabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_TRANSITORY_NEED_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Esigenza transitoria non documentata", description: "Esigenza transitoria non documentata", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TRANSITORY"},{"op":"neq","path":"rental.application.transitoryNeedStatus","value":"VERIFIED"}]}, outcome: {"code":"TRANSITORY_NEED_EVIDENCE_REQUIRED","message":"La candidatura transitoria richiede evidenza corrente dell'esigenza.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_TRANSITORY_RENTAL",30), active: true, version: 1 },
  { id: "R07_STUDENT_STATUS_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Status studente non documentato", description: "Status studente non documentato", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_STUDENT"},{"op":"neq","path":"rental.application.studentStatus","value":"VERIFIED"}]}, outcome: {"code":"STUDENT_STATUS_EVIDENCE_REQUIRED","message":"Verificare lo status studente applicabile senza raccogliere dati eccedenti.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_STUDENT_RENTAL",30), active: true, version: 1 },
  { id: "R07_RETENTION_PLAN_MISSING", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Piano di conservazione candidatura mancante", description: "Piano di conservazione candidatura mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.application.retentionPlanStatus","value":"ACTIVE"}, outcome: {"code":"CANDIDATE_RETENTION_PLAN_REQUIRED","message":"Definire durata, scadenza e cancellazione dei dati della candidatura.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_PROTECTED_ATTRIBUTE_REQUESTED", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Attributo protetto richiesto in candidatura", description: "Attributo protetto richiesto in candidatura", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.application.protectedAttributeFieldCount","value":0}, outcome: {"code":"PROTECTED_ATTRIBUTE_FORBIDDEN","message":"Bloccare la raccolta e aprire audit di sicurezza.","blockProgress":true,"reasonCodes":["FAIR_HOUSING","DATA_PROTECTION"]}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R07_PIPELINE_READY", module: "RENTAL_CANDIDATE_INTAKE", phase: P, title: "Candidatura pronta per la review", description: "Candidatura pronta per la review", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.application.status","value":"EVIDENCE_REVIEW"}, outcome: {"code":"CANDIDATE_INTAKE_READY","message":"La candidatura può passare alla review delle evidenze."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
