
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK06Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K06_PLAYBOOK_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Playbook Missing",factPath:"guimmia.orchestrator.k06.playbook_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_PLAYBOOK_VERSION_MISMATCH",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Playbook Version Mismatch",factPath:"guimmia.orchestrator.k06.playbook_version_mismatch.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_STAGE_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Stage Missing",factPath:"guimmia.orchestrator.k06.stage_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_STAGE_UNSUPPORTED",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Stage Unsupported",factPath:"guimmia.orchestrator.k06.stage_unsupported.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_STAGE_PREREQUISITE_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Stage Prerequisite Missing",factPath:"guimmia.orchestrator.k06.stage_prerequisite_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_STAGE_TRANSITION_UNVERIFIED",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Stage Transition Unverified",factPath:"guimmia.orchestrator.k06.stage_transition_unverified.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_OPERATION_SPECIFIC_REQUIREMENT_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Operation Specific Requirement Missing",factPath:"guimmia.orchestrator.k06.operation_specific_requirement_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_MODE_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Mode Missing",factPath:"guimmia.orchestrator.k06.command_mode_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_IDEMPOTENCY_KEY_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Idempotency Key Missing",factPath:"guimmia.orchestrator.k06.command_idempotency_key_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_EXPECTED_CASE_VERSION_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Expected Case Version Missing",factPath:"guimmia.orchestrator.k06.command_expected_case_version_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_CASE_VERSION_CONFLICT",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Case Version Conflict",factPath:"guimmia.orchestrator.k06.command_case_version_conflict.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_AUTHORITY_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Authority Missing",factPath:"guimmia.orchestrator.k06.command_authority_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_CONFIRMATION_EVIDENCE_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Confirmation Evidence Missing",factPath:"guimmia.orchestrator.k06.command_confirmation_evidence_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_APPROVAL_EVIDENCE_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Approval Evidence Missing",factPath:"guimmia.orchestrator.k06.command_approval_evidence_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_EXECUTION_BLOCKED",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Execution Blocked",factPath:"guimmia.orchestrator.k06.command_execution_blocked.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_UNKNOWN_ACTION_TYPE_BLOCKED",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Unknown Action Type Blocked",factPath:"guimmia.orchestrator.k06.unknown_action_type_blocked.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_RESULT_HASH_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Result Hash Missing",factPath:"guimmia.orchestrator.k06.command_result_hash_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K06_COMMAND_AUDIT_EVENT_MISSING",module:"CASE_PLAYBOOK_EXECUTION",phase:"PHASE_K06_PLAYBOOK_EXECUTION_SAFETY",title:"Command Audit Event Missing",factPath:"guimmia.orchestrator.k06.command_audit_event_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
