import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO09Rules:BrainRule[]=[
  makeAgencyRule({"id":"O09_CUSTOMER_IDENTITY_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Customer Identity Missing","factPath":"agency.o09.customer_identity_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_IDENTITY_EVIDENCE_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Identity Evidence Missing","factPath":"agency.o09.identity_evidence_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_IDENTITY_EVIDENCE"}),
  makeAgencyRule({"id":"O09_IDENTITY_EVIDENCE_STALE","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Identity Evidence Stale","factPath":"agency.o09.identity_evidence_stale.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_IDENTITY_EVIDENCE"}),
  makeAgencyRule({"id":"O09_CONTACT_ROLE_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Contact Role Missing","factPath":"agency.o09.contact_role_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_PARTY_ROLE_CONFLICT","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Party Role Conflict","factPath":"agency.o09.party_role_conflict.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_CUSTOMER_INTENT_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Customer Intent Missing","factPath":"agency.o09.customer_intent_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_MANDATE_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Mandate Missing","factPath":"agency.o09.mandate_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_MANDATE"}),
  makeAgencyRule({"id":"O09_MANDATE_SCOPE_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Mandate Scope Missing","factPath":"agency.o09.mandate_scope_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_MANDATE_SCOPE"}),
  makeAgencyRule({"id":"O09_MANDATE_EXPIRED","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Mandate Expired","factPath":"agency.o09.mandate_expired.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_MANDATE"}),
  makeAgencyRule({"id":"O09_MANDATE_REVOKED","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Mandate Revoked","factPath":"agency.o09.mandate_revoked.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"],"rulesetKey":"ITALY_AGENCY_MANDATE_REVOKED"}),
  makeAgencyRule({"id":"O09_AUTHORITY_LIMIT_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Authority Limit Missing","factPath":"agency.o09.authority_limit_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_REPRESENTATIVE_POWER_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Representative Power Missing","factPath":"agency.o09.representative_power_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_BENEFICIAL_OWNER_REVIEW_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Beneficial Owner Review Missing","factPath":"agency.o09.beneficial_owner_review_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_DUPLICATE_IDENTITY_UNRESOLVED","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Duplicate Identity Unresolved","factPath":"agency.o09.duplicate_identity_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_HUMAN_IDENTITY_REVIEW_MISSING","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Human Identity Review Missing","factPath":"agency.o09.human_identity_review_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O09_READY","module":"AGENCY_IDENTITY_MANDATE","phase":"PHASE_O09_IDENTITY_MANDATE_INTENT","title":"Ready","factPath":"agency.o09.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]})
];
