import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R09_SIGN_REGISTER";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR09Rules: BrainRule[] = [
  { id: "R09_UPSTREAM_DECISION_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Decisione umana sul candidato mancante", description: "Decisione umana sul candidato mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.screening.status","value":"HUMAN_DECIDED"}, outcome: {"code":"HUMAN_DECISION_REQUIRED_BEFORE_LEASE","message":"Non preparare la firma senza una decisione umana valida.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_PHASE05_SNAPSHOT_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Snapshot contrattuale V76.6 non corrente", description: "Snapshot contrattuale V76.6 non corrente", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"transaction.phase05SnapshotStatus","value":"CURRENT"}, outcome: {"code":"CURRENT_PHASE05_SNAPSHOT_REQUIRED","message":"Usare lo snapshot V76.6 corrente per la versione contrattuale.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_TEMPLATE_NOT_APPROVED", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Template contrattuale non approvato", description: "Template contrattuale non approvato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"transaction.contractTemplateStatus","value":"APPROVED"}, outcome: {"code":"APPROVED_LEASE_TEMPLATE_REQUIRED","message":"Sono ammessi solo template versionati e approvati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_INPUTS_STALE", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Input del contratto modificati", description: "Input del contratto modificati", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"eq","path":"transaction.contractInputStatus","value":"STALE"}, outcome: {"code":"LEASE_INPUTS_STALE","message":"Rigenerare la bozza e ripetere la review umana.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_HUMAN_REVIEW_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Review umana del contratto mancante", description: "Review umana del contratto mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"neq","path":"transaction.contractReviewStatus","value":"APPROVED"}, outcome: {"code":"HUMAN_LEASE_REVIEW_REQUIRED","message":"Un agente autorizzato deve approvare la versione esatta da firmare.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_PARTY_IDENTITY_MISMATCH", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Identità delle parti non riconciliata", description: "Identità delle parti non riconciliata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"transaction.partyIdentityConflictCount","value":0}, outcome: {"code":"LEASE_PARTY_IDENTITY_CONFLICT","message":"Riconciliare identità, ruoli e poteri prima della firma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_SIGNATURE_ORDER_UNKNOWN", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Ordine e ruoli di firma non definiti", description: "Ordine e ruoli di firma non definiti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"transaction.signaturePlanStatus","value":"READY"}, outcome: {"code":"LEASE_SIGNATURE_PLAN_REQUIRED","message":"Definire firmatari, ordine, metodo e scadenze.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_SIGNATURES_INCOMPLETE", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Firme contrattuali incomplete", description: "Firme contrattuali incomplete", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.contractStatus","value":"SIGNING"},{"op":"neq","path":"transaction.signatureStatus","value":"COMPLETED"}]}, outcome: {"code":"LEASE_SIGNATURES_INCOMPLETE","message":"Non marcare il contratto come firmato finché tutte le firme richieste non sono verificate.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_SIGNATURE_EVIDENCE_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Evidenza della firma mancante", description: "Evidenza della firma mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.signatureStatus","value":"COMPLETED"},{"op":"neq","path":"transaction.signatureEvidenceStatus","value":"VERIFIED"}]}, outcome: {"code":"SIGNATURE_EVIDENCE_REQUIRED","message":"Conservare ricevute, hash e prova temporale della firma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], evidencePolicy: {requiredFactPaths:["transaction.signatureEvidenceStatus"],requireVerifiedEvidence:true,acceptedProvenance:["DOCUMENT","OFFICIAL_SOURCE","AGENT","PROFESSIONAL","SYSTEM"]}, active: true, version: 1 },
  { id: "R09_REGISTRATION_APPLICABILITY_UNKNOWN", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Applicabilità della registrazione non determinata", description: "Applicabilità della registrazione non determinata", stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"transaction.registrationApplicability","value":"UNKNOWN"}, outcome: {"code":"REGISTRATION_APPLICABILITY_REVIEW","message":"Determinare obbligo, termini e modalità con ruleset corrente.","blockProgress":true,"escalationTo":"ACCOUNTANT"}, sourceRefs: [SOURCE_MAP.AE_RENTAL_REGISTRATION], freshnessPolicy: fresh("ITALY_RENTAL_REGISTRATION",30), active: true, version: 1 },
  { id: "R09_REGISTRATION_TASK_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Task di registrazione mancante", description: "Task di registrazione mancante", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.registrationApplicability","value":"REQUIRED"},{"op":"neq","path":"transaction.registrationPlanStatus","value":"READY"}]}, outcome: {"code":"LEASE_REGISTRATION_TASK_REQUIRED","message":"Creare task, responsabile, scadenza e canale di registrazione.","blockProgress":true}, sourceRefs: [SOURCE_MAP.AE_RENTAL_REGISTRATION], freshnessPolicy: fresh("ITALY_RENTAL_REGISTRATION",30), active: true, version: 1 },
  { id: "R09_REGISTRATION_DEADLINE_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Scadenza di registrazione non definita", description: "Scadenza di registrazione non definita", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.registrationApplicability","value":"REQUIRED"},{"op":"not","condition":{"op":"exists","path":"transaction.registrationDeadline"}}]}, outcome: {"code":"REGISTRATION_DEADLINE_REQUIRED","message":"Calcolare e registrare la scadenza con fonte corrente.","blockProgress":true}, sourceRefs: [SOURCE_MAP.AE_RENTAL_REGISTRATION], freshnessPolicy: fresh("ITALY_RENTAL_REGISTRATION",30), active: true, version: 1 },
  { id: "R09_REGISTRATION_RECEIPT_MISSING", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Ricevuta di registrazione mancante", description: "Ricevuta di registrazione mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.registrationStatus","value":"COMPLETED"},{"op":"neq","path":"transaction.registrationReceiptStatus","value":"VERIFIED"}]}, outcome: {"code":"REGISTRATION_RECEIPT_REQUIRED","message":"Acquisire e verificare la ricevuta prima dell'attivazione definitiva.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_ACTIVE_BEFORE_REGISTRATION", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Contratto attivato prima degli adempimenti richiesti", description: "Contratto attivato prima degli adempimenti richiesti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"transaction.contractStatus","value":"ACTIVE"},{"op":"eq","path":"transaction.registrationApplicability","value":"REQUIRED"},{"op":"neq","path":"transaction.registrationStatus","value":"COMPLETED"}]}, outcome: {"code":"LEASE_ACTIVATION_BLOCKED","message":"Bloccare l'attivazione finché la registrazione richiesta non è completata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_SIGNED_CONTENT_CHANGED", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Contenuto firmato modificato", description: "Contenuto firmato modificato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"eq","path":"transaction.signedContentIntegrityStatus","value":"MISMATCH"}, outcome: {"code":"SIGNED_LEASE_IMMUTABILITY_VIOLATION","message":"Bloccare il flusso e conservare l'evidenza dell'alterazione.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R09_READY", module: "RENTAL_SIGNING_REGISTRATION", phase: P, title: "Contratto firmato e adempimenti instradati", description: "Contratto firmato e adempimenti instradati", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"transaction.leaseOperationalStatus","value":"READY_FOR_HANDOVER"}, outcome: {"code":"LEASE_READY_FOR_HANDOVER","message":"Il contratto è pronto per la fase di consegna."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
