import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";

const P = "PHASE_01_CLIENT_MANDATE";
const M = "CLIENT_MANDATE";

export const phase01Rules: BrainRule[] = [
  {
    id: "P01_IDENTITY_NOT_COLLECTED", module: M, phase: P,
    title: "Identità cliente incompleta",
    description: "La pratica non può diventare operativa finché l'identità minima del cliente non è stata raccolta.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "neq", path: "client.identityStatus", value: "COLLECTED" },
    outcome: { code: "IDENTITY_REQUIRED", message: "Completare i dati identificativi e acquisire il documento previsto dal processo.", blockProgress: true, suggestedActions: ["Raccogli dati anagrafici", "Acquisisci documento", "Registra provenienza dei dati"] },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION, internalPolicy("Onboarding cliente")], active: true, version: 2,
  },
  {
    id: "P01_IDENTITY_DOCUMENT_EXPIRED", module: M, phase: P,
    title: "Documento identificativo dichiarato scaduto",
    description: "Un documento scaduto richiede gestione prima dell'attivazione secondo il processo di identificazione adottato.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "eq", path: "client.identityDocumentStatus", value: "EXPIRED" },
    outcome: { code: "IDENTITY_DOCUMENT_REFRESH", message: "Richiedere un documento valido o applicare la procedura approvata.", blockProgress: true },
    sourceRefs: [internalPolicy("Controllo identità")], active: true, version: 2,
  },
  {
    id: "P01_CAPACITY_SPECIAL_CASE", module: M, phase: P,
    title: "Capacità di agire / rappresentanza speciale da verificare",
    description: "Se emergono minore età, amministrazione di sostegno, tutela o altra limitazione dichiarata, Guimmia non conclude autonomamente sulla capacità di agire.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "in", path: "client.capacityCase", values: ["MINOR", "SUPPORT_ADMINISTRATION", "GUARDIANSHIP", "INCAPACITY_OTHER"] },
    outcome: { code: "CAPACITY_PROFESSIONAL_REVIEW", message: "Fermare il gate e verificare poteri, autorizzazioni e soggetti necessari.", blockProgress: true, escalationTo: "LAWYER", suggestedActions: ["Acquisisci provvedimenti/atti", "Coinvolgi agente e professionista appropriato"] },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, internalPolicy("Human-in-the-loop")], active: true, version: 2,
  },
  {
    id: "P01_REPRESENTATIVE_AUTHORITY", module: M, phase: P,
    title: "Potere di rappresentanza non verificato",
    description: "Chi agisce per un'altra persona deve essere instradato a verifica del titolo rappresentativo.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "client.relationshipToProperty", value: "REPRESENTATIVE" },
      { op: "neq", path: "client.authorityStatus", value: "VERIFIED" },
    ] },
    outcome: { code: "AUTHORITY_REVIEW_REQUIRED", message: "Verificare procura o altro titolo rappresentativo prima dell'operatività.", blockProgress: true, escalationTo: "AGENT", requiredFacts: ["client.authorityDocument","client.authorityStatus"] },
    sourceRefs: [SOURCE_MAP.CONTRACTS, SOURCE_MAP.MANDATE_MEDIATION], active: true, version: 2,
  },
  {
    id: "P01_COOWNERSHIP_DECLARED", module: M, phase: P,
    title: "Comproprietà dichiarata",
    description: "La presenza di più titolari apre il percorso di identificazione e riconciliazione dei soggetti.",
    stability: "STABLE", decisionLevel: "REVIEW", severity: "warning",
    condition: { op: "eq", path: "property.ownershipClaim", value: "COOWNERSHIP" },
    outcome: { code: "COOWNERSHIP_ROUTE", message: "Raccogliere dati e quote dichiarate di tutti i comproprietari; la verifica sostanziale avverrà in Fase 2.", suggestedActions: ["Identifica comproprietari", "Registra quote dichiarate"] },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL], active: true, version: 2,
  },
  {
    id: "P01_EXISTING_MANDATE_UNKNOWN_OR_YES", module: M, phase: P,
    title: "Possibile incarico immobiliare preesistente",
    description: "Un incarico già in essere o non conosciuto deve essere acquisito e controllato prima di assumere un nuovo impegno incompatibile.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "in", path: "sale.existingAgencyMandate", values: ["YES", "UNKNOWN"] },
    outcome: { code: "EXISTING_MANDATE_CHECK", message: "Acquisire il contratto/incarico esistente e farlo verificare dall'agente.", blockProgress: true, escalationTo: "AGENT", suggestedActions: ["Richiedi copia incarico", "Verifica durata, esclusiva, recesso e scadenza"] },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION, internalPolicy("Conflitti incarico")], active: true, version: 2,
  },
  {
    id: "P01_COMPLIANCE_RULESET", module: "PRO_COMPLIANCE", phase: P,
    title: "Compliance professionale da eseguire con ruleset corrente",
    description: "Privacy, antiriciclaggio, obblighi informativi e altri adempimenti variabili non vengono congelati dal manuale.",
    stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "neq", path: "compliance.status", value: "PASSED" },
    outcome: { code: "COMPLIANCE_GATE", message: "Eseguire il gate di compliance con il ruleset normativo corrente.", blockProgress: true, requiredFacts: ["compliance.status","compliance.rulesetVersion"] },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION], freshnessPolicy: { required: true, maxAgeDays: 90, rulesetKey: "ITALY_AGENCY_COMPLIANCE" }, active: true, version: 2,
  },
  {
    id: "P01_SERVICE_PLAN_MISSING", module: M, phase: P,
    title: "Piano di servizio non selezionato",
    description: "Ogni incarico deve indicare quale servizio Guimmia viene acquistato e la versione tariffaria applicabile.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "not", condition: { op: "exists", path: "service.plan" } },
    outcome: { code: "SERVICE_SELECTION_REQUIRED", message: "Selezionare piano e pricing version prima di generare il mandato.", blockProgress: true, requiredFacts: ["service.plan","service.pricingVersion"] },
    sourceRefs: [internalPolicy("Pricing versionato")], active: true, version: 2,
  },
  {
    id: "P01_PRICING_VERSION_MISSING", module: M, phase: P,
    title: "Versione tariffaria mancante",
    description: "Il prezzo non deve essere ricostruito a posteriori: va salvata la versione tariffaria applicata.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: { op: "not", condition: { op: "exists", path: "service.pricingVersion" } },
    outcome: { code: "PRICING_VERSION_REQUIRED", message: "Associare alla pratica una versione tariffaria immutabile.", blockProgress: true },
    sourceRefs: [internalPolicy("Audit commerciale")], active: true, version: 2,
  },
  {
    id: "P01_CONTRACT_TEMPLATE_MISSING", module: M, phase: P,
    title: "Template contrattuale approvato mancante",
    description: "Il contratto deve essere composto da template e clausole approvati/versionati; l'LLM non può inventare clausole legali.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "not", condition: { op: "exists", path: "mandate.templateVersion" } },
    outcome: { code: "CONTRACT_TEMPLATE_REQUIRED", message: "Selezionare un template approvato e versionato.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION, internalPolicy("No free-form legal drafting")], active: true, version: 2,
  },
  {
    id: "P01_DISTANCE_CONTRACT_HANDLING", module: "PRO_COMPLIANCE", phase: P,
    title: "Gestione contratto a distanza non completata",
    description: "Quando applicabile, gli adempimenti consumeristici del contratto concluso online devono seguire il ruleset corrente.",
    stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "mandate.channel", value: "ONLINE" },
      { op: "neq", path: "mandate.consumerDistanceHandling", value: "PASSED" },
    ] },
    outcome: { code: "DISTANCE_CONTRACT_GATE", message: "Completare gli adempimenti applicabili al contratto a distanza secondo il ruleset verificato.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION], freshnessPolicy: { required: true, maxAgeDays: 90, rulesetKey: "ITALY_DISTANCE_CONTRACTS" }, active: true, version: 2,
  },
  {
    id: "P01_MANDATE_UNSIGNED", module: M, phase: P,
    title: "Mandato non sottoscritto",
    description: "L'attivazione operativa richiede che lo stato della sottoscrizione previsto dal processo sia completato.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "neq", path: "mandate.status", value: "SIGNED" },
    outcome: { code: "MANDATE_SIGNATURE_REQUIRED", message: "Completare la sottoscrizione e registrare audit trail/versioni.", blockProgress: true },
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION, internalPolicy("Audit contratti")], active: true, version: 2,
  },
  {
    id: "P01_AUDIT_TRAIL_INCOMPLETE", module: "PRO_COMPLIANCE", phase: P,
    title: "Audit trail contrattuale incompleto",
    description: "Dopo la firma devono essere ricostruibili template, termini, privacy, pricing e timestamp essenziali.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "mandate.status", value: "SIGNED" },
      { op: "neq", path: "mandate.auditStatus", value: "COMPLETE" },
    ] },
    outcome: { code: "CONTRACT_AUDIT_REQUIRED", message: "Persistenza audit contrattuale incompleta.", blockProgress: true },
    sourceRefs: [internalPolicy("Audit e tracciabilità")], active: true, version: 2,
  },
  {
    id: "P01_PAYMENT_PENDING", module: M, phase: P,
    title: "Pagamento di attivazione pendente",
    description: "Se la policy commerciale richiede il pagamento prima dell'attivazione, il gate resta chiuso fino alla conferma.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "payment.requiredForActivation", value: true },
      { op: "neq", path: "payment.status", value: "PAID" },
    ] },
    outcome: { code: "PAYMENT_GATE", message: "Attendere o gestire il pagamento richiesto dalla policy commerciale.", blockProgress: true },
    sourceRefs: [internalPolicy("Gate commerciale")], active: true, version: 2,
  },
];
