import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseC02Rules:BrainRule[]=[
  makeAgencyRule({"id":"C02_DOCUMENT_TYPE_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Document Type Missing","factPath":"guimmia.customer.c02.document_type_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_CASE_CONTEXT_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Case Context Missing","factPath":"guimmia.customer.c02.case_context_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_TEMPLATE_VERSION_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Template Version Missing","factPath":"guimmia.customer.c02.template_version_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_REQUIRED_INPUT_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Required Input Missing","factPath":"guimmia.customer.c02.required_input_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_SOURCE_DOCUMENT_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Source Document Missing","factPath":"guimmia.customer.c02.source_document_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_IDENTITY_LINK_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Identity Link Missing","factPath":"guimmia.customer.c02.identity_link_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_MANDATE_SCOPE_MISMATCH","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Mandate Scope Mismatch","factPath":"guimmia.customer.c02.mandate_scope_mismatch.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"],"rulesetKey":"ITALY_AGENCY_MANDATE_SCOPE_MISMATCH"}),
  makeAgencyRule({"id":"C02_CLAUSE_CONTEXT_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Clause Context Missing","factPath":"guimmia.customer.c02.clause_context_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_DYNAMIC_RULESET_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Dynamic Ruleset Missing","factPath":"guimmia.customer.c02.dynamic_ruleset_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"],"rulesetKey":"ITALY_AGENCY_DYNAMIC_RULESET"}),
  makeAgencyRule({"id":"C02_LEGAL_REVIEW_REQUIRED","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Legal Review Required","factPath":"guimmia.customer.c02.legal_review_required.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"],"rulesetKey":"ITALY_AGENCY_LEGAL_REVIEW_REQUIRED"}),
  makeAgencyRule({"id":"C02_PROFESSIONAL_REVIEW_REQUIRED","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Professional Review Required","factPath":"guimmia.customer.c02.professional_review_required.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"],"rulesetKey":"ITALY_AGENCY_PROFESSIONAL_REVIEW_REQUIRED"}),
  makeAgencyRule({"id":"C02_CUSTOMER_REVIEW_PENDING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Customer Review Pending","factPath":"guimmia.customer.c02.customer_review_pending.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_HUMAN_APPROVAL_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Human Approval Missing","factPath":"guimmia.customer.c02.human_approval_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_SIGNATURE_AUTHORITY_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Signature Authority Missing","factPath":"guimmia.customer.c02.signature_authority_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_SIGNATURE_EVIDENCE_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Signature Evidence Missing","factPath":"guimmia.customer.c02.signature_evidence_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_VERSION_HASH_MISSING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Version Hash Missing","factPath":"guimmia.customer.c02.version_hash_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_BUREAUCRATIC_STEP_PENDING","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Bureaucratic Step Pending","factPath":"guimmia.customer.c02.bureaucratic_step_pending.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]}),
  makeAgencyRule({"id":"C02_DOCUMENT_READY","module":"GUIMMIA_DOCUMENT_ASSISTANCE","phase":"PHASE_C02_DOCUMENT_BUREAUCRACY_ASSISTANCE","title":"Document Ready","factPath":"guimmia.customer.c02.document_ready.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","LEASE_SIGNING","LEASE_REGISTRATION"]})
];
