import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO12Rules:BrainRule[]=[
  makeAgencyRule({"id":"O12_REQUEST_ID_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Request Id Missing","factPath":"agency.o12.request_id_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_IDEMPOTENCY_COLLISION","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Idempotency Collision","factPath":"agency.o12.idempotency_collision.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_VERSION_CONFLICT","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Version Conflict","factPath":"agency.o12.version_conflict.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_OUTBOX_STALLED","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Outbox Stalled","factPath":"agency.o12.outbox_stalled.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_RETRY_POLICY_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Retry Policy Missing","factPath":"agency.o12.retry_policy_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_RETRY_EXHAUSTED","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Retry Exhausted","factPath":"agency.o12.retry_exhausted.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_DEAD_LETTER_UNREVIEWED","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Dead Letter Unreviewed","factPath":"agency.o12.dead_letter_unreviewed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_WEBHOOK_REPLAY_DETECTED","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Webhook Replay Detected","factPath":"agency.o12.webhook_replay_detected.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_SIGNATURE_TIMESTAMP_STALE","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Signature Timestamp Stale","factPath":"agency.o12.signature_timestamp_stale.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_PAYLOAD_FINGERPRINT_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Payload Fingerprint Missing","factPath":"agency.o12.payload_fingerprint_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_AUDIT_CHAIN_BROKEN","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Audit Chain Broken","factPath":"agency.o12.audit_chain_broken.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_COMPENSATING_EVENT_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Compensating Event Missing","factPath":"agency.o12.compensating_event_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_RECOVERY_OWNER_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Recovery Owner Missing","factPath":"agency.o12.recovery_owner_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_RECOVERY_DEADLINE_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Recovery Deadline Missing","factPath":"agency.o12.recovery_deadline_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_HUMAN_RECOVERY_APPROVAL_MISSING","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Human Recovery Approval Missing","factPath":"agency.o12.human_recovery_approval_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O12_READY","module":"AGENCY_RELIABILITY_RECOVERY","phase":"PHASE_O12_RELIABILITY_RECOVERY","title":"Ready","factPath":"agency.o12.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","BOOKING","GUEST_REPORTING"]})
];
