import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R03_RENTAL_DOCUMENT_DOSSIER";
const fresh = (rulesetKey:string) => ({required:true,rulesetKey,maxAgeDays:30});

export const phaseR03Rules: BrainRule[] = [
  { id: "R03_AUTHORITY_NOT_READY", module: "RENTAL_DOCUMENTS", phase: P, title: "Potere di locare non pronto", description: "Potere di locare non pronto", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"neq","path":"rental.authorityStatus","value":"VERIFIED"}, outcome: {"code":"AUTHORITY_PREREQUISITE","message":"Completare R02 prima del fascicolo locativo.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_REQUIREMENTS_NOT_EVALUATED", module: "RENTAL_DOCUMENTS", phase: P, title: "Requisiti documentali locativi non valutati", description: "Requisiti documentali locativi non valutati", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"neq","path":"rental.documents.requirementsStatus","value":"CURRENT"}, outcome: {"code":"RENTAL_REQUIREMENTS_REQUIRED","message":"Calcolare requisiti in base a tipo locazione, immobile e territorio.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_UNKNOWN_REQUIREMENTS", module: "RENTAL_DOCUMENTS", phase: P, title: "Requisiti locativi ancora UNKNOWN", description: "Requisiti locativi ancora UNKNOWN", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.documents.unknownRequirementCount","value":0}, outcome: {"code":"UNKNOWN_RENTAL_REQUIREMENTS","message":"Raccogliere i fatti che determinano l applicabilità dei documenti.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_MISSING_REQUIRED_DOCUMENTS", module: "RENTAL_DOCUMENTS", phase: P, title: "Documenti locativi obbligatori mancanti", description: "Documenti locativi obbligatori mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.documents.missingRequiredCount","value":0}, outcome: {"code":"MISSING_RENTAL_DOCUMENTS","message":"Richiedere i documenti mancanti e tracciare la richiesta.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_DOCUMENT_CONFLICTS_OPEN", module: "RENTAL_DOCUMENTS", phase: P, title: "Conflitti documentali aperti", description: "Conflitti documentali aperti", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.documents.openConflictCount","value":0}, outcome: {"code":"RENTAL_DOCUMENT_CONFLICT","message":"Riconciliare i claim in conflitto prima di avanzare.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_HIGH_RISK_PUBLIC_STORAGE", module: "RENTAL_DOCUMENTS", phase: P, title: "Documento sensibile su storage pubblico", description: "Documento sensibile su storage pubblico", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.documents.publicSensitiveDocumentCount","value":0}, outcome: {"code":"SENSITIVE_DOCUMENT_PUBLIC","message":"Spostare immediatamente i documenti sensibili in storage protetto.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_EXISTING_LEASE_DOCUMENT_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Contratto locativo esistente non acquisito", description: "Contratto locativo esistente non acquisito", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.currentOccupancyStatus","value":"ACTIVE_LEASE"},{"op":"falsy","path":"rental.documents.hasExistingLease"}]}, outcome: {"code":"EXISTING_LEASE_DOCUMENT_REQUIRED","message":"Acquisire il contratto locativo esistente.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R03_APE_APPLICABILITY_UNKNOWN", module: "RENTAL_DOCUMENTS", phase: P, title: "Applicabilità APE non determinata", description: "Applicabilità APE non determinata", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"rental.documents.apeRequirement","value":"UNKNOWN"}, outcome: {"code":"APE_REQUIREMENT_UNKNOWN","message":"Determinare l applicabilità con ruleset corrente.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_HOUSING], freshnessPolicy: fresh("ITALY_APE"), active: true, version: 1 },
  { id: "R03_APE_REQUIRED_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "APE richiesto ma mancante", description: "APE richiesto ma mancante", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.documents.apeRequirement","value":"REQUIRED"},{"op":"neq","path":"rental.documents.apeStatus","value":"AVAILABLE"}]}, outcome: {"code":"APE_REQUIRED","message":"Acquisire APE o instradare produzione/aggiornamento.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_HOUSING], freshnessPolicy: fresh("ITALY_APE"), active: true, version: 1 },
  { id: "R03_TRANSITORY_EVIDENCE_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Esigenza transitoria non documentata", description: "Esigenza transitoria non documentata", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TRANSITORY"},{"op":"neq","path":"rental.documents.transitoryNeedEvidenceStatus","value":"AVAILABLE"}]}, outcome: {"code":"TRANSITORY_EVIDENCE_REQUIRED","message":"Acquisire documentazione dell esigenza transitoria prevista dal percorso.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_TRANSITORY_RENTAL"), active: true, version: 1 },
  { id: "R03_STUDENT_EVIDENCE_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Documentazione studente mancante", description: "Documentazione studente mancante", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_STUDENT"},{"op":"neq","path":"rental.documents.studentEvidenceStatus","value":"AVAILABLE"}]}, outcome: {"code":"STUDENT_EVIDENCE_REQUIRED","message":"Acquisire evidenza del requisito studentesco rilevante per il contratto.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_STUDENT_RENTAL"), active: true, version: 1 },
  { id: "R03_LOCAL_AGREEMENT_REFERENCE_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Accordo territoriale non identificato", description: "Accordo territoriale non identificato", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"in","path":"operation.type","values":["RENT_TRANSITORY","RENT_STUDENT"]},{"op":"neq","path":"rental.documents.localAgreementStatus","value":"IDENTIFIED"}]}, outcome: {"code":"LOCAL_AGREEMENT_REQUIRED","message":"Identificare accordo territoriale e versione applicabile.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_LOCAL_RENTAL_AGREEMENTS"), active: true, version: 1 },
  { id: "R03_CIN_EVIDENCE_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "CIN non acquisito", description: "CIN non acquisito", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TOURIST_SHORT"},{"op":"neq","path":"rental.documents.cinEvidenceStatus","value":"AVAILABLE"}]}, outcome: {"code":"CIN_EVIDENCE_REQUIRED","message":"Acquisire e verificare il CIN prima della pubblicazione turistica.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER, SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_TOURIST_CIN"), active: true, version: 1 },
  { id: "R03_TOURIST_SAFETY_EVIDENCE_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Evidenza sicurezza turistica mancante", description: "Evidenza sicurezza turistica mancante", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TOURIST_SHORT"},{"op":"neq","path":"rental.documents.safetyEvidenceStatus","value":"AVAILABLE"}]}, outcome: {"code":"TOURIST_SAFETY_EVIDENCE_REQUIRED","message":"Acquisire evidenza dei requisiti di sicurezza applicabili.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER, SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_TOURIST_SAFETY"), active: true, version: 1 },
  { id: "R03_SCIA_EVIDENCE_UNKNOWN", module: "RENTAL_DOCUMENTS", phase: P, title: "SCIA turistica non determinata", description: "SCIA turistica non determinata", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TOURIST_SHORT"},{"op":"eq","path":"rental.documents.sciaRequirement","value":"UNKNOWN"}]}, outcome: {"code":"SCIA_REQUIREMENT_UNKNOWN","message":"Determinare forma imprenditoriale e obblighi locali prima di chiudere il fascicolo.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER, SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_TOURIST_SCIA"), active: true, version: 1 },
  { id: "R03_SCIA_REQUIRED_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "SCIA richiesta ma non acquisita", description: "SCIA richiesta ma non acquisita", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.documents.sciaRequirement","value":"REQUIRED"},{"op":"neq","path":"rental.documents.sciaEvidenceStatus","value":"AVAILABLE"}]}, outcome: {"code":"SCIA_EVIDENCE_REQUIRED","message":"Acquisire evidenza SCIA prima del gate applicabile.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER, SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_TOURIST_SCIA"), active: true, version: 1 },
  { id: "R03_CONDO_RULES_NEEDED", module: "RENTAL_DOCUMENTS", phase: P, title: "Regolamento condominiale da acquisire", description: "Regolamento condominiale da acquisire", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"truthy","path":"rental.documents.condominiumRulesRequired"},{"op":"neq","path":"rental.documents.condominiumRulesStatus","value":"AVAILABLE"}]}, outcome: {"code":"CONDO_RULES_REQUIRED","message":"Acquisire il regolamento per verificare limitazioni rilevanti.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_INVENTORY_REQUIRED_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Inventario arredi richiesto ma mancante", description: "Inventario arredi richiesto ma mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"truthy","path":"rental.furnished"},{"op":"neq","path":"rental.documents.inventoryStatus","value":"AVAILABLE"}]}, outcome: {"code":"INVENTORY_REQUIRED","message":"Predisporre inventario versionato per consegna/contratto.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R03_GUEST_REPORTING_CREDENTIALS_MISSING", module: "RENTAL_DOCUMENTS", phase: P, title: "Credenziali/processo alloggiati non pronto", description: "Credenziali/processo alloggiati non pronto", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TOURIST_SHORT"},{"op":"neq","path":"rental.documents.guestReportingProcessStatus","value":"READY"}]}, outcome: {"code":"GUEST_REPORTING_PROCESS_REQUIRED","message":"Definire il soggetto responsabile e il processo per gli adempimenti ospiti.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER, SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_GUEST_REPORTING"), active: true, version: 1 },
  { id: "R03_DOSSIER_SNAPSHOT_NOT_CURRENT", module: "RENTAL_DOCUMENTS", phase: P, title: "Snapshot fascicolo locativo non corrente", description: "Snapshot fascicolo locativo non corrente", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.documents.requirementsStatus","value":"CURRENT"},{"op":"neq","path":"rental.documents.snapshotStatus","value":"CURRENT"}]}, outcome: {"code":"RENTAL_DOSSIER_SNAPSHOT_REQUIRED","message":"Salvare snapshot del fascicolo prima della fase di readiness.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
];
