import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R10_HANDOVER";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR10Rules: BrainRule[] = [
  { id: "R10_LEASE_NOT_ACTIVE", module: "RENTAL_HANDOVER", phase: P, title: "Contratto non pronto per la consegna", description: "Contratto non pronto per la consegna", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"not_in","path":"transaction.contractStatus","values":["SIGNED","ACTIVE"]}, outcome: {"code":"SIGNED_LEASE_REQUIRED_FOR_HANDOVER","message":"La consegna richiede un contratto firmato e valido per il workflow.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_SCHEDULE_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Appuntamento di consegna non definito", description: "Appuntamento di consegna non definito", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.scheduleStatus","value":"CONFIRMED"}, outcome: {"code":"HANDOVER_SCHEDULE_REQUIRED","message":"Confermare data, luogo, partecipanti e accesso.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_INVENTORY_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Inventario di consegna incompleto", description: "Inventario di consegna incompleto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.inventoryStatus","value":"READY"}, outcome: {"code":"HANDOVER_INVENTORY_REQUIRED","message":"Versionare inventario e stato dei beni prima della firma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_CONDITION_EVIDENCE_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Evidenze dello stato dei locali mancanti", description: "Evidenze dello stato dei locali mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.conditionEvidenceStatus","value":"VERIFIED"}, outcome: {"code":"HANDOVER_CONDITION_EVIDENCE_REQUIRED","message":"Acquisire foto e note datate collegate all'inventario.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_KEY_COUNT_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Chiavi non censite", description: "Chiavi non censite", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.keyStatus","value":"READY"}, outcome: {"code":"HANDOVER_KEYS_REQUIRED","message":"Registrare quantità, tipo, identificativo e consegnatario delle chiavi.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_METER_READINGS_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Letture contatori mancanti", description: "Letture contatori mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.meterStatus","value":"READY"}, outcome: {"code":"HANDOVER_METERS_REQUIRED","message":"Registrare letture, unità, foto e data dei contatori applicabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_DEPOSIT_EVIDENCE_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Evidenza deposito non riconciliata", description: "Evidenza deposito non riconciliata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.depositStatus","value":"RECONCILED"}, outcome: {"code":"HANDOVER_DEPOSIT_RECONCILIATION_REQUIRED","message":"Riconciliare importo, modalità, data e ricevuta del deposito.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_OPEN_RESERVATIONS", module: "RENTAL_HANDOVER", phase: P, title: "Riserve sulla consegna non risolte", description: "Riserve sulla consegna non risolte", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.handover.openReservationCount","value":0}, outcome: {"code":"HANDOVER_RESERVATIONS_OPEN","message":"Assegnare responsabilità e scadenza a ogni riserva aperta.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_PARTY_SIGNOFF_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Verbale non firmato dalle parti", description: "Verbale non firmato dalle parti", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.handover.signoffStatus","value":"COMPLETED"}, outcome: {"code":"HANDOVER_SIGNOFF_REQUIRED","message":"Il verbale finale richiede conferma delle parti presenti.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_UTILITY_INSTRUCTIONS_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Istruzioni utenze e servizi mancanti", description: "Istruzioni utenze e servizi mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.utilityInstructionStatus","value":"READY"}, outcome: {"code":"HANDOVER_UTILITY_INSTRUCTIONS_REQUIRED","message":"Consegnare istruzioni e responsabilità per utenze e servizi.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_EMERGENCY_CONTACTS_MISSING", module: "RENTAL_HANDOVER", phase: P, title: "Contatti di assistenza mancanti", description: "Contatti di assistenza mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.handover.supportContactStatus","value":"READY"}, outcome: {"code":"HANDOVER_SUPPORT_CONTACT_REQUIRED","message":"Fornire canale Guimmia e contatti di emergenza applicabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_AI_COMPLETION_SOURCE", module: "RENTAL_HANDOVER", phase: P, title: "Completamento consegna attribuito all'AI", description: "Completamento consegna attribuito all'AI", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"eq","path":"rental.handover.completionSource","value":"AI_ONLY"}, outcome: {"code":"AI_HANDOVER_COMPLETION_FORBIDDEN","message":"La chiusura del verbale richiede un attore umano.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_KEY_EVENT_CONFLICT", module: "RENTAL_HANDOVER", phase: P, title: "Conflitto negli eventi chiavi", description: "Conflitto negli eventi chiavi", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.handover.keyEventConflictCount","value":0}, outcome: {"code":"HANDOVER_KEY_EVENT_CONFLICT","message":"Riconciliare gli eventi senza sovrascrivere la cronologia.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R10_READY", module: "RENTAL_HANDOVER", phase: P, title: "Consegna completata", description: "Consegna completata", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.handoverStatus","value":"COMPLETED"}, outcome: {"code":"HANDOVER_COMPLETED","message":"Consegna, evidenze e verbale sono completi."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
