
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK03Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K03_DECISION_RUN_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Decision Run Missing",factPath:"guimmia.orchestrator.k03.decision_run_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_INPUT_FINGERPRINT_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Input Fingerprint Missing",factPath:"guimmia.orchestrator.k03.input_fingerprint_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_RULE_EVALUATION_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Rule Evaluation Missing",factPath:"guimmia.orchestrator.k03.rule_evaluation_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_CANDIDATE_ACTION_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Candidate Action Missing",factPath:"guimmia.orchestrator.k03.candidate_action_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_PRIORITY_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Priority Missing",factPath:"guimmia.orchestrator.k03.action_priority_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_OWNER_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Owner Missing",factPath:"guimmia.orchestrator.k03.action_owner_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_DUE_AT_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Due At Missing",factPath:"guimmia.orchestrator.k03.action_due_at_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_REASON_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Reason Missing",factPath:"guimmia.orchestrator.k03.action_reason_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_DEPENDENCY_UNRESOLVED",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Dependency Unresolved",factPath:"guimmia.orchestrator.k03.action_dependency_unresolved.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_DUPLICATE_ACTIVE",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Duplicate Active",factPath:"guimmia.orchestrator.k03.action_duplicate_active.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_ACTION_SUPERSEDED_NOT_CLOSED",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Action Superseded Not Closed",factPath:"guimmia.orchestrator.k03.action_superseded_not_closed.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_CUSTOMER_QUESTION_NOT_MINIMAL",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Customer Question Not Minimal",factPath:"guimmia.orchestrator.k03.customer_question_not_minimal.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_CUSTOMER_QUESTION_ALREADY_ANSWERED",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Customer Question Already Answered",factPath:"guimmia.orchestrator.k03.customer_question_already_answered.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_NEXT_ACTION_NOT_SELECTED",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Next Action Not Selected",factPath:"guimmia.orchestrator.k03.next_action_not_selected.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_NEXT_ACTION_NOT_EXPLAINED",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Next Action Not Explained",factPath:"guimmia.orchestrator.k03.next_action_not_explained.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_NEXT_ACTION_STALE",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Next Action Stale",factPath:"guimmia.orchestrator.k03.next_action_stale.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_NO_SAFE_ACTION_AVAILABLE",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"No Safe Action Available",factPath:"guimmia.orchestrator.k03.no_safe_action_available.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K03_DECISION_OUTPUT_MISSING",module:"CASE_NEXT_BEST_ACTION",phase:"PHASE_K03_NEXT_BEST_ACTION",title:"Decision Output Missing",factPath:"guimmia.orchestrator.k03.decision_output_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
