import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO08Rules:BrainRule[]=[
  makeAgencyRule({"id":"O08_MEMBER_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Member Missing","factPath":"agency.o08.member_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_ROLE_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Role Missing","factPath":"agency.o08.role_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_PERMISSION_DENIED","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Permission Denied","factPath":"agency.o08.permission_denied.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_FOUR_EYES_REVIEW_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Four Eyes Review Missing","factPath":"agency.o08.four_eyes_review_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_CRITICAL_ACTION_UNAPPROVED","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Critical Action Unapproved","factPath":"agency.o08.critical_action_unapproved.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_AUDIT_EVENT_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Audit Event Missing","factPath":"agency.o08.audit_event_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_AUDIT_HASH_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Audit Hash Missing","factPath":"agency.o08.audit_hash_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_POLICY_VERSION_MISSING","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Policy Version Missing","factPath":"agency.o08.policy_version_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"],"rulesetKey":"ITALY_AGENCY_POLICY_VERSION"}),
  makeAgencyRule({"id":"O08_KNOWLEDGE_FRESHNESS_EXPIRED","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Knowledge Freshness Expired","factPath":"agency.o08.knowledge_freshness_expired.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"],"rulesetKey":"ITALY_AGENCY_KNOWLEDGE_FRESHNESS"}),
  makeAgencyRule({"id":"O08_WORKLOAD_OVER_CAPACITY","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Workload Over Capacity","factPath":"agency.o08.workload_over_capacity.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_SLA_DASHBOARD_STALE","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Sla Dashboard Stale","factPath":"agency.o08.sla_dashboard_stale.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_OPEN_ESCALATION","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Open Escalation","factPath":"agency.o08.open_escalation.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_CLIENT_COMPLAINT_UNRESOLVED","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Client Complaint Unresolved","factPath":"agency.o08.client_complaint_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_CUSTOMER_SERVICE_MODEL_MISMATCH","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Customer Service Model Mismatch","factPath":"agency.o08.customer_service_model_mismatch.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_OUTCOME_FEE_LABEL_FORBIDDEN","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Outcome Fee Label Forbidden","factPath":"agency.o08.outcome_fee_label_forbidden.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]}),
  makeAgencyRule({"id":"O08_READY","module":"AGENCY_CONTROL_AUDIT","phase":"PHASE_O08_AGENCY_CONTROL","title":"Ready","factPath":"agency.o08.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","LEASE_REGISTRATION","HANDOVER","TOURIST_PUBLICATION","BOOKING","CHECK_IN","GUEST_REPORTING","PAYOUT_TAX"]})
];
