import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP13Rules:BrainRule[]=[
  makeSaleRule({"id":"P13_ACCEPTED_OFFER_MISSING","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Accepted Offer Missing","factPath":"sale.p13.accepted_offer_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_PRELIMINARY_GATE_NOT_READY","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Preliminary Gate Not Ready","factPath":"sale.p13.preliminary_gate_not_ready.status","decisionLevel":"REVIEW","severity":"critical","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_TEMPLATE_NOT_APPROVED","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Template Not Approved","factPath":"sale.p13.template_not_approved.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_INPUTS_STALE","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Inputs Stale","factPath":"sale.p13.inputs_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_PARTY_IDENTITY_MISMATCH","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Party Identity Mismatch","factPath":"sale.p13.party_identity_mismatch.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_PROFESSIONAL_REVIEW_MISSING","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Professional Review Missing","factPath":"sale.p13.professional_review_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_SUSPENSIVE_CONDITION_UNTRACKED","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Suspensive Condition Untracked","factPath":"sale.p13.suspensive_condition_untracked.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_DEPOSIT_EVIDENCE_MISSING","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Deposit Evidence Missing","factPath":"sale.p13.deposit_evidence_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_SIGNATURES_INCOMPLETE","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Signatures Incomplete","factPath":"sale.p13.signatures_incomplete.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_REGISTRATION_TASK_UNKNOWN","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Registration Task Unknown","factPath":"sale.p13.registration_task_unknown.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PRELIMINARY","rulesetKey":"ITALY_SALE_REGISTRATION_TASK"}),
  makeSaleRule({"id":"P13_TRANSCRIPTION_REVIEW_UNKNOWN","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Transcription Review Unknown","factPath":"sale.p13.transcription_review_unknown.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PRELIMINARY","rulesetKey":"ITALY_SALE_TRANSCRIPTION_REVIEW"}),
  makeSaleRule({"id":"P13_DEADLINE_MISSING","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Deadline Missing","factPath":"sale.p13.deadline_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_CONTENT_CHANGED","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Content Changed","factPath":"sale.p13.content_changed.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PRELIMINARY"}),
  makeSaleRule({"id":"P13_READY","module":"SALE_PRELIMINARY","phase":"PHASE_13_PRELIMINARY","title":"Ready","factPath":"sale.p13.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"PRELIMINARY"})
];
