import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO03Rules:BrainRule[]=[
  makeAgencyRule({"id":"O03_THREAD_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Thread Missing","factPath":"agency.o03.thread_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_CASE_LINK_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Case Link Missing","factPath":"agency.o03.case_link_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_PARTICIPANT_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Participant Missing","factPath":"agency.o03.participant_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_MESSAGE_DIRECTION_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Message Direction Missing","factPath":"agency.o03.message_direction_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_ACTOR_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Actor Missing","factPath":"agency.o03.actor_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_CONTENT_HASH_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Content Hash Missing","factPath":"agency.o03.content_hash_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_IDEMPOTENCY_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Idempotency Missing","factPath":"agency.o03.idempotency_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_TEMPLATE_VERSION_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Template Version Missing","factPath":"agency.o03.template_version_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_MATERIAL_COMMUNICATION_UNRECORDED","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Material Communication Unrecorded","factPath":"agency.o03.material_communication_unrecorded.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_DECISION_RATIONALE_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Decision Rationale Missing","factPath":"agency.o03.decision_rationale_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_HUMAN_DECISION_MISSING","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Human Decision Missing","factPath":"agency.o03.human_decision_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_AI_LEGAL_CONCLUSION_FORBIDDEN","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Ai Legal Conclusion Forbidden","factPath":"agency.o03.ai_legal_conclusion_forbidden.status","decisionLevel":"REVIEW","severity":"critical","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_AI_COUNTEROFFER_FORBIDDEN","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Ai Counteroffer Forbidden","factPath":"agency.o03.ai_counteroffer_forbidden.status","decisionLevel":"REVIEW","severity":"critical","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_DELIVERY_FAILURE_UNRESOLVED","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Delivery Failure Unresolved","factPath":"agency.o03.delivery_failure_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_FOLLOWUP_OVERDUE","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Followup Overdue","factPath":"agency.o03.followup_overdue.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]}),
  makeAgencyRule({"id":"O03_ACTIVE","module":"AGENCY_COMMUNICATION_AUDIT","phase":"PHASE_O03_COMMUNICATION_AUDIT","title":"Active","factPath":"agency.o03.active.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["OFFER","PRELIMINARY","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING"]})
];
