import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO04Rules:BrainRule[]=[
  makeAgencyRule({"id":"O04_APPOINTMENT_TYPE_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Appointment Type Missing","factPath":"agency.o04.appointment_type_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_CASE_LINK_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Case Link Missing","factPath":"agency.o04.case_link_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_PARTICIPANT_CONFIRMATION_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Participant Confirmation Missing","factPath":"agency.o04.participant_confirmation_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_CALENDAR_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Calendar Missing","factPath":"agency.o04.calendar_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_AVAILABILITY_STALE","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Availability Stale","factPath":"agency.o04.availability_stale.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_TIMEZONE_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Timezone Missing","factPath":"agency.o04.timezone_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_SLOT_CONFLICT","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Slot Conflict","factPath":"agency.o04.slot_conflict.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_TRAVEL_BUFFER_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Travel Buffer Missing","factPath":"agency.o04.travel_buffer_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_LOCATION_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Location Missing","factPath":"agency.o04.location_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_ACCESS_INSTRUCTIONS_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Access Instructions Missing","factPath":"agency.o04.access_instructions_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_PROVIDER_ACCEPTANCE_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Provider Acceptance Missing","factPath":"agency.o04.provider_acceptance_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_CUSTOMER_CONFIRMATION_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Customer Confirmation Missing","factPath":"agency.o04.customer_confirmation_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_REMINDER_UNSENT","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Reminder Unsent","factPath":"agency.o04.reminder_unsent.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_RESCHEDULE_UNACKNOWLEDGED","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Reschedule Unacknowledged","factPath":"agency.o04.reschedule_unacknowledged.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_CANCELLATION_POLICY_MISSING","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Cancellation Policy Missing","factPath":"agency.o04.cancellation_policy_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_NO_SHOW_UNRESOLVED","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"No Show Unresolved","factPath":"agency.o04.no_show_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_AI_UNCONFIRMED_BOOKING_FORBIDDEN","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Ai Unconfirmed Booking Forbidden","factPath":"agency.o04.ai_unconfirmed_booking_forbidden.status","decisionLevel":"REVIEW","severity":"critical","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O04_READY","module":"AGENCY_APPOINTMENT_SCHEDULING","phase":"PHASE_O04_APPOINTMENT_SCHEDULING","title":"Ready","factPath":"agency.o04.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]})
];
