import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP14Rules:BrainRule[]=[
  makeSaleRule({"id":"P14_PRELIMINARY_NOT_READY","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Preliminary Not Ready","factPath":"sale.p14.preliminary_not_ready.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_CLOSING_GATE_NOT_READY","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Closing Gate Not Ready","factPath":"sale.p14.closing_gate_not_ready.status","decisionLevel":"REVIEW","severity":"critical","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_NOTARY_ASSIGNMENT_MISSING","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Notary Assignment Missing","factPath":"sale.p14.notary_assignment_missing.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"CLOSING","rulesetKey":"ITALY_SALE_NOTARY_ASSIGNMENT"}),
  makeSaleRule({"id":"P14_NOTARY_CHECKLIST_INCOMPLETE","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Notary Checklist Incomplete","factPath":"sale.p14.notary_checklist_incomplete.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"CLOSING","rulesetKey":"ITALY_SALE_NOTARY_CHECKLIST_INCOMPLETE"}),
  makeSaleRule({"id":"P14_DOCUMENT_PACKAGE_STALE","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Document Package Stale","factPath":"sale.p14.document_package_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_PARTY_IDENTITY_MISMATCH","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Party Identity Mismatch","factPath":"sale.p14.party_identity_mismatch.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_PAYMENT_PLAN_UNVERIFIED","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Payment Plan Unverified","factPath":"sale.p14.payment_plan_unverified.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_MORTGAGE_CANCELLATION_UNRESOLVED","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Mortgage Cancellation Unresolved","factPath":"sale.p14.mortgage_cancellation_unresolved.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING","rulesetKey":"ITALY_SALE_MORTGAGE_CANCELLATION"}),
  makeSaleRule({"id":"P14_CONDOMINIUM_UPDATE_STALE","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Condominium Update Stale","factPath":"sale.p14.condominium_update_stale.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING","rulesetKey":"ITALY_SALE_CONDOMINIUM_UPDATE"}),
  makeSaleRule({"id":"P14_TAX_REVIEW_STALE","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Tax Review Stale","factPath":"sale.p14.tax_review_stale.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING","rulesetKey":"ITALY_SALE_TAX_REVIEW"}),
  makeSaleRule({"id":"P14_UTILITIES_HANDOVER_MISSING","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Utilities Handover Missing","factPath":"sale.p14.utilities_handover_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_KEY_HANDOVER_MISSING","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Key Handover Missing","factPath":"sale.p14.key_handover_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_FINAL_STATEMENT_MISSING","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Final Statement Missing","factPath":"sale.p14.final_statement_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_SIGNATURE_EVIDENCE_MISSING","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Signature Evidence Missing","factPath":"sale.p14.signature_evidence_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_AI_COMPLETION_FORBIDDEN","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Ai Completion Forbidden","factPath":"sale.p14.ai_completion_forbidden.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gate":"CLOSING"}),
  makeSaleRule({"id":"P14_COMPLETED","module":"SALE_CLOSING","phase":"PHASE_14_NOTARY_CLOSING","title":"Completed","factPath":"sale.p14.completed.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"CLOSING"})
];
