import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";

const P = "PHASE_04_URBAN_CADASTRAL";
const M = "URBAN_CADASTRAL";
const fresh = (rulesetKey: string) => ({ required: true, rulesetKey, maxAgeDays: 30 });

export const phase04Rules: BrainRule[] = [
  {
    id: "P04_DOSSIER_NOT_READY", module: M, phase: P,
    title: "Fascicolo P03 non pronto",
    description: "La due diligence tecnica parte solo da uno snapshot documentale corrente.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"neq","path":"documents.dossierReadiness","value":"READY"},
    outcome: {"code":"DOSSIER_NOT_READY","message":"Riaprire/completare P03 prima di P04.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SCOPE_NOT_LOCKED", module: M, phase: P,
    title: "Oggetto tecnico non definito",
    description: "Unità principale, pertinenze, quote fisiche e componenti devono essere esplicitamente incluse/escluse.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"neq","path":"technical.scopeStatus","value":"LOCKED"},
    outcome: {"code":"SCOPE_NOT_LOCKED","message":"Definire e approvare l'oggetto tecnico della verifica.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_COMPONENTS_UNMAPPED", module: M, phase: P,
    title: "Pertinenze/componenti non mappati",
    description: "Garage, cantine, posti auto, soffitte e altri componenti dichiarati devono essere riconciliati.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"gt","path":"technical.unmappedComponentCount","value":0},
    outcome: {"code":"COMPONENTS_UNMAPPED","message":"Riconciliare tutti i componenti dell'oggetto di vendita.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_COMPONENT_EXCLUSION_UNEXPLAINED", module: M, phase: P,
    title: "Componente escluso senza motivazione",
    description: "Un componente presente nelle fonti ma escluso dal perimetro deve avere motivazione e approvazione.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: {"op":"gt","path":"technical.unexplainedExcludedComponentCount","value":0},
    outcome: {"code":"COMPONENT_EXCLUSION_UNEXPLAINED","message":"Documentare l'esclusione dal perimetro.","escalationTo":"AGENT","gateImpact":["PUBLICATION"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SOURCE_MAP_INCOMPLETE", module: M, phase: P,
    title: "Mappa fonti incompleta",
    description: "Ogni conclusione tecnica deve essere ricondotta a fonti classificate per dominio.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"neq","path":"technical.sourceMapStatus","value":"COMPLETE"},
    outcome: {"code":"SOURCE_MAP_INCOMPLETE","message":"Completare la mappa delle fonti tecniche.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SOURCE_DOMAIN_CONFLICT", module: M, phase: P,
    title: "Conflitto tra domini informativi",
    description: "Catasto, urbanistica, titolo e stato fisico non devono essere appiattiti in un'unica gerarchia.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"gt","path":"technical.crossDomainConflictCount","value":0},
    outcome: {"code":"SOURCE_DOMAIN_CONFLICT","message":"Richiedere interpretazione professionale del conflitto; non auto-risolvere.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"],"professionalScope":["Interpretare fonti di domini differenti","Indicare quale ulteriore evidenza è necessaria"],"reasonCodes":["SOURCE_DOMAIN_CONFLICT"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CURRENT_STATE_REQUIRED", module: M, phase: P,
    title: "Stato fisico attuale non rilevato",
    description: "Quando il confronto dipende dalla configurazione reale serve osservazione/sopralluogo adeguato.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"all","conditions":[{"op":"truthy","path":"technical.physicalObservationRequired"},{"op":"neq","path":"technical.physicalObservationStatus","value":"COMPLETED"}]},
    outcome: {"code":"CURRENT_STATE_REQUIRED","message":"Acquisire osservazione professionale dello stato attuale.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER"],"professionalScope":["Rilevare configurazione attuale","Documentare differenze visibili"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_TIMELINE_NOT_BUILT", module: M, phase: P,
    title: "Cronologia tecnica non costruita",
    description: "Titoli, lavori, variazioni, agibilità e aggiornamenti devono essere collocati in timeline.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"neq","path":"technical.timelineStatus","value":"BUILT"},
    outcome: {"code":"TIMELINE_NOT_BUILT","message":"Costruire la cronologia tecnica.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_TIMELINE_UNKNOWN_EVENTS", module: M, phase: P,
    title: "Cronologia con eventi non chiariti",
    description: "Eventi tecnici UNKNOWN impediscono una ricostruzione affidabile.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"gt","path":"technical.timelineUnknownCount","value":0},
    outcome: {"code":"TIMELINE_UNKNOWN_EVENTS","message":"Chiarire gli eventi tecnici non documentati.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_INPUT_FINGERPRINT_MISSING", module: M, phase: P,
    title: "Fingerprint input assente",
    description: "La verifica deve essere legata a un set preciso di documenti/facts.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"falsy","path":"technical.inputFingerprint"},
    outcome: {"code":"INPUT_FINGERPRINT_MISSING","message":"Generare il fingerprint degli input tecnici.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CHAIN_OF_EVIDENCE_GAP", module: M, phase: P,
    title: "Catena evidenze incompleta",
    description: "Finding e confronti sostanziali devono risalire a documenti/evidence anchor o osservazioni professionali.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"gt","path":"technical.unanchoredConclusionCount","value":0},
    outcome: {"code":"CHAIN_OF_EVIDENCE_GAP","message":"Collegare evidenze alle conclusioni tecniche.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_REQUIRED", module: M, phase: P,
    title: "Accesso atti da avviare",
    description: "La pratica richiede acquisizione di atti comunali/tecnici non ancora disponibili.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.recordAccessStatus","value":"TO_REQUEST"},
    outcome: {"code":"RECORD_ACCESS_REQUIRED","message":"Avviare richiesta accesso atti.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_NOT_INITIATED", module: M, phase: P,
    title: "Accesso atti richiesto ma non avviato",
    description: "Un bisogno di accesso atti identificato non può restare senza richiesta.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"all","conditions":[{"op":"truthy","path":"technical.recordAccessRequired"},{"op":"eq","path":"technical.recordAccessStatus","value":"NOT_REQUIRED"}]},
    outcome: {"code":"RECORD_ACCESS_NOT_INITIATED","message":"Correggere lo stato e aprire la richiesta accesso atti.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_PENDING", module: M, phase: P,
    title: "Accesso atti in attesa",
    description: "La richiesta è stata inoltrata ma il fascicolo non è ancora disponibile.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.recordAccessStatus","value":"REQUESTED"},
    outcome: {"code":"RECORD_ACCESS_PENDING","message":"Monitorare accesso atti e non chiudere la verifica.","gateImpact":["OFFER","PRELIMINARY"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_PARTIAL", module: M, phase: P,
    title: "Accesso atti parziale",
    description: "Il Comune/ente ha fornito solo parte del fascicolo richiesto.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.recordAccessStatus","value":"PARTIAL"},
    outcome: {"code":"RECORD_ACCESS_PARTIAL","message":"Valutare con il tecnico se gli atti disponibili sono sufficienti e cosa integrare.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_FAILED", module: M, phase: P,
    title: "Accesso atti non completato",
    description: "La richiesta è fallita o non ha prodotto documentazione utilizzabile.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.recordAccessStatus","value":"FAILED"},
    outcome: {"code":"RECORD_ACCESS_FAILED","message":"Gestire il fallimento della richiesta e decidere il percorso alternativo.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RECORD_ACCESS_STALE", module: M, phase: P,
    title: "Accesso atti non più corrente",
    description: "Nuovi fatti/documenti rendono necessario rivalutare l'accesso atti.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"eq","path":"technical.recordAccessStatus","value":"STALE"},
    outcome: {"code":"RECORD_ACCESS_STALE","message":"Ricalcolare la necessità e aggiornare gli atti.","blockProgress":true,"gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_COMPARISONS_NOT_COMPLETE", module: M, phase: P,
    title: "Confronti strutturati incompleti",
    description: "I confronti applicabili devono essere eseguiti o marcati motivatamente non applicabili.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"neq","path":"technical.comparisonStatus","value":"COMPLETED"},
    outcome: {"code":"COMPARISONS_NOT_COMPLETE","message":"Completare i confronti tecnici applicabili.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_UNKNOWN_COMPARISONS", module: M, phase: P,
    title: "Confronti con esito UNKNOWN",
    description: "Gli esiti UNKNOWN devono essere instradati a integrazione/review.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"gt","path":"technical.unknownComparisonCount","value":0},
    outcome: {"code":"UNKNOWN_COMPARISONS","message":"Raccogliere evidenze o motivare l'impossibilità del confronto.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CADASTRAL_ID_MISSING", module: M, phase: P,
    title: "Identificativi catastali mancanti",
    description: "Foglio/particella/subalterno non sono disponibili in forma sufficiente.",
    stability: "STABLE", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"eq","path":"technical.cadastralIdentityStatus","value":"MISSING"},
    outcome: {"code":"CADASTRAL_ID_MISSING","message":"Acquisire e verificare gli identificativi catastali.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_CADASTRAL_ID_MISMATCH", module: M, phase: P,
    title: "Identificativi catastali discordanti",
    description: "Le fonti riportano identificativi non coerenti.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.cadastralIdentityStatus","value":"MISMATCH"},
    outcome: {"code":"CADASTRAL_ID_MISMATCH","message":"Riconciliare l'identità dell'unità prima di proseguire.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_CADASTRAL_ADDRESS_MISMATCH", module: M, phase: P,
    title: "Indirizzo catastale discordante",
    description: "L'indirizzo catastale differisce dai dati della pratica.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.cadastralAddressComparison","value":"MISMATCH"},
    outcome: {"code":"CADASTRAL_ADDRESS_MISMATCH","message":"Verificare natura e materialità della discordanza.","gateImpact":["PUBLICATION"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CADASTRAL_CATEGORY_MISMATCH", module: M, phase: P,
    title: "Categoria catastale da approfondire",
    description: "Categoria catastale e uso dichiarato non sono coerenti o non interpretabili automaticamente.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.cadastralCategoryComparison","value":"MISMATCH"},
    outcome: {"code":"CADASTRAL_CATEGORY_MISMATCH","message":"Aprire review senza dedurre automaticamente irregolarità urbanistica.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PLAN_MISSING", module: M, phase: P,
    title: "Planimetria catastale non disponibile",
    description: "Manca la planimetria necessaria ai confronti previsti.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"eq","path":"technical.cadastralPlanStatus","value":"MISSING"},
    outcome: {"code":"PLAN_MISSING","message":"Acquisire planimetria o documentare perché non applicabile.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PLAN_STALE", module: M, phase: P,
    title: "Planimetria potenzialmente non corrente",
    description: "La versione disponibile non è allineata agli eventi successivi noti.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"eq","path":"technical.cadastralPlanStatus","value":"STALE"},
    outcome: {"code":"PLAN_STALE","message":"Acquisire/validare una planimetria corrente.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PLAN_OBSERVED_MISMATCH", module: M, phase: P,
    title: "Planimetria e stato osservato discordanti",
    description: "Il confronto automatico/assistito segnala possibile differenza di configurazione.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.planVsObserved","value":"MISMATCH"},
    outcome: {"code":"PLAN_OBSERVED_MISMATCH","message":"Richiedere verifica tecnica; Guimmia non qualifica la difformità.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY"],"professionalScope":["Confrontare planimetria e stato rilevato","Qualificare tecnicamente la differenza"],"reasonCodes":["PLAN_OBSERVED_MISMATCH"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PLAN_DECLARED_MISMATCH", module: M, phase: P,
    title: "Planimetria e dichiarazione proprietario discordanti",
    description: "La dichiarazione del cliente non coincide con la planimetria disponibile.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.planVsDeclared","value":"MISMATCH"},
    outcome: {"code":"PLAN_DECLARED_MISMATCH","message":"Chiarire con cliente/agente prima di assumere il dato.","gateImpact":["PUBLICATION"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SURFACE_MISMATCH", module: M, phase: P,
    title: "Superficie discordante",
    description: "Le superfici disponibili differiscono in modo da richiedere review.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.surfaceComparison","value":"MISMATCH"},
    outcome: {"code":"SURFACE_MISMATCH","message":"Mostrare valori, metodi e fonti; non scegliere automaticamente.","gateImpact":["PUBLICATION"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CADASTRAL_HISTORY_GAP", module: M, phase: P,
    title: "Storico catastale insufficiente",
    description: "La ricostruzione temporale richiede dati catastali storici non disponibili.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"truthy","path":"technical.cadastralHistoryGap"},
    outcome: {"code":"CADASTRAL_HISTORY_GAP","message":"Valutare acquisizione storico catastale.","gateImpact":["OFFER","PRELIMINARY"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_URBAN_TITLE_CHAIN_INCOMPLETE", module: M, phase: P,
    title: "Catena titoli edilizi incompleta",
    description: "Le pratiche disponibili non consentono una ricostruzione tecnica completa.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.urbanTitleChainStatus","value":"INCOMPLETE"},
    outcome: {"code":"URBAN_TITLE_CHAIN_INCOMPLETE","message":"Richiedere ricostruzione professionale della catena documentale.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"],"professionalScope":["Ricostruire titoli/pratiche rilevanti","Segnalare lacune documentali"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_URBAN_TITLE_STATUS_UNCLEAR", module: M, phase: P,
    title: "Stato pratica edilizia non chiaro",
    description: "Una pratica risulta dichiarata/presente ma il suo stato/esito non è documentato.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.urbanTitleStatus","value":"UNCLEAR"},
    outcome: {"code":"URBAN_TITLE_STATUS_UNCLEAR","message":"Chiarire lo stato della pratica presso fonte competente.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_DECLARED_WORKS_NO_TITLE", module: M, phase: P,
    title: "Lavori dichiarati senza titolo collegato",
    description: "Sono dichiarati interventi ma non è stato ricostruito il relativo percorso amministrativo.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"gt","path":"technical.declaredWorksWithoutTitleCount","value":0},
    outcome: {"code":"DECLARED_WORKS_NO_TITLE","message":"Instradare al tecnico per verifica di titoli/pratiche applicabili.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_OBSERVED_WORKS_NO_TITLE", module: M, phase: P,
    title: "Opere osservate senza titolo collegato",
    description: "Lo stato rilevato presenta elementi non riconciliati con la documentazione amministrativa.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: {"op":"gt","path":"technical.observedWorksWithoutTitleCount","value":0},
    outcome: {"code":"OBSERVED_WORKS_NO_TITLE","message":"Bloccare conclusioni automatiche e richiedere verifica tecnica.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    active: true, version: 2,
  },
  {
    id: "P04_STATE_LEGITIMATE_UNKNOWN", module: M, phase: P,
    title: "Stato legittimo non ricostruito",
    description: "La qualificazione dello stato legittimo dipende da normativa corrente e ricostruzione tecnica.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.legitimateStateStatus","value":"UNKNOWN"},
    outcome: {"code":"STATE_LEGITIMATE_UNKNOWN","message":"Richiedere ricostruzione tecnica secondo normativa corrente.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"],"professionalScope":["Ricostruire lo stato legittimo","Indicare titoli/documenti probanti utilizzati"],"reasonCodes":["STATE_LEGITIMATE_NOT_RECONSTRUCTED"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_STATE],
    freshnessPolicy: fresh("IT_DPR380_STATE_LEGITIMATE"),
    active: true, version: 2,
  },
  {
    id: "P04_HISTORIC_BASIS_UNPROVEN", module: M, phase: P,
    title: "Immobile storico: base documentale da verificare",
    description: "Per epoca/circostanze dichiarate non è sufficiente una semplice dichiarazione del proprietario.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.historicConstructionBasisReviewRequired"},
    outcome: {"code":"HISTORIC_BASIS_UNPROVEN","message":"Verificare documenti probanti e normativa applicabile.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_STATE],
    freshnessPolicy: fresh("IT_DPR380_STATE_LEGITIMATE"),
    active: true, version: 2,
  },
  {
    id: "P04_USE_CADASTRAL_MISMATCH", module: M, phase: P,
    title: "Uso dichiarato e categoria catastale discordanti",
    description: "La discordanza è un segnale da approfondire ma non prova da sola l'uso urbanistico legittimo.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.useCadastreComparison","value":"MISMATCH"},
    outcome: {"code":"USE_CADASTRAL_MISMATCH","message":"Aprire review e verificare la fonte urbanistica competente.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_USE_URBAN_MISMATCH", module: M, phase: P,
    title: "Uso dichiarato e uso urbanistico discordanti",
    description: "Il dato richiede applicazione della disciplina vigente sul mutamento d'uso.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.useUrbanComparison","value":"MISMATCH"},
    outcome: {"code":"USE_URBAN_MISMATCH","message":"Richiedere qualificazione tecnica del possibile mutamento d'uso.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_USE],
    freshnessPolicy: fresh("IT_DPR380_USE"),
    active: true, version: 2,
  },
  {
    id: "P04_CHANGE_OF_USE_SUSPECTED", module: M, phase: P,
    title: "Possibile mutamento di destinazione d'uso",
    description: "Segnali documentali/fisici suggeriscono un possibile mutamento d'uso.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.changeOfUseSuspected"},
    outcome: {"code":"CHANGE_OF_USE_SUSPECTED","message":"Non qualificare automaticamente; attivare verifica tecnica e normativa.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_USE],
    freshnessPolicy: fresh("IT_DPR380_USE"),
    active: true, version: 2,
  },
  {
    id: "P04_AGIBILITY_UNKNOWN", module: M, phase: P,
    title: "Agibilità non chiarita",
    description: "La pratica non ha ancora una posizione documentata sull'agibilità.",
    stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"eq","path":"technical.agibilityStatus","value":"UNKNOWN"},
    outcome: {"code":"AGIBILITY_UNKNOWN","message":"Raccogliere/interpretare documentazione corrente sull'agibilità.","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_AGIBILITY],
    freshnessPolicy: fresh("IT_DPR380_AGIBILITY"),
    active: true, version: 2,
  },
  {
    id: "P04_AGIBILITY_SCOPE_MISMATCH", module: M, phase: P,
    title: "Ambito agibilità da verificare",
    description: "L'ambito della documentazione di agibilità non appare allineato alla configurazione attuale.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.agibilityScopeComparison","value":"MISMATCH"},
    outcome: {"code":"AGIBILITY_SCOPE_MISMATCH","message":"Richiedere verifica professionale dell'ambito e degli effetti.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_AGIBILITY],
    freshnessPolicy: fresh("IT_DPR380_AGIBILITY"),
    active: true, version: 2,
  },
  {
    id: "P04_PROTECTED_PROPERTY", module: M, phase: P,
    title: "Immobile soggetto a tutela/vincolo",
    description: "La verifica urbanistica deve considerare la disciplina di tutela applicabile.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.protectedPropertyReviewRequired"},
    outcome: {"code":"PROTECTED_PROPERTY","message":"Attivare verifica competente prima di assumere conclusioni.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    freshnessPolicy: fresh("IT_PROTECTED_PROPERTY"),
    active: true, version: 2,
  },
  {
    id: "P04_LOCAL_RULES_REQUIRED", module: M, phase: P,
    title: "Disciplina regionale/comunale necessaria",
    description: "Il caso richiede norme/local planning non presenti nel ruleset nazionale.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.localRulesRequired"},
    outcome: {"code":"LOCAL_RULES_REQUIRED","message":"Verificare normativa regionale/comunale e strumenti urbanistici vigenti.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    freshnessPolicy: fresh("IT_REGIONAL_LOCAL_URBAN"),
    active: true, version: 2,
  },
  {
    id: "P04_TOLERANCE_CLAIM", module: M, phase: P,
    title: "Possibile tolleranza da qualificare",
    description: "Guimmia può rilevare uno scostamento ma non può dichiararlo tolleranza.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.toleranceClaimCandidate"},
    outcome: {"code":"TOLERANCE_CLAIM","message":"Richiedere qualificazione del tecnico con ruleset corrente.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"],"professionalScope":["Valutare applicabilità delle tolleranze","Documentare misure e basi normative"],"reasonCodes":["TOLERANCE_REVIEW"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_TOLERANCES],
    freshnessPolicy: fresh("IT_DPR380_TOLERANCES"),
    active: true, version: 2,
  },
  {
    id: "P04_SANATORIA_PENDING", module: M, phase: P,
    title: "Regolarizzazione pendente",
    description: "È indicato un procedimento di regolarizzazione non concluso.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: {"op":"eq","path":"technical.sanatoriaStatus","value":"PENDING"},
    outcome: {"code":"SANATORIA_PENDING","message":"Mantenere il caso bloccato sui gate interessati fino a esito/documentazione adeguata.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_CONFORMITY],
    freshnessPolicy: fresh("IT_DPR380_CONFORMITY"),
    active: true, version: 2,
  },
  {
    id: "P04_SANATORIA_OUTCOME_UNKNOWN", module: M, phase: P,
    title: "Esito regolarizzazione non documentato",
    description: "Una pratica dichiarata non ha esito verificato.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.sanatoriaStatus","value":"OUTCOME_UNKNOWN"},
    outcome: {"code":"SANATORIA_OUTCOME_UNKNOWN","message":"Acquisire esito e verifica professionale.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_CONFORMITY],
    freshnessPolicy: fresh("IT_DPR380_CONFORMITY"),
    active: true, version: 2,
  },
  {
    id: "P04_CONDONO_PENDING", module: M, phase: P,
    title: "Condono pendente",
    description: "È presente una domanda di condono senza esito documentato.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: {"op":"eq","path":"technical.condonoStatus","value":"PENDING"},
    outcome: {"code":"CONDONO_PENDING","message":"Acquisire fascicolo/esito e verifica professionale.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    freshnessPolicy: fresh("IT_REGIONAL_LOCAL_URBAN"),
    active: true, version: 2,
  },
  {
    id: "P04_CONDONO_OUTCOME_UNKNOWN", module: M, phase: P,
    title: "Esito condono non documentato",
    description: "La pratica di condono dichiarata non ha un esito riconciliato.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.condonoStatus","value":"OUTCOME_UNKNOWN"},
    outcome: {"code":"CONDONO_OUTCOME_UNKNOWN","message":"Acquisire provvedimento/documentazione e farla interpretare.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE],
    freshnessPolicy: fresh("IT_REGIONAL_LOCAL_URBAN"),
    active: true, version: 2,
  },
  {
    id: "P04_POSSIBLE_UNAUTHORIZED_WORK", module: M, phase: P,
    title: "Possibile opera non assistita da percorso documentale coerente",
    description: "È un red flag, non una dichiarazione di abuso.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.possibleUnauthorizedWork"},
    outcome: {"code":"POSSIBLE_UNAUTHORIZED_WORK","message":"Bloccare verdict automatici e richiedere tecnico.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_CONFORMITY],
    freshnessPolicy: fresh("IT_DPR380_CONFORMITY"),
    active: true, version: 2,
  },
  {
    id: "P04_ONGOING_WORKS", module: M, phase: P,
    title: "Lavori in corso",
    description: "La configurazione dell'immobile è in evoluzione e gli snapshot tecnici possono diventare obsoleti.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: {"op":"truthy","path":"technical.ongoingWorks"},
    outcome: {"code":"ONGOING_WORKS","message":"Definire data/fase di riesame e documenti finali richiesti.","escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_TRANSFER_FORMALITY_REVIEW", module: M, phase: P,
    title: "Profili formali del trasferimento da verificare",
    description: "Il caso presenta elementi tecnici che richiedono verifica dei requisiti/formalità del trasferimento.",
    stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.transferFormalityReviewRequired"},
    outcome: {"code":"TRANSFER_FORMALITY_REVIEW","message":"Instradare la questione al professionista appropriato senza verdict IA.","blockProgress":true,"escalationTo":"NOTARY","gateImpact":["PRELIMINARY","CLOSING"]},
    sourceRefs: [SOURCE_MAP.URBAN_PRACTICE, SOURCE_MAP.DPR380_TRANSFER],
    freshnessPolicy: fresh("IT_DPR380_TRANSFER_FORMALITIES"),
    active: true, version: 2,
  },
  {
    id: "P04_AI_CONFORMITY_VERDICT_BLOCK", module: M, phase: P,
    title: "Verdict IA di conformità vietato",
    description: "Guimmia non deve produrre una certificazione autonoma di conformità urbanistica/catastale.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.aiConformityVerdictAttempted"},
    outcome: {"code":"AI_CONFORMITY_VERDICT_BLOCK","message":"Scartare il verdict e sostituirlo con finding/evidenze/review.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_AI_SANABILITY_VERDICT_BLOCK", module: M, phase: P,
    title: "Verdict IA di sanabilità vietato",
    description: "La sanabilità richiede valutazione normativa/tecnica corrente.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.aiSanabilityVerdictAttempted"},
    outcome: {"code":"AI_SANABILITY_VERDICT_BLOCK","message":"Bloccare l'output IA e attivare professionista.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_AI_TOLERANCE_VERDICT_BLOCK", module: M, phase: P,
    title: "Verdict IA di tolleranza vietato",
    description: "Un algoritmo non deve qualificare autonomamente uno scostamento come tolleranza.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.aiToleranceVerdictAttempted"},
    outcome: {"code":"AI_TOLERANCE_VERDICT_BLOCK","message":"Bloccare output e richiedere tecnico.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_AI_MARKETABILITY_VERDICT_BLOCK", module: M, phase: P,
    title: "Verdict IA di commerciabilità vietato",
    description: "Guimmia non rilascia nulla-osta alla circolazione dell'immobile.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.aiMarketabilityVerdictAttempted"},
    outcome: {"code":"AI_MARKETABILITY_VERDICT_BLOCK","message":"Bloccare il verdict e coinvolgere agente/professionista.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_EVIDENCE_GAP", module: M, phase: P,
    title: "Finding senza evidenza sufficiente",
    description: "Un finding sostanziale non ha collegamenti documentali/anchor adeguati.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"gt","path":"technical.evidenceGapCount","value":0},
    outcome: {"code":"EVIDENCE_GAP","message":"Completare la catena di evidenza.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PRO_REQUIRED_NO_REQUEST", module: M, phase: P,
    title: "Professionista richiesto ma handoff non creato",
    description: "La presenza di finding PROFESSIONAL_REQUIRED deve generare un incarico/handoff tracciato.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"all","conditions":[{"op":"truthy","path":"technical.professionalRequired"},{"op":"eq","path":"technical.professionalRequestStatus","value":"MISSING"}]},
    outcome: {"code":"PRO_REQUIRED_NO_REQUEST","message":"Creare richiesta tecnica con scope ed evidenze.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PRO_SCOPE_INCOMPLETE", module: M, phase: P,
    title: "Scope professionale incompleto",
    description: "La richiesta al tecnico deve specificare finding, controlli, input e output attesi.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.professionalScopeStatus","value":"INCOMPLETE"},
    outcome: {"code":"PRO_SCOPE_INCOMPLETE","message":"Completare lo scope del professionista.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SIGNOFF_PENDING", module: M, phase: P,
    title: "Sign-off tecnico pendente",
    description: "La verifica professionale richiesta non è ancora completata.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.signoffStatus","value":"PENDING"},
    outcome: {"code":"SIGNOFF_PENDING","message":"Attendere/completare il sign-off.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SIGNOFF_REJECTED", module: M, phase: P,
    title: "Sign-off tecnico negativo",
    description: "Il professionista non approva il perimetro/esito richiesto.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"eq","path":"technical.signoffStatus","value":"REJECTED"},
    outcome: {"code":"SIGNOFF_REJECTED","message":"Bloccare i gate e gestire le azioni correttive.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SIGNOFF_STALE", module: M, phase: P,
    title: "Sign-off tecnico obsoleto",
    description: "Sono cambiati input rilevanti dopo il sign-off.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"eq","path":"technical.signoffStatus","value":"STALE"},
    outcome: {"code":"SIGNOFF_STALE","message":"Riattivare la verifica sul nuovo fingerprint.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_SIGNOFF_FINGERPRINT_MISMATCH", module: M, phase: P,
    title: "Fingerprint sign-off non corrente",
    description: "Il sign-off è riferito a un set di documenti/fatti differente da quello corrente.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.signoffFingerprintMismatch"},
    outcome: {"code":"SIGNOFF_FINGERPRINT_MISMATCH","message":"Invalidare il sign-off e richiedere riesame.","blockProgress":true,"escalationTo":"TECHNICIAN","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_TECH_REVIEW_STALE", module: M, phase: P,
    title: "Verifica tecnica invalidata da nuovi input",
    description: "Una nuova versione documentale rilevante ha invalidato la review.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op":"eq","path":"technical.reviewStatus","value":"STALE"},
    outcome: {"code":"TECH_REVIEW_STALE","message":"Ricalcolare confronti/findings e ripetere i sign-off necessari.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CRITICAL_FINDINGS_OPEN", module: M, phase: P,
    title: "Finding critici aperti",
    description: "Una criticità tecnica aperta impedisce i gate interessati.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"gt","path":"technical.openCriticalFindingCount","value":0},
    outcome: {"code":"CRITICAL_FINDINGS_OPEN","message":"Risoluzione/escalation obbligatoria prima di proseguire.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_BLOCKING_FINDINGS_OPEN", module: M, phase: P,
    title: "Finding bloccanti aperti",
    description: "Sono presenti finding bloccanti non risolti.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"gt","path":"technical.openBlockingFindingCount","value":0},
    outcome: {"code":"BLOCKING_FINDINGS_OPEN","message":"Gestire i finding bloccanti.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_REVIEW_FINDINGS_OPEN", module: M, phase: P,
    title: "Finding di review aperti",
    description: "Esistono aspetti da controllare senza blocco tecnico automatico universale.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op":"gt","path":"technical.openReviewFindingCount","value":0},
    outcome: {"code":"REVIEW_FINDINGS_OPEN","message":"Mostrare all'agente la coda review.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_RISK_REGISTER_STALE", module: M, phase: P,
    title: "Risk register non aggiornato",
    description: "Il registro rischi deve riflettere gli ultimi finding e sign-off.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"eq","path":"technical.riskRegisterStatus","value":"STALE"},
    outcome: {"code":"RISK_REGISTER_STALE","message":"Rigenerare il risk register.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PUBLICATION_GATE", module: M, phase: P,
    title: "Gate pubblicazione non pronto",
    description: "Policy interna Guimmia: non pubblicare automaticamente con gate tecnico non READY.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"neq","path":"technical.gates.PUBLICATION","value":"READY"},
    outcome: {"code":"PUBLICATION_GATE","message":"Risoluzione/review prima della pubblicazione oppure decisione agente nei limiti consentiti.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_OFFER_GATE", module: M, phase: P,
    title: "Gate proposta non pronto",
    description: "Policy interna Guimmia prima della gestione formale di una proposta.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"neq","path":"technical.gates.OFFER","value":"READY"},
    outcome: {"code":"OFFER_GATE","message":"Completare i controlli richiesti per il gate proposta.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_PRELIMINARY_GATE", module: M, phase: P,
    title: "Gate preliminare non pronto",
    description: "Policy interna Guimmia prima del preliminare.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"neq","path":"technical.gates.PRELIMINARY","value":"READY"},
    outcome: {"code":"PRELIMINARY_GATE","message":"Completare review/professionisti richiesti.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PRELIMINARY"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CLOSING_GATE", module: M, phase: P,
    title: "Gate rogito non pronto",
    description: "Readiness interna verso il rogito; non equivale a nulla-osta notarile.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"neq","path":"technical.gates.CLOSING","value":"READY"},
    outcome: {"code":"CLOSING_GATE","message":"Coordinare ultime verifiche con professionisti/notai.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_GATE_SNAPSHOT_STALE", module: M, phase: P,
    title: "Decisione gate basata su snapshot obsoleto",
    description: "Ogni gate deve essere ricostruibile sullo snapshot corrente.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"truthy","path":"technical.gateSnapshotStale"},
    outcome: {"code":"GATE_SNAPSHOT_STALE","message":"Ricalcolare i gate sul nuovo snapshot.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CONTROLLED_OVERRIDE_PRESENT", module: M, phase: P,
    title: "Override agente registrato",
    description: "Un override ammesso deve essere motivato, circoscritto e auditabile.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: {"op":"gt","path":"technical.activeOverrideCount","value":0},
    outcome: {"code":"CONTROLLED_OVERRIDE_PRESENT","message":"Verificare motivazione, scope e scadenza degli override.","escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_CRITICAL_OVERRIDE_ATTEMPT", module: M, phase: P,
    title: "Override critico non consentito",
    description: "Guimmia non consente di nascondere/chiudere una criticità tecnica critica senza risoluzione/evidenza appropriata.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op":"truthy","path":"technical.criticalOverrideAttempted"},
    outcome: {"code":"CRITICAL_OVERRIDE_ATTEMPT","message":"Rifiutare override e mantenere il finding aperto.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_AGENT_MEMO_STALE", module: M, phase: P,
    title: "Memo tecnico agente obsoleto",
    description: "Il riepilogo operativo deve essere rigenerato dopo cambiamenti rilevanti.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "warning",
    condition: {"op":"eq","path":"technical.agentMemoStatus","value":"STALE"},
    outcome: {"code":"AGENT_MEMO_STALE","message":"Rigenerare il memo tecnico.","gateImpact":["PUBLICATION","OFFER"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_TECH_SNAPSHOT_STALE", module: M, phase: P,
    title: "Snapshot P04 non corrente",
    description: "La fase non può dirsi chiusa senza snapshot immutabile corrente.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op":"neq","path":"technical.snapshotStatus","value":"CURRENT"},
    outcome: {"code":"TECH_SNAPSHOT_STALE","message":"Creare un nuovo snapshot P04 dopo l'ultima review.","blockProgress":true,"gateImpact":["PUBLICATION","OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
  {
    id: "P04_LEGAL_SOURCE_MAP_MISSING", module: M, phase: P,
    title: "Mappa ruleset normativa incompleta",
    description: "Le regole dinamiche applicabili devono avere ruleset e fonti ufficiali tracciate.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op":"truthy","path":"technical.applicableLegalRulesetMissing"},
    outcome: {"code":"LEGAL_SOURCE_MAP_MISSING","message":"Completare la mappa normativa prima di applicare regole dinamiche.","blockProgress":true,"escalationTo":"AGENT","gateImpact":["OFFER","PRELIMINARY","CLOSING"]},
    sourceRefs: [internalPolicy("P04 Technical Due Diligence Engine")],
    active: true, version: 2,
  },
];
