
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK04Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K04_AUTHORITY_CLASS_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Authority Class Missing",factPath:"guimmia.orchestrator.k04.authority_class_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_MATERIAL_ACTION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Material Action Blocked",factPath:"guimmia.orchestrator.k04.ai_material_action_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_DOCUMENT_APPROVAL_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Document Approval Blocked",factPath:"guimmia.orchestrator.k04.ai_document_approval_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_SIGNATURE_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Signature Blocked",factPath:"guimmia.orchestrator.k04.ai_signature_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_PRICE_DECISION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Price Decision Blocked",factPath:"guimmia.orchestrator.k04.ai_price_decision_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_COUNTEROFFER_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Counteroffer Blocked",factPath:"guimmia.orchestrator.k04.ai_counteroffer_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_CANDIDATE_SELECTION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Candidate Selection Blocked",factPath:"guimmia.orchestrator.k04.ai_candidate_selection_blocked.status",decisionLevel:"AGENT_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_LEGAL_CONCLUSION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Legal Conclusion Blocked",factPath:"guimmia.orchestrator.k04.ai_legal_conclusion_blocked.status",decisionLevel:"PROFESSIONAL_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_TAX_CONCLUSION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Tax Conclusion Blocked",factPath:"guimmia.orchestrator.k04.ai_tax_conclusion_blocked.status",decisionLevel:"PROFESSIONAL_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_AI_TECHNICAL_CONCLUSION_BLOCKED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Ai Technical Conclusion Blocked",factPath:"guimmia.orchestrator.k04.ai_technical_conclusion_blocked.status",decisionLevel:"PROFESSIONAL_REQUIRED",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_BOOKING_CONFIRMATION_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Booking Confirmation Missing",factPath:"guimmia.orchestrator.k04.booking_confirmation_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_CUSTOMER_DECISION_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Customer Decision Missing",factPath:"guimmia.orchestrator.k04.customer_decision_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_PROFESSIONAL_AUTHORITY_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Professional Authority Missing",factPath:"guimmia.orchestrator.k04.professional_authority_missing.status",decisionLevel:"PROFESSIONAL_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_HUMAN_OWNER_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Human Owner Missing",factPath:"guimmia.orchestrator.k04.human_owner_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_HANDOFF_REASON_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Handoff Reason Missing",factPath:"guimmia.orchestrator.k04.handoff_reason_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_HANDOFF_CONTEXT_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Handoff Context Missing",factPath:"guimmia.orchestrator.k04.handoff_context_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_HANDOFF_SLA_MISSING",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Handoff Sla Missing",factPath:"guimmia.orchestrator.k04.handoff_sla_missing.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K04_HANDOFF_UNRESOLVED",module:"CASE_AUTHORITY_HANDOFF",phase:"PHASE_K04_AUTHORITY_HANDOFF",title:"Handoff Unresolved",factPath:"guimmia.orchestrator.k04.handoff_unresolved.status",decisionLevel:"AGENT_REQUIRED",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
