
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK02Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K02_REQUIRED_FACT_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Required Fact Missing",factPath:"guimmia.orchestrator.k02.required_fact_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_EVIDENCE_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Evidence Missing",factPath:"guimmia.orchestrator.k02.evidence_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_EVIDENCE_UNVERIFIED",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Evidence Unverified",factPath:"guimmia.orchestrator.k02.evidence_unverified.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_EVIDENCE_STALE",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Evidence Stale",factPath:"guimmia.orchestrator.k02.evidence_stale.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:true,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_EVIDENCE_SOURCE_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Evidence Source Missing",factPath:"guimmia.orchestrator.k02.evidence_source_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_EVIDENCE_HASH_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Evidence Hash Missing",factPath:"guimmia.orchestrator.k02.evidence_hash_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_DYNAMIC_RULESET_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Dynamic Ruleset Missing",factPath:"guimmia.orchestrator.k02.dynamic_ruleset_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:true,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_DYNAMIC_RULESET_STALE",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Dynamic Ruleset Stale",factPath:"guimmia.orchestrator.k02.dynamic_ruleset_stale.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:true,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_READINESS_ASSESSMENT_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Readiness Assessment Missing",factPath:"guimmia.orchestrator.k02.readiness_assessment_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_READINESS_SCORE_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Readiness Score Missing",factPath:"guimmia.orchestrator.k02.readiness_score_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_BLOCKING_FINDING_UNRESOLVED",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Blocking Finding Unresolved",factPath:"guimmia.orchestrator.k02.blocking_finding_unresolved.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_PROFESSIONAL_REVIEW_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Professional Review Missing",factPath:"guimmia.orchestrator.k02.professional_review_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:true,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_CUSTOMER_CONFIRMATION_MISSING",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Customer Confirmation Missing",factPath:"guimmia.orchestrator.k02.customer_confirmation_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_MANDATE_SCOPE_MISMATCH",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Mandate Scope Mismatch",factPath:"guimmia.orchestrator.k02.mandate_scope_mismatch.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_READINESS_GATE_MISMATCH",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Readiness Gate Mismatch",factPath:"guimmia.orchestrator.k02.readiness_gate_mismatch.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K02_CASE_NOT_READY",module:"CASE_EVIDENCE_READINESS",phase:"PHASE_K02_EVIDENCE_READINESS",title:"Case Not Ready",factPath:"guimmia.orchestrator.k02.case_not_ready.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
