import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP06Rules:BrainRule[]=[
  makeSaleRule({"id":"P06_P05_SNAPSHOT_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"P05 Snapshot Missing","factPath":"sale.p06.p05_snapshot_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_VALUATION_PURPOSE_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Valuation Purpose Missing","factPath":"sale.p06.valuation_purpose_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_PROPERTY_FACTS_STALE","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Property Facts Stale","factPath":"sale.p06.property_facts_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_COMPARABLES_INSUFFICIENT","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Comparables Insufficient","factPath":"sale.p06.comparables_insufficient.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_COMPARABLE_SOURCE_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Comparable Source Missing","factPath":"sale.p06.comparable_source_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_COMPARABLE_STALE","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Comparable Stale","factPath":"sale.p06.comparable_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_ADJUSTMENT_RATIONALE_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Adjustment Rationale Missing","factPath":"sale.p06.adjustment_rationale_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_OUTLIER_UNREVIEWED","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Outlier Unreviewed","factPath":"sale.p06.outlier_unreviewed.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_MARKET_CONTEXT_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Market Context Missing","factPath":"sale.p06.market_context_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_METHOD_NOT_SELECTED","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Method Not Selected","factPath":"sale.p06.method_not_selected.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_PRICE_RANGE_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Price Range Missing","factPath":"sale.p06.price_range_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_SINGLE_PRICE_AI_ONLY","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Single Price Ai Only","factPath":"sale.p06.single_price_ai_only.status","decisionLevel":"REVIEW","severity":"critical","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_HUMAN_PRICE_REVIEW_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Human Price Review Missing","factPath":"sale.p06.human_price_review_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_VALUATION_VERSION_CONFLICT","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Valuation Version Conflict","factPath":"sale.p06.valuation_version_conflict.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_APPROVAL_FINGERPRINT_MISSING","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Approval Fingerprint Missing","factPath":"sale.p06.approval_fingerprint_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P06_READY","module":"SALE_VALUATION","phase":"PHASE_06_VALUATION","title":"Ready","factPath":"sale.p06.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"PUBLICATION"})
];
