import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO05Rules:BrainRule[]=[
  makeAgencyRule({"id":"O05_SERVICE_TYPE_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Service Type Missing","factPath":"agency.o05.service_type_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_PROVIDER_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Provider Missing","factPath":"agency.o05.provider_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_CREDENTIALS_UNVERIFIED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Credentials Unverified","factPath":"agency.o05.credentials_unverified.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"],"rulesetKey":"ITALY_AGENCY_CREDENTIALS"}),
  makeAgencyRule({"id":"O05_CREDENTIALS_EXPIRED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Credentials Expired","factPath":"agency.o05.credentials_expired.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"],"rulesetKey":"ITALY_AGENCY_CREDENTIALS"}),
  makeAgencyRule({"id":"O05_JURISDICTION_MISMATCH","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Jurisdiction Mismatch","factPath":"agency.o05.jurisdiction_mismatch.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"],"rulesetKey":"ITALY_AGENCY_JURISDICTION_MISMATCH"}),
  makeAgencyRule({"id":"O05_CONFLICT_CHECK_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Conflict Check Missing","factPath":"agency.o05.conflict_check_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_SCOPE_UNAPPROVED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Scope Unapproved","factPath":"agency.o05.scope_unapproved.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_QUOTE_UNAPPROVED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Quote Unapproved","factPath":"agency.o05.quote_unapproved.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_HUMAN_PROVIDER_SELECTION_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Human Provider Selection Missing","factPath":"agency.o05.human_provider_selection_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_ASSIGNMENT_UNACCEPTED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Assignment Unaccepted","factPath":"agency.o05.assignment_unaccepted.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_INPUT_PACKAGE_INCOMPLETE","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Input Package Incomplete","factPath":"agency.o05.input_package_incomplete.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_EVIDENCE_REQUEST_OPEN","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Evidence Request Open","factPath":"agency.o05.evidence_request_open.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_PROFESSIONAL_CONCLUSION_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Professional Conclusion Missing","factPath":"agency.o05.professional_conclusion_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_PROFESSIONAL_REVIEW_STALE","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Professional Review Stale","factPath":"agency.o05.professional_review_stale.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"],"rulesetKey":"ITALY_AGENCY_PROFESSIONAL_REVIEW"}),
  makeAgencyRule({"id":"O05_DELIVERABLE_MISSING","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Deliverable Missing","factPath":"agency.o05.deliverable_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_DELIVERABLE_UNVERIFIED","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Deliverable Unverified","factPath":"agency.o05.deliverable_unverified.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_SLA_AT_RISK","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Sla At Risk","factPath":"agency.o05.sla_at_risk.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O05_READY","module":"AGENCY_PROFESSIONAL_SERVICES","phase":"PHASE_O05_PROFESSIONAL_SERVICES","title":"Ready","factPath":"agency.o05.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","LEASE_SIGNING","LEASE_REGISTRATION","TOURIST_PUBLICATION"]})
];
