import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_T09_PAYOUT_ARCHIVE";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseT09Rules: BrainRule[] = [
  { id: "T09_CHECKOUT_MISSING", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Check-out non completato", description: "Check-out non completato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.stayStatus","value":"CHECKED_OUT"}, outcome: {"code":"TOURIST_CHECKOUT_REQUIRED","message":"Non riconciliare il soggiorno prima del check-out.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_LEDGER_INCOMPLETE", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Ledger del soggiorno incompleto", description: "Ledger del soggiorno incompleto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.paymentLedgerStatus","value":"COMPLETE"}, outcome: {"code":"TOURIST_PAYMENT_LEDGER_REQUIRED","message":"Acquisire tutti gli eventi economici prima del consuntivo.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_PAYOUT_MISMATCH", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Payout non riconciliato", description: "Payout non riconciliato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.payoutMatchStatus","value":"MATCHED"}, outcome: {"code":"TOURIST_PAYOUT_MISMATCH","message":"Riconciliare lordo, commissioni, trattenute, rimborsi e netto.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_COMMISSION_MISMATCH", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Commissioni non riconciliate", description: "Commissioni non riconciliate", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.commissionConflictCount","value":0}, outcome: {"code":"TOURIST_COMMISSION_CONFLICT","message":"Confrontare contratto, provider e movimento senza sovrascrivere l'evidenza.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_REFUND_UNRESOLVED", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Rimborso o deposito non risolto", description: "Rimborso o deposito non risolto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.unresolvedRefundCount","value":0}, outcome: {"code":"TOURIST_REFUND_RECONCILIATION_REQUIRED","message":"Chiudere o motivare ogni movimento pendente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_TAX_RULESET_MISSING", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Ruleset fiscale turistico non corrente", description: "Ruleset fiscale turistico non corrente", stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"tax.rental.shortStayRulesetStatus","value":"CURRENT"}, outcome: {"code":"TOURIST_TAX_RULESET_REQUIRED","message":"Verificare obblighi e ruolo dell'intermediario su fonti correnti.","blockProgress":true,"escalationTo":"ACCOUNTANT"}, sourceRefs: [SOURCE_MAP.AE_RENTAL_GUIDANCE], freshnessPolicy: fresh("ITALY_SHORT_RENT_TAX",30), active: true, version: 1 },
  { id: "T09_AI_TAX_VERDICT", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Verdetto fiscale finale attribuito all'AI", description: "Verdetto fiscale finale attribuito all'AI", stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical", condition: {"op":"eq","path":"tax.finalVerdictSource","value":"AI_ONLY"}, outcome: {"code":"AI_TOURIST_TAX_VERDICT_FORBIDDEN","message":"La conclusione fiscale definitiva richiede review umana o professionale.","blockProgress":true,"escalationTo":"ACCOUNTANT"}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_PAYOUT_BEFORE_TAX_REVIEW", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Payout disposto prima della review fiscale", description: "Payout disposto prima della review fiscale", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.payoutStatus","value":"RELEASED"},{"op":"neq","path":"tax.reviewStatus","value":"REVIEWED"}]}, outcome: {"code":"TOURIST_PAYOUT_TAX_REVIEW_BLOCK","message":"Bloccare l'automazione del payout finché la review richiesta non è completata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_RECONCILIATION_ACTOR_MISSING", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Attore umano della riconciliazione mancante", description: "Attore umano della riconciliazione mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.reconciliationStatus","value":"FINAL"},{"op":"neq","path":"rental.tourist.reconciliationActorStatus","value":"AUTHORIZED_HUMAN"}]}, outcome: {"code":"HUMAN_RECONCILIATION_REQUIRED","message":"La chiusura economica deve essere approvata da una persona autorizzata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_ARCHIVE_INCOMPLETE", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Fascicolo soggiorno incompleto", description: "Fascicolo soggiorno incompleto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.archiveStatus","value":"COMPLETE"}, outcome: {"code":"TOURIST_ARCHIVE_REQUIRED","message":"Archiviare prenotazione, ospiti, reporting, incidenti e movimenti economici.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_EVENT_HISTORY_CONFLICT", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Cronologia economica in conflitto", description: "Cronologia economica in conflitto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.paymentEventConflictCount","value":0}, outcome: {"code":"TOURIST_PAYMENT_EVENT_CONFLICT","message":"Aprire review e usare eventi compensativi, mai modifica distruttiva.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T09_RECONCILED", module: "TOURIST_PAYOUT_ARCHIVE", phase: P, title: "Soggiorno riconciliato e archiviato", description: "Soggiorno riconciliato e archiviato", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.tourist.lifecycleStatus","value":"ARCHIVED"}, outcome: {"code":"TOURIST_STAY_ARCHIVED","message":"Il fascicolo del soggiorno è riconciliato, verificato e immutabile."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
