import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP05Rules:BrainRule[]=[
  makeSaleRule({"id":"P05_UPSTREAM_TECH_SNAPSHOT_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Upstream Tech Snapshot Missing","factPath":"sale.p05.upstream_tech_snapshot_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_ENCUMBRANCE_RULESET_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Encumbrance Ruleset Missing","factPath":"sale.p05.encumbrance_ruleset_missing.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_ENCUMBRANCE_RULESET"}),
  makeSaleRule({"id":"P05_ENCUMBRANCE_SEARCH_STALE","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Encumbrance Search Stale","factPath":"sale.p05.encumbrance_search_stale.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_ENCUMBRANCE_SEARCH"}),
  makeSaleRule({"id":"P05_ENCUMBRANCE_FINDINGS_UNRESOLVED","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Encumbrance Findings Unresolved","factPath":"sale.p05.encumbrance_findings_unresolved.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_ENCUMBRANCE_FINDINGS"}),
  makeSaleRule({"id":"P05_MORTGAGE_BALANCE_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Mortgage Balance Missing","factPath":"sale.p05.mortgage_balance_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_MORTGAGE_BALANCE"}),
  makeSaleRule({"id":"P05_CANCELLATION_PLAN_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Cancellation Plan Missing","factPath":"sale.p05.cancellation_plan_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_CONDOMINIUM_RULESET_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Condominium Ruleset Missing","factPath":"sale.p05.condominium_ruleset_missing.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_CONDOMINIUM_RULESET"}),
  makeSaleRule({"id":"P05_CONDOMINIUM_CERTIFICATE_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Condominium Certificate Missing","factPath":"sale.p05.condominium_certificate_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_CONDOMINIUM_CERTIFICATE"}),
  makeSaleRule({"id":"P05_CONDOMINIUM_DEBTS_UNRESOLVED","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Condominium Debts Unresolved","factPath":"sale.p05.condominium_debts_unresolved.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_CONDOMINIUM_DEBTS"}),
  makeSaleRule({"id":"P05_EXTRAORDINARY_WORKS_UNKNOWN","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Extraordinary Works Unknown","factPath":"sale.p05.extraordinary_works_unknown.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_LITIGATION_UNKNOWN","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Litigation Unknown","factPath":"sale.p05.litigation_unknown.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_SALE_TAX_RULESET_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Sale Tax Ruleset Missing","factPath":"sale.p05.sale_tax_ruleset_missing.status","dynamic":true,"decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_SALE_TAX_RULESET"}),
  makeSaleRule({"id":"P05_TAX_SCENARIO_UNREVIEWED","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Tax Scenario Unreviewed","factPath":"sale.p05.tax_scenario_unreviewed.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_TAX_SCENARIO_UNREVIEWED"}),
  makeSaleRule({"id":"P05_COST_ALLOCATION_UNCLEAR","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Cost Allocation Unclear","factPath":"sale.p05.cost_allocation_unclear.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_HUMAN_REVIEW_MISSING","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Human Review Missing","factPath":"sale.p05.human_review_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P05_READY","module":"SALE_PREMARKET_DUE_DILIGENCE","phase":"PHASE_05_ENCUMBRANCES_CONDO_TAX","title":"Ready","factPath":"sale.p05.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"PUBLICATION"})
];
