import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO01Rules:BrainRule[]=[
  makeAgencyRule({"id":"O01_TRANSACTION_PROFILE_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Transaction Profile Missing","factPath":"agency.o01.transaction_profile_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_ROUTE_NOT_CONFIRMED","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Route Not Confirmed","factPath":"agency.o01.route_not_confirmed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_GUIMMIA_OPERATING_PROFILE_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Guimmia Operating Profile Missing","factPath":"agency.o01.guimmia_operating_profile_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_INTERNAL_CASE_OWNER_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Internal Case Owner Missing","factPath":"agency.o01.internal_case_owner_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_CASE_ASSIGNMENT_STALE","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Case Assignment Stale","factPath":"agency.o01.case_assignment_stale.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_DUPLICATE_CASE_UNRESOLVED","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Duplicate Case Unresolved","factPath":"agency.o01.duplicate_case_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_CUSTOMER_SERVICE_SCOPE_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Customer Service Scope Missing","factPath":"agency.o01.customer_service_scope_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_CUSTOMER_SERVICE_MODEL_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Customer Service Model Missing","factPath":"agency.o01.customer_service_model_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_FIXED_CUSTOMER_TERMS_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Fixed Customer Terms Missing","factPath":"agency.o01.fixed_customer_terms_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_COMMERCIAL_TERMS_UNAPPROVED","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Commercial Terms Unapproved","factPath":"agency.o01.commercial_terms_unapproved.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_REQUIRED_ROLE_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Required Role Missing","factPath":"agency.o01.required_role_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_HANDOFF_UNACKNOWLEDGED","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Handoff Unacknowledged","factPath":"agency.o01.handoff_unacknowledged.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_PRIORITY_UNSET","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Priority Unset","factPath":"agency.o01.priority_unset.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_CLIENT_EXPECTATIONS_UNRECORDED","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Client Expectations Unrecorded","factPath":"agency.o01.client_expectations_unrecorded.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_HUMAN_OVERSIGHT_MISSING","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Human Oversight Missing","factPath":"agency.o01.human_oversight_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]}),
  makeAgencyRule({"id":"O01_READY","module":"AGENCY_CASE_ROUTING","phase":"PHASE_O01_CASE_ROUTING_ASSIGNMENT","title":"Ready","factPath":"agency.o01.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION"]})
];
