import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP11Rules:BrainRule[]=[
  makeSaleRule({"id":"P11_INTERESTED_PARTY_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Interested Party Missing","factPath":"sale.p11.interested_party_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_NEGOTIATION_SCOPE_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Negotiation Scope Missing","factPath":"sale.p11.negotiation_scope_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_OWNER_LIMITS_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Owner Limits Missing","factPath":"sale.p11.owner_limits_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_PRICE_SCENARIO_STALE","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Price Scenario Stale","factPath":"sale.p11.price_scenario_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_MATERIAL_TERM_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Material Term Missing","factPath":"sale.p11.material_term_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_COUNTERPARTY_AUTHORITY_UNKNOWN","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Counterparty Authority Unknown","factPath":"sale.p11.counterparty_authority_unknown.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_AI_COUNTEROFFER_FORBIDDEN","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Ai Counteroffer Forbidden","factPath":"sale.p11.ai_counteroffer_forbidden.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gate":"OFFER"}),
  makeSaleRule({"id":"P11_HUMAN_DECISION_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Human Decision Missing","factPath":"sale.p11.human_decision_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"critical","gate":"OFFER"}),
  makeSaleRule({"id":"P11_DECISION_RATIONALE_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Decision Rationale Missing","factPath":"sale.p11.decision_rationale_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_COMMUNICATION_UNRECORDED","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Communication Unrecorded","factPath":"sale.p11.communication_unrecorded.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_DEADLINE_MISSING","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Deadline Missing","factPath":"sale.p11.deadline_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_CONFLICTING_INSTRUCTIONS","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Conflicting Instructions","factPath":"sale.p11.conflicting_instructions.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_OPEN_ISSUES_UNRESOLVED","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Open Issues Unresolved","factPath":"sale.p11.open_issues_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gate":"OFFER"}),
  makeSaleRule({"id":"P11_ACTIVE","module":"SALE_NEGOTIATION","phase":"PHASE_11_NEGOTIATION","title":"Active","factPath":"sale.p11.active.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"OFFER"})
];
