import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R06_MARKET_READINESS";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR06Rules: BrainRule[] = [
  { id: "R06_UPSTREAM_SNAPSHOT_MISSING", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Snapshot V76.6 mancante", description: "Snapshot V76.6 mancante", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"neq","path":"transaction.phase05SnapshotStatus","value":"CURRENT"}, outcome: {"code":"PHASE05_SNAPSHOT_REQUIRED","message":"La pubblicazione locativa richiede uno snapshot contrattuale e fiscale V76.6 corrente.","blockProgress":true,"gateImpact":["RENTAL_PUBLICATION"]}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_OPERATION_NOT_RESIDENTIAL", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Profilo locativo residenziale non valido", description: "Profilo locativo residenziale non valido", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"not_in","path":"operation.type","values":["RENT_LONG_TERM","RENT_TRANSITORY","RENT_STUDENT"]}, outcome: {"code":"RESIDENTIAL_RENTAL_PROFILE_REQUIRED","message":"R06 è applicabile solo alle locazioni residenziali supportate.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_PUBLICATION_GATE_NOT_READY", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Gate pubblicazione locativa non pronto", description: "Gate pubblicazione locativa non pronto", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.gates.RENTAL_PUBLICATION","value":"READY"}, outcome: {"code":"RENTAL_PUBLICATION_GATE_BLOCK","message":"Non pubblicare finché il gate locativo non è pronto.","blockProgress":true,"gateImpact":["RENTAL_PUBLICATION"]}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_MASTER_CONTENT_MISSING", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Listing master incompleto", description: "Listing master incompleto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.masterContentStatus","value":"READY"}, outcome: {"code":"LISTING_MASTER_REQUIRED","message":"Completare titolo, descrizione, dotazioni, condizioni e informazioni obbligatorie.","blockProgress":true,"requiredFacts":["rental.listing.masterContentStatus"]}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_RENT_AMOUNT_MISMATCH", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Canone dell'annuncio non riconciliato", description: "Canone dell'annuncio non riconciliato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.rentAmountMatchStatus","value":"MATCHED"}, outcome: {"code":"LISTING_RENT_MISMATCH","message":"Riconciliare il canone pubblicato con contratto, mandato e snapshot economico.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_EXPENSES_UNCLEAR", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Spese e oneri non trasparenti", description: "Spese e oneri non trasparenti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.expensesDisclosureStatus","value":"READY"}, outcome: {"code":"LISTING_EXPENSES_REQUIRED","message":"Specificare spese, deposito, utenze e oneri senza formulazioni ambigue.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_ENERGY_DISCLOSURE_MISMATCH", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Dati energetici dell'annuncio non verificati", description: "Dati energetici dell'annuncio non verificati", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.energyDisclosureStatus","value":"VERIFIED"}, outcome: {"code":"ENERGY_DISCLOSURE_REQUIRED","message":"Usare solo dati energetici supportati dal fascicolo corrente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], evidencePolicy: {requiredFactPaths:["rental.listing.energyDisclosureStatus"],requireVerifiedEvidence:true,acceptedProvenance:["DOCUMENT","OFFICIAL_SOURCE","AGENT","PROFESSIONAL","SYSTEM"]}, active: true, version: 1 },
  { id: "R06_PROPERTY_FACTS_STALE", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Fatti dell'immobile modificati dopo la review", description: "Fatti dell'immobile modificati dopo la review", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"eq","path":"rental.listing.propertyFactsStatus","value":"STALE"}, outcome: {"code":"LISTING_FACTS_STALE","message":"Rigenerare l'annuncio e ripetere la review dopo modifiche materiali.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_MEDIA_RIGHTS_MISSING", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Diritti e consensi sui media mancanti", description: "Diritti e consensi sui media mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.listing.mediaRightsStatus","value":"VERIFIED"}, outcome: {"code":"LISTING_MEDIA_RIGHTS_REQUIRED","message":"Verificare titolarità, consenso e utilizzabilità di foto, video e planimetrie.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_UNSUPPORTED_CLAIMS", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Affermazioni promozionali non supportate", description: "Affermazioni promozionali non supportate", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.listing.unsupportedClaimCount","value":0}, outcome: {"code":"UNSUPPORTED_LISTING_CLAIMS","message":"Rimuovere o documentare ogni affermazione non sostenuta da evidenze.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_CHANNEL_NOT_AUTHORIZED", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Canale di pubblicazione non autorizzato", description: "Canale di pubblicazione non autorizzato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.listing.channelAuthorizationStatus","value":"APPROVED"}, outcome: {"code":"LISTING_CHANNEL_APPROVAL_REQUIRED","message":"Pubblicare soltanto sui canali autorizzati dall'incarico.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_HUMAN_APPROVAL_MISSING", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Approvazione umana dell'annuncio mancante", description: "Approvazione umana dell'annuncio mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"neq","path":"rental.listing.humanApprovalStatus","value":"APPROVED"}, outcome: {"code":"HUMAN_LISTING_APPROVAL_REQUIRED","message":"Un agente autorizzato deve approvare la versione esatta dell'annuncio.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_DUPLICATE_ACTIVE_LISTING", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Possibile annuncio attivo duplicato", description: "Possibile annuncio attivo duplicato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.listing.activeDuplicateCount","value":0}, outcome: {"code":"DUPLICATE_LISTING_REVIEW","message":"Riconciliare gli annunci attivi prima di una nuova pubblicazione.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R06_READY", module: "RENTAL_MARKET_OPERATIONS", phase: P, title: "Annuncio residenziale pronto", description: "Annuncio residenziale pronto", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.listing.status","value":"READY"}, outcome: {"code":"RENTAL_LISTING_READY","message":"L'annuncio è pronto per la pubblicazione umana autorizzata."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
