import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R11_LIFECYCLE";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR11Rules: BrainRule[] = [
  { id: "R11_ACTIVATION_MISSING", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Lifecycle locativo non attivato", description: "Lifecycle locativo non attivato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.lifecycle.activationStatus","value":"ACTIVE"}, outcome: {"code":"RENTAL_LIFECYCLE_ACTIVATION_REQUIRED","message":"Attivare calendario, responsabilità e canali di assistenza dopo la consegna.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_RENT_CALENDAR_MISSING", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Calendario canoni e scadenze mancante", description: "Calendario canoni e scadenze mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.lifecycle.rentCalendarStatus","value":"READY"}, outcome: {"code":"RENT_CALENDAR_REQUIRED","message":"Creare scadenze, importi, causali e reminder senza disporre incassi non autorizzati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_PAYMENT_OVERDUE", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Pagamento locativo scaduto", description: "Pagamento locativo scaduto", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning", condition: {"op":"gt","path":"rental.lifecycle.paymentOverdueDays","value":0}, outcome: {"code":"RENT_PAYMENT_OVERDUE","message":"Aprire follow-up, conservare comunicazioni e richiedere decisione umana sulle azioni."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_EMERGENCY_UNASSIGNED", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Manutenzione urgente non assegnata", description: "Manutenzione urgente non assegnata", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.lifecycle.maintenancePriority","value":"EMERGENCY"},{"op":"neq","path":"rental.lifecycle.maintenanceAssignmentStatus","value":"ASSIGNED"}]}, outcome: {"code":"EMERGENCY_MAINTENANCE_ASSIGNMENT_REQUIRED","message":"Escalare immediatamente a un umano reperibile.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_MAINTENANCE_SLA_BREACH", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "SLA manutenzione superato", description: "SLA manutenzione superato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning", condition: {"op":"gt","path":"rental.lifecycle.maintenanceSlaOverdueMinutes","value":0}, outcome: {"code":"MAINTENANCE_SLA_BREACH","message":"Notificare l'agente e registrare causa, impatto e piano d'azione."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_COMMUNICATION_UNANSWERED", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Comunicazione del conduttore senza risposta", description: "Comunicazione del conduttore senza risposta", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning", condition: {"op":"gt","path":"rental.lifecycle.unansweredCommunicationHours","value":24}, outcome: {"code":"TENANT_COMMUNICATION_OVERDUE","message":"Inserire la richiesta nella coda 24/7 ed escalare in base alla priorità."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_INDEXATION_RULESET_MISSING", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Aggiornamento del canone non verificato", description: "Aggiornamento del canone non verificato", stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"rental.lifecycle.indexationStatus","value":"REVIEW_REQUIRED"}, outcome: {"code":"RENT_INDEXATION_RULESET_REQUIRED","message":"Verificare applicabilità, calcolo e comunicazione prima di modificare il canone.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_HOUSING], freshnessPolicy: fresh("ITALY_RESIDENTIAL_RENTAL",30), active: true, version: 1 },
  { id: "R11_RENEWAL_DEADLINE", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Scadenza di rinnovo o disdetta imminente", description: "Scadenza di rinnovo o disdetta imminente", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning", condition: {"op":"gt","path":"rental.lifecycle.renewalActionDueCount","value":0}, outcome: {"code":"RENTAL_RENEWAL_ACTION_DUE","message":"Preparare scenari e scadenze per una decisione umana tempestiva."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_TRANSITORY_EXPIRY", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Locazione transitoria prossima alla scadenza", description: "Locazione transitoria prossima alla scadenza", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_TRANSITORY"},{"op":"truthy","path":"rental.lifecycle.transitoryExpiryDue"}]}, outcome: {"code":"TRANSITORY_EXPIRY_REVIEW","message":"Verificare chiusura, nuova esigenza e divieto di rinnovo automatico non supportato.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_TRANSITORY_RENTAL",30), active: true, version: 1 },
  { id: "R11_STUDENT_STATUS_REVIEW", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Status studente da aggiornare", description: "Status studente da aggiornare", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"operation.type","value":"RENT_STUDENT"},{"op":"eq","path":"rental.lifecycle.studentEvidenceStatus","value":"STALE"}]}, outcome: {"code":"STUDENT_STATUS_REVIEW_REQUIRED","message":"Raccogliere soltanto l'evidenza aggiornata necessaria al lifecycle.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DM_16_01_2017], freshnessPolicy: fresh("ITALY_STUDENT_RENTAL",30), active: true, version: 1 },
  { id: "R11_DEPOSIT_EVENT_UNRESOLVED", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Movimento deposito non riconciliato", description: "Movimento deposito non riconciliato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.lifecycle.unresolvedDepositEventCount","value":0}, outcome: {"code":"DEPOSIT_EVENT_RECONCILIATION_REQUIRED","message":"Riconciliare ogni movimento con documento e decisione umana.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_NOTICE_UNKNOWN", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Validità di una comunicazione formale non determinata", description: "Validità di una comunicazione formale non determinata", stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"rental.lifecycle.noticeValidityStatus","value":"UNKNOWN"}, outcome: {"code":"FORMAL_NOTICE_REVIEW_REQUIRED","message":"Non dichiarare valida la comunicazione senza review professionale.","blockProgress":true,"escalationTo":"LAWYER"}, sourceRefs: [SOURCE_MAP.L431_CONSOLIDATED], freshnessPolicy: fresh("ITALY_RESIDENTIAL_RENTAL",30), active: true, version: 1 },
  { id: "R11_TERMINATION_AI_VERDICT", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Verdetto AI sulla cessazione", description: "Verdetto AI sulla cessazione", stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical", condition: {"op":"eq","path":"rental.lifecycle.terminationVerdictSource","value":"AI_ONLY"}, outcome: {"code":"AI_TERMINATION_VERDICT_FORBIDDEN","message":"La cessazione richiede una decisione umana e, quando necessario, professionale.","blockProgress":true,"escalationTo":"LAWYER"}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_FINAL_HANDOVER_MISSING", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Chiusura senza riconsegna finale", description: "Chiusura senza riconsegna finale", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.lifecycleStatus","value":"CLOSING"},{"op":"neq","path":"rental.lifecycle.finalHandoverStatus","value":"COMPLETED"}]}, outcome: {"code":"FINAL_HANDOVER_REQUIRED","message":"Completare chiavi, contatori, inventario, danni e deposito finale.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_RETENTION_OVERDUE", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Dati del rapporto oltre retention", description: "Dati del rapporto oltre retention", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.lifecycle.retentionOverdueItemCount","value":0}, outcome: {"code":"RENTAL_RETENTION_REVIEW_REQUIRED","message":"Cancellare, anonimizzare o giustificare la conservazione residua.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R11_ACTIVE", module: "RENTAL_ACTIVE_LIFECYCLE", phase: P, title: "Lifecycle locativo operativo", description: "Lifecycle locativo operativo", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.lifecycleStatus","value":"ACTIVE"}, outcome: {"code":"RENTAL_LIFECYCLE_ACTIVE","message":"Scadenze, assistenza e audit del rapporto sono attivi."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
