
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK01Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K01_CASE_ID_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Case Id Missing",factPath:"guimmia.orchestrator.k01.case_id_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CASE_VERSION_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Case Version Missing",factPath:"guimmia.orchestrator.k01.case_version_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CASE_VERSION_CONFLICT",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Case Version Conflict",factPath:"guimmia.orchestrator.k01.case_version_conflict.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_OPERATION_TYPE_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Operation Type Missing",factPath:"guimmia.orchestrator.k01.operation_type_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"ANY"}),
  makeOrchestratorRule({id:"K01_OPERATION_TYPE_UNSUPPORTED",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Operation Type Unsupported",factPath:"guimmia.orchestrator.k01.operation_type_unsupported.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"ANY"}),
  makeOrchestratorRule({id:"K01_CUSTOMER_ROLE_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Customer Role Missing",factPath:"guimmia.orchestrator.k01.customer_role_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_SERVICE_MODEL_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Service Model Missing",factPath:"guimmia.orchestrator.k01.service_model_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_PROPERTY_LINK_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Property Link Missing",factPath:"guimmia.orchestrator.k01.property_link_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CONTEXT_SNAPSHOT_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Context Snapshot Missing",factPath:"guimmia.orchestrator.k01.context_snapshot_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CONTEXT_FINGERPRINT_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Context Fingerprint Missing",factPath:"guimmia.orchestrator.k01.context_fingerprint_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CONTEXT_SNAPSHOT_STALE",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Context Snapshot Stale",factPath:"guimmia.orchestrator.k01.context_snapshot_stale.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_DUPLICATE_CASE_UNRESOLVED",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Duplicate Case Unresolved",factPath:"guimmia.orchestrator.k01.duplicate_case_unresolved.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_GUIMMIA_PROFILE_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Guimmia Profile Missing",factPath:"guimmia.orchestrator.k01.guimmia_profile_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_INTERNAL_OWNER_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Internal Owner Missing",factPath:"guimmia.orchestrator.k01.internal_owner_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CURRENT_PHASE_MISSING",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Current Phase Missing",factPath:"guimmia.orchestrator.k01.current_phase_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K01_CASE_TRUTH_NOT_READY",module:"CASE_TRUTH_CONTEXT",phase:"PHASE_K01_CASE_TRUTH_CONTEXT",title:"Case Truth Not Ready",factPath:"guimmia.orchestrator.k01.case_truth_not_ready.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
