import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO06Rules:BrainRule[]=[
  makeAgencyRule({"id":"O06_TASK_OWNER_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Task Owner Missing","factPath":"agency.o06.task_owner_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_TASK_STATUS_INVALID","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Task Status Invalid","factPath":"agency.o06.task_status_invalid.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_DUE_DATE_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Due Date Missing","factPath":"agency.o06.due_date_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_SLA_POLICY_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Sla Policy Missing","factPath":"agency.o06.sla_policy_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_SLA_BREACH","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Sla Breach","factPath":"agency.o06.sla_breach.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_ESCALATION_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Escalation Missing","factPath":"agency.o06.escalation_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_DEPENDENCY_BLOCKED","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Dependency Blocked","factPath":"agency.o06.dependency_blocked.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_EVIDENCE_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Evidence Missing","factPath":"agency.o06.evidence_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_COMPLETION_ACTOR_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Completion Actor Missing","factPath":"agency.o06.completion_actor_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_COMPLETION_FINGERPRINT_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Completion Fingerprint Missing","factPath":"agency.o06.completion_fingerprint_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_REOPEN_REASON_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Reopen Reason Missing","factPath":"agency.o06.reopen_reason_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_DUPLICATE_TASK","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Duplicate Task","factPath":"agency.o06.duplicate_task.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_CRITICAL_TASK_HIDDEN","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Critical Task Hidden","factPath":"agency.o06.critical_task_hidden.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_CLIENT_WAITING_UNTRACKED","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Client Waiting Untracked","factPath":"agency.o06.client_waiting_untracked.status","decisionLevel":"REVIEW","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_HUMAN_CLOSURE_MISSING","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Human Closure Missing","factPath":"agency.o06.human_closure_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O06_READY","module":"AGENCY_TASK_SLA","phase":"PHASE_O06_TASK_SLA","title":"Ready","factPath":"agency.o06.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["CLOSING","HANDOVER","CHECK_IN","GUEST_REPORTING"]})
];
