import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO02Rules:BrainRule[]=[
  makeAgencyRule({"id":"O02_CONTACT_IDENTITY_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Contact Identity Missing","factPath":"agency.o02.contact_identity_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_CONTACT_CHANNEL_UNVERIFIED","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Contact Channel Unverified","factPath":"agency.o02.contact_channel_unverified.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_COMMUNICATION_PURPOSE_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Communication Purpose Missing","factPath":"agency.o02.communication_purpose_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_LEGAL_BASIS_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Legal Basis Missing","factPath":"agency.o02.legal_basis_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"],"rulesetKey":"ITALY_AGENCY_LEGAL_BASIS"}),
  makeAgencyRule({"id":"O02_CONSENT_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Consent Missing","factPath":"agency.o02.consent_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"],"rulesetKey":"ITALY_AGENCY_CONSENT"}),
  makeAgencyRule({"id":"O02_CONSENT_STALE","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Consent Stale","factPath":"agency.o02.consent_stale.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"],"rulesetKey":"ITALY_AGENCY_CONSENT"}),
  makeAgencyRule({"id":"O02_OPT_OUT_UNPROCESSED","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Opt Out Unprocessed","factPath":"agency.o02.opt_out_unprocessed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_CHANNEL_PREFERENCE_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Channel Preference Missing","factPath":"agency.o02.channel_preference_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_QUIET_HOURS_VIOLATION","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Quiet Hours Violation","factPath":"agency.o02.quiet_hours_violation.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_DATA_MINIMIZATION_FAILED","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Data Minimization Failed","factPath":"agency.o02.data_minimization_failed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_RETENTION_POLICY_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Retention Policy Missing","factPath":"agency.o02.retention_policy_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"],"rulesetKey":"ITALY_AGENCY_RETENTION_POLICY"}),
  makeAgencyRule({"id":"O02_CONTACT_DUPLICATE_UNRESOLVED","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Contact Duplicate Unresolved","factPath":"agency.o02.contact_duplicate_unresolved.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_SENSITIVE_DATA_EXCESS","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Sensitive Data Excess","factPath":"agency.o02.sensitive_data_excess.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_MINOR_REVIEW_MISSING","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Minor Review Missing","factPath":"agency.o02.minor_review_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]}),
  makeAgencyRule({"id":"O02_PRIVACY_ESCALATION_OPEN","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Privacy Escalation Open","factPath":"agency.o02.privacy_escalation_open.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"],"rulesetKey":"ITALY_AGENCY_PRIVACY_ESCALATION_OPEN"}),
  makeAgencyRule({"id":"O02_READY","module":"AGENCY_CONTACT_CONSENT","phase":"PHASE_O02_CONTACT_CONSENT","title":"Ready","factPath":"agency.o02.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["OFFER","CANDIDATE_SELECTION","BOOKING"]})
];
