import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_T06_TOURIST_MARKET";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseT06Rules: BrainRule[] = [
  { id: "T06_OPERATION_NOT_TOURIST", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Profilo turistico non valido", description: "Profilo turistico non valido", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"operation.type","value":"RENT_TOURIST_SHORT"}, outcome: {"code":"TOURIST_PROFILE_REQUIRED","message":"T06 è applicabile soltanto al profilo turistico breve.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_PHASE05_SNAPSHOT_MISSING", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Snapshot turistico V76.6 mancante", description: "Snapshot turistico V76.6 mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"transaction.phase05SnapshotStatus","value":"CURRENT"}, outcome: {"code":"TOURIST_PHASE05_SNAPSHOT_REQUIRED","message":"La pubblicazione richiede lo snapshot turistico, contrattuale e fiscale corrente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_PUBLICATION_GATE_NOT_READY", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Gate pubblicazione turistica non pronto", description: "Gate pubblicazione turistica non pronto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.gates.TOURIST_PUBLICATION","value":"READY"}, outcome: {"code":"TOURIST_PUBLICATION_GATE_BLOCK","message":"Non pubblicare finché il gate turistico non è pronto.","blockProgress":true,"gateImpact":["TOURIST_PUBLICATION"]}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_CIN_NOT_VERIFIED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "CIN non verificato", description: "CIN non verificato", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.cinStatus","value":"VERIFIED"}, outcome: {"code":"TOURIST_CIN_REQUIRED","message":"Verificare l'identificativo applicabile prima della pubblicazione.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER], freshnessPolicy: fresh("ITALY_TOURIST_CIN",30), active: true, version: 1 },
  { id: "T06_CIN_NOT_DISPLAYED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "CIN non riportato nell'annuncio", description: "CIN non riportato nell'annuncio", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.cinDisplayStatus","value":"VERIFIED"}, outcome: {"code":"TOURIST_CIN_DISPLAY_REQUIRED","message":"Riconciliare il CIN del fascicolo con tutti i canali attivi.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER], freshnessPolicy: fresh("ITALY_TOURIST_CIN",30), active: true, version: 1 },
  { id: "T06_SAFETY_NOT_VERIFIED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Requisiti di sicurezza non verificati", description: "Requisiti di sicurezza non verificati", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"neq","path":"rental.tourist.safetyStatus","value":"VERIFIED"}, outcome: {"code":"TOURIST_SAFETY_REQUIRED","message":"Bloccare la pubblicazione finché le evidenze di sicurezza applicabili non sono correnti.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER], freshnessPolicy: fresh("ITALY_TOURIST_SAFETY",30), active: true, version: 1 },
  { id: "T06_LOCAL_RULES_MISSING", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Regole territoriali turistiche non correnti", description: "Regole territoriali turistiche non correnti", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.localRulesetStatus","value":"CURRENT"}, outcome: {"code":"TOURIST_LOCAL_RULESET_REQUIRED","message":"Verificare il ruleset regionale e comunale applicabile.","blockProgress":true}, sourceRefs: [SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_TOURIST_LOCAL_RULES",30), active: true, version: 1 },
  { id: "T06_BUSINESS_FORM_UNKNOWN", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Forma imprenditoriale non definita", description: "Forma imprenditoriale non definita", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"in","path":"rental.tourist.businessForm","values":["UNKNOWN",null]}, outcome: {"code":"TOURIST_BUSINESS_FORM_REQUIRED","message":"Definire la forma operativa prima della pubblicazione.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER], freshnessPolicy: fresh("ITALY_TOURIST_BUSINESS_STATUS",30), active: true, version: 1 },
  { id: "T06_SCIA_NOT_VERIFIED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "SCIA o adempimento d'impresa non verificato", description: "SCIA o adempimento d'impresa non verificato", stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.businessForm","value":"BUSINESS"},{"op":"neq","path":"rental.tourist.sciaStatus","value":"VERIFIED"}]}, outcome: {"code":"TOURIST_SCIA_REQUIRED","message":"Acquisire evidenza dell'adempimento applicabile.","blockProgress":true}, sourceRefs: [SOURCE_MAP.DL145_ART13TER], freshnessPolicy: fresh("ITALY_TOURIST_SCIA",30), active: true, version: 1 },
  { id: "T06_PRICING_SNAPSHOT_MISSING", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Snapshot tariffe e costi mancante", description: "Snapshot tariffe e costi mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.pricingSnapshotStatus","value":"CURRENT"}, outcome: {"code":"TOURIST_PRICING_SNAPSHOT_REQUIRED","message":"Congelare tariffa, pulizia, tasse, commissioni e deposito visualizzati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_HOUSE_RULES_NOT_APPROVED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "House rules non approvate", description: "House rules non approvate", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.houseRulesStatus","value":"APPROVED"}, outcome: {"code":"TOURIST_HOUSE_RULES_REQUIRED","message":"Far approvare capienza, accesso, rumore, animali e regole applicabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_UNSUPPORTED_CLAIMS", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Claim turistici non supportati", description: "Claim turistici non supportati", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.unsupportedClaimCount","value":0}, outcome: {"code":"TOURIST_CLAIMS_EVIDENCE_REQUIRED","message":"Rimuovere o documentare ogni claim su servizi, posizione e dotazioni.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_CHANNEL_NOT_AUTHORIZED", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Canale turistico non autorizzato", description: "Canale turistico non autorizzato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.channelAuthorizationStatus","value":"APPROVED"}, outcome: {"code":"TOURIST_CHANNEL_APPROVAL_REQUIRED","message":"Distribuire soltanto sui canali autorizzati e tracciati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T06_HUMAN_APPROVAL_MISSING", module: "TOURIST_MARKET_OPERATIONS", phase: P, title: "Approvazione umana annuncio turistico mancante", description: "Approvazione umana annuncio turistico mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"neq","path":"rental.tourist.listingHumanApprovalStatus","value":"APPROVED"}, outcome: {"code":"HUMAN_TOURIST_LISTING_APPROVAL_REQUIRED","message":"Un agente deve approvare versione, prezzi e adempimenti prima della pubblicazione.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
