import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_T07_BOOKING";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseT07Rules: BrainRule[] = [
  { id: "T07_LISTING_NOT_PUBLISHED", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Annuncio turistico non pubblicato", description: "Annuncio turistico non pubblicato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.listingStatus","value":"PUBLISHED"}, outcome: {"code":"PUBLISHED_TOURIST_LISTING_REQUIRED","message":"Accettare prenotazioni soltanto per un listing pubblicato e corrente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_AVAILABILITY_STALE", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Calendario disponibilità non corrente", description: "Calendario disponibilità non corrente", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.availabilityStatus","value":"CURRENT"}, outcome: {"code":"TOURIST_AVAILABILITY_REFRESH_REQUIRED","message":"Aggiornare disponibilità e blocchi prima di accettare la richiesta.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_OVERLAPPING_BOOKING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Sovrapposizione di prenotazioni", description: "Sovrapposizione di prenotazioni", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"gt","path":"rental.tourist.overlappingBookingCount","value":0}, outcome: {"code":"TOURIST_BOOKING_OVERLAP","message":"Bloccare la conferma e riconciliare il calendario.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_GUEST_COUNT_INVALID", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Numero ospiti non compatibile", description: "Numero ospiti non compatibile", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"truthy","path":"rental.tourist.guestCountInvalid"}, outcome: {"code":"TOURIST_GUEST_COUNT_INVALID","message":"Rispettare capienza e configurazione approvate.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_TERMS_SNAPSHOT_MISSING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Snapshot condizioni di prenotazione mancante", description: "Snapshot condizioni di prenotazione mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.bookingTermsSnapshotStatus","value":"CURRENT"}, outcome: {"code":"BOOKING_TERMS_SNAPSHOT_REQUIRED","message":"Salvare le condizioni accettate nella versione mostrata all'ospite.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_CANCELLATION_SNAPSHOT_MISSING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Policy di cancellazione non congelata", description: "Policy di cancellazione non congelata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.cancellationSnapshotStatus","value":"CURRENT"}, outcome: {"code":"CANCELLATION_POLICY_SNAPSHOT_REQUIRED","message":"Conservare policy, finestre, importi e canale della conferma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_PAYMENT_ROLE_UNKNOWN", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Ruolo nel pagamento non definito", description: "Ruolo nel pagamento non definito", stability: "DYNAMIC", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"transaction.paymentRole","value":"UNKNOWN"}, outcome: {"code":"TOURIST_PAYMENT_ROLE_REQUIRED","message":"Definire se Guimmia incassa, interviene o coordina soltanto.","blockProgress":true}, sourceRefs: [SOURCE_MAP.AE_RENTAL_GUIDANCE], freshnessPolicy: fresh("ITALY_SHORT_RENT_INTERMEDIARY_TAX",30), active: true, version: 1 },
  { id: "T07_PAYMENT_AMOUNT_MISMATCH", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Importo del pagamento non riconciliato", description: "Importo del pagamento non riconciliato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.paymentAmountStatus","value":"MATCHED"}, outcome: {"code":"TOURIST_PAYMENT_AMOUNT_MISMATCH","message":"Riconciliare lordo, commissioni, imposte, deposito e netto.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_PROVIDER_REFERENCE_MISSING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Riferimento del provider di pagamento mancante", description: "Riferimento del provider di pagamento mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.paymentStatus","value":"CAPTURED"},{"op":"falsy","path":"rental.tourist.paymentProviderReferencePresent"}]}, outcome: {"code":"PAYMENT_PROVIDER_REFERENCE_REQUIRED","message":"Conservare riferimento e prova del provider.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_CONFIRMED_BEFORE_PAYMENT", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Prenotazione confermata prima del pagamento richiesto", description: "Prenotazione confermata prima del pagamento richiesto", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.bookingStatus","value":"CONFIRMED"},{"op":"eq","path":"rental.tourist.paymentRequirement","value":"PREPAID"},{"op":"neq","path":"rental.tourist.paymentStatus","value":"CAPTURED"}]}, outcome: {"code":"BOOKING_CONFIRMATION_PAYMENT_BLOCK","message":"Rifiutare la conferma finché la condizione economica richiesta non è soddisfatta.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_REFUND_DUE", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Rimborso dovuto non completato", description: "Rimborso dovuto non completato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.refundOverdueHours","value":0}, outcome: {"code":"TOURIST_REFUND_OVERDUE","message":"Aprire task umano e conservare calcolo, decisione e prova del rimborso.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_CANCELLATION_SOURCE_MISSING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Autore della cancellazione non registrato", description: "Autore della cancellazione non registrato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.bookingStatus","value":"CANCELLED"},{"op":"falsy","path":"rental.tourist.cancellationActorPresent"}]}, outcome: {"code":"CANCELLATION_ACTOR_REQUIRED","message":"Registrare attore, canale, momento e policy applicata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_CHARGEBACK_UNRESOLVED", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Contestazione di pagamento aperta", description: "Contestazione di pagamento aperta", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.tourist.openChargebackCount","value":0}, outcome: {"code":"TOURIST_CHARGEBACK_REVIEW","message":"Bloccare la riconciliazione e assegnare la contestazione.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_EXCESSIVE_IDENTITY_REQUEST", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Dati ospite eccedenti richiesti in prenotazione", description: "Dati ospite eccedenti richiesti in prenotazione", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"gt","path":"rental.tourist.excessiveGuestFieldCount","value":0}, outcome: {"code":"TOURIST_GUEST_DATA_MINIMIZATION_BLOCK","message":"Rimuovere dati non necessari prima della conferma.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_IDEMPOTENCY_KEY_MISSING", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Chiave di idempotenza prenotazione mancante", description: "Chiave di idempotenza prenotazione mancante", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"falsy","path":"rental.tourist.idempotencyKeyPresent"}, outcome: {"code":"BOOKING_IDEMPOTENCY_REQUIRED","message":"Ogni comando di prenotazione o pagamento deve essere idempotente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T07_CONFIRMED", module: "TOURIST_BOOKING_OPERATIONS", phase: P, title: "Prenotazione confermata", description: "Prenotazione confermata", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.tourist.bookingStatus","value":"CONFIRMED"}, outcome: {"code":"TOURIST_BOOKING_CONFIRMED","message":"Prenotazione, condizioni e pagamento sono congelati e auditabili."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
