import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R02_LETTING_AUTHORITY";
const fresh = (rulesetKey:string) => ({required:true,rulesetKey,maxAgeDays:30});

export const phaseR02Rules: BrainRule[] = [
  { id: "R02_OPERATION_NOT_RENTAL", module: "RENTAL_AUTHORITY", phase: P, title: "Operazione locativa non definita", description: "Operazione locativa non definita", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"not_in","path":"operation.type","values":["RENT_LONG_TERM","RENT_TRANSITORY","RENT_STUDENT","RENT_TOURIST_SHORT"]}, outcome: {"code":"RENTAL_OPERATION_REQUIRED","message":"Selezionare il tipo di locazione prima del percorso locativo.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_RELATIONSHIP_UNKNOWN", module: "RENTAL_AUTHORITY", phase: P, title: "Rapporto con immobile non definito", description: "Rapporto con immobile non definito", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"not","condition":{"op":"exists","path":"rental.authorityBasis"}}, outcome: {"code":"AUTHORITY_BASIS_REQUIRED","message":"Indicare a quale titolo il cliente può concedere il godimento dell immobile.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_AUTHORITY_EVIDENCE_MISSING", module: "RENTAL_AUTHORITY", phase: P, title: "Evidenza del potere di locare mancante", description: "Evidenza del potere di locare mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"eq","path":"rental.authorityStatus","value":"EVIDENCE_PENDING"}, outcome: {"code":"AUTHORITY_EVIDENCE_REQUIRED","message":"Acquisire titolo o documentazione del potere di locare.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_AUTHORITY_REVIEW_REQUIRED", module: "RENTAL_AUTHORITY", phase: P, title: "Potere di locare da verificare", description: "Potere di locare da verificare", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"rental.authorityStatus","value":"REVIEW_REQUIRED"}, outcome: {"code":"AUTHORITY_REVIEW","message":"Revisione agente/professionista necessaria.","blockProgress":true,"escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_AUTHORITY_BLOCKED", module: "RENTAL_AUTHORITY", phase: P, title: "Potere di locare bloccato", description: "Potere di locare bloccato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"eq","path":"rental.authorityStatus","value":"BLOCKED"}, outcome: {"code":"AUTHORITY_BLOCKED","message":"Non proseguire finché il potere di locare non è risolto.","blockProgress":true,"escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_AUTHORITY_STALE", module: "RENTAL_AUTHORITY", phase: P, title: "Verifica potere di locare non corrente", description: "Verifica potere di locare non corrente", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"eq","path":"rental.authorityStatus","value":"STALE"}, outcome: {"code":"AUTHORITY_STALE","message":"Ricalcolare la verifica a seguito di nuovi documenti o fatti.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_COOWNERSHIP_UNRESOLVED", module: "RENTAL_AUTHORITY", phase: P, title: "Comproprietà non riconciliata", description: "Comproprietà non riconciliata", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.authorityBasis","value":"COOWNER"},{"op":"neq","path":"rental.coownerAuthorityStatus","value":"RESOLVED"}]}, outcome: {"code":"COOWNER_AUTHORITY_UNRESOLVED","message":"Chiarire soggetti, quote e poteri necessari per la locazione.","blockProgress":true,"escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_USUFRUCT_ROUTE", module: "RENTAL_AUTHORITY", phase: P, title: "Locazione da usufruttuario da instradare", description: "Locazione da usufruttuario da instradare", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning", condition: {"op":"eq","path":"rental.authorityBasis","value":"USUFRUCTUARY"}, outcome: {"code":"USUFRUCT_RENTAL_REVIEW","message":"Verificare titolo, durata e limiti rilevanti prima del contratto.","escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_PROXY_SCOPE_NOT_VERIFIED", module: "RENTAL_AUTHORITY", phase: P, title: "Procura per locare non verificata", description: "Procura per locare non verificata", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.authorityBasis","value":"PROXY"},{"op":"neq","path":"rental.proxyScopeStatus","value":"VERIFIED"}]}, outcome: {"code":"PROXY_SCOPE_REQUIRED","message":"Verificare che la procura copra l atto e gli impegni previsti.","blockProgress":true,"escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_COMPANY_SIGNER_NOT_VERIFIED", module: "RENTAL_AUTHORITY", phase: P, title: "Poteri firmatario societario non verificati", description: "Poteri firmatario societario non verificati", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"client.type","value":"LEGAL_ENTITY"},{"op":"neq","path":"rental.companySignerStatus","value":"VERIFIED"}]}, outcome: {"code":"COMPANY_SIGNER_REQUIRED","message":"Verificare poteri e rappresentanza della societa locatrice.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_SUBLEASE_RIGHT_UNKNOWN", module: "RENTAL_AUTHORITY", phase: P, title: "Diritto di sublocare non verificato", description: "Diritto di sublocare non verificato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.authorityBasis","value":"TENANT_SUBLESSOR"},{"op":"neq","path":"rental.subleaseRightStatus","value":"VERIFIED"}]}, outcome: {"code":"SUBLEASE_RIGHT_REQUIRED","message":"Acquisire e verificare il titolo che consente la sublocazione.","blockProgress":true}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_EXISTING_OCCUPANCY_UNKNOWN", module: "RENTAL_AUTHORITY", phase: P, title: "Stato occupazione non chiarito", description: "Stato occupazione non chiarito", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"eq","path":"rental.currentOccupancyStatus","value":"UNKNOWN"}, outcome: {"code":"OCCUPANCY_STATUS_REQUIRED","message":"Chiarire se l immobile è libero, occupato o già locato.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_EXISTING_LEASE_CONFLICT", module: "RENTAL_AUTHORITY", phase: P, title: "Contratto di locazione esistente da gestire", description: "Contratto di locazione esistente da gestire", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"eq","path":"rental.currentOccupancyStatus","value":"ACTIVE_LEASE"}, outcome: {"code":"EXISTING_LEASE_REVIEW","message":"Acquisire il contratto esistente e definire compatibilità, scadenze e disponibilità.","blockProgress":true,"escalationTo":"AGENT"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_EXISTING_AGENCY_MANDATE", module: "RENTAL_AUTHORITY", phase: P, title: "Possibile incarico locativo preesistente", description: "Possibile incarico locativo preesistente", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"in","path":"rental.existingAgencyMandate","values":["YES","UNKNOWN"]}, outcome: {"code":"EXISTING_RENTAL_MANDATE_CHECK","message":"Acquisire e verificare incarico preesistente prima di assumere impegni incompatibili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_SPECIAL_CAPACITY_CASE", module: "RENTAL_AUTHORITY", phase: P, title: "Caso speciale di capacità/rappresentanza", description: "Caso speciale di capacità/rappresentanza", stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking", condition: {"op":"truthy","path":"rental.specialCapacityCase"}, outcome: {"code":"SPECIAL_CAPACITY_REVIEW","message":"Coinvolgere il professionista appropriato prima di procedere.","blockProgress":true,"escalationTo":"LAWYER"}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_AUTHORITY_FACT_CONFLICT", module: "RENTAL_AUTHORITY", phase: P, title: "Conflitto tra evidenze sul potere di locare", description: "Conflitto tra evidenze sul potere di locare", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.authorityConflictCount","value":0}, outcome: {"code":"AUTHORITY_CONFLICT","message":"Non auto-risolvere: mostrare le evidenze e aprire review.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
  { id: "R02_AUTHORITY_READY", module: "RENTAL_AUTHORITY", phase: P, title: "Potere di locare verificato", description: "Potere di locare verificato", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.authorityStatus","value":"VERIFIED"}, outcome: {"code":"AUTHORITY_READY","message":"Potere di locare verificato per il workflow corrente."}, sourceRefs: [SOURCE_MAP.RENTAL_GENERAL], active: true, version: 1 },
  { id: "R02_SNAPSHOT_MISSING", module: "RENTAL_AUTHORITY", phase: P, title: "Snapshot autorità locativa mancante", description: "Snapshot autorità locativa mancante", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.authorityStatus","value":"VERIFIED"},{"op":"neq","path":"rental.authoritySnapshotStatus","value":"CURRENT"}]}, outcome: {"code":"AUTHORITY_SNAPSHOT_REQUIRED","message":"Salvare snapshot delle evidenze e della decisione prima di avanzare.","blockProgress":true}, sourceRefs: [internalPolicy("V76.6 Multi-Transaction Rental & Fiscal Engine")], active: true, version: 1 },
];
