import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";

const P = "PHASE_03_DOCUMENT_DOSSIER";
const M = "DOCUMENT_DOSSIER";

export const phase03Rules: BrainRule[] = [
  {
    id: "P03_INVENTORY_NOT_INITIALIZED", module: M, phase: P,
    title: "Inventario non inizializzato",
    description: "Il fascicolo deve essere materializzato prima di qualsiasi decisione.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op": "neq", "path": "documents.inventoryStatus", "value": "INITIALIZED"},
    outcome: {"code": "DOC_INVENTORY_REQUIRED", "message": "Inizializzare inventario documentale.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_REQUIREMENTS_NOT_GENERATED", module: M, phase: P,
    title: "Requisiti non generati",
    description: "I requisiti devono essere calcolati sul contesto corrente.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op": "neq", "path": "documents.requirementsStatus", "value": "GENERATED"},
    outcome: {"code": "DOC_REQUIREMENTS_REQUIRED", "message": "Generare i requisiti documentali contestuali.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_REQUIREMENTS_STALE", module: M, phase: P,
    title: "Requisiti obsoleti",
    description: "I facts sono cambiati dopo il calcolo requisiti.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op": "gt", "path": "documents.requirementsStaleCount", "value": 0},
    outcome: {"code": "DOC_REQUIREMENTS_STALE", "message": "Ricalcolare i requisiti documentali.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_UNKNOWN_APPLICABILITY", module: M, phase: P,
    title: "Applicabilità non determinata",
    description: "Un requisito non può essere trattato come non applicabile solo perché mancano fatti.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.unknownApplicabilityCount", "value": 0},
    outcome: {"code": "DOC_APPLICABILITY_REVIEW", "message": "Completare i facts necessari a determinare i requisiti."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_UNROUTED_MISSING", module: M, phase: P,
    title: "Documenti mancanti non instradati",
    description: "Ogni mancanza applicabile deve avere richiesta/task/escalation.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op": "gt", "path": "documents.unroutedMissingCount", "value": 0},
    outcome: {"code": "DOC_MISSING_ROUTE_REQUIRED", "message": "Instradare ogni mancanza rilevante.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_UNCLASSIFIED_FILES", module: M, phase: P,
    title: "File non classificati",
    description: "I file ricevuti devono essere classificati o esclusi esplicitamente.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "warning",
    condition: {"op": "gt", "path": "documents.unclassifiedCount", "value": 0},
    outcome: {"code": "DOC_CLASSIFICATION_REQUIRED", "message": "Classificare i file non riconosciuti."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_PROCESSING_ERRORS", module: M, phase: P,
    title: "Elaborazioni fallite",
    description: "Errori di ingestion/extraction richiedono retry o review.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.processingErrorCount", "value": 0},
    outcome: {"code": "DOC_PROCESSING_RETRY", "message": "Gestire errori di elaborazione."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_UNREADABLE_CURRENT", module: M, phase: P,
    title: "Documento corrente illeggibile",
    description: "Una versione corrente illeggibile non può soddisfare il requisito.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op": "gt", "path": "documents.unreadableCount", "value": 0},
    outcome: {"code": "DOC_UNREADABLE", "message": "Richiedere nuova copia o review manuale.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_PARTIAL_QUALITY", module: M, phase: P,
    title: "Qualità parziale",
    description: "Un documento parziale richiede review prima di usare i claim.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.partialQualityCount", "value": 0},
    outcome: {"code": "DOC_PARTIAL_REVIEW", "message": "Verificare completezza delle pagine/contenuto."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_EXACT_DUPLICATES", module: M, phase: P,
    title: "Duplicati esatti",
    description: "Hash identici devono essere deduplicati senza perdere audit.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "info",
    condition: {"op": "gt", "path": "documents.exactDuplicateCount", "value": 0},
    outcome: {"code": "DOC_EXACT_DUPLICATE", "message": "Collegare il duplicato alla versione esistente."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_POSSIBLE_DUPLICATES", module: M, phase: P,
    title: "Possibili duplicati",
    description: "Fingerprint contenuto uguale ma hash diverso richiede review/versioning.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.possibleDuplicateCount", "value": 0},
    outcome: {"code": "DOC_POSSIBLE_DUPLICATE", "message": "Verificare se si tratta di nuova scansione/versione."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_SUPERSEDED_STILL_CURRENT", module: M, phase: P,
    title: "Versioning incoerente",
    description: "Una versione superseded non può essere anche current.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op": "gt", "path": "documents.versioningInvariantErrorCount", "value": 0},
    outcome: {"code": "DOC_VERSIONING_INVARIANT", "message": "Correggere il versioning.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_LOW_CONFIDENCE", module: M, phase: P,
    title: "Estrazione a bassa confidenza",
    description: "Claim a bassa confidenza non devono diventare facts verificati automaticamente.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.lowConfidenceExtractionCount", "value": 0},
    outcome: {"code": "DOC_LOW_CONFIDENCE", "message": "Aprire review dei campi a bassa confidenza."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_EXTRACTION_WITHOUT_ANCHOR", module: M, phase: P,
    title: "Claim senza evidence anchor",
    description: "Ogni claim rilevante deve poter essere ricondotto al documento/pagina.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.unanchoredClaimCount", "value": 0},
    outcome: {"code": "DOC_EVIDENCE_ANCHOR_REQUIRED", "message": "Creare evidence anchor prima della promozione del claim."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_CRITICAL_FACT_NO_EVIDENCE", module: M, phase: P,
    title: "Fact critico senza evidenza",
    description: "Un fact critico non può essere verificato senza evidenza tracciata.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: {"op": "gt", "path": "documents.criticalFactWithoutEvidenceCount", "value": 0},
    outcome: {"code": "DOC_CRITICAL_EVIDENCE_REQUIRED", "message": "Collegare evidenza verificabile.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_OPEN_CONFLICTS", module: M, phase: P,
    title: "Conflitti documentali aperti",
    description: "Conflitti fra claim/facts non devono essere risolti silenziosamente.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: {"op": "gt", "path": "documents.openConflictCount", "value": 0},
    outcome: {"code": "DOC_CONFLICT_REVIEW", "message": "Riconciliare conflitti e registrare decisione.", "escalationTo": "AGENT"},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_CRITICAL_CONFLICTS", module: M, phase: P,
    title: "Conflitti critici aperti",
    description: "Conflitti critici bloccano la fase.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op": "gt", "path": "documents.criticalConflictCount", "value": 0},
    outcome: {"code": "DOC_CRITICAL_CONFLICT", "message": "Bloccare e risolvere il conflitto.", "blockProgress": true, "escalationTo": "AGENT"},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_DECLARATION_DOCUMENT_MISMATCH", module: M, phase: P,
    title: "Dichiarazione vs documento",
    description: "Discordanza tra dichiarazione cliente e documento richiede review.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.declarationMismatchCount", "value": 0},
    outcome: {"code": "DOC_DECLARATION_MISMATCH", "message": "Mostrare differenze e chiedere chiarimento."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_OFFICIAL_SOURCE_MISMATCH", module: M, phase: P,
    title: "Fonte ufficiale discordante",
    description: "Discordanza con fonte ufficiale richiede decisione professionale.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op": "gt", "path": "documents.officialSourceMismatchCount", "value": 0},
    outcome: {"code": "DOC_OFFICIAL_SOURCE_MISMATCH", "message": "Escalation professionale necessaria.", "blockProgress": true, "escalationTo": "NOTARY"},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_REVIEW_QUEUE_PENDING", module: M, phase: P,
    title: "Review documentali pendenti",
    description: "La coda review deve essere gestita prima dello snapshot finale.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.pendingReviewCount", "value": 0},
    outcome: {"code": "DOC_REVIEW_PENDING", "message": "Completare le review documentali."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_HIGH_PUBLIC_STORAGE", module: M, phase: P,
    title: "Documento sensibile esposto",
    description: "Documenti HIGH non devono avere storage pubblico.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op": "gt", "path": "documents.publicHighSensitivityCount", "value": 0},
    outcome: {"code": "DOC_SECURITY_PUBLIC_STORAGE", "message": "Rimuovere esposizione pubblica e ruotare eventuali link.", "blockProgress": true, "escalationTo": "AGENT"},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_SYNTHETIC_EVIDENCE", module: M, phase: P,
    title: "Output sintetico usato come fonte",
    description: "Un documento generato dall’IA non può essere fonte primaria di un fatto esterno.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical",
    condition: {"op": "gt", "path": "documents.syntheticEvidenceCount", "value": 0},
    outcome: {"code": "DOC_SYNTHETIC_EVIDENCE_BLOCK", "message": "Sostituire con evidenza primaria o verificata.", "blockProgress": true, "escalationTo": "AGENT"},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_ACCESS_AUDIT_GAP", module: M, phase: P,
    title: "Accesso sensibile senza audit",
    description: "Accessi a documenti HIGH devono essere tracciati secondo policy interna.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "gt", "path": "documents.accessAuditGapCount", "value": 0},
    outcome: {"code": "DOC_ACCESS_AUDIT_GAP", "message": "Ripristinare audit trail accessi."},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_LEASE_DOC_MISSING", module: M, phase: P,
    title: "Contratto locazione non acquisito",
    description: "Se l’immobile è locato il fascicolo deve contenere o instradare il contratto.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "property.occupancy", "value": "LEASED"}, {"op": "neq", "path": "documents.leaseContractStatus", "value": "RECEIVED_OR_VERIFIED"}]},
    outcome: {"code": "LEASE_DOC_REQUIRED", "message": "Acquisire/instradare contratto di locazione.", "blockProgress": true},
    sourceRefs: [SOURCE_MAP.MANDATE_MEDIATION],
    active: true, version: 1,
  },
  {
    id: "P03_MORTGAGE_DOC_MISSING", module: M, phase: P,
    title: "Documentazione mutuo non instradata",
    description: "Mutuo attivo richiede routing documentale banca.",
    stability: "STABLE", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "finance.activeMortgage", "value": true}, {"op": "eq", "path": "documents.mortgageRoutingStatus", "value": "MISSING"}]},
    outcome: {"code": "MORTGAGE_DOC_ROUTE", "message": "Aprire richiesta/routing banca."},
    sourceRefs: [SOURCE_MAP.MORTGAGES],
    active: true, version: 1,
  },
  {
    id: "P03_CONDO_DOC_MISSING", module: M, phase: P,
    title: "Documentazione condominiale non instradata",
    description: "Per unità in condominio la situazione amministrativa deve avere routing.",
    stability: "STABLE", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "property.isCondominium", "value": true}, {"op": "eq", "path": "documents.condominiumRoutingStatus", "value": "MISSING"}]},
    outcome: {"code": "CONDO_DOC_ROUTE", "message": "Richiedere/instradare documentazione condominiale."},
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL],
    active: true, version: 1,
  },
  {
    id: "P03_SUCCESSION_DOC_MISSING", module: M, phase: P,
    title: "Documenti successione mancanti",
    description: "Provenienza successoria richiede documentazione e routing notarile.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "ownership.originType", "value": "SUCCESSION"}, {"op": "neq", "path": "documents.successionStatus", "value": "RECEIVED_OR_ROUTED"}]},
    outcome: {"code": "SUCCESSION_DOC_ROUTE", "message": "Acquisire documentazione e instradare al notaio.", "blockProgress": true, "escalationTo": "NOTARY"},
    sourceRefs: [SOURCE_MAP.SUCCESSION],
    active: true, version: 1,
  },
  {
    id: "P03_DONATION_DOC_MISSING", module: M, phase: P,
    title: "Atto di donazione mancante",
    description: "Provenienza donativa richiede atto e routing professionale.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "ownership.originType", "value": "DONATION"}, {"op": "neq", "path": "documents.donationStatus", "value": "RECEIVED_OR_ROUTED"}]},
    outcome: {"code": "DONATION_DOC_ROUTE", "message": "Acquisire atto di donazione.", "blockProgress": true, "escalationTo": "NOTARY"},
    sourceRefs: [SOURCE_MAP.SUCCESSION],
    active: true, version: 1,
  },
  {
    id: "P03_POA_DOC_MISSING", module: M, phase: P,
    title: "Procura mancante",
    description: "Rappresentanza dichiarata richiede evidenza dei poteri.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "ownership.representationUsed", "value": true}, {"op": "neq", "path": "documents.powerOfAttorneyStatus", "value": "RECEIVED_OR_VERIFIED"}]},
    outcome: {"code": "POA_DOC_REQUIRED", "message": "Acquisire procura/poteri.", "blockProgress": true},
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL],
    active: true, version: 1,
  },
  {
    id: "P03_COMPANY_DOC_MISSING", module: M, phase: P,
    title: "Poteri societari mancanti",
    description: "Venditore società richiede evidenza dei poteri.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "client.type", "value": "LEGAL_ENTITY"}, {"op": "neq", "path": "documents.companyAuthorityStatus", "value": "RECEIVED_OR_VERIFIED"}]},
    outcome: {"code": "COMPANY_DOC_REQUIRED", "message": "Acquisire documenti societari/poteri.", "blockProgress": true, "escalationTo": "LAWYER"},
    sourceRefs: [SOURCE_MAP.COMMERCIAL],
    active: true, version: 1,
  },
  {
    id: "P03_TAX_BONUS_DOC_ROUTING", module: M, phase: P,
    title: "Storia bonus senza documenti",
    description: "La storia di interventi agevolati deve avere documentazione/routing fiscale.",
    stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "tax.superbonusOrArticle119History", "value": true}, {"op": "neq", "path": "documents.taxBonusRoutingStatus", "value": "ROUTED_OR_RECEIVED"}]},
    outcome: {"code": "TAX_BONUS_DOC_ROUTE", "message": "Raccogliere documentazione e applicare ruleset fiscale corrente.", "escalationTo": "ACCOUNTANT"},
    sourceRefs: [SOURCE_MAP.TAX],
    freshnessPolicy: {"required": true, "maxAgeDays": 90, "rulesetKey": "ITALY_REAL_ESTATE_TAX"},
    active: true, version: 1,
  },
  {
    id: "P03_APE_ROUTING", module: M, phase: P,
    title: "APE richiesto ma non instradato",
    description: "Quando il ruleset corrente determina necessità APE, il fascicolo deve instradarlo.",
    stability: "DYNAMIC", decisionLevel: "REVIEW", severity: "warning",
    condition: {"op": "all", "conditions": [{"op": "eq", "path": "documents.apeRequired", "value": true}, {"op": "neq", "path": "documents.apeRoutingStatus", "value": "ROUTED_OR_RECEIVED"}]},
    outcome: {"code": "APE_DOC_ROUTE", "message": "Acquisire/instradare APE."},
    sourceRefs: [SOURCE_MAP.URBAN],
    freshnessPolicy: {"required": true, "maxAgeDays": 90, "rulesetKey": "ITALY_APE"},
    active: true, version: 1,
  },
  {
    id: "P03_SNAPSHOT_MISSING", module: M, phase: P,
    title: "Snapshot dossier mancante",
    description: "Il gate deve essere riproducibile con uno snapshot immutabile.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking",
    condition: {"op": "neq", "path": "documents.snapshotStatus", "value": "CURRENT"},
    outcome: {"code": "DOSSIER_SNAPSHOT_REQUIRED", "message": "Generare snapshot P03 prima della chiusura.", "blockProgress": true},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
  {
    id: "P03_READY_GATE", module: M, phase: P,
    title: "Fascicolo pronto per fase successiva",
    description: "Tutti i gate P03 risultano soddisfatti.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "info",
    condition: {"op": "eq", "path": "documents.dossierReadiness", "value": "READY"},
    outcome: {"code": "P03_READY", "message": "Fascicolo pronto per le verifiche successive.", "blockProgress": false},
    sourceRefs: [internalPolicy("Document Intelligence V76.3")],
    active: true, version: 1,
  },
];