import type { BrainRule } from "../types";
import { makeSaleRule } from "../sale-operations/ruleFactory";
export const phaseP07Rules:BrainRule[]=[
  makeSaleRule({"id":"P07_VALUATION_SNAPSHOT_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Valuation Snapshot Missing","factPath":"sale.p07.valuation_snapshot_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_ASKING_PRICE_MISMATCH","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Asking Price Mismatch","factPath":"sale.p07.asking_price_mismatch.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_MASTER_CONTENT_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Master Content Missing","factPath":"sale.p07.master_content_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_PROPERTY_FACTS_STALE","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Property Facts Stale","factPath":"sale.p07.property_facts_stale.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_ENERGY_DISCLOSURE_MISMATCH","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Energy Disclosure Mismatch","factPath":"sale.p07.energy_disclosure_mismatch.status","dynamic":true,"decisionLevel":"AGENT_REQUIRED","severity":"blocking","gate":"PUBLICATION","rulesetKey":"ITALY_SALE_ENERGY_DISCLOSURE_MISMATCH"}),
  makeSaleRule({"id":"P07_MEDIA_RIGHTS_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Media Rights Missing","factPath":"sale.p07.media_rights_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_FLOORPLAN_UNVERIFIED","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Floorplan Unverified","factPath":"sale.p07.floorplan_unverified.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_UNSUPPORTED_CLAIMS","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Unsupported Claims","factPath":"sale.p07.unsupported_claims.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_OWNER_APPROVAL_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Owner Approval Missing","factPath":"sale.p07.owner_approval_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_AGENT_APPROVAL_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Agent Approval Missing","factPath":"sale.p07.agent_approval_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_CHANNEL_PLAN_MISSING","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Channel Plan Missing","factPath":"sale.p07.channel_plan_missing.status","decisionLevel":"REVIEW","severity":"blocking","gate":"PUBLICATION"}),
  makeSaleRule({"id":"P07_READY","module":"SALE_MARKET_READINESS","phase":"PHASE_07_MARKET_READINESS","title":"Ready","factPath":"sale.p07.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gate":"PUBLICATION"})
];
