import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseC01Rules:BrainRule[]=[
  makeAgencyRule({"id":"C01_CUSTOMER_ENTRYPOINT_MISSING","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Customer Entrypoint Missing","factPath":"guimmia.customer.c01.customer_entrypoint_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CUSTOMER_ROLE_MISSING","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Customer Role Missing","factPath":"guimmia.customer.c01.customer_role_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CUSTOMER_INTENT_MISSING","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Customer Intent Missing","factPath":"guimmia.customer.c01.customer_intent_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_PROPERTY_RELATION_MISSING","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Property Relation Missing","factPath":"guimmia.customer.c01.property_relation_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_OPERATION_ROUTE_UNCONFIRMED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Operation Route Unconfirmed","factPath":"guimmia.customer.c01.operation_route_unconfirmed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CUSTOMER_SERVICE_MODEL_UNSELECTED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Customer Service Model Unselected","factPath":"guimmia.customer.c01.customer_service_model_unselected.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_SERVICE_SCOPE_UNACKNOWLEDGED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Service Scope Unacknowledged","factPath":"guimmia.customer.c01.service_scope_unacknowledged.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_FIXED_COMPENSATION_UNDISCLOSED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Fixed Compensation Undisclosed","factPath":"guimmia.customer.c01.fixed_compensation_undisclosed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CUSTOMER_EXPECTATIONS_UNRECORDED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Customer Expectations Unrecorded","factPath":"guimmia.customer.c01.customer_expectations_unrecorded.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_REQUIRED_OFFLINE_ACTIONS_UNEXPLAINED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Required Offline Actions Unexplained","factPath":"guimmia.customer.c01.required_offline_actions_unexplained.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_PHYSICAL_STEP_OWNER_UNASSIGNED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Physical Step Owner Unassigned","factPath":"guimmia.customer.c01.physical_step_owner_unassigned.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CONTACT_CHANNEL_UNVERIFIED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Contact Channel Unverified","factPath":"guimmia.customer.c01.contact_channel_unverified.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_LANGUAGE_UNSET","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Language Unset","factPath":"guimmia.customer.c01.language_unset.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_ACCESSIBILITY_NEEDS_UNRECORDED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Accessibility Needs Unrecorded","factPath":"guimmia.customer.c01.accessibility_needs_unrecorded.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_CONTEXT_HANDOFF_MISSING","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Context Handoff Missing","factPath":"guimmia.customer.c01.context_handoff_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_INTERNAL_HUMAN_OWNER_UNASSIGNED","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Internal Human Owner Unassigned","factPath":"guimmia.customer.c01.internal_human_owner_unassigned.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_JOURNEY_READY","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Journey Ready","factPath":"guimmia.customer.c01.journey_ready.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]}),
  makeAgencyRule({"id":"C01_READY","module":"GUIMMIA_CUSTOMER_JOURNEY","phase":"PHASE_C01_DIRECT_CUSTOMER_JOURNEY","title":"Ready","factPath":"guimmia.customer.c01.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","OFFER","BOOKING"]})
];
