import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO10Rules:BrainRule[]=[
  makeAgencyRule({"id":"O10_PRIVACY_NOTICE_MISSING","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Privacy Notice Missing","factPath":"agency.o10.privacy_notice_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_PRIVACY_NOTICE"}),
  makeAgencyRule({"id":"O10_PURPOSE_SCOPE_MISMATCH","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Purpose Scope Mismatch","factPath":"agency.o10.purpose_scope_mismatch.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_DATA_CATEGORY_EXCESS","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Data Category Excess","factPath":"agency.o10.data_category_excess.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_RETENTION_DATE_MISSING","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Retention Date Missing","factPath":"agency.o10.retention_date_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_RETENTION_DATE"}),
  makeAgencyRule({"id":"O10_RETENTION_EXPIRED","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Retention Expired","factPath":"agency.o10.retention_expired.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_RETENTION"}),
  makeAgencyRule({"id":"O10_ERASURE_REQUEST_OPEN","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Erasure Request Open","factPath":"agency.o10.erasure_request_open.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_ACCESS_REQUEST_OVERDUE","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Access Request Overdue","factPath":"agency.o10.access_request_overdue.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_RECTIFICATION_REQUEST_OPEN","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Rectification Request Open","factPath":"agency.o10.rectification_request_open.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_PORTABILITY_REQUEST_OPEN","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Portability Request Open","factPath":"agency.o10.portability_request_open.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_PROCESSING_RESTRICTION_OPEN","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Processing Restriction Open","factPath":"agency.o10.processing_restriction_open.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_LEGAL_HOLD_CONFLICT","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Legal Hold Conflict","factPath":"agency.o10.legal_hold_conflict.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_LEGAL_HOLD_CONFLICT"}),
  makeAgencyRule({"id":"O10_EXPORT_UNREDACTED","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Export Unredacted","factPath":"agency.o10.export_unredacted.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_SENSITIVE_FIELD_EXPOSED","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Sensitive Field Exposed","factPath":"agency.o10.sensitive_field_exposed.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_ROLE_SCOPE_VIOLATION","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Role Scope Violation","factPath":"agency.o10.role_scope_violation.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O10_PRIVACY_HUMAN_REVIEW_MISSING","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Privacy Human Review Missing","factPath":"agency.o10.privacy_human_review_missing.status","dynamic":true,"decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_PRIVACY_HUMAN_REVIEW"}),
  makeAgencyRule({"id":"O10_READY","module":"AGENCY_PRIVACY_RETENTION","phase":"PHASE_O10_PRIVACY_RETENTION_REQUESTS","title":"Ready","factPath":"agency.o10.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","OFFER","CANDIDATE_SELECTION","BOOKING","GUEST_REPORTING"]})
];
