import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO11Rules:BrainRule[]=[
  makeAgencyRule({"id":"O11_VOICE_PROVIDER_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Voice Provider Missing","factPath":"agency.o11.voice_provider_missing.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_VOICE_CAPABILITY_DISABLED","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Voice Capability Disabled","factPath":"agency.o11.voice_capability_disabled.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_CALL_PURPOSE_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Call Purpose Missing","factPath":"agency.o11.call_purpose_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_CALL_CONSENT_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Call Consent Missing","factPath":"agency.o11.call_consent_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"],"rulesetKey":"ITALY_AGENCY_CALL_CONSENT"}),
  makeAgencyRule({"id":"O11_RECORDING_NOTICE_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Recording Notice Missing","factPath":"agency.o11.recording_notice_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"],"rulesetKey":"ITALY_AGENCY_RECORDING_NOTICE"}),
  makeAgencyRule({"id":"O11_RECORDING_CONSENT_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Recording Consent Missing","factPath":"agency.o11.recording_consent_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"],"rulesetKey":"ITALY_AGENCY_RECORDING_CONSENT"}),
  makeAgencyRule({"id":"O11_CALL_IDENTITY_UNVERIFIED","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Call Identity Unverified","factPath":"agency.o11.call_identity_unverified.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_INTENT_CONFIDENCE_LOW","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Intent Confidence Low","factPath":"agency.o11.intent_confidence_low.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_REQUIRED_DISCLOSURE_UNSPOKEN","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Required Disclosure Unspoken","factPath":"agency.o11.required_disclosure_unspoken.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_TRANSCRIPT_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Transcript Missing","factPath":"agency.o11.transcript_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_TRANSCRIPT_HASH_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Transcript Hash Missing","factPath":"agency.o11.transcript_hash_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_MATERIAL_CALL_UNREVIEWED","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Material Call Unreviewed","factPath":"agency.o11.material_call_unreviewed.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_APPOINTMENT_CONFIRMATION_UNCAPTURED","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Appointment Confirmation Uncaptured","factPath":"agency.o11.appointment_confirmation_uncaptured.status","decisionLevel":"REVIEW","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_HUMAN_HANDOFF_MISSING","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Human Handoff Missing","factPath":"agency.o11.human_handoff_missing.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_CALL_SUMMARY_UNAPPROVED","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Call Summary Unapproved","factPath":"agency.o11.call_summary_unapproved.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"O11_READY","module":"AGENCY_VOICE_READINESS","phase":"PHASE_O11_VOICE_CONVERSATION_READINESS","title":"Ready","factPath":"agency.o11.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["OFFER","CANDIDATE_SELECTION","BOOKING","CHECK_IN"]})
];
