import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseC03Rules:BrainRule[]=[
  makeAgencyRule({"id":"C03_MILESTONE_PLAN_MISSING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Milestone Plan Missing","factPath":"guimmia.customer.c03.milestone_plan_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_CUSTOMER_VISIBLE_STATUS_STALE","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Customer Visible Status Stale","factPath":"guimmia.customer.c03.customer_visible_status_stale.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_NEXT_ACTION_MISSING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Next Action Missing","factPath":"guimmia.customer.c03.next_action_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_ACTION_OWNER_MISSING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Action Owner Missing","factPath":"guimmia.customer.c03.action_owner_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_DUE_DATE_MISSING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Due Date Missing","factPath":"guimmia.customer.c03.due_date_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_CUSTOMER_NOTIFICATION_PENDING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Customer Notification Pending","factPath":"guimmia.customer.c03.customer_notification_pending.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_APPOINTMENT_PROPOSAL_PENDING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Appointment Proposal Pending","factPath":"guimmia.customer.c03.appointment_proposal_pending.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_APPOINTMENT_CONFIRMATION_PENDING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Appointment Confirmation Pending","factPath":"guimmia.customer.c03.appointment_confirmation_pending.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_PROFESSIONAL_STATUS_HIDDEN","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Professional Status Hidden","factPath":"guimmia.customer.c03.professional_status_hidden.status","decisionLevel":"PROFESSIONAL_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_OFFER_STATUS_HIDDEN","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Offer Status Hidden","factPath":"guimmia.customer.c03.offer_status_hidden.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_CONTRACT_STATUS_HIDDEN","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Contract Status Hidden","factPath":"guimmia.customer.c03.contract_status_hidden.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_CLOSING_STATUS_HIDDEN","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Closing Status Hidden","factPath":"guimmia.customer.c03.closing_status_hidden.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_AI_CONTEXT_STALE","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Ai Context Stale","factPath":"guimmia.customer.c03.ai_context_stale.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_HUMAN_HANDOFF_PENDING","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Human Handoff Pending","factPath":"guimmia.customer.c03.human_handoff_pending.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_COMPLAINT_STATUS_HIDDEN","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Complaint Status Hidden","factPath":"guimmia.customer.c03.complaint_status_hidden.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]}),
  makeAgencyRule({"id":"C03_JOURNEY_COMPLETE","module":"GUIMMIA_CUSTOMER_PROGRESS","phase":"PHASE_C03_CUSTOMER_PROGRESS_ASSISTANCE","title":"Journey Complete","factPath":"guimmia.customer.c03.journey_complete.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"]})
];
