import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_T08_STAY";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseT08Rules: BrainRule[] = [
  { id: "T08_BOOKING_NOT_CONFIRMED", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Prenotazione non confermata", description: "Prenotazione non confermata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.bookingStatus","value":"CONFIRMED"}, outcome: {"code":"CONFIRMED_BOOKING_REQUIRED_FOR_CHECKIN","message":"Il check-in richiede una prenotazione confermata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_GUEST_IDENTITY_INCOMPLETE", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Identità ospiti incompleta", description: "Identità ospiti incompleta", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.guestIdentityStatus","value":"VERIFIED"}, outcome: {"code":"TOURIST_GUEST_IDENTITY_REQUIRED","message":"Verificare i dati necessari senza eccedenze.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_REPORTING_RULESET_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Ruleset comunicazione ospiti non corrente", description: "Ruleset comunicazione ospiti non corrente", stability: "DYNAMIC", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.guestReportingRulesetStatus","value":"CURRENT"}, outcome: {"code":"GUEST_REPORTING_RULESET_REQUIRED","message":"Verificare fonte, scadenza e procedura applicabili.","blockProgress":true}, sourceRefs: [SOURCE_MAP.BDSR_FAQ], freshnessPolicy: fresh("ITALY_GUEST_REPORTING",30), active: true, version: 1 },
  { id: "T08_REPORTING_CREDENTIALS_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Credenziali di reporting ospiti mancanti", description: "Credenziali di reporting ospiti mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.guestReportingCredentialStatus","value":"READY"}, outcome: {"code":"GUEST_REPORTING_CREDENTIAL_REQUIRED","message":"Verificare disponibilità e responsabilità delle credenziali prima dell'arrivo.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_REPORTING_TASK_OVERDUE", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Comunicazione ospiti scaduta", description: "Comunicazione ospiti scaduta", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.tourist.guestReportingOverdueMinutes","value":0}, outcome: {"code":"GUEST_REPORTING_OVERDUE","message":"Escalare immediatamente e conservare prova dell'adempimento.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_CHECKIN_WINDOW_VIOLATION", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Check-in fuori finestra autorizzata", description: "Check-in fuori finestra autorizzata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"truthy","path":"rental.tourist.checkinWindowViolation"}, outcome: {"code":"CHECKIN_WINDOW_REVIEW_REQUIRED","message":"Richiedere autorizzazione umana e aggiornare assistenza/accesso.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_SAFETY_ACK_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Informazioni di sicurezza non confermate", description: "Informazioni di sicurezza non confermate", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.safetyAcknowledgementStatus","value":"CONFIRMED"}, outcome: {"code":"TOURIST_SAFETY_ACK_REQUIRED","message":"Fornire e registrare le informazioni di sicurezza applicabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_ACCESS_INSTRUCTIONS_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Istruzioni di accesso mancanti", description: "Istruzioni di accesso mancanti", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.accessInstructionStatus","value":"READY"}, outcome: {"code":"TOURIST_ACCESS_INSTRUCTIONS_REQUIRED","message":"Preparare accesso, contatto e alternativa in caso di problema.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_SUPPORT_UNAVAILABLE", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Assistenza umana non reperibile", description: "Assistenza umana non reperibile", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.stayStatus","value":"ACTIVE"},{"op":"neq","path":"rental.tourist.humanSupportStatus","value":"AVAILABLE"}]}, outcome: {"code":"HUMAN_SUPPORT_REQUIRED","message":"La risposta automatica deve poter escalare a un umano reperibile.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_CRITICAL_INCIDENT_UNASSIGNED", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Incidente critico non assegnato", description: "Incidente critico non assegnato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.incidentPriority","value":"CRITICAL"},{"op":"neq","path":"rental.tourist.incidentAssignmentStatus","value":"ASSIGNED_HUMAN"}]}, outcome: {"code":"CRITICAL_STAY_INCIDENT_ESCALATION","message":"Escalare subito e bloccare risposte definitive automatiche.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_UNAUTHORIZED_KEY_DELIVERY", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Consegna accesso non autorizzata", description: "Consegna accesso non autorizzata", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"neq","path":"rental.tourist.keyDeliveryActorStatus","value":"AUTHORIZED"}, outcome: {"code":"TOURIST_KEY_DELIVERY_BLOCK","message":"Rifiutare la consegna e registrare l'anomalia.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_CHECKOUT_EVIDENCE_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Evidenza di check-out mancante", description: "Evidenza di check-out mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.tourist.stayStatus","value":"CHECKED_OUT"},{"op":"neq","path":"rental.tourist.checkoutEvidenceStatus","value":"READY"}]}, outcome: {"code":"TOURIST_CHECKOUT_EVIDENCE_REQUIRED","message":"Registrare chiavi, stato, orario e riserve prima della chiusura.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_RETENTION_PLAN_MISSING", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Retention dati soggiorno mancante", description: "Retention dati soggiorno mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.tourist.stayRetentionStatus","value":"ACTIVE"}, outcome: {"code":"TOURIST_STAY_RETENTION_REQUIRED","message":"Definire conservazione differenziata per obbligo e finalità.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "T08_ACTIVE", module: "TOURIST_STAY_OPERATIONS", phase: P, title: "Soggiorno operativo", description: "Soggiorno operativo", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.tourist.stayStatus","value":"ACTIVE"}, outcome: {"code":"TOURIST_STAY_ACTIVE","message":"Check-in, assistenza e task operativi sono attivi."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
