import type{BrainRule}from"../types";
import{makeAgencyRule}from"../agency-operations/ruleFactory";
export const phaseO07Rules:BrainRule[]=[
  makeAgencyRule({"id":"O07_CONNECTION_MISSING","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Connection Missing","factPath":"agency.o07.connection_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_CONNECTION_DISABLED","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Connection Disabled","factPath":"agency.o07.connection_disabled.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_CREDENTIAL_REFERENCE_MISSING","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Credential Reference Missing","factPath":"agency.o07.credential_reference_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_CAPABILITY_NOT_ALLOWED","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Capability Not Allowed","factPath":"agency.o07.capability_not_allowed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_PAYLOAD_SCHEMA_MISMATCH","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Payload Schema Mismatch","factPath":"agency.o07.payload_schema_mismatch.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_DATA_ALLOWLIST_VIOLATION","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Data Allowlist Violation","factPath":"agency.o07.data_allowlist_violation.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_CUSTOMER_CONSENT_MISSING","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Customer Consent Missing","factPath":"agency.o07.customer_consent_missing.status","dynamic":true,"decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"],"rulesetKey":"ITALY_AGENCY_CUSTOMER_CONSENT"}),
  makeAgencyRule({"id":"O07_IDEMPOTENCY_MISSING","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Idempotency Missing","factPath":"agency.o07.idempotency_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_DELIVERY_FAILED","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Delivery Failed","factPath":"agency.o07.delivery_failed.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_RETRY_EXHAUSTED","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Retry Exhausted","factPath":"agency.o07.retry_exhausted.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_WEBHOOK_SIGNATURE_INVALID","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Webhook Signature Invalid","factPath":"agency.o07.webhook_signature_invalid.status","decisionLevel":"REVIEW","severity":"critical","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_ACKNOWLEDGEMENT_MISSING","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Acknowledgement Missing","factPath":"agency.o07.acknowledgement_missing.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_REMOTE_STATE_CONFLICT","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Remote State Conflict","factPath":"agency.o07.remote_state_conflict.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_HUMAN_REVIEW_REQUIRED","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Human Review Required","factPath":"agency.o07.human_review_required.status","decisionLevel":"AGENT_REQUIRED","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_PORTAL_API_UNAVAILABLE","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Portal Api Unavailable","factPath":"agency.o07.portal_api_unavailable.status","decisionLevel":"REVIEW","severity":"blocking","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]}),
  makeAgencyRule({"id":"O07_READY","module":"AGENCY_INTEGRATION_DELIVERY","phase":"PHASE_O07_INTEGRATION_DELIVERY","title":"Ready","factPath":"agency.o07.ready.status","ready":true,"decisionLevel":"AUTO","severity":"info","gates":["PUBLICATION","RENTAL_PUBLICATION","TOURIST_PUBLICATION","BOOKING","GUEST_REPORTING"]})
];
