
import type{BrainRule}from"../types";
import{makeOrchestratorRule}from"../case-orchestrator/ruleFactory";
export const phaseK05Rules:BrainRule[]=[
  makeOrchestratorRule({id:"K05_DECISION_REASON_CODES_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Reason Codes Missing",factPath:"guimmia.orchestrator.k05.decision_reason_codes_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_EVIDENCE_REFS_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Evidence Refs Missing",factPath:"guimmia.orchestrator.k05.decision_evidence_refs_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_RULE_REFS_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Rule Refs Missing",factPath:"guimmia.orchestrator.k05.decision_rule_refs_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_ACTOR_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Actor Missing",factPath:"guimmia.orchestrator.k05.decision_actor_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_TIMESTAMP_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Timestamp Missing",factPath:"guimmia.orchestrator.k05.decision_timestamp_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_HASH_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Hash Missing",factPath:"guimmia.orchestrator.k05.decision_hash_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_PREVIOUS_DECISION_HASH_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Previous Decision Hash Missing",factPath:"guimmia.orchestrator.k05.previous_decision_hash_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_CHAIN_BROKEN",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Chain Broken",factPath:"guimmia.orchestrator.k05.decision_chain_broken.status",decisionLevel:"REVIEW",severity:"critical",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_CUSTOMER_EXPLANATION_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Customer Explanation Missing",factPath:"guimmia.orchestrator.k05.customer_explanation_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_CUSTOMER_EXPLANATION_NOT_PLAIN",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Customer Explanation Not Plain",factPath:"guimmia.orchestrator.k05.customer_explanation_not_plain.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_INTERNAL_EXPLANATION_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Internal Explanation Missing",factPath:"guimmia.orchestrator.k05.internal_explanation_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_SENSITIVE_DATA_EXPOSED",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Sensitive Data Exposed",factPath:"guimmia.orchestrator.k05.sensitive_data_exposed.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_CONFIDENCE_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Confidence Missing",factPath:"guimmia.orchestrator.k05.confidence_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_LOW_CONFIDENCE_HANDOFF_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Low Confidence Handoff Missing",factPath:"guimmia.orchestrator.k05.low_confidence_handoff_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_DECISION_REPLAY_MISMATCH",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Decision Replay Mismatch",factPath:"guimmia.orchestrator.k05.decision_replay_mismatch.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"}),
  makeOrchestratorRule({id:"K05_AUDIT_EVENT_MISSING",module:"CASE_DECISION_AUDIT",phase:"PHASE_K05_DECISION_AUDIT_EXPLANATION",title:"Audit Event Missing",factPath:"guimmia.orchestrator.k05.audit_event_missing.status",decisionLevel:"REVIEW",severity:"blocking",gates:["PUBLICATION","OFFER","PRELIMINARY","CLOSING","RENTAL_PUBLICATION","CANDIDATE_SELECTION","LEASE_SIGNING","BOOKING","CHECK_IN"],dynamic:false,operationScope:"SUPPORTED"})
];
