import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";
const P = "PHASE_R08_SCREENING";
const fresh = (rulesetKey:string,maxAgeDays=30) => ({required:true,rulesetKey,maxAgeDays});

export const phaseR08Rules: BrainRule[] = [
  { id: "R08_CRITERIA_VERSION_MISSING", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Versione criteri di screening mancante", description: "Versione criteri di screening mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"not","condition":{"op":"exists","path":"rental.screening.criteriaVersion"}}, outcome: {"code":"SCREENING_CRITERIA_VERSION_REQUIRED","message":"Associare la candidatura a criteri approvati, trasparenti e versionati.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_PROTECTED_ATTRIBUTE_PRESENT", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Attributi protetti presenti nello screening", description: "Attributi protetti presenti nello screening", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.screening.protectedAttributeCount","value":0}, outcome: {"code":"PROTECTED_ATTRIBUTE_SCREENING_BLOCK","message":"Rimuovere gli attributi protetti e invalidare il risultato derivato.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_PROXY_DISCRIMINATOR_PRESENT", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Proxy potenzialmente discriminatorio rilevato", description: "Proxy potenzialmente discriminatorio rilevato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"gt","path":"rental.screening.proxyDiscriminatorCount","value":0}, outcome: {"code":"DISCRIMINATORY_PROXY_REVIEW","message":"Sospendere lo screening e sottoporre il criterio a review umana.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_CONSENT_STALE", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Consenso o base del trattamento non corrente", description: "Consenso o base del trattamento non corrente", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"neq","path":"rental.screening.consentStatus","value":"VALID"}, outcome: {"code":"SCREENING_CONSENT_INVALID","message":"Non valutare dati la cui base di trattamento non è valida.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_UNVERIFIED_EVIDENCE", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Evidenze di screening non verificate", description: "Evidenze di screening non verificate", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"gt","path":"rental.screening.unverifiedEvidenceCount","value":0}, outcome: {"code":"VERIFIED_SCREENING_EVIDENCE_REQUIRED","message":"La decisione non può basarsi su evidenze non verificate.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], evidencePolicy: {requiredFactPaths:["rental.screening.evidenceStatus"],requireVerifiedEvidence:true,acceptedProvenance:["DOCUMENT","OFFICIAL_SOURCE","AGENT","PROFESSIONAL","SYSTEM"]}, active: true, version: 1 },
  { id: "R08_EVIDENCE_CONFLICT", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Evidenze del candidato in conflitto", description: "Evidenze del candidato in conflitto", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.screening.evidenceConflictCount","value":0}, outcome: {"code":"CANDIDATE_EVIDENCE_CONFLICT","message":"Mostrare il conflitto senza risolverlo automaticamente.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_AUTOMATIC_SCORE_FINAL", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Punteggio automatico usato come decisione finale", description: "Punteggio automatico usato come decisione finale", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"truthy","path":"rental.screening.automaticScoreIsFinal"}, outcome: {"code":"AUTOMATIC_TENANT_DECISION_FORBIDDEN","message":"Il punteggio può assistere la review ma non selezionare il conduttore.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_AI_DECISION_SOURCE", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Decisione candidato attribuita all'AI", description: "Decisione candidato attribuita all'AI", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"eq","path":"rental.screening.decisionSource","value":"AI_ONLY"}, outcome: {"code":"AI_CANDIDATE_DECISION_FORBIDDEN","message":"La decisione finale deve essere presa e firmata da una persona autorizzata.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_HUMAN_DECISION_MISSING", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Decisione umana mancante", description: "Decisione umana mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"in","path":"rental.screening.status","values":["SHORTLISTED","FINAL_REVIEW"]},{"op":"neq","path":"rental.screening.humanDecisionStatus","value":"RECORDED"}]}, outcome: {"code":"HUMAN_CANDIDATE_DECISION_REQUIRED","message":"Registrare la decisione dell'agente o del locatore autorizzato.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_RATIONALE_MISSING", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Motivazione ammessa non registrata", description: "Motivazione ammessa non registrata", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.screening.humanDecisionStatus","value":"RECORDED"},{"op":"falsy","path":"rental.screening.allowedRationalePresent"}]}, outcome: {"code":"ALLOWED_RATIONALE_REQUIRED","message":"La decisione deve conservare una motivazione pertinente e non discriminatoria.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_CRITERIA_CHANGED", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Criteri modificati dopo la candidatura", description: "Criteri modificati dopo la candidatura", stability: "INTERNAL", decisionLevel: "AUTO", severity: "blocking", condition: {"op":"eq","path":"rental.screening.criteriaSnapshotStatus","value":"STALE"}, outcome: {"code":"SCREENING_CRITERIA_STALE","message":"Ripetere la review con criteri correnti e informare l'attore umano.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_ADVERSE_EXPLANATION_MISSING", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Spiegazione della decisione negativa mancante", description: "Spiegazione della decisione negativa mancante", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"eq","path":"rental.screening.decision","value":"REJECTED"},{"op":"neq","path":"rental.screening.explanationStatus","value":"READY"}]}, outcome: {"code":"ADVERSE_DECISION_EXPLANATION_REQUIRED","message":"Preparare una spiegazione basata soltanto su criteri ammessi.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_RETENTION_OVERDUE", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Dati candidato oltre il termine di conservazione", description: "Dati candidato oltre il termine di conservazione", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"gt","path":"rental.screening.retentionOverdueDays","value":0}, outcome: {"code":"CANDIDATE_DATA_RETENTION_OVERDUE","message":"Cancellare o anonimizzare i dati scaduti salvo obbligo documentato.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_UNAUTHORIZED_ACTOR", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Attore della decisione non autorizzato", description: "Attore della decisione non autorizzato", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "critical", condition: {"op":"neq","path":"rental.screening.decisionActorStatus","value":"AUTHORIZED_HUMAN"}, outcome: {"code":"CANDIDATE_DECISION_ACTOR_FORBIDDEN","message":"Rifiutare la decisione e richiedere un attore umano autorizzato.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_SINGLE_CANDIDATE_AUTO_ACCEPT", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Accettazione automatica dell'unico candidato", description: "Accettazione automatica dell'unico candidato", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "critical", condition: {"op":"truthy","path":"rental.screening.singleCandidateAutoAccepted"}, outcome: {"code":"AUTO_ACCEPTANCE_FORBIDDEN","message":"Anche in presenza di un solo candidato la decisione resta umana.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_OVERRIDE_WITHOUT_REASON", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Override manuale senza motivazione", description: "Override manuale senza motivazione", stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking", condition: {"op":"all","conditions":[{"op":"truthy","path":"rental.screening.manualOverride"},{"op":"falsy","path":"rental.screening.overrideReasonPresent"}]}, outcome: {"code":"SCREENING_OVERRIDE_REASON_REQUIRED","message":"Registrare ragione, autore e data dell'override.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_EQUAL_TREATMENT_AUDIT_MISSING", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Audit di parità di trattamento mancante", description: "Audit di parità di trattamento mancante", stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking", condition: {"op":"neq","path":"rental.screening.equalTreatmentAuditStatus","value":"PASSED"}, outcome: {"code":"EQUAL_TREATMENT_AUDIT_REQUIRED","message":"Verificare applicazione coerente dei criteri fra candidature comparabili.","blockProgress":true}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
  { id: "R08_READY", module: "RENTAL_HUMAN_SCREENING", phase: P, title: "Decisione umana candidato registrata", description: "Decisione umana candidato registrata", stability: "INTERNAL", decisionLevel: "AUTO", severity: "info", condition: {"op":"eq","path":"rental.screening.status","value":"HUMAN_DECIDED"}, outcome: {"code":"HUMAN_CANDIDATE_DECISION_READY","message":"La scelta è stata registrata da un attore umano autorizzato."}, sourceRefs: [internalPolicy("V76.7 Rental Operations & Tourist Lifecycle Engine")], active: true, version: 1 },
];
