import type { BrainRule } from "../types";
import { SOURCE_MAP, internalPolicy } from "../data/sourceMap";

const P = "PHASE_02_OWNERSHIP_TITLE";
const M = "OWNERSHIP_TITLE";

export const phase02Rules: BrainRule[] = [
  {
    id: "P02_TITLE_DOCUMENT_MISSING", module: M, phase: P,
    title: "Atto/titolo di provenienza non acquisito",
    description: "La verifica della titolarità richiede il documento di provenienza o altra evidenza appropriata.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "neq", path: "ownership.titleDocumentStatus", value: "ACQUIRED" },
    outcome: { code: "TITLE_DOCUMENT_REQUIRED", message: "Acquisire il titolo di provenienza e registrare il documento nel fascicolo.", blockProgress: true, suggestedActions: ["Richiedi atto", "Classifica tipologia di provenienza"] },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, SOURCE_MAP.TRANSCRIPTION, internalPolicy("Fascicolo titolarità")], active: true, version: 1,
  },
  {
    id: "P02_HOLDERS_NOT_RECONCILED", module: M, phase: P,
    title: "Titolari non riconciliati",
    description: "I soggetti dichiarati dal cliente devono essere confrontati con i documenti e le verifiche disponibili.",
    stability: "INTERNAL", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "neq", path: "ownership.holdersStatus", value: "RECONCILED" },
    outcome: { code: "HOLDERS_RECONCILIATION_REQUIRED", message: "Riconciliare titolari, quote e diritti prima di proseguire.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, SOURCE_MAP.TRANSCRIPTION], active: true, version: 1,
  },
  {
    id: "P02_MULTIPLE_HOLDERS_INCOMPLETE", module: M, phase: P,
    title: "Comproprietari incompleti",
    description: "Se esistono più titolari, Guimmia deve sapere se tutti sono identificati e quale diritto/Quota risulta per ciascuno.",
    stability: "STABLE", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "ownership.multipleHolders", value: true },
      { op: "neq", path: "ownership.allHoldersIdentified", value: true },
    ] },
    outcome: { code: "ALL_HOLDERS_REQUIRED", message: "Completare l'elenco dei titolari e dei diritti dichiarati/documentati.", blockProgress: true },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL], active: true, version: 1,
  },
  {
    id: "P02_MARITAL_REGIME_UNKNOWN", module: M, phase: P,
    title: "Regime patrimoniale rilevante non chiarito",
    description: "Quando il regime familiare può incidere sulla titolarità o sul potere di disporre, Guimmia deve aprire una verifica e non assumere conclusioni.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "warning",
    condition: { op: "eq", path: "ownership.maritalRegimeRelevance", value: "UNKNOWN" },
    outcome: { code: "MARITAL_REGIME_REVIEW", message: "Chiarire il regime patrimoniale e l'eventuale rilevanza per la vendita.", escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.FAMILY], active: true, version: 1,
  },
  {
    id: "P02_SPOUSAL_RIGHTS_UNRESOLVED", module: M, phase: P,
    title: "Possibile rilevanza del coniuge non risolta",
    description: "Se dai documenti o dalle dichiarazioni emerge una possibile rilevanza del coniuge, il caso richiede verifica umana.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "eq", path: "ownership.spousalRightsStatus", value: "UNRESOLVED" },
    outcome: { code: "SPOUSAL_RIGHTS_REVIEW", message: "Verificare chi deve partecipare o prestare consenso secondo il caso concreto.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.FAMILY], active: true, version: 1,
  },
  {
    id: "P02_USUFRUCT_OR_NAKED_OWNERSHIP", module: M, phase: P,
    title: "Usufrutto / nuda proprietà presenti",
    description: "La presenza di diritti distinti richiede identificazione dei rispettivi titolari e dell'oggetto della vendita.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "in", path: "ownership.rightType", values: ["USUFRUCT", "NAKED_OWNERSHIP", "MIXED_USUFRUCT_NAKED"] },
    outcome: { code: "REAL_RIGHT_SPLIT_REVIEW", message: "Identificare tutti i titolari dei diritti e verificare l'operazione che si intende compiere.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, SOURCE_MAP.LEGAL_ESTIMATE], active: true, version: 1,
  },
  {
    id: "P02_SURFACE_OR_OTHER_REAL_RIGHT", module: M, phase: P,
    title: "Diritto reale particolare",
    description: "Superficie, enfiteusi, uso, abitazione o altri diritti reali richiedono routing specifico.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "in", path: "ownership.rightType", values: ["SURFACE", "EMPHYTEUSIS", "USE", "HABITATION", "OTHER_REAL_RIGHT"] },
    outcome: { code: "SPECIAL_REAL_RIGHT_REVIEW", message: "Non trattare come piena proprietà ordinaria; acquisire documenti e coinvolgere il professionista appropriato.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, SOURCE_MAP.LEGAL_ESTIMATE], active: true, version: 1,
  },
  {
    id: "P02_SUCCESSION_PENDING", module: M, phase: P,
    title: "Provenienza successoria non completata",
    description: "Una successione dichiarata ma non documentalmente risolta deve essere approfondita prima di presentare la titolarità come verificata.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "ownership.originType", value: "SUCCESSION" },
      { op: "neq", path: "ownership.successionStatus", value: "RESOLVED" },
    ] },
    outcome: { code: "SUCCESSION_REVIEW_REQUIRED", message: "Acquisire la documentazione successoria e verificare gli adempimenti/atti rilevanti con il professionista appropriato.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.SUCCESSION, SOURCE_MAP.TRANSCRIPTION], active: true, version: 1,
  },
  {
    id: "P02_FOREIGN_SUCCESSION", module: M, phase: P,
    title: "Successione con elemento estero",
    description: "Gli elementi transfrontalieri non vengono risolti autonomamente dal motore.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "eq", path: "ownership.foreignSuccession", value: true },
    outcome: { code: "FOREIGN_SUCCESSION_ESCALATION", message: "Richiedere verifica notarile/legale sul titolo successorio e sui documenti applicabili.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.SUCCESSION], active: true, version: 1,
  },
  {
    id: "P02_DONATION_ORIGIN", module: M, phase: P,
    title: "Provenienza da donazione",
    description: "La donazione è una provenienza da evidenziare e sottoporre a verifica specifica; Guimmia non conclude automaticamente sulla libera circolazione.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "warning",
    condition: { op: "eq", path: "ownership.originType", value: "DONATION" },
    outcome: { code: "DONATION_PROVENANCE_REVIEW", message: "Raccogliere dati dell'atto e richiedere verifica notarile/legale del caso concreto prima di qualificare il rischio.", escalationTo: "NOTARY", suggestedActions: ["Acquisisci atto di donazione", "Registra date e soggetti", "Non dare esito automatico sulla commerciabilità"] },
    sourceRefs: [SOURCE_MAP.SUCCESSION], active: true, version: 1,
  },
  {
    id: "P02_USUCAPION_ASSERTED", module: M, phase: P,
    title: "Titolarità dichiarata per usucapione / possesso",
    description: "Un'affermazione di acquisto per usucapione non viene equiparata automaticamente a un titolo verificato.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "eq", path: "ownership.originType", value: "USUCAPION" },
    outcome: { code: "USUCAPION_PROFESSIONAL_REVIEW", message: "Acquisire il titolo/accertamento disponibile e richiedere verifica legale/notarile prima di proseguire.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL, SOURCE_MAP.TRANSCRIPTION], active: true, version: 1,
  },
  {
    id: "P02_POWER_OF_ATTORNEY_UNRESOLVED", module: M, phase: P,
    title: "Procura non risolta",
    description: "Il potere di vendere o conferire incarico per conto altrui deve risultare verificato nel fascicolo.",
    stability: "STABLE", decisionLevel: "AGENT_REQUIRED", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "ownership.representationUsed", value: true },
      { op: "neq", path: "ownership.powerOfAttorneyStatus", value: "VERIFIED" },
    ] },
    outcome: { code: "POWER_OF_ATTORNEY_REVIEW", message: "Verificare la procura e il perimetro dei poteri prima di procedere.", blockProgress: true, escalationTo: "AGENT" },
    sourceRefs: [SOURCE_MAP.CONTRACTS, SOURCE_MAP.MANDATE_MEDIATION], active: true, version: 1,
  },
  {
    id: "P02_COMPANY_SELLER_AUTHORITY", module: "COMPANIES_COMPLEX", phase: P,
    title: "Venditore persona giuridica: poteri non verificati",
    description: "Quando il venditore è una società/ente, la persona che agisce deve essere instradata alla verifica dei poteri rappresentativi.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "all", conditions: [
      { op: "eq", path: "client.type", value: "LEGAL_ENTITY" },
      { op: "neq", path: "ownership.companyAuthorityStatus", value: "VERIFIED" },
    ] },
    outcome: { code: "COMPANY_AUTHORITY_REVIEW", message: "Acquisire dati societari e verificare poteri dell'organo/soggetto che conferisce l'incarico e dispone del bene.", blockProgress: true, escalationTo: "LAWYER" },
    sourceRefs: [SOURCE_MAP.COMMERCIAL], active: true, version: 1,
  },
  {
    id: "P02_MINOR_OR_PROTECTED_HOLDER", module: M, phase: P,
    title: "Titolare minore o soggetto protetto",
    description: "La presenza di un titolare con capacità limitata richiede gestione professionale e verifica delle autorizzazioni applicabili.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: { op: "eq", path: "ownership.protectedHolderPresent", value: true },
    outcome: { code: "PROTECTED_HOLDER_ESCALATION", message: "Bloccare l'avanzamento automatico e coinvolgere professionista per poteri/autorizzazioni necessari.", blockProgress: true, escalationTo: "LAWYER" },
    sourceRefs: [SOURCE_MAP.RIGHTS_REAL], active: true, version: 1,
  },
  {
    id: "P02_HEREDITARY_SHARE_ONLY", module: M, phase: P,
    title: "Vendita di quota ereditaria / diritto non coincidente con intero immobile",
    description: "Il caso non segue il percorso standard di vendita dell'intero appartamento.",
    stability: "STABLE", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "blocking",
    condition: { op: "in", path: "sale.object", values: ["HEREDITARY_SHARE", "COOWNERSHIP_SHARE", "RIGHT_ONLY"] },
    outcome: { code: "NON_STANDARD_SALE_OBJECT", message: "Instradare a percorso speciale e chiarire esattamente l'oggetto della cessione.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.SUCCESSION, SOURCE_MAP.RIGHTS_REAL], active: true, version: 1,
  },
  {
    id: "P02_TITLE_CHAIN_INCONSISTENCY", module: M, phase: P,
    title: "Incongruenza nella catena di provenienza",
    description: "Dati o soggetti discordanti fra atto, dichiarazioni e verifiche devono diventare una red flag esplicita.",
    stability: "INTERNAL", decisionLevel: "PROFESSIONAL_REQUIRED", severity: "critical",
    condition: { op: "eq", path: "ownership.titleChainStatus", value: "INCONSISTENT" },
    outcome: { code: "TITLE_CHAIN_INCONSISTENCY", message: "Non dichiarare la titolarità come verificata; aprire escalation documentale/notarile.", blockProgress: true, escalationTo: "NOTARY" },
    sourceRefs: [SOURCE_MAP.TRANSCRIPTION, SOURCE_MAP.SUCCESSION, internalPolicy("No false-positive title verification")], active: true, version: 1,
  },
  {
    id: "P02_TRANSCRIPTION_REVIEW_MISSING", module: "ENCUMBRANCES", phase: P,
    title: "Verifica pubblicità immobiliare non completata",
    description: "Prima di chiudere la verifica della titolarità deve risultare gestito il controllo delle formalità/trascrizioni previsto dal processo.",
    stability: "INTERNAL", decisionLevel: "REVIEW", severity: "blocking",
    condition: { op: "neq", path: "ownership.transcriptionReviewStatus", value: "COMPLETED" },
    outcome: { code: "TRANSCRIPTION_REVIEW_REQUIRED", message: "Completare o far completare la verifica delle formalità rilevanti prima del gate di uscita.", blockProgress: true },
    sourceRefs: [SOURCE_MAP.TRANSCRIPTION, internalPolicy("Title gate")], active: true, version: 1,
  },
  {
    id: "P02_OWNERSHIP_READY", module: M, phase: P,
    title: "Titolarità pronta per il passaggio di fase",
    description: "Segnale positivo quando i gate minimi della titolarità risultano completati; non sostituisce il controllo professionale nei casi speciali.",
    stability: "INTERNAL", decisionLevel: "AUTO", severity: "info",
    condition: { op: "all", conditions: [
      { op: "eq", path: "ownership.titleDocumentStatus", value: "ACQUIRED" },
      { op: "eq", path: "ownership.holdersStatus", value: "RECONCILED" },
      { op: "eq", path: "ownership.transcriptionReviewStatus", value: "COMPLETED" },
      { op: "eq", path: "ownership.specialCaseStatus", value: "RESOLVED_OR_NOT_APPLICABLE" },
    ] },
    outcome: { code: "OWNERSHIP_PHASE_CAN_CLOSE", message: "I controlli minimi strutturali della Fase 2 risultano completati.", blockProgress: false },
    sourceRefs: [internalPolicy("Gate Fase 2")], active: true, version: 1,
  },
];
