export type AgencyActorKind="HUMAN"|"SYSTEM"|"AI"|"CUSTOMER"|"EXTERNAL_PROVIDER";
export interface AgencyActor{kind:AgencyActorKind;id?:string;roles?:string[]}
export interface AgencyCommand<E extends string>{event:E;actor:AgencyActor;idempotencyKey:string;guards?:Record<string,boolean>;occurredAt?:string}
export interface AgencyEdge<S extends string,E extends string>{from:S;event:E;to:S;allowedActors?:AgencyActorKind[];guard?:string}
export interface AgencyMachine<S extends string,E extends string>{name:string;initial:S;terminal:S[];edges:AgencyEdge<S,E>[]}
export function applyAgencyTransition<S extends string,E extends string>(machine:AgencyMachine<S,E>,state:S,command:AgencyCommand<E>){const audit={machine:machine.name,event:command.event,actorKind:command.actor.kind,actorId:command.actor.id,idempotencyKey:command.idempotencyKey,occurredAt:command.occurredAt??new Date().toISOString()};if(!command.idempotencyKey.trim())return{allowed:false,state,previousState:state,reasonCodes:["IDEMPOTENCY_KEY_REQUIRED"],audit};const edge=machine.edges.find(x=>x.from===state&&x.event===command.event);if(!edge)return{allowed:false,state,previousState:state,reasonCodes:["ILLEGAL_STATE_TRANSITION"],audit};if(edge.allowedActors&&!edge.allowedActors.includes(command.actor.kind))return{allowed:false,state,previousState:state,reasonCodes:["ACTOR_NOT_ALLOWED"],audit};if(edge.allowedActors&&command.actor.kind!=="SYSTEM"&&!command.actor.id?.trim())return{allowed:false,state,previousState:state,reasonCodes:["ACTOR_ID_REQUIRED"],audit};if(edge.guard&&command.guards?.[edge.guard]!==true)return{allowed:false,state,previousState:state,reasonCodes:["GUARD_NOT_SATISFIED:"+edge.guard],audit};return{allowed:true,state:edge.to,previousState:state,reasonCodes:[],audit}}
export type CommunicationState="OPEN"|"WAITING_CUSTOMER"|"WAITING_AGENCY"|"RESOLVED"|"ARCHIVED";export type CommunicationEvent="WAIT_CUSTOMER"|"WAIT_AGENCY"|"RESOLVE"|"REOPEN"|"ARCHIVE";
export const agencyCommunicationMachine:AgencyMachine<CommunicationState,CommunicationEvent>={name:"AGENCY_COMMUNICATION",initial:"OPEN",terminal:["ARCHIVED"],edges:[{from:"OPEN",event:"WAIT_CUSTOMER",to:"WAITING_CUSTOMER",allowedActors:["HUMAN","SYSTEM"]},{from:"OPEN",event:"WAIT_AGENCY",to:"WAITING_AGENCY",allowedActors:["CUSTOMER","EXTERNAL_PROVIDER"]},{from:"WAITING_CUSTOMER",event:"RESOLVE",to:"RESOLVED",allowedActors:["HUMAN"]},{from:"WAITING_AGENCY",event:"RESOLVE",to:"RESOLVED",allowedActors:["HUMAN"]},{from:"RESOLVED",event:"REOPEN",to:"OPEN",allowedActors:["HUMAN","CUSTOMER"]},{from:"RESOLVED",event:"ARCHIVE",to:"ARCHIVED",allowedActors:["HUMAN"],guard:"AUDIT_COMPLETE"}]};
export type AppointmentState="DRAFT"|"PROPOSED"|"CUSTOMER_CONFIRMED"|"BOOKED"|"RESCHEDULE_PENDING"|"COMPLETED"|"CANCELLED"|"NO_SHOW";export type AppointmentEvent="PROPOSE"|"CUSTOMER_CONFIRM"|"BOOK"|"REQUEST_RESCHEDULE"|"REBOOK"|"COMPLETE"|"CANCEL"|"MARK_NO_SHOW";
export const agencyAppointmentMachine:AgencyMachine<AppointmentState,AppointmentEvent>={name:"AGENCY_APPOINTMENT",initial:"DRAFT",terminal:["COMPLETED","CANCELLED","NO_SHOW"],edges:[{from:"DRAFT",event:"PROPOSE",to:"PROPOSED",allowedActors:["HUMAN","AI","SYSTEM"],guard:"SLOT_AVAILABLE"},{from:"PROPOSED",event:"CUSTOMER_CONFIRM",to:"CUSTOMER_CONFIRMED",allowedActors:["CUSTOMER"],guard:"CONSENT_CURRENT"},{from:"CUSTOMER_CONFIRMED",event:"BOOK",to:"BOOKED",allowedActors:["HUMAN","SYSTEM"],guard:"CALENDAR_LOCKED"},{from:"BOOKED",event:"REQUEST_RESCHEDULE",to:"RESCHEDULE_PENDING",allowedActors:["HUMAN","CUSTOMER","EXTERNAL_PROVIDER"]},{from:"RESCHEDULE_PENDING",event:"REBOOK",to:"BOOKED",allowedActors:["HUMAN","SYSTEM"],guard:"CUSTOMER_RECONFIRMED"},{from:"BOOKED",event:"COMPLETE",to:"COMPLETED",allowedActors:["HUMAN","EXTERNAL_PROVIDER"]},{from:"PROPOSED",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN","CUSTOMER"]},{from:"CUSTOMER_CONFIRMED",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN","CUSTOMER"]},{from:"BOOKED",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN","CUSTOMER","EXTERNAL_PROVIDER"]},{from:"BOOKED",event:"MARK_NO_SHOW",to:"NO_SHOW",allowedActors:["HUMAN","EXTERNAL_PROVIDER"]}]};
export type ServiceRequestState="DRAFT"|"SUBMITTED"|"ASSIGNED"|"ACCEPTED"|"IN_PROGRESS"|"DELIVERED"|"VERIFIED"|"CLOSED"|"CANCELLED";export type ServiceRequestEvent="SUBMIT"|"ASSIGN"|"ACCEPT"|"START"|"DELIVER"|"VERIFY"|"CLOSE"|"CANCEL";
export const agencyServiceRequestMachine:AgencyMachine<ServiceRequestState,ServiceRequestEvent>={name:"AGENCY_SERVICE_REQUEST",initial:"DRAFT",terminal:["CLOSED","CANCELLED"],edges:[{from:"DRAFT",event:"SUBMIT",to:"SUBMITTED",allowedActors:["HUMAN"]},{from:"SUBMITTED",event:"ASSIGN",to:"ASSIGNED",allowedActors:["HUMAN"],guard:"PROVIDER_VERIFIED"},{from:"ASSIGNED",event:"ACCEPT",to:"ACCEPTED",allowedActors:["EXTERNAL_PROVIDER"]},{from:"ACCEPTED",event:"START",to:"IN_PROGRESS",allowedActors:["EXTERNAL_PROVIDER"]},{from:"IN_PROGRESS",event:"DELIVER",to:"DELIVERED",allowedActors:["EXTERNAL_PROVIDER"],guard:"DELIVERABLE_EVIDENCE_READY"},{from:"DELIVERED",event:"VERIFY",to:"VERIFIED",allowedActors:["HUMAN"],guard:"PROFESSIONAL_SCOPE_MATCHED"},{from:"VERIFIED",event:"CLOSE",to:"CLOSED",allowedActors:["HUMAN"]},{from:"DRAFT",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN"]},{from:"SUBMITTED",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN"]}]};
export type AgencyTaskState="OPEN"|"IN_PROGRESS"|"BLOCKED"|"COMPLETED"|"CANCELLED";export type AgencyTaskEvent="START"|"BLOCK"|"UNBLOCK"|"COMPLETE"|"REOPEN"|"CANCEL";
export const agencyTaskMachine:AgencyMachine<AgencyTaskState,AgencyTaskEvent>={name:"AGENCY_TASK",initial:"OPEN",terminal:["COMPLETED","CANCELLED"],edges:[{from:"OPEN",event:"START",to:"IN_PROGRESS",allowedActors:["HUMAN","SYSTEM"]},{from:"IN_PROGRESS",event:"BLOCK",to:"BLOCKED",allowedActors:["HUMAN","SYSTEM"]},{from:"BLOCKED",event:"UNBLOCK",to:"IN_PROGRESS",allowedActors:["HUMAN"]},{from:"IN_PROGRESS",event:"COMPLETE",to:"COMPLETED",allowedActors:["HUMAN"],guard:"EVIDENCE_READY"},{from:"COMPLETED",event:"REOPEN",to:"OPEN",allowedActors:["HUMAN"],guard:"REOPEN_REASON_RECORDED"},{from:"OPEN",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN"]}]};
export type IntegrationState="PENDING"|"APPROVED"|"SENDING"|"DELIVERED"|"FAILED"|"CANCELLED";export type IntegrationEvent="APPROVE"|"SEND"|"ACK"|"FAIL"|"RETRY"|"CANCEL";
export const agencyIntegrationMachine:AgencyMachine<IntegrationState,IntegrationEvent>={name:"AGENCY_INTEGRATION",initial:"PENDING",terminal:["DELIVERED","CANCELLED"],edges:[{from:"PENDING",event:"APPROVE",to:"APPROVED",allowedActors:["HUMAN"],guard:"PAYLOAD_ALLOWLISTED"},{from:"APPROVED",event:"SEND",to:"SENDING",allowedActors:["SYSTEM"]},{from:"SENDING",event:"ACK",to:"DELIVERED",allowedActors:["SYSTEM"],guard:"REMOTE_ACK_VALID"},{from:"SENDING",event:"FAIL",to:"FAILED",allowedActors:["SYSTEM"]},{from:"FAILED",event:"RETRY",to:"APPROVED",allowedActors:["HUMAN","SYSTEM"],guard:"RETRY_ALLOWED"},{from:"PENDING",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN"]},{from:"APPROVED",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN"]}]};
export type AssignmentState="UNASSIGNED"|"ASSIGNED"|"ACCEPTED"|"TRANSFER_PENDING"|"CLOSED";export type AssignmentEvent="ASSIGN"|"ACCEPT"|"REQUEST_TRANSFER"|"TRANSFER"|"CLOSE";
export const agencyAssignmentMachine:AgencyMachine<AssignmentState,AssignmentEvent>={name:"AGENCY_ASSIGNMENT",initial:"UNASSIGNED",terminal:["CLOSED"],edges:[{from:"UNASSIGNED",event:"ASSIGN",to:"ASSIGNED",allowedActors:["HUMAN"],guard:"MEMBER_ACTIVE"},{from:"ASSIGNED",event:"ACCEPT",to:"ACCEPTED",allowedActors:["HUMAN"]},{from:"ACCEPTED",event:"REQUEST_TRANSFER",to:"TRANSFER_PENDING",allowedActors:["HUMAN"]},{from:"TRANSFER_PENDING",event:"TRANSFER",to:"ASSIGNED",allowedActors:["HUMAN"],guard:"HANDOFF_RECORDED"},{from:"ACCEPTED",event:"CLOSE",to:"CLOSED",allowedActors:["HUMAN"],guard:"CASE_OPERATIONS_COMPLETE"}]};
export type ConsentState="REQUESTED"|"GRANTED"|"REVOKED"|"EXPIRED";export type ConsentEvent="GRANT"|"REVOKE"|"EXPIRE";
export const agencyConsentMachine:AgencyMachine<ConsentState,ConsentEvent>={name:"AGENCY_CONSENT",initial:"REQUESTED",terminal:["REVOKED","EXPIRED"],edges:[{from:"REQUESTED",event:"GRANT",to:"GRANTED",allowedActors:["CUSTOMER"],guard:"PURPOSE_DISCLOSED"},{from:"GRANTED",event:"REVOKE",to:"REVOKED",allowedActors:["CUSTOMER"]},{from:"GRANTED",event:"EXPIRE",to:"EXPIRED",allowedActors:["SYSTEM"]}]};
export type VoiceSessionState="CREATED"|"CONSENT_PENDING"|"ACTIVE"|"HANDOFF_PENDING"|"COMPLETED"|"ABORTED";export type VoiceSessionEvent="REQUEST_CONSENT"|"START"|"REQUEST_HANDOFF"|"COMPLETE"|"ABORT";
export const agencyVoiceSessionMachine:AgencyMachine<VoiceSessionState,VoiceSessionEvent>={name:"AGENCY_VOICE_SESSION",initial:"CREATED",terminal:["COMPLETED","ABORTED"],edges:[{from:"CREATED",event:"REQUEST_CONSENT",to:"CONSENT_PENDING",allowedActors:["SYSTEM","AI"]},{from:"CONSENT_PENDING",event:"START",to:"ACTIVE",allowedActors:["SYSTEM"],guard:"VOICE_CONSENT_CAPTURED"},{from:"ACTIVE",event:"REQUEST_HANDOFF",to:"HANDOFF_PENDING",allowedActors:["AI","SYSTEM","CUSTOMER"]},{from:"ACTIVE",event:"COMPLETE",to:"COMPLETED",allowedActors:["HUMAN","SYSTEM"],guard:"CALL_SUMMARY_APPROVED"},{from:"HANDOFF_PENDING",event:"COMPLETE",to:"COMPLETED",allowedActors:["HUMAN"],guard:"HANDOFF_COMPLETED"},{from:"CREATED",event:"ABORT",to:"ABORTED",allowedActors:["HUMAN","SYSTEM","CUSTOMER"]},{from:"CONSENT_PENDING",event:"ABORT",to:"ABORTED",allowedActors:["HUMAN","SYSTEM","CUSTOMER"]},{from:"ACTIVE",event:"ABORT",to:"ABORTED",allowedActors:["HUMAN","SYSTEM","CUSTOMER"]}]};
export type ComplaintState="OPEN"|"ACKNOWLEDGED"|"INVESTIGATING"|"RESOLVED"|"CLOSED";export type ComplaintEvent="ACKNOWLEDGE"|"INVESTIGATE"|"RESOLVE"|"CLOSE"|"REOPEN";
export const agencyComplaintMachine:AgencyMachine<ComplaintState,ComplaintEvent>={name:"AGENCY_COMPLAINT",initial:"OPEN",terminal:["CLOSED"],edges:[{from:"OPEN",event:"ACKNOWLEDGE",to:"ACKNOWLEDGED",allowedActors:["HUMAN"]},{from:"ACKNOWLEDGED",event:"INVESTIGATE",to:"INVESTIGATING",allowedActors:["HUMAN"]},{from:"INVESTIGATING",event:"RESOLVE",to:"RESOLVED",allowedActors:["HUMAN"],guard:"RESOLUTION_EVIDENCE_READY"},{from:"RESOLVED",event:"CLOSE",to:"CLOSED",allowedActors:["HUMAN"],guard:"CUSTOMER_NOTIFIED"},{from:"RESOLVED",event:"REOPEN",to:"INVESTIGATING",allowedActors:["CUSTOMER","HUMAN"]}]};
export type PrivacyRequestState="RECEIVED"|"IDENTITY_PENDING"|"IN_PROGRESS"|"FULFILLED"|"REJECTED"|"CLOSED";export type PrivacyRequestEvent="REQUEST_IDENTITY"|"VERIFY_IDENTITY"|"FULFILL"|"REJECT"|"CLOSE";
export const agencyPrivacyRequestMachine:AgencyMachine<PrivacyRequestState,PrivacyRequestEvent>={name:"AGENCY_PRIVACY_REQUEST",initial:"RECEIVED",terminal:["CLOSED"],edges:[{from:"RECEIVED",event:"REQUEST_IDENTITY",to:"IDENTITY_PENDING",allowedActors:["HUMAN","SYSTEM"]},{from:"IDENTITY_PENDING",event:"VERIFY_IDENTITY",to:"IN_PROGRESS",allowedActors:["HUMAN"],guard:"IDENTITY_VERIFIED"},{from:"IN_PROGRESS",event:"FULFILL",to:"FULFILLED",allowedActors:["HUMAN"],guard:"EXPORT_REDACTED"},{from:"IN_PROGRESS",event:"REJECT",to:"REJECTED",allowedActors:["HUMAN"],guard:"REJECTION_REASON_RECORDED"},{from:"FULFILLED",event:"CLOSE",to:"CLOSED",allowedActors:["HUMAN"],guard:"CUSTOMER_NOTIFIED"},{from:"REJECTED",event:"CLOSE",to:"CLOSED",allowedActors:["HUMAN"],guard:"CUSTOMER_NOTIFIED"}]};
export type RecoveryState="DETECTED"|"TRIAGED"|"RETRYING"|"COMPENSATING"|"RESOLVED"|"ESCALATED";export type RecoveryEvent="TRIAGE"|"RETRY"|"COMPENSATE"|"RESOLVE"|"ESCALATE";
export const agencyRecoveryMachine:AgencyMachine<RecoveryState,RecoveryEvent>={name:"AGENCY_RECOVERY",initial:"DETECTED",terminal:["RESOLVED","ESCALATED"],edges:[{from:"DETECTED",event:"TRIAGE",to:"TRIAGED",allowedActors:["HUMAN","SYSTEM"]},{from:"TRIAGED",event:"RETRY",to:"RETRYING",allowedActors:["HUMAN","SYSTEM"],guard:"RETRY_ALLOWED"},{from:"RETRYING",event:"RESOLVE",to:"RESOLVED",allowedActors:["SYSTEM","HUMAN"],guard:"REMOTE_ACK_VALID"},{from:"RETRYING",event:"COMPENSATE",to:"COMPENSATING",allowedActors:["HUMAN"],guard:"COMPENSATION_APPROVED"},{from:"COMPENSATING",event:"RESOLVE",to:"RESOLVED",allowedActors:["HUMAN"],guard:"COMPENSATION_RECORDED"},{from:"TRIAGED",event:"ESCALATE",to:"ESCALATED",allowedActors:["HUMAN","SYSTEM"]},{from:"RETRYING",event:"ESCALATE",to:"ESCALATED",allowedActors:["HUMAN","SYSTEM"]}]};
export type CustomerJourneyState="INTAKE"|"PROFILE_COMPLETE"|"SERVICE_SELECTED"|"ACTIVE"|"WAITING_CUSTOMER"|"WAITING_PROFESSIONAL"|"COMPLETED"|"CANCELLED";export type CustomerJourneyEvent="COMPLETE_PROFILE"|"SELECT_SERVICE"|"ACTIVATE"|"WAIT_CUSTOMER"|"WAIT_PROFESSIONAL"|"RESUME"|"COMPLETE"|"CANCEL";
export const guimmiaCustomerJourneyMachine:AgencyMachine<CustomerJourneyState,CustomerJourneyEvent>={name:"GUIMMIA_CUSTOMER_JOURNEY",initial:"INTAKE",terminal:["COMPLETED","CANCELLED"],edges:[{from:"INTAKE",event:"COMPLETE_PROFILE",to:"PROFILE_COMPLETE",allowedActors:["CUSTOMER","HUMAN"],guard:"ROLE_INTENT_CONFIRMED"},{from:"PROFILE_COMPLETE",event:"SELECT_SERVICE",to:"SERVICE_SELECTED",allowedActors:["CUSTOMER","HUMAN"],guard:"SERVICE_SCOPE_ACKNOWLEDGED"},{from:"SERVICE_SELECTED",event:"ACTIVATE",to:"ACTIVE",allowedActors:["HUMAN","SYSTEM"],guard:"INTERNAL_OWNER_ASSIGNED"},{from:"ACTIVE",event:"WAIT_CUSTOMER",to:"WAITING_CUSTOMER",allowedActors:["HUMAN","SYSTEM","AI"]},{from:"ACTIVE",event:"WAIT_PROFESSIONAL",to:"WAITING_PROFESSIONAL",allowedActors:["HUMAN","SYSTEM"]},{from:"WAITING_CUSTOMER",event:"RESUME",to:"ACTIVE",allowedActors:["CUSTOMER","HUMAN","SYSTEM"]},{from:"WAITING_PROFESSIONAL",event:"RESUME",to:"ACTIVE",allowedActors:["EXTERNAL_PROVIDER","HUMAN","SYSTEM"]},{from:"ACTIVE",event:"COMPLETE",to:"COMPLETED",allowedActors:["HUMAN","SYSTEM"],guard:"CUSTOMER_VISIBLE_MILESTONES_COMPLETE"},{from:"INTAKE",event:"CANCEL",to:"CANCELLED",allowedActors:["CUSTOMER","HUMAN"]},{from:"ACTIVE",event:"CANCEL",to:"CANCELLED",allowedActors:["CUSTOMER","HUMAN"]}]};
export type DocumentWorkspaceState="DRAFT"|"INPUT_PENDING"|"PREPARED"|"HUMAN_REVIEW"|"CUSTOMER_REVIEW"|"APPROVED"|"SIGNED"|"ARCHIVED"|"CANCELLED";export type DocumentWorkspaceEvent="REQUEST_INPUT"|"PREPARE"|"SUBMIT_HUMAN_REVIEW"|"APPROVE_FOR_CUSTOMER"|"APPROVE"|"SIGN"|"ARCHIVE"|"CANCEL";
export const guimmiaDocumentWorkspaceMachine:AgencyMachine<DocumentWorkspaceState,DocumentWorkspaceEvent>={name:"GUIMMIA_DOCUMENT_WORKSPACE",initial:"DRAFT",terminal:["ARCHIVED","CANCELLED"],edges:[{from:"DRAFT",event:"REQUEST_INPUT",to:"INPUT_PENDING",allowedActors:["HUMAN","SYSTEM","AI"]},{from:"INPUT_PENDING",event:"PREPARE",to:"PREPARED",allowedActors:["HUMAN","SYSTEM","AI"],guard:"INPUTS_COMPLETE"},{from:"PREPARED",event:"SUBMIT_HUMAN_REVIEW",to:"HUMAN_REVIEW",allowedActors:["HUMAN","SYSTEM"]},{from:"HUMAN_REVIEW",event:"APPROVE_FOR_CUSTOMER",to:"CUSTOMER_REVIEW",allowedActors:["HUMAN"],guard:"HUMAN_REVIEW_COMPLETE"},{from:"CUSTOMER_REVIEW",event:"APPROVE",to:"APPROVED",allowedActors:["HUMAN"],guard:"CUSTOMER_REVIEW_CAPTURED"},{from:"APPROVED",event:"SIGN",to:"SIGNED",allowedActors:["CUSTOMER","HUMAN"],guard:"SIGNATURE_EVIDENCE_READY"},{from:"SIGNED",event:"ARCHIVE",to:"ARCHIVED",allowedActors:["HUMAN","SYSTEM"],guard:"AUDIT_COMPLETE"},{from:"DRAFT",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN","CUSTOMER"]},{from:"INPUT_PENDING",event:"CANCEL",to:"CANCELLED",allowedActors:["HUMAN","CUSTOMER"]}]};
