import type { DocumentRequirementDefinition } from "./types";

export const DOCUMENT_REQUIREMENTS: DocumentRequirementDefinition[] = [
  { key: "REQ_TITLE_DEED", documentCode: "TITLE_DEED", level: "CORE", exitPolicy: "RECEIVED", reason: "Atto di provenienza necessario come evidenza strutturale del fascicolo." },
  { key: "REQ_CADASTRAL_REPORT", documentCode: "CADASTRAL_REPORT", level: "CORE", exitPolicy: "ROUTED", reason: "Visura da acquisire/instradare prima della fase catastale." },
  { key: "REQ_CADASTRAL_PLAN", documentCode: "CADASTRAL_PLAN", level: "CORE", exitPolicy: "ROUTED", reason: "Planimetria da acquisire/instradare a P04.", professionalType: "TECHNICIAN" },
  { key: "REQ_URBAN_TITLES_OR_ACCESS", documentCode: "URBAN_TITLES", level: "CORE", exitPolicy: "ROUTED", reason: "Titoli disponibili o accesso atti devono essere instradati alla verifica tecnica.", professionalType: "TECHNICIAN" },
  { key: "REQ_LAND_REGISTRY", documentCode: "LAND_REGISTRY_INSPECTION", level: "CORE", exitPolicy: "ROUTED", reason: "Formalit\u00e0/pubblicit\u00e0 immobiliare devono essere instradate al controllo dedicato.", professionalType: "NOTARY" },
  { key: "REQ_APE", documentCode: "APE", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Applicabilit\u00e0 determinata dal ruleset corrente.", appliesWhen: {"op": "eq", "path": "documents.apeRequired", "value": true}, legalRulesetKey: "ITALY_APE" },
  { key: "REQ_CONDO_ADMIN", documentCode: "CONDOMINIUM_ADMIN_CERT", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Unit\u00e0 in condominio: instradare documentazione amministratore.", appliesWhen: {"op": "eq", "path": "property.isCondominium", "value": true} },
  { key: "REQ_CONDO_MINUTES", documentCode: "CONDOMINIUM_MINUTES", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Unit\u00e0 in condominio: raccogliere verbali rilevanti disponibili.", appliesWhen: {"op": "eq", "path": "property.isCondominium", "value": true} },
  { key: "REQ_CONDO_EXPENSES", documentCode: "CONDOMINIUM_EXPENSES", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Unit\u00e0 in condominio: spese/lavori devono avere una fonte documentale o richiesta aperta.", appliesWhen: {"op": "eq", "path": "property.isCondominium", "value": true} },
  { key: "REQ_LEASE", documentCode: "LEASE_CONTRACT", level: "CONDITIONAL", exitPolicy: "RECEIVED", reason: "Immobile locato: contratto necessario per il routing corretto.", appliesWhen: {"op": "eq", "path": "property.occupancy", "value": "LEASED"} },
  { key: "REQ_MORTGAGE", documentCode: "MORTGAGE_STATEMENT", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Mutuo attivo: raccogliere/instradare documentazione banca.", appliesWhen: {"op": "eq", "path": "finance.activeMortgage", "value": true}, professionalType: "BANK" },
  { key: "REQ_MORTGAGE_PAYOFF", documentCode: "MORTGAGE_PAYOFF_QUOTE", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Se \u00e8 previsto percorso di estinzione, instradare il conteggio banca quando richiesto dal workflow.", appliesWhen: {"op": "eq", "path": "finance.payoffQuoteRequired", "value": true}, professionalType: "BANK" },
  { key: "REQ_SUCCESSION", documentCode: "SUCCESSION_DECLARATION", level: "CONDITIONAL", exitPolicy: "RECEIVED", reason: "Provenienza successoria: acquisire documentazione di base.", appliesWhen: {"op": "eq", "path": "ownership.originType", "value": "SUCCESSION"}, professionalType: "NOTARY" },
  { key: "REQ_SUCCESSION_ACCEPTANCE", documentCode: "SUCCESSION_ACCEPTANCE_EVIDENCE", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Nei casi indicati dal professionista/ruleset, instradare evidenza di accettazione/trascrizione.", appliesWhen: {"op": "eq", "path": "ownership.successionAcceptanceEvidenceRequired", "value": true}, professionalType: "NOTARY" },
  { key: "REQ_DONATION", documentCode: "DONATION_DEED", level: "CONDITIONAL", exitPolicy: "RECEIVED", reason: "Provenienza donativa: acquisire atto.", appliesWhen: {"op": "eq", "path": "ownership.originType", "value": "DONATION"}, professionalType: "NOTARY" },
  { key: "REQ_POA", documentCode: "POWER_OF_ATTORNEY", level: "CONDITIONAL", exitPolicy: "RECEIVED", reason: "Rappresentanza: acquisire evidenza dei poteri.", appliesWhen: {"op": "eq", "path": "ownership.representationUsed", "value": true}, professionalType: "AGENT" },
  { key: "REQ_COMPANY_AUTH", documentCode: "COMPANY_AUTHORITY_DOCS", level: "CONDITIONAL", exitPolicy: "RECEIVED", reason: "Venditore societ\u00e0/ente: acquisire documenti e poteri.", appliesWhen: {"op": "eq", "path": "client.type", "value": "LEGAL_ENTITY"}, professionalType: "LAWYER" },
  { key: "REQ_TAX_BONUS", documentCode: "TAX_BONUS_DOCS", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Storia di interventi agevolati: raccogliere documenti senza derivare fiscalit\u00e0 dal manuale.", appliesWhen: {"op": "eq", "path": "tax.superbonusOrArticle119History", "value": true}, legalRulesetKey: "ITALY_REAL_ESTATE_TAX", professionalType: "ACCOUNTANT" },
  { key: "REQ_TECHNICAL_REPORT", documentCode: "TECHNICAL_REPORT", level: "PROFESSIONAL", exitPolicy: "ROUTED", reason: "Se P04 richiede relazione tecnica, aprire routing al professionista.", appliesWhen: {"op": "eq", "path": "technical.reportRequired", "value": true}, legalRulesetKey: "ITALY_URBAN_BUILDING", professionalType: "TECHNICIAN" },
  { key: "REQ_TENANT_NOTICE", documentCode: "TENANT_NOTICES", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Se il workflow determina una comunicazione rilevante al conduttore, instradarla.", appliesWhen: {"op": "eq", "path": "lease.tenantNoticeRequired", "value": true}, legalRulesetKey: "ITALY_REAL_ESTATE_TAX", professionalType: "AGENT" },
  { key: "REQ_HISTORICAL_CADASTRE", documentCode: "HISTORICAL_CADASTRAL_REPORT", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Storico catastale quando richiesto dal tecnico/agente per riconciliare variazioni.", appliesWhen: {"op": "eq", "path": "technical.historicalCadastreRequired", "value": true}, professionalType: "TECHNICIAN" },
  { key: "REQ_URBAN_ACCESS", documentCode: "URBAN_ACCESS_REQUEST", level: "CONDITIONAL", exitPolicy: "ROUTED", reason: "Se i titoli non sono nella disponibilit\u00e0 del cliente, tracciare richiesta/accesso atti.", appliesWhen: {"op": "eq", "path": "technical.urbanAccessRequired", "value": true}, legalRulesetKey: "ITALY_URBAN_BUILDING", professionalType: "TECHNICIAN" },
];

export const requirementByKey = new Map(DOCUMENT_REQUIREMENTS.map(item => [item.key, item] as const));
