export const TECHNICAL_SOURCE_CLASSES = [
  "OWNER_DECLARATION","TITLE_DEED","CADASTRAL_CURRENT","CADASTRAL_HISTORICAL","URBAN_TITLE",
  "MUNICIPAL_RECORD","AGIBILITY_RECORD","PROFESSIONAL_OBSERVATION","PROFESSIONAL_SIGNED_REPORT",
  "OFFICIAL_EXTERNAL_SOURCE","AI_INFERENCE",
] as const;

export const TECHNICAL_FINDING_CATALOG = [
  ["SCOPE_NOT_LOCKED","Oggetto tecnico della verifica non definito","blocking"],
  ["COMPONENTS_UNMAPPED","Pertinenze/componenti non mappati","blocking"],
  ["SOURCE_MAP_INCOMPLETE","Mappa fonti tecnica incompleta","blocking"],
  ["SOURCE_DOMAIN_CONFLICT","Conflitto tra fonti/domìni da interpretare","blocking"],
  ["CURRENT_STATE_UNOBSERVED","Stato fisico attuale non rilevato quando necessario","blocking"],
  ["TIMELINE_INCOMPLETE","Cronologia tecnica incompleta","blocking"],
  ["RECORD_ACCESS_REQUIRED","Accesso atti necessario","blocking"],
  ["RECORD_ACCESS_PARTIAL","Accesso atti parziale","blocking"],
  ["RECORD_ACCESS_FAILED","Accesso atti non completato","blocking"],
  ["CADASTRAL_ID_MISSING","Identificativi catastali mancanti","blocking"],
  ["CADASTRAL_ID_MISMATCH","Identificativi catastali discordanti","blocking"],
  ["CADASTRAL_ADDRESS_MISMATCH","Indirizzo catastale discordante","warning"],
  ["CADASTRAL_CATEGORY_MISMATCH","Categoria catastale da approfondire","warning"],
  ["CADASTRAL_PLAN_MISSING","Planimetria catastale non disponibile","blocking"],
  ["CADASTRAL_PLAN_STALE","Planimetria potenzialmente non corrente","blocking"],
  ["CADASTRAL_PLAN_OBSERVED_MISMATCH","Possibile differenza planimetria/stato osservato","blocking"],
  ["CADASTRAL_SURFACE_MISMATCH","Superficie discordante","warning"],
  ["CADASTRAL_HISTORY_GAP","Storico catastale insufficiente per la ricostruzione","warning"],
  ["URBAN_TITLE_CHAIN_INCOMPLETE","Catena titoli/pratiche edilizie incompleta","blocking"],
  ["URBAN_TITLE_STATUS_UNCLEAR","Stato di una pratica edilizia non chiaro","blocking"],
  ["WORK_WITHOUT_LINKED_TITLE","Lavori dichiarati/osservati senza pratica collegata","blocking"],
  ["STATE_LEGITIMATE_NOT_RECONSTRUCTED","Stato legittimo non ricostruito","blocking"],
  ["HISTORIC_CONSTRUCTION_BASIS_UNPROVEN","Base documentale edificio storico insufficiente","blocking"],
  ["USE_DECLARED_VS_CADASTRAL_MISMATCH","Uso dichiarato e catastale discordanti","warning"],
  ["USE_DECLARED_VS_URBAN_MISMATCH","Uso dichiarato e urbanistico discordanti","blocking"],
  ["CHANGE_OF_USE_SUSPECTED","Possibile mutamento d'uso","blocking"],
  ["AGIBILITY_STATUS_UNKNOWN","Agibilità non chiarita","warning"],
  ["AGIBILITY_SCOPE_MISMATCH","Ambito agibilità/configurazione da verificare","blocking"],
  ["PROTECTED_PROPERTY_REVIEW","Vincolo/tutela da verificare","blocking"],
  ["TOLERANCE_CLAIM_REQUIRES_TECHNICIAN","Possibile tolleranza: qualificazione riservata al tecnico","blocking"],
  ["SANATORIA_PENDING","Procedimento di regolarizzazione pendente","critical"],
  ["SANATORIA_OUTCOME_UNKNOWN","Esito regolarizzazione non documentato","blocking"],
  ["CONDONO_PENDING","Condono pendente","critical"],
  ["CONDONO_OUTCOME_UNKNOWN","Esito condono non documentato","blocking"],
  ["POSSIBLE_UNAUTHORIZED_WORK","Possibile opera non assistita da titolo coerente","critical"],
  ["ONGOING_WORKS","Lavori in corso","warning"],
  ["TRANSFER_FORMALITY_REVIEW","Profili formali trasferimento da verificare","blocking"],
  ["TECHNICAL_EVIDENCE_GAP","Finding tecnico senza evidenza sufficiente","blocking"],
  ["PROFESSIONAL_SCOPE_INCOMPLETE","Richiesta al tecnico incompleta","blocking"],
  ["PROFESSIONAL_SIGNOFF_STALE","Sign-off professionale non più corrente","blocking"],
  ["CONTROLLED_OVERRIDE_PRESENT","Override agente registrato","warning"],
  ["CRITICAL_OVERRIDE_ATTEMPT","Tentativo di override su criticità non derogabile","critical"],
] as const;

export const TECHNICAL_COMPARISON_DEFS = [
  ["CADASTRAL_IDENTIFIERS_VS_TITLE","cadastre.identifiers","title.cadastralIdentifiers"],
  ["CADASTRAL_IDENTIFIERS_VS_DECLARATION","cadastre.identifiers","property.declaredCadastralIdentifiers"],
  ["CADASTRAL_ADDRESS_VS_CASE","cadastre.address","property.address"],
  ["CADASTRAL_PLAN_VS_OBSERVED","cadastre.planLayout","physical.observedLayout"],
  ["CADASTRAL_PLAN_VS_DECLARED","cadastre.planLayout","property.declaredLayout"],
  ["CADASTRAL_SURFACE_VS_DECLARED","cadastre.surface","property.declaredSurface"],
  ["CADASTRAL_CATEGORY_VS_DECLARED_USE","cadastre.category","property.declaredUse"],
  ["URBAN_AUTHORIZED_USE_VS_DECLARED","urban.authorizedUse","property.declaredUse"],
  ["URBAN_AUTHORIZED_STATE_VS_OBSERVED","urban.authorizedState","physical.observedState"],
  ["URBAN_AUTHORIZED_STATE_VS_CADASTRAL_PLAN","urban.authorizedState","cadastre.planLayout"],
  ["DECLARED_WORKS_VS_URBAN_TITLES","property.declaredWorks","urban.linkedWorks"],
  ["OBSERVED_WORKS_VS_URBAN_TITLES","physical.observedWorks","urban.linkedWorks"],
  ["AGIBILITY_SCOPE_VS_CURRENT_CONFIGURATION","agibility.scope","physical.currentConfiguration"],
  ["TITLE_DEED_COMPONENTS_VS_SCOPE","title.components","technical.scopeComponents"],
  ["CADASTRAL_UNITS_VS_SCOPE","cadastre.units","technical.scopeComponents"],
  ["HISTORICAL_CADASTRE_VS_TIMELINE","cadastre.historicalEvents","technical.timeline"],
  ["URBAN_TITLES_VS_TIMELINE","urban.titleEvents","technical.timeline"],
  ["DECLARED_CONSTRUCTION_DATE_VS_EVIDENCE","property.declaredConstructionDate","technical.constructionEvidence"],
] as const;

export const TECHNICAL_GATE_DEFS = [
  ["PUBLICATION","Prima della pubblicazione marketing"],
  ["OFFER","Prima della gestione di una proposta"],
  ["PRELIMINARY","Prima del preliminare"],
  ["CLOSING","Readiness verso rogito"],
] as const;
