"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { findService } from "@/lib/professionals/catalog";
import { getLead,updateLead } from "@/lib/professionals/store";
import type { LeadRequest } from "@/lib/professionals/types";
import { Badge,Page } from "./ui";
import ChatPanel from "./ChatPanel";
export default function LeadWorkspace({leadId}:{leadId:string}){ const [lead,setLead]=useState<LeadRequest|null>(null); useEffect(()=>{const value=getLead(leadId);if(value){setLead(value);if(["submitted","matched"].includes(value.status))updateLead(value.id,{status:"viewed"})}},[leadId]); if(!lead)return <Page>Richiesta non trovata.</Page>; const service=findService(lead.serviceId); return <Page><Link href="/dashboard/professional" className="text-sm font-semibold text-blue-600">← Dashboard professionista</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-slate-200 bg-white p-7"><div className="flex flex-wrap gap-2"><Badge tone={lead.leadScore>=80?"success":"warning"}>Qualità {lead.leadScore}/100</Badge><Badge>{lead.location}</Badge><Badge tone="blue">{lead.urgency}</Badge></div><h1 className="mt-4 text-3xl font-semibold">{service?.name}</h1><p className="mt-2 text-slate-600">{service?.shortDescription}</p><dl className="mt-7 divide-y divide-slate-100 rounded-2xl border border-slate-200"><div className="grid gap-1 px-5 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-sm text-slate-500">Immobile</dt><dd className="text-sm font-semibold">{lead.propertyLabel}</dd></div>{Object.entries(lead.answers).map(([k,v])=><div key={k} className="grid gap-1 px-5 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-sm capitalize text-slate-500">{k.replaceAll("_"," ")}</dt><dd className="text-sm">{Array.isArray(v)?v.join(", "):String(v)}</dd></div>)}</dl>{lead.notes&&<div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">{lead.notes}</div>}</section><aside className="space-y-5"><div className="rounded-3xl border border-blue-200 bg-blue-50 p-6"><h2 className="font-semibold text-blue-950">Contatti protetti</h2><p className="mt-2 text-sm text-blue-800">Telefono, email e indirizzo completo saranno disponibili dopo l’accettazione.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Come vuoi procedere?</h2><div className="mt-4 grid gap-3"><Link href={`/dashboard/professional/requests/${lead.id}/quote`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white">Prepara preventivo</Link><button className="min-h-11 rounded-xl border border-slate-200 text-sm font-semibold">Rifiuta richiesta</button></div></div><ChatPanel leadId={lead.id} role="professional"/></aside></div></Page>; }
