"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { findService } from "@/lib/professionals/catalog";
import { getLeads,getProfile } from "@/lib/professionals/store";
import type { LeadRequest,ProfessionalProfile } from "@/lib/professionals/types";
import { Badge,Heading,Page } from "./ui";
import ProfessionalNav from "./ProfessionalNav";
export default function ProfessionalDashboard(){ const [leads,setLeads]=useState<LeadRequest[]>([]),[profile,setProfile]=useState<ProfessionalProfile|null>(null); useEffect(()=>{setLeads(getLeads());setProfile(getProfile())},[]); const stats=useMemo(()=>[["Nuove richieste",leads.filter(x=>["submitted","matched"].includes(x.status)).length],["Lead ≥ 80",leads.filter(x=>x.leadScore>=80).length],["Preventivi da seguire",leads.filter(x=>x.status==="quote_received").length],["Tempo medio risposta","2h 18m"]], [leads]); return <Page><ProfessionalNav/><Heading eyebrow="Area professionista" title={profile?`Bentornato, ${profile.displayName}`:"La tua dashboard professionale"} description="Richieste qualificate, preventivi confrontabili, contatti protetti e risultati misurabili."/>{!profile&&<div className="mb-8 rounded-3xl border border-blue-200 bg-blue-50 p-6"><h2 className="font-semibold text-blue-950">Completa il profilo per ricevere lead compatibili</h2><Link href="/dashboard/professional/onboarding" className="mt-4 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Configura il profilo</Link></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-3xl font-semibold text-slate-950">{v}</p></div>)}</div><h2 className="mt-8 text-xl font-semibold">Richieste da valutare</h2><div className="mt-4 space-y-4">{leads.map(lead=><article key={lead.id} className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge tone={lead.leadScore>=80?"success":"warning"}>Qualità {lead.leadScore}/100</Badge><Badge>{lead.location}</Badge><Badge tone="blue">{lead.urgency}</Badge></div><h3 className="mt-3 text-lg font-semibold">{findService(lead.serviceId)?.name}</h3><p className="mt-1 text-sm text-slate-600">{lead.propertyLabel} · {lead.budget}</p></div><Link href={`/dashboard/professional/requests/${lead.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Valuta la richiesta</Link></div></article>)}</div></Page>; }
