import type { ReactNode } from "react";
export const Page = ({children}:{children:ReactNode}) => <main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8">{children}</main>;
export function Heading({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){ return <div className="mb-8">{eyebrow&&<p className="mb-2 text-sm font-semibold uppercase tracking-[.18em] text-blue-600">{eyebrow}</p>}<h1 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{title}</h1>{description&&<p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">{description}</p>}</div>; }
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"blue"}){ const tones={neutral:"bg-slate-100 text-slate-700",success:"bg-emerald-50 text-emerald-700",warning:"bg-amber-50 text-amber-700",blue:"bg-blue-50 text-blue-700"}; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${tones[tone]}`}>{children}</span>; }
export const Primary = ({children,onClick,disabled}:{children:ReactNode;onClick?:()=>void;disabled?:boolean}) => <button type="button" onClick={onClick} disabled={disabled} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{children}</button>;
export const Secondary = ({children,onClick}:{children:ReactNode;onClick?:()=>void}) => <button type="button" onClick={onClick} className="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">{children}</button>;
export function Choice({title,description,icon,selected,onClick}:{title:string;description?:string;icon?:string;selected?:boolean;onClick:()=>void}){ return <button type="button" onClick={onClick} className={`w-full rounded-2xl border p-5 text-left transition ${selected?"border-blue-500 bg-blue-50 ring-2 ring-blue-100":"border-slate-200 bg-white hover:border-blue-300 hover:shadow-sm"}`}><div className="flex items-start gap-4">{icon&&<span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-50 text-2xl">{icon}</span>}<span><span className="block font-semibold text-slate-950">{title}</span>{description&&<span className="mt-1 block text-sm leading-6 text-slate-600">{description}</span>}</span></div></button>; }
export function Frame({title,helper,label,children,actions}:{title:string;helper?:string;label:string;children:ReactNode;actions:ReactNode}){ return <div className="mx-auto max-w-3xl"><div className="mb-4 flex items-center justify-between text-sm text-slate-500"><span>{label}</span><span>Salvataggio automatico</span></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-6 sm:px-8"><h1 className="text-2xl font-semibold tracking-tight text-slate-950">{title}</h1>{helper&&<p className="mt-2 text-sm leading-6 text-slate-600">{helper}</p>}</div><div className="px-6 py-6 sm:px-8">{children}</div><div className="flex flex-col-reverse gap-3 border-t border-slate-100 bg-slate-50 px-6 py-5 sm:flex-row sm:justify-between sm:px-8">{actions}</div></div></div>; }
export function Empty({title,description}:{title:string;description:string}){ return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-lg font-semibold text-slate-950">{title}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">{description}</p></div>; }
