
import type{CustomerQuestion,GuimmiaOperationType}from"./types";
const prompts:Record<string,[string,string]>={
  "customer.identity.status":["Puoi confermare i tuoi dati identificativi?","Servono per collegare correttamente persone, documenti e autorizzazioni alla pratica."],
  "customer.intent.status":["Qual e il risultato immobiliare che vuoi ottenere?","Permette a Guimmia di scegliere il percorso corretto senza fare supposizioni."],
  "property.link.status":["A quale immobile si riferisce questa richiesta?","Ogni documento, appuntamento e decisione deve appartenere allo stesso Case."],
  "service.model.status":["Preferisci il servizio Completa o Mensile?","Definisce cosa prepara e coordina Guimmia nella pratica."],
  "mandate.status":["Hai gia confermato l'incarico e il suo ambito?","Guimmia puo operare soltanto entro un incarico chiaro e attivo."],
  "fixed.compensation.disclosure.status":["Hai preso visione del compenso fisso previsto per il servizio?","Rende trasparenti costi e perimetro del servizio prima di procedere."],
  "property.ownership.evidence.status":["Puoi fornire il documento che dimostra la titolarita dell'immobile?","Serve a collegare l'incarico alla persona correttamente autorizzata."],
  "technical.dossier.status":["Quali documenti tecnici dell'immobile hai gia disponibili?","Permette a Guimmia di preparare il dossier e segnalare cosa deve verificare un tecnico."],
  "legal.ruleset.status":["In quale Comune si trova l'immobile e quale operazione vuoi fare?","Serve a individuare le regole applicabili senza formulare conclusioni legali automatiche."],
  "listing.draft.status":["Vuoi che Guimmia prepari la bozza dell'annuncio?","La bozza raccoglie in modo coerente dati, immagini e caratteristiche del Case."],
  "rental.authority.status":["Puoi confermare a quale titolo concedi l'immobile in locazione?","Serve a verificare che la gestione della locazione sia autorizzata."],
  "property.readiness.status":["L'immobile e pronto per essere proposto in locazione?","Consente di individuare prima eventuali attivita o documenti mancanti."],
  "rental.contract.profile.status":["Quale durata e quali condizioni generali desideri per la locazione?","Permette di preparare il profilo contrattuale corretto senza decidere al posto tuo."],
  "student.contract.profile.status":["Quali durata e condizioni vuoi prevedere per la locazione a studenti?","Serve a impostare il percorso studenti coerente con la tua scelta."],
  "transitory.reason.status":["Qual e l'esigenza temporanea che giustifica il contratto transitorio?","Il percorso transitorio richiede una motivazione specifica e documentabile."],
  "transitory.evidence.status":["Hai un documento che dimostri l'esigenza transitoria?","La motivazione deve essere supportata da evidenze adeguate."],
  "rental.duration.status":["Quale durata temporanea deve avere la locazione?","La durata deve essere coerente con l'esigenza transitoria documentata."],
  "student.enrollment.status":["Puoi fornire l'iscrizione o l'ammissione al corso di studi?","Serve a utilizzare correttamente il percorso dedicato agli studenti."],
  "student.course.period.status":["Qual e il periodo previsto del corso di studi?","Aiuta a coordinare durata della locazione e necessita dello studente."],
  "guarantor.or.income.status":["Puoi indicare il garante oppure fornire le informazioni economiche richieste?","Serve per preparare la verifica della candidatura senza scegliere automaticamente il candidato."],
  "tourist.unit.compliance.status":["Hai la documentazione disponibile per l'utilizzo turistico dell'immobile?","La pubblicazione turistica deve attendere le verifiche locali applicabili."],
  "tourist.local.ruleset.status":["In quale Comune e Regione si trova l'immobile?","Le regole per gli affitti turistici possono cambiare in base al territorio."],
  "tourist.reporting.profile.status":["Quali adempimenti e canali di comunicazione ospiti sono gia attivi?","Serve a preparare correttamente le comunicazioni previste per i soggiorni."],
  "listing.channel_authorization.status":["Su quali portali autorizzi Guimmia a predisporre la pubblicazione?","Evita pubblicazioni su canali non approvati."],
  "listing.human_approval.status":["Vuoi approvare la versione dell'annuncio preparata da Guimmia?","L'annuncio non viene pubblicato senza una decisione umana tracciata."],
  "lead.identity.status":["Puoi confermare i dati essenziali della persona interessata?","Serve a distinguere correttamente richieste e conversazioni collegate all'immobile."],
  "lead.intent.status":["Che cosa sta cercando la persona interessata e con quali tempi?","Permette di organizzare la richiesta senza attribuire intenzioni non dichiarate."],
  "availability.status":["Quali giorni e orari sono disponibili?","Guimmia puo proporre solo fasce realmente disponibili."],
  "customer.confirmation.status":["Confermi l'appuntamento proposto?","Guimmia puo proporre gli orari, ma prenota soltanto dopo la tua conferma."],
  "guest.confirmation.status":["Confermi la richiesta di prenotazione e le date indicate?","La prenotazione non viene finalizzata senza una conferma esplicita."],
  "offer.document.status":["Puoi fornire o confermare il documento dell'offerta?","Serve a riepilogare fedelmente condizioni e scadenze senza modificarle."],
  "offer.customer.decision.status":["Quale decisione vuoi prendere sull'offerta ricevuta?","Accettazione, rifiuto e controproposta restano decisioni umane."],
  "contract.draft.status":["Vuoi che Guimmia prepari la bozza del contratto per la revisione?","La bozza organizza i dati del Case ma non sostituisce approvazione e firma."],
  "contract.human_approval.status":["Hai approvato la versione del contratto da sottoporre alla firma?","Nessun documento contrattuale viene considerato definitivo senza approvazione umana."],
  "lease.draft.status":["Vuoi che Guimmia prepari la bozza di locazione per la revisione?","La bozza deve essere controllata e approvata prima della firma."],
  "lease.human_approval.status":["Hai approvato la bozza del contratto di locazione?","La firma e gli effetti del contratto richiedono una decisione umana esplicita."],
  "transitory.clause.review.status":["La clausola relativa all'esigenza transitoria e stata verificata?","Serve a evitare che la bozza proceda senza la revisione necessaria."],
  "student.clause.review.status":["Le clausole dedicate alla locazione studenti sono state verificate?","Serve a mantenere il contratto coerente con il percorso studenti."],
  "candidate.selection.human_decision.status":["Quale decisione vuoi prendere sui candidati verificati?","Guimmia organizza le informazioni ma non sceglie il candidato al posto tuo."],
  "candidate.income.evidence.status":["Il candidato puo fornire le evidenze economiche richieste?","Servono a preparare il riepilogo di screening senza una selezione automatica."],
  "screening.checks.status":["Le verifiche previste per la candidatura sono state completate?","Permette di presentare un quadro ordinato prima della decisione umana."],
  "candidate.identity.status":["Puoi confermare i dati identificativi del candidato?","Evita di associare documenti e verifiche alla persona sbagliata."],
  "candidate.evidence.status":["Quali documenti della candidatura sono disponibili?","Serve a distinguere informazioni dichiarate ed evidenze verificate."],
  "closing.checklist.status":["La lista delle attivita necessarie alla chiusura e completa?","Riduce il rischio di arrivare alla chiusura con passaggi ancora aperti."],
  "professional.signoff.status":["Il professionista competente ha completato la propria verifica?","Guimmia non sostituisce le conclusioni riservate a un professionista qualificato."],
  "handover.evidence.status":["Sono disponibili le evidenze della consegna?","Servono a documentare in modo chiaro cosa e stato consegnato e quando."],
  "case.archive.status":["Possiamo considerare completa la documentazione finale della pratica?","Serve a chiudere il Case senza perdere documenti, decisioni o passaggi ancora aperti."],
  "handover.record.status":["Il verbale o riepilogo di consegna e pronto?","Permette di chiudere la fase di consegna con una traccia verificabile."],
  "deposit.status":["Qual e lo stato del deposito previsto?","Serve a coordinare la consegna senza presumere pagamenti o accordi."],
  "guest.identity.status":["Puoi confermare i dati richiesti degli ospiti?","Servono per preparare correttamente check-in e comunicazioni previste."],
  "checkin.instructions.status":["Le istruzioni di accesso e check-in sono pronte?","Consentono di assistere l'ospite senza inviare indicazioni incomplete."],
  "guest.support.status":["Durante il soggiorno ci sono richieste dell'ospite ancora da gestire?","Permette a Guimmia di organizzare assistenza e aggiornamenti senza perdere continuita."],
  "incident.status":["Si e verificato un problema durante il soggiorno?","Serve a indirizzare subito la gestione corretta e coinvolgere una persona quando necessario."],
  "guest.reporting.status":["Le comunicazioni ospiti previste sono state preparate o completate?","Permette di mantenere tracciato lo stato degli adempimenti del soggiorno."],
  "tourist.tax.status":["Qual e lo stato della gestione dell'imposta di soggiorno?","Serve a coordinare l'attivita senza formulare automaticamente conclusioni fiscali."],
  "checkout.status":["Il check-out e stato completato?","Avvia correttamente verifica dell'immobile e riassetto."],
  "property.condition.status":["Qual e lo stato dell'immobile dopo il soggiorno?","Serve a documentare eventuali necessita prima della disponibilita successiva."],
  "turnover.plan.status":["Il piano di pulizia e riassetto e confermato?","Consente di coordinare le attivita prima del prossimo soggiorno."],
  "next.availability.status":["Da quando l'immobile sara nuovamente disponibile?","Evita di proporre date non ancora confermate."]
};
export function buildCustomerQuestions(paths:string[],operationType:GuimmiaOperationType,limit=3):CustomerQuestion[]{return[...new Set(paths)].slice(0,limit).map((factPath,index)=>{const item=prompts[factPath]??["Ci serve un'informazione aggiuntiva per continuare la pratica.","Evita che Guimmia proceda usando dati incompleti o presunti."];return{questionCode:"Q_"+operationType+"_"+(index+1)+"_"+factPath.toUpperCase().replace(/[^A-Z0-9]+/g,"_").slice(0,48),factPath,prompt:item[0],whyItMatters:item[1],operationType}})}
