
export const guimmiaCaseContextMachine={DRAFT:["SNAPSHOT_READY","INVALID"],SNAPSHOT_READY:["SUPERSEDED","INVALID"],SUPERSEDED:[],INVALID:["DRAFT"]}as const;
export const guimmiaDecisionRunMachine={CREATED:["EVALUATING","CANCELLED"],EVALUATING:["DECIDED","BLOCKED","FAILED"],DECIDED:["COMMITTED","SUPERSEDED"],BLOCKED:["SUPERSEDED"],COMMITTED:[],SUPERSEDED:[],FAILED:["CREATED"],CANCELLED:[]}as const;
export const guimmiaNextActionMachine={PROPOSED:["READY","BLOCKED","CANCELLED"],READY:["IN_PROGRESS","SUPERSEDED","CANCELLED"],IN_PROGRESS:["COMPLETED","BLOCKED","CANCELLED"],BLOCKED:["READY","CANCELLED"],COMPLETED:[],SUPERSEDED:[],CANCELLED:[]}as const;
export const guimmiaHumanHandoffMachine={REQUESTED:["ASSIGNED","CANCELLED"],ASSIGNED:["ACCEPTED","ESCALATED","CANCELLED"],ACCEPTED:["RESOLVED","ESCALATED"],ESCALATED:["ASSIGNED","RESOLVED"],RESOLVED:[],CANCELLED:[]}as const;
export const guimmiaPlaybookMachine={ACTIVE:["WAITING_INPUT","STAGE_READY","PAUSED","COMPLETED"],WAITING_INPUT:["ACTIVE","PAUSED"],STAGE_READY:["ACTIVE","PAUSED","COMPLETED"],PAUSED:["ACTIVE","CANCELLED"],COMPLETED:[],CANCELLED:[]}as const;
export const guimmiaExecutionCommandMachine={DRAFT:["VALIDATED","BLOCKED","CANCELLED"],VALIDATED:["EXECUTING","BLOCKED","CANCELLED"],BLOCKED:["DRAFT","CANCELLED"],EXECUTING:["SUCCEEDED","FAILED"],FAILED:["DRAFT","CANCELLED"],SUCCEEDED:[],CANCELLED:[]}as const;
