import "server-only";

const OPENAI_PLACEHOLDERS = new Set([
  "",
  "sk-your-openai-api-key",
  "your-openai-api-key",
]);

export const GUIMMIA_OPENAI_MODEL = "gpt-5.6-luna" as const;
export const GUIMMIA_AI_MODE = "DRY_RUN" as const;
export const GUIMMIA_AI_MONTHLY_BUDGET_USD = 5;
export const GUIMMIA_AI_MAX_REQUEST_COST_USD = 0.05;
export const GUIMMIA_AI_RATE_LIMIT_REQUESTS = 3;
export const GUIMMIA_AI_RATE_LIMIT_WINDOW_MINUTES = 30;
export const GUIMMIA_BRAIN_MAX_REQUEST_COST_USD = 0.02;
export const GUIMMIA_BRAIN_RATE_LIMIT_REQUESTS = 12;
export const GUIMMIA_BRAIN_RATE_LIMIT_WINDOW_MINUTES = 30;
export const GUIMMIA_BRAIN_REUSE_WINDOW_MINUTES = 15;
export const GUIMMIA_BRAIN_MAX_RULES = 10;
export const GUIMMIA_BRAIN_MAX_KNOWLEDGE_CARDS = 6;
export const GUIMMIA_BRAIN_MAX_OUTPUT_TOKENS = 900;
export const GUIMMIA_INTAKE_MAX_REQUEST_COST_USD = 0.01;
export const GUIMMIA_INTAKE_RATE_LIMIT_REQUESTS = 20;
export const GUIMMIA_INTAKE_RATE_LIMIT_WINDOW_MINUTES = 30;
export const GUIMMIA_INTAKE_REUSE_WINDOW_MINUTES = 15;
export const GUIMMIA_INTAKE_MAX_OUTPUT_TOKENS = 520;
export const GUIMMIA_DOCUMENT_MAX_FILE_BYTES = 10 * 1024 * 1024;
export const GUIMMIA_DOCUMENT_MAX_REQUEST_COST_USD = 0.03;
export const GUIMMIA_DOCUMENT_RATE_LIMIT_REQUESTS = 8;
export const GUIMMIA_DOCUMENT_RATE_LIMIT_WINDOW_MINUTES = 30;
export const GUIMMIA_DOCUMENT_MAX_OUTPUT_TOKENS = 700;
export const GUIMMIA_SCHEDULING_MAX_REQUEST_COST_USD = 0.01;
export const GUIMMIA_SCHEDULING_RATE_LIMIT_REQUESTS = 12;
export const GUIMMIA_SCHEDULING_RATE_LIMIT_WINDOW_MINUTES = 30;
export const GUIMMIA_SCHEDULING_MAX_OUTPUT_TOKENS = 420;

export function getOpenAIConfiguration() {
  const apiKey = process.env.OPENAI_API_KEY?.trim() ?? "";

  return {
    apiKey,
    model: GUIMMIA_OPENAI_MODEL,
    mode: GUIMMIA_AI_MODE,
    monthlyBudgetUsd: GUIMMIA_AI_MONTHLY_BUDGET_USD,
    maxRequestCostUsd: GUIMMIA_AI_MAX_REQUEST_COST_USD,
    rateLimitRequests: GUIMMIA_AI_RATE_LIMIT_REQUESTS,
    rateLimitWindowMinutes: GUIMMIA_AI_RATE_LIMIT_WINDOW_MINUTES,
    configured: Boolean(apiKey) && !OPENAI_PLACEHOLDERS.has(apiKey),
  };
}
