-- GUIMMIA V76.6 - profiles, gates, legal map, workflows
insert into public.guimmia_transaction_profiles(code,family,label,workflow_slug) values
('SALE','SALE','Vendita','sale-private-apartment'),
('RENT_LONG_TERM','RENTAL_RESIDENTIAL','Locazione abitativa lungo termine','rent-long-term-residential'),
('RENT_TRANSITORY','RENTAL_RESIDENTIAL','Locazione transitoria','rent-transitory-residential'),
('RENT_STUDENT','RENTAL_RESIDENTIAL','Locazione studenti universitari','rent-student-residential'),
('RENT_TOURIST_SHORT','RENTAL_TOURIST','Locazione breve/turistica','rent-tourist-short')
on conflict(code) do update set family=excluded.family,label=excluded.label,workflow_slug=excluded.workflow_slug,active=true,updated_at=now();

insert into public.guimmia_transaction_gate_defs(code,family,label,sort_order) values
('PUBLICATION','SALE','Pubblicazione vendita',10),('OFFER','SALE','Proposta',20),('PRELIMINARY','SALE','Preliminare',30),('CLOSING','SALE','Rogito',40),
('RENTAL_PUBLICATION','RENTAL_RESIDENTIAL','Pubblicazione locazione',50),('CANDIDATE_SELECTION','RENTAL_RESIDENTIAL','Scelta candidato',60),('LEASE_SIGNING','RENTAL_RESIDENTIAL','Firma contratto',70),('LEASE_REGISTRATION','RENTAL_RESIDENTIAL','Registrazione',80),('HANDOVER','RENTAL_RESIDENTIAL','Consegna',90),
('TOURIST_PUBLICATION','RENTAL_TOURIST','Pubblicazione turistica',100),('BOOKING','RENTAL_TOURIST','Prenotazione',110),('CHECK_IN','RENTAL_TOURIST','Check-in',120),('GUEST_REPORTING','RENTAL_TOURIST','Comunicazione ospiti',130),('PAYOUT_TAX','RENTAL_TOURIST','Incassi e fiscalita',140)
on conflict(code) do update set family=excluded.family,label=excluded.label,sort_order=excluded.sort_order,active=true;

insert into public.guimmia_brain_modules(code,title,priority,sort_order) values
('TRANSACTION_ROUTING','Routing operazione','P0',15),('RENTAL_AUTHORITY','Potere di locare','P0',25),('RENTAL_DOCUMENTS','Fascicolo locazione','P0',35),('RENTAL_READINESS','Prontezza immobile per locazione','P0',45),('TAX_RENTAL','Fiscalita delle locazioni','P0',75),('RENTAL_CONTRACTS','Contratti di locazione','P0',85),('TENANT_SCREENING','Candidati conduttori e screening','P0',125),('TOURIST_COMPLIANCE','Locazioni turistiche e brevi','P0',135),('RENTAL_OPERATIONS','Consegna, soggiorni, rinnovi e cessazioni','P0',145)
on conflict(code) do update set title=excluded.title,priority=excluded.priority,sort_order=excluded.sort_order,active=true,updated_at=now();

insert into public.guimmia_brain_sources(code,title,source_kind,normative_authority,notes) values
('IT_L431_1998','Legge 431/1998 - locazioni abitative','OFFICIAL_LAW',true,'Reference only; verify current consolidated text before production conclusions.'),
('IT_DM_2017_RENTAL_AGREEMENTS','D.M. 16 gennaio 2017 - canone concordato, transitori, studenti','OFFICIAL_LAW',true,'Reference only; local agreements remain dynamic.'),
('IT_DL145_2023_ART13TER','D.L. 145/2023 art. 13-ter - CIN e locazioni turistiche','OFFICIAL_LAW',true,'Reference only; ruleset must be verified as current.'),
('IT_BDSR_FAQ','Ministero Turismo - FAQ BDSR/CIN','OFFICIAL_GUIDANCE',true,'FAQ official guidance; refreshed separately.'),
('IT_AE_RENTAL_GUIDANCE','Agenzia Entrate - fiscalita locazioni','OFFICIAL_GUIDANCE',true,'Tax guidance; dynamic.'),
('IT_AE_RENTAL_REGISTRATION','Agenzia Entrate - registrazione locazioni','OFFICIAL_GUIDANCE',true,'Registration guidance; dynamic.')
on conflict(code) do update set title=excluded.title,source_kind=excluded.source_kind,normative_authority=excluded.normative_authority,notes=excluded.notes,updated_at=now();

insert into public.guimmia_brain_rulesets(ruleset_key,jurisdiction,title,status,official_sources) values
('ITALY_RESIDENTIAL_RENTAL','IT','Locazioni abitative - disciplina generale','MISSING','["Normattiva L.431/1998"]'::jsonb),
('ITALY_LOCAL_RENTAL_AGREEMENTS','IT','Accordi territoriali locazioni','MISSING','["D.M. 16/01/2017","accordo locale applicabile"]'::jsonb),
('ITALY_TRANSITORY_RENTAL','IT','Locazioni transitorie','MISSING','["D.M. 16/01/2017","accordo locale"]'::jsonb),
('ITALY_STUDENT_RENTAL','IT','Locazioni studenti universitari','MISSING','["D.M. 16/01/2017","accordo locale"]'::jsonb),
('ITALY_RENTAL_REGISTRATION','IT','Registrazione contratti locazione','MISSING','["Agenzia delle Entrate"]'::jsonb),
('ITALY_RENTAL_TAX','IT','Fiscalita locazioni residenziali','MISSING','["Agenzia delle Entrate"]'::jsonb),
('ITALY_SHORT_RENT_TAX','IT','Fiscalita locazioni brevi','MISSING','["Agenzia delle Entrate","D.L.50/2017 art.4"]'::jsonb),
('ITALY_SHORT_RENT_INTERMEDIARY_TAX','IT','Obblighi fiscali intermediari locazioni brevi','MISSING','["Agenzia delle Entrate","D.L.50/2017 art.4"]'::jsonb),
('ITALY_TOURIST_CIN','IT','CIN/BDSR locazioni turistiche e brevi','MISSING','["D.L.145/2023 art.13-ter","Ministero Turismo BDSR"]'::jsonb),
('ITALY_TOURIST_SAFETY','IT','Sicurezza locazioni turistiche e brevi','MISSING','["D.L.145/2023 art.13-ter","FAQ BDSR"]'::jsonb),
('ITALY_TOURIST_SCIA','IT','SCIA locazioni turistiche in forma imprenditoriale','MISSING','["D.L.145/2023 art.13-ter","normativa locale"]'::jsonb),
('ITALY_TOURIST_BUSINESS_STATUS','IT','Qualificazione imprenditoriale locazioni turistiche','MISSING','["legge vigente","Agenzia Entrate"]'::jsonb),
('ITALY_TOURIST_LOCAL_RULES','IT','Regole regionali e comunali locazioni turistiche','MISSING','["Regione","Comune","SUAP"]'::jsonb),
('ITALY_GUEST_REPORTING','IT','Adempimenti pubblica sicurezza ospiti','MISSING','["TULPS art.109","Ministero Turismo guidance"]'::jsonb)
on conflict(ruleset_key,jurisdiction) do nothing;

insert into public.guimmia_brain_workflows(slug,title,description,version,active) values('rent-long-term-residential','Locazione abitativa lungo termine','V76.6 multi-transaction workflow',1,true) on conflict(slug,version) do update set title=excluded.title,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P01','PHASE_01_CLIENT_MANDATE',10,'Cliente e mandato','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R02','PHASE_R02_LETTING_AUTHORITY',20,'Potere di locare','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R03','PHASE_R03_RENTAL_DOCUMENT_DOSSIER',30,'Fascicolo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R04','PHASE_R04_RENTAL_READINESS',40,'Prontezza immobile','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P05','PHASE_05_TRANSACTION_TAX_CONTRACT',50,'Contratto e fiscalita','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R06','PHASE_R06_MARKET_READINESS',60,'Preparazione annuncio','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R07','PHASE_R07_CANDIDATES',70,'Candidati','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R08','PHASE_R08_SCREENING',80,'Screening e scelta','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R09','PHASE_R09_SIGN_REGISTER',90,'Firma e registrazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R10','PHASE_R10_HANDOVER',100,'Consegna','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R11','PHASE_R11_LIFECYCLE',110,'Ciclo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-long-term-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();

insert into public.guimmia_brain_workflows(slug,title,description,version,active) values('rent-transitory-residential','Locazione abitativa transitoria','V76.6 multi-transaction workflow',1,true) on conflict(slug,version) do update set title=excluded.title,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P01','PHASE_01_CLIENT_MANDATE',10,'Cliente e mandato','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R02','PHASE_R02_LETTING_AUTHORITY',20,'Potere di locare','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R03','PHASE_R03_RENTAL_DOCUMENT_DOSSIER',30,'Fascicolo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R04','PHASE_R04_RENTAL_READINESS',40,'Prontezza immobile','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P05','PHASE_05_TRANSACTION_TAX_CONTRACT',50,'Contratto e fiscalita','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R06','PHASE_R06_MARKET_READINESS',60,'Preparazione annuncio','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R07','PHASE_R07_CANDIDATES',70,'Candidati','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R08','PHASE_R08_SCREENING',80,'Screening e scelta','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R09','PHASE_R09_SIGN_REGISTER',90,'Firma e registrazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R10','PHASE_R10_HANDOVER',100,'Consegna','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R11','PHASE_R11_LIFECYCLE',110,'Ciclo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-transitory-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();

insert into public.guimmia_brain_workflows(slug,title,description,version,active) values('rent-student-residential','Locazione studenti universitari','V76.6 multi-transaction workflow',1,true) on conflict(slug,version) do update set title=excluded.title,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P01','PHASE_01_CLIENT_MANDATE',10,'Cliente e mandato','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R02','PHASE_R02_LETTING_AUTHORITY',20,'Potere di locare','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R03','PHASE_R03_RENTAL_DOCUMENT_DOSSIER',30,'Fascicolo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R04','PHASE_R04_RENTAL_READINESS',40,'Prontezza immobile','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P05','PHASE_05_TRANSACTION_TAX_CONTRACT',50,'Contratto e fiscalita','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R06','PHASE_R06_MARKET_READINESS',60,'Preparazione annuncio','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R07','PHASE_R07_CANDIDATES',70,'Candidati','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R08','PHASE_R08_SCREENING',80,'Screening e scelta','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R09','PHASE_R09_SIGN_REGISTER',90,'Firma e registrazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R10','PHASE_R10_HANDOVER',100,'Consegna','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R11','PHASE_R11_LIFECYCLE',110,'Ciclo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-student-residential' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();

insert into public.guimmia_brain_workflows(slug,title,description,version,active) values('rent-tourist-short','Locazione breve/turistica','V76.6 multi-transaction workflow',1,true) on conflict(slug,version) do update set title=excluded.title,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P01','PHASE_01_CLIENT_MANDATE',10,'Cliente e mandato','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R02','PHASE_R02_LETTING_AUTHORITY',20,'Potere di locare','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R03','PHASE_R03_RENTAL_DOCUMENT_DOSSIER',30,'Fascicolo locazione','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'R04','PHASE_R04_RENTAL_READINESS',40,'Prontezza immobile','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'P05','PHASE_05_TRANSACTION_TAX_CONTRACT',50,'Contratto e fiscalita','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'T06','PHASE_T06_TOURIST_MARKET',60,'Annuncio turistico','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'T07','PHASE_T07_BOOKING',70,'Prenotazioni','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'T08','PHASE_T08_STAY',80,'Soggiorno','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
insert into public.guimmia_brain_workflow_steps(workflow_id,code,phase_code,sort_order,label,description) select id,'T09','PHASE_T09_PAYOUT_ARCHIVE',90,'Incassi e chiusura','V76.6 step' from public.guimmia_brain_workflows where slug='rent-tourist-short' and version=1 on conflict(workflow_id,code) do update set phase_code=excluded.phase_code,sort_order=excluded.sort_order,label=excluded.label,description=excluded.description,active=true,updated_at=now();
