-- V76.3 P03 rule seed
with wf as (select id from public.guimmia_brain_workflows where slug='sale-private-apartment' and version=2 limit 1)
insert into public.guimmia_brain_rules(code,workflow_id,step_id,module,phase_code,title,description,stability,decision_level,severity,condition_definition,outcome_definition,source_refs,freshness_policy,evidence_policy,version,active)
select 'P03_INVENTORY_NOT_INITIALIZED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Inventario non inizializzato','Il fascicolo deve essere materializzato prima di qualsiasi decisione.','INTERNAL','AUTO','blocking','{"op": "neq", "path": "documents.inventoryStatus", "value": "INITIALIZED"}'::jsonb,'{"code": "DOC_INVENTORY_REQUIRED", "message": "Inizializzare inventario documentale.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_REQUIREMENTS_NOT_GENERATED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Requisiti non generati','I requisiti devono essere calcolati sul contesto corrente.','INTERNAL','AUTO','blocking','{"op": "neq", "path": "documents.requirementsStatus", "value": "GENERATED"}'::jsonb,'{"code": "DOC_REQUIREMENTS_REQUIRED", "message": "Generare i requisiti documentali contestuali.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_REQUIREMENTS_STALE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Requisiti obsoleti','I facts sono cambiati dopo il calcolo requisiti.','INTERNAL','AUTO','blocking','{"op": "gt", "path": "documents.requirementsStaleCount", "value": 0}'::jsonb,'{"code": "DOC_REQUIREMENTS_STALE", "message": "Ricalcolare i requisiti documentali.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_UNKNOWN_APPLICABILITY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Applicabilità non determinata','Un requisito non può essere trattato come non applicabile solo perché mancano fatti.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.unknownApplicabilityCount", "value": 0}'::jsonb,'{"code": "DOC_APPLICABILITY_REVIEW", "message": "Completare i facts necessari a determinare i requisiti."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_UNROUTED_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documenti mancanti non instradati','Ogni mancanza applicabile deve avere richiesta/task/escalation.','INTERNAL','REVIEW','blocking','{"op": "gt", "path": "documents.unroutedMissingCount", "value": 0}'::jsonb,'{"code": "DOC_MISSING_ROUTE_REQUIRED", "message": "Instradare ogni mancanza rilevante.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_UNCLASSIFIED_FILES',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','File non classificati','I file ricevuti devono essere classificati o esclusi esplicitamente.','INTERNAL','AUTO','warning','{"op": "gt", "path": "documents.unclassifiedCount", "value": 0}'::jsonb,'{"code": "DOC_CLASSIFICATION_REQUIRED", "message": "Classificare i file non riconosciuti."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_PROCESSING_ERRORS',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Elaborazioni fallite','Errori di ingestion/extraction richiedono retry o review.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.processingErrorCount", "value": 0}'::jsonb,'{"code": "DOC_PROCESSING_RETRY", "message": "Gestire errori di elaborazione."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_UNREADABLE_CURRENT',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documento corrente illeggibile','Una versione corrente illeggibile non può soddisfare il requisito.','INTERNAL','REVIEW','blocking','{"op": "gt", "path": "documents.unreadableCount", "value": 0}'::jsonb,'{"code": "DOC_UNREADABLE", "message": "Richiedere nuova copia o review manuale.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_PARTIAL_QUALITY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Qualità parziale','Un documento parziale richiede review prima di usare i claim.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.partialQualityCount", "value": 0}'::jsonb,'{"code": "DOC_PARTIAL_REVIEW", "message": "Verificare completezza delle pagine/contenuto."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_EXACT_DUPLICATES',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Duplicati esatti','Hash identici devono essere deduplicati senza perdere audit.','INTERNAL','AUTO','info','{"op": "gt", "path": "documents.exactDuplicateCount", "value": 0}'::jsonb,'{"code": "DOC_EXACT_DUPLICATE", "message": "Collegare il duplicato alla versione esistente."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_POSSIBLE_DUPLICATES',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Possibili duplicati','Fingerprint contenuto uguale ma hash diverso richiede review/versioning.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.possibleDuplicateCount", "value": 0}'::jsonb,'{"code": "DOC_POSSIBLE_DUPLICATE", "message": "Verificare se si tratta di nuova scansione/versione."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_SUPERSEDED_STILL_CURRENT',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Versioning incoerente','Una versione superseded non può essere anche current.','INTERNAL','AUTO','blocking','{"op": "gt", "path": "documents.versioningInvariantErrorCount", "value": 0}'::jsonb,'{"code": "DOC_VERSIONING_INVARIANT", "message": "Correggere il versioning.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_LOW_CONFIDENCE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Estrazione a bassa confidenza','Claim a bassa confidenza non devono diventare facts verificati automaticamente.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.lowConfidenceExtractionCount", "value": 0}'::jsonb,'{"code": "DOC_LOW_CONFIDENCE", "message": "Aprire review dei campi a bassa confidenza."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_EXTRACTION_WITHOUT_ANCHOR',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Claim senza evidence anchor','Ogni claim rilevante deve poter essere ricondotto al documento/pagina.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.unanchoredClaimCount", "value": 0}'::jsonb,'{"code": "DOC_EVIDENCE_ANCHOR_REQUIRED", "message": "Creare evidence anchor prima della promozione del claim."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_CRITICAL_FACT_NO_EVIDENCE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Fact critico senza evidenza','Un fact critico non può essere verificato senza evidenza tracciata.','INTERNAL','REVIEW','blocking','{"op": "gt", "path": "documents.criticalFactWithoutEvidenceCount", "value": 0}'::jsonb,'{"code": "DOC_CRITICAL_EVIDENCE_REQUIRED", "message": "Collegare evidenza verificabile.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_OPEN_CONFLICTS',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Conflitti documentali aperti','Conflitti fra claim/facts non devono essere risolti silenziosamente.','INTERNAL','AGENT_REQUIRED','warning','{"op": "gt", "path": "documents.openConflictCount", "value": 0}'::jsonb,'{"code": "DOC_CONFLICT_REVIEW", "message": "Riconciliare conflitti e registrare decisione.", "escalationTo": "AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_CRITICAL_CONFLICTS',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Conflitti critici aperti','Conflitti critici bloccano la fase.','INTERNAL','AGENT_REQUIRED','critical','{"op": "gt", "path": "documents.criticalConflictCount", "value": 0}'::jsonb,'{"code": "DOC_CRITICAL_CONFLICT", "message": "Bloccare e risolvere il conflitto.", "blockProgress": true, "escalationTo": "AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_DECLARATION_DOCUMENT_MISMATCH',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Dichiarazione vs documento','Discordanza tra dichiarazione cliente e documento richiede review.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.declarationMismatchCount", "value": 0}'::jsonb,'{"code": "DOC_DECLARATION_MISMATCH", "message": "Mostrare differenze e chiedere chiarimento."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_OFFICIAL_SOURCE_MISMATCH',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Fonte ufficiale discordante','Discordanza con fonte ufficiale richiede decisione professionale.','INTERNAL','PROFESSIONAL_REQUIRED','blocking','{"op": "gt", "path": "documents.officialSourceMismatchCount", "value": 0}'::jsonb,'{"code": "DOC_OFFICIAL_SOURCE_MISMATCH", "message": "Escalation professionale necessaria.", "blockProgress": true, "escalationTo": "NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_REVIEW_QUEUE_PENDING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Review documentali pendenti','La coda review deve essere gestita prima dello snapshot finale.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.pendingReviewCount", "value": 0}'::jsonb,'{"code": "DOC_REVIEW_PENDING", "message": "Completare le review documentali."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_HIGH_PUBLIC_STORAGE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documento sensibile esposto','Documenti HIGH non devono avere storage pubblico.','INTERNAL','AGENT_REQUIRED','critical','{"op": "gt", "path": "documents.publicHighSensitivityCount", "value": 0}'::jsonb,'{"code": "DOC_SECURITY_PUBLIC_STORAGE", "message": "Rimuovere esposizione pubblica e ruotare eventuali link.", "blockProgress": true, "escalationTo": "AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_SYNTHETIC_EVIDENCE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Output sintetico usato come fonte','Un documento generato dall’IA non può essere fonte primaria di un fatto esterno.','INTERNAL','AGENT_REQUIRED','critical','{"op": "gt", "path": "documents.syntheticEvidenceCount", "value": 0}'::jsonb,'{"code": "DOC_SYNTHETIC_EVIDENCE_BLOCK", "message": "Sostituire con evidenza primaria o verificata.", "blockProgress": true, "escalationTo": "AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_ACCESS_AUDIT_GAP',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Accesso sensibile senza audit','Accessi a documenti HIGH devono essere tracciati secondo policy interna.','INTERNAL','REVIEW','warning','{"op": "gt", "path": "documents.accessAuditGapCount", "value": 0}'::jsonb,'{"code": "DOC_ACCESS_AUDIT_GAP", "message": "Ripristinare audit trail accessi."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_LEASE_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Contratto locazione non acquisito','Se l’immobile è locato il fascicolo deve contenere o instradare il contratto.','STABLE','AGENT_REQUIRED','blocking','{"op": "all", "conditions": [{"op": "eq", "path": "property.occupancy", "value": "LEASED"}, {"op": "neq", "path": "documents.leaseContractStatus", "value": "RECEIVED_OR_VERIFIED"}]}'::jsonb,'{"code": "LEASE_DOC_REQUIRED", "message": "Acquisire/instradare contratto di locazione.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_MORTGAGE_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documentazione mutuo non instradata','Mutuo attivo richiede routing documentale banca.','STABLE','REVIEW','warning','{"op": "all", "conditions": [{"op": "eq", "path": "finance.activeMortgage", "value": true}, {"op": "eq", "path": "documents.mortgageRoutingStatus", "value": "MISSING"}]}'::jsonb,'{"code": "MORTGAGE_DOC_ROUTE", "message": "Aprire richiesta/routing banca."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_CONDO_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documentazione condominiale non instradata','Per unità in condominio la situazione amministrativa deve avere routing.','STABLE','REVIEW','warning','{"op": "all", "conditions": [{"op": "eq", "path": "property.isCondominium", "value": true}, {"op": "eq", "path": "documents.condominiumRoutingStatus", "value": "MISSING"}]}'::jsonb,'{"code": "CONDO_DOC_ROUTE", "message": "Richiedere/instradare documentazione condominiale."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_SUCCESSION_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Documenti successione mancanti','Provenienza successoria richiede documentazione e routing notarile.','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op": "all", "conditions": [{"op": "eq", "path": "ownership.originType", "value": "SUCCESSION"}, {"op": "neq", "path": "documents.successionStatus", "value": "RECEIVED_OR_ROUTED"}]}'::jsonb,'{"code": "SUCCESSION_DOC_ROUTE", "message": "Acquisire documentazione e instradare al notaio.", "blockProgress": true, "escalationTo": "NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_DONATION_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Atto di donazione mancante','Provenienza donativa richiede atto e routing professionale.','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op": "all", "conditions": [{"op": "eq", "path": "ownership.originType", "value": "DONATION"}, {"op": "neq", "path": "documents.donationStatus", "value": "RECEIVED_OR_ROUTED"}]}'::jsonb,'{"code": "DONATION_DOC_ROUTE", "message": "Acquisire atto di donazione.", "blockProgress": true, "escalationTo": "NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_POA_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Procura mancante','Rappresentanza dichiarata richiede evidenza dei poteri.','STABLE','AGENT_REQUIRED','blocking','{"op": "all", "conditions": [{"op": "eq", "path": "ownership.representationUsed", "value": true}, {"op": "neq", "path": "documents.powerOfAttorneyStatus", "value": "RECEIVED_OR_VERIFIED"}]}'::jsonb,'{"code": "POA_DOC_REQUIRED", "message": "Acquisire procura/poteri.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_COMPANY_DOC_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Poteri societari mancanti','Venditore società richiede evidenza dei poteri.','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op": "all", "conditions": [{"op": "eq", "path": "client.type", "value": "LEGAL_ENTITY"}, {"op": "neq", "path": "documents.companyAuthorityStatus", "value": "RECEIVED_OR_VERIFIED"}]}'::jsonb,'{"code": "COMPANY_DOC_REQUIRED", "message": "Acquisire documenti societari/poteri.", "blockProgress": true, "escalationTo": "LAWYER"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_TAX_BONUS_DOC_ROUTING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Storia bonus senza documenti','La storia di interventi agevolati deve avere documentazione/routing fiscale.','DYNAMIC','AGENT_REQUIRED','warning','{"op": "all", "conditions": [{"op": "eq", "path": "tax.superbonusOrArticle119History", "value": true}, {"op": "neq", "path": "documents.taxBonusRoutingStatus", "value": "ROUTED_OR_RECEIVED"}]}'::jsonb,'{"code": "TAX_BONUS_DOC_ROUTE", "message": "Raccogliere documentazione e applicare ruleset fiscale corrente.", "escalationTo": "ACCOUNTANT"}'::jsonb,'[]'::jsonb,'{"required": true, "maxAgeDays": 90, "rulesetKey": "ITALY_REAL_ESTATE_TAX"}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_APE_ROUTING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','APE richiesto ma non instradato','Quando il ruleset corrente determina necessità APE, il fascicolo deve instradarlo.','DYNAMIC','REVIEW','warning','{"op": "all", "conditions": [{"op": "eq", "path": "documents.apeRequired", "value": true}, {"op": "neq", "path": "documents.apeRoutingStatus", "value": "ROUTED_OR_RECEIVED"}]}'::jsonb,'{"code": "APE_DOC_ROUTE", "message": "Acquisire/instradare APE."}'::jsonb,'[]'::jsonb,'{"required": true, "maxAgeDays": 90, "rulesetKey": "ITALY_APE"}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_SNAPSHOT_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Snapshot dossier mancante','Il gate deve essere riproducibile con uno snapshot immutabile.','INTERNAL','AUTO','blocking','{"op": "neq", "path": "documents.snapshotStatus", "value": "CURRENT"}'::jsonb,'{"code": "DOSSIER_SNAPSHOT_REQUIRED", "message": "Generare snapshot P03 prima della chiusura.", "blockProgress": true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P03_READY_GATE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P03'),'DOCUMENT_DOSSIER','PHASE_03_DOCUMENT_DOSSIER','Fascicolo pronto per fase successiva','Tutti i gate P03 risultano soddisfatti.','INTERNAL','AUTO','info','{"op": "eq", "path": "documents.dossierReadiness", "value": "READY"}'::jsonb,'{"code": "P03_READY", "message": "Fascicolo pronto per le verifiche successive.", "blockProgress": false}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
on conflict(code,version) do update set workflow_id=excluded.workflow_id,step_id=excluded.step_id,module=excluded.module,phase_code=excluded.phase_code,title=excluded.title,description=excluded.description,stability=excluded.stability,decision_level=excluded.decision_level,severity=excluded.severity,condition_definition=excluded.condition_definition,outcome_definition=excluded.outcome_definition,freshness_policy=excluded.freshness_policy,evidence_policy=excluded.evidence_policy,active=true,updated_at=now();
