-- CasaPilot V69 Professionisti Plus. Eseguire solo dopo backup del database.
create extension if not exists "pgcrypto";
create table if not exists public.professional_categories(id text primary key,name text not null,description text not null default '',availability_status text not null default 'limited' check(availability_status in('active','limited','activating')),sort_order integer not null default 0,is_enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.professional_service_catalog(id text primary key,category_id text not null references public.professional_categories(id) on delete cascade,name text not null,description text not null default '',availability_status text not null default 'limited' check(availability_status in('active','limited','activating')),eligible_professions jsonb not null default '[]'::jsonb,wizard_config jsonb not null default '{}'::jsonb,quote_config jsonb not null default '{}'::jsonb,review_config jsonb not null default '{}'::jsonb,is_enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.professional_profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,account_type text not null,display_name text not null,profession text not null,bio text not null default '',years_experience integer not null default 0,online_available boolean not null default false,verification_status text not null default 'incomplete' check(verification_status in('incomplete','pending','verified','update_required','suspended')),average_rating numeric(3,2) not null default 0,verified_reviews_count integer not null default 0,average_response_minutes integer,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.professional_profile_services(professional_id uuid not null references public.professional_profiles(id) on delete cascade,service_id text not null references public.professional_service_catalog(id) on delete cascade,pricing_mode text,price_min numeric(12,2),price_max numeric(12,2),is_active boolean not null default true,primary key(professional_id,service_id));
create table if not exists public.professional_service_areas(id uuid primary key default gen_random_uuid(),professional_id uuid not null references public.professional_profiles(id) on delete cascade,service_id text references public.professional_service_catalog(id) on delete cascade,country_code text not null default 'IT',region text,province text,municipality text,radius_km integer,online_only boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.professional_verifications(id uuid primary key default gen_random_uuid(),professional_id uuid not null references public.professional_profiles(id) on delete cascade,verification_type text not null,status text not null default 'pending' check(status in('pending','verified','rejected','expired')),document_path text,verified_by uuid references auth.users(id),verified_at timestamptz,expires_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.lead_requests(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,property_id uuid,category_id text not null references public.professional_categories(id),service_id text not null references public.professional_service_catalog(id),property_label text not null,approximate_location text not null,exact_address jsonb,answers jsonb not null default '{}'::jsonb,urgency text,budget_min numeric(12,2),budget_max numeric(12,2),notes text not null default '',lead_score smallint not null default 0 check(lead_score between 0 and 100),status text not null default 'draft' check(status in('draft','submitted','matching','matched','viewed','quote_received','quote_accepted','contacts_unlocked','job_in_progress','job_completed','cancelled')),max_matches integer not null default 3 check(max_matches between 1 and 5),submitted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lead_matches(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.lead_requests(id) on delete cascade,professional_id uuid not null references public.professional_profiles(id) on delete cascade,match_score numeric(5,2),status text not null default 'invited' check(status in('invited','viewed','declined','quoting','quoted','expired')),decline_reason text,invited_at timestamptz not null default now(),viewed_at timestamptz,responded_at timestamptz,unique(lead_id,professional_id));
create table if not exists public.quotes(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.lead_requests(id) on delete cascade,professional_id uuid not null references public.professional_profiles(id) on delete cascade,price_type text not null,price_min numeric(12,2) not null,price_max numeric(12,2),vat_included boolean not null default true,included_items jsonb not null default '[]'::jsonb,excluded_items jsonb not null default '[]'::jsonb,additional_costs text not null default '',first_availability text,estimated_duration text,valid_until timestamptz,message text not null default '',status text not null default 'draft' check(status in('draft','sent','viewed','accepted','rejected','withdrawn')),sent_at timestamptz,viewed_at timestamptz,accepted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.lead_requests(id) on delete cascade,professional_id uuid not null references public.professional_profiles(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,contacts_unlocked boolean not null default false,created_at timestamptz not null default now(),unique(lead_id,professional_id));
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,sender_id uuid not null references auth.users(id),body text not null,filtered_contact_data boolean not null default false,attachment_paths jsonb not null default '[]'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.contact_unlocks(id uuid primary key default gen_random_uuid(),lead_id uuid not null unique references public.lead_requests(id) on delete cascade,quote_id uuid not null unique references public.quotes(id) on delete cascade,owner_id uuid not null references auth.users(id),professional_id uuid not null references public.professional_profiles(id),unlocked_at timestamptz not null default now());
create table if not exists public.professional_jobs(id uuid primary key default gen_random_uuid(),lead_id uuid not null unique references public.lead_requests(id) on delete cascade,quote_id uuid not null unique references public.quotes(id) on delete cascade,owner_id uuid not null references auth.users(id),professional_id uuid not null references public.professional_profiles(id),status text not null default 'pending' check(status in('pending','appointment_scheduled','waiting_documents','in_progress','waiting_owner','completed','issue_reported','cancelled')),started_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.professional_reviews(id uuid primary key default gen_random_uuid(),job_id uuid not null unique references public.professional_jobs(id) on delete cascade,lead_id uuid not null references public.lead_requests(id),owner_id uuid not null references auth.users(id),professional_id uuid not null references public.professional_profiles(id),clarity smallint not null check(clarity between 1 and 5),communication smallint not null check(communication between 1 and 5),punctuality smallint not null check(punctuality between 1 and 5),quality smallint not null check(quality between 1 and 5),value smallint not null check(value between 1 and 5),comment text not null default '',professional_reply text,is_verified boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.lead_events(id bigint generated always as identity primary key,lead_id uuid not null references public.lead_requests(id) on delete cascade,actor_id uuid references auth.users(id) on delete set null,event_type text not null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
insert into public.professional_categories(id,name,description,availability_status,sort_order) values ('documenti-conformita','Documenti e conformità','Catasto, urbanistica, certificazioni, pratiche comunali e regolarizzazione.','active',10),
('vendita-intermediazione','Vendita e intermediazione','Valutazione, strategia, visite, trattativa e supporto fino alla firma.','limited',20),
('affitto-gestione','Affitto e gestione','Contratti, inquilini, affitti brevi, cauzioni e gestione continuativa.','limited',30),
('legale-notarile-fiscale','Legale, notarile e fiscale','Contratti, successioni, tasse, controversie e atti notarili.','limited',40),
('presentazione-valorizzazione','Presentazione e valorizzazione','Foto, video, home staging, render, annunci e promozione.','active',50),
('lavori-manutenzione','Lavori e manutenzione','Ristrutturazioni, impianti, guasti, efficientamento e spazi esterni.','limited',60),
('pulizia-sgombero-trasloco','Pulizia, sgombero e trasloco','Pulizia, svuotamento, smaltimento, deposito e trasporto.','active',70),
('finanza-assicurazioni-amministrazione','Finanza, assicurazioni e amministrazione','Mutui, polizze, incentivi, condominio, utenze e pratiche economiche.','activating',80) on conflict(id) do update set name=excluded.name,description=excluded.description,availability_status=excluded.availability_status,sort_order=excluded.sort_order,updated_at=now();
insert into public.professional_service_catalog(id,category_id,name,description,availability_status,eligible_professions) values ('verifica-catastale-urbanistica','documenti-conformita','Verifica catastale e urbanistica','Controllo coordinato tra documenti, planimetria e stato reale.','active','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('verifica-planimetria','documenti-conformita','Confronto planimetria e stato reale','Individua differenze tra la planimetria depositata e l’immobile.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('aggiornamento-catastale','documenti-conformita','Aggiornamento catastale','Variazione, rettifica o aggiornamento della situazione catastale.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('sanatoria-regolarizzazione','documenti-conformita','Sanatoria e regolarizzazione','Valutazione e gestione di difformità o modifiche non regolarizzate.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('accesso-atti','documenti-conformita','Accesso agli atti','Ricerca delle pratiche edilizie conservate dal Comune.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('rilievo-planimetria','documenti-conformita','Rilievo e nuova planimetria','Misurazione dell’immobile e produzione di elaborati aggiornati.','limited','["Geometra", "Architetto", "Ingegnere", "Topografo"]'::jsonb),
('frazionamento-fusione','documenti-conformita','Frazionamento o fusione','Pratiche per dividere o unire unità immobiliari.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('cambio-destinazione','documenti-conformita','Cambio di destinazione d’uso','Verifica di fattibilità e gestione della pratica.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('certificazione-energetica','documenti-conformita','Certificazione energetica (APE)','Sopralluogo e rilascio dell’attestato di prestazione energetica.','active','["Certificatore energetico", "Geometra", "Architetto", "Ingegnere"]'::jsonb),
('certificazione-impianti','documenti-conformita','Certificazione degli impianti','Verifica e documentazione di conformità degli impianti.','limited','["Elettricista abilitato", "Idraulico abilitato", "Perito industriale"]'::jsonb),
('agibilita-abitabilita','documenti-conformita','Agibilità e abitabilità','Verifica o predisposizione delle pratiche necessarie.','limited','["Geometra", "Architetto", "Ingegnere"]'::jsonb),
('successione-voltura','documenti-conformita','Successione e voltura catastale','Supporto tecnico e catastale dopo una successione.','limited','["Geometra", "Commercialista", "Notaio"]'::jsonb),
('stima-perizia','documenti-conformita','Stima tecnica e perizia','Valutazione tecnica documentata dell’immobile.','limited','["Perito estimatore", "Geometra", "Architetto", "Ingegnere"]'::jsonb),
('valutazione-immobiliare','vendita-intermediazione','Valutazione immobiliare','Analisi del valore e del posizionamento dell’immobile.','limited','["Agente immobiliare", "Perito estimatore"]'::jsonb),
('vendita-privati','vendita-intermediazione','Vendita tra privati con assistenza','Supporto professionale senza affidare l’intero incarico.','limited','["Consulente immobiliare", "Avvocato immobiliare", "Agente immobiliare"]'::jsonb),
('analisi-mercato','vendita-intermediazione','Analisi comparativa di mercato','Confronto con immobili e transazioni della zona.','limited','["Agente immobiliare", "Perito estimatore"]'::jsonb),
('ricerca-agente','vendita-intermediazione','Ricerca agente immobiliare','Confronto tra professionisti per affidare la vendita.','limited','["Agente immobiliare", "Agenzia immobiliare"]'::jsonb),
('verifica-proposta','vendita-intermediazione','Verifica proposta d’acquisto','Controllo di condizioni e rischi prima della firma.','limited','["Avvocato immobiliare", "Agente immobiliare"]'::jsonb),
('assistenza-trattativa','vendita-intermediazione','Assistenza nella trattativa','Supporto nella negoziazione di prezzo e condizioni.','limited','["Agente immobiliare", "Consulente immobiliare", "Avvocato immobiliare"]'::jsonb),
('organizzazione-visite','vendita-intermediazione','Organizzazione delle visite','Pianificazione, gestione e raccolta dei riscontri.','limited','["Agente immobiliare", "Consulente immobiliare"]'::jsonb),
('supporto-preliminare','vendita-intermediazione','Supporto fino al preliminare','Coordinamento dei passaggi fino al compromesso.','limited','["Agente immobiliare", "Avvocato immobiliare", "Notaio"]'::jsonb),
('vendita-ereditato','vendita-intermediazione','Vendita immobile ereditato','Coordinamento tecnico, fiscale e commerciale.','limited','["Agente immobiliare", "Notaio", "Commercialista", "Avvocato"]'::jsonb),
('vendita-occupato','vendita-intermediazione','Vendita immobile occupato','Strategia per immobili locati o occupati.','limited','["Agente immobiliare", "Avvocato immobiliare"]'::jsonb),
('aste-procedure','vendita-intermediazione','Aste e procedure particolari','Assistenza specialistica in situazioni non ordinarie.','limited','["Consulente aste", "Avvocato immobiliare"]'::jsonb),
('definizione-canone','affitto-gestione','Definizione del canone','Analisi del canone sostenibile e competitivo.','limited','["Agente immobiliare", "Consulente locativo"]'::jsonb),
('contratto-locazione','affitto-gestione','Scelta e preparazione del contratto','Scelta, redazione e registrazione del contratto.','limited','["Avvocato", "Commercialista", "Agente immobiliare"]'::jsonb),
('selezione-inquilino','affitto-gestione','Ricerca e selezione inquilini','Pubblicazione, selezione e verifica dei candidati.','limited','["Agente immobiliare", "Property manager"]'::jsonb),
('verifica-candidato','affitto-gestione','Verifica documentale candidato','Controllo della documentazione e dell’affidabilità.','limited','["Agente immobiliare", "Consulente locativo"]'::jsonb),
('inventario-consegna','affitto-gestione','Inventario e verbale di consegna','Documentazione dello stato dell’immobile e delle dotazioni.','limited','["Property manager", "Agente immobiliare", "Perito"]'::jsonb),
('gestione-affitto','affitto-gestione','Gestione affitto tradizionale','Rapporto con l’inquilino, scadenze e manutenzioni.','limited','["Property manager", "Agente immobiliare"]'::jsonb),
('gestione-affitto-breve','affitto-gestione','Gestione affitti brevi','Annunci, ospiti, check-in, pulizie e rendicontazione.','limited','["Property manager", "Gestore affitti brevi"]'::jsonb),
('checkin-checkout','affitto-gestione','Check-in e check-out','Accoglienza, verifica e riconsegna dell’immobile.','limited','["Property manager", "Servizio di accoglienza"]'::jsonb),
('gestione-morosita','affitto-gestione','Gestione morosità','Supporto operativo e legale per mancati pagamenti.','limited','["Avvocato", "Property manager"]'::jsonb),
('chiusura-contratto','affitto-gestione','Chiusura contratto e riconsegna','Verbale finale, cauzione e adempimenti conclusivi.','limited','["Avvocato", "Agente immobiliare", "Property manager"]'::jsonb),
('consulenza-legale','legale-notarile-fiscale','Consulenza legale immobiliare','Analisi della situazione e delle possibili soluzioni.','limited','["Avvocato immobiliare"]'::jsonb),
('controllo-preliminare','legale-notarile-fiscale','Controllo del preliminare','Revisione del compromesso prima della firma.','limited','["Avvocato immobiliare", "Notaio"]'::jsonb),
('redazione-contratti','legale-notarile-fiscale','Redazione o revisione contratti','Supporto per accordi di vendita, affitto o gestione.','limited','["Avvocato", "Notaio"]'::jsonb),
('assistenza-notarile','legale-notarile-fiscale','Assistenza notarile','Preventivo e gestione degli atti necessari.','limited','["Notaio"]'::jsonb),
('successioni-donazioni','legale-notarile-fiscale','Successioni e donazioni','Coordinamento notarile, fiscale e documentale.','limited','["Notaio", "Avvocato", "Commercialista"]'::jsonb),
('divisioni-comproprieta','legale-notarile-fiscale','Divisioni e comproprietà','Accordi e gestione di beni condivisi.','limited','["Avvocato", "Notaio", "Mediatore civile"]'::jsonb),
('usufrutto-nuda-proprieta','legale-notarile-fiscale','Usufrutto e nuda proprietà','Valutazione e formalizzazione dei diritti immobiliari.','limited','["Notaio", "Avvocato", "Commercialista"]'::jsonb),
('sfratti-recupero','legale-notarile-fiscale','Sfratti e recupero crediti','Assistenza per morosità e rilascio dell’immobile.','limited','["Avvocato"]'::jsonb),
('controversie-condominiali','legale-notarile-fiscale','Controversie condominiali','Consulenza, negoziazione e mediazione.','limited','["Avvocato", "Mediatore civile"]'::jsonb),
('tassazione-vendita','legale-notarile-fiscale','Tassazione della vendita','Imposte, plusvalenza e dichiarazioni.','limited','["Commercialista", "Consulente fiscale"]'::jsonb),
('tassazione-affitti','legale-notarile-fiscale','Tassazione degli affitti','Cedolare secca, regime ordinario e adempimenti.','limited','["Commercialista", "Consulente fiscale"]'::jsonb),
('bonus-agevolazioni','legale-notarile-fiscale','Bonus e agevolazioni','Verifica dei requisiti e gestione documentale.','limited','["Commercialista", "Consulente fiscale", "Tecnico"]'::jsonb),
('mediazione-civile','legale-notarile-fiscale','Mediazione civile','Tentativo di accordo assistito prima del contenzioso.','limited','["Mediatore civile", "Avvocato"]'::jsonb),
('fotografia-immobiliare','presentazione-valorizzazione','Fotografia immobiliare','Servizio fotografico professionale per vendita o affitto.','active','["Fotografo immobiliare"]'::jsonb),
('video-immobiliare','presentazione-valorizzazione','Video professionale','Video di presentazione dell’immobile.','limited','["Videomaker immobiliare"]'::jsonb),
('riprese-drone','presentazione-valorizzazione','Riprese con drone','Foto e video aerei realizzati da operatori abilitati.','limited','["Operatore drone", "Videomaker"]'::jsonb),
('virtual-tour','presentazione-valorizzazione','Virtual tour','Visita immersiva e navigabile dell’immobile.','limited','["Fotografo 360", "Tecnico virtual tour"]'::jsonb),
('planimetria-arredata','presentazione-valorizzazione','Planimetria arredata','Rappresentazione chiara e accattivante degli spazi.','limited','["Render artist", "Interior designer", "Geometra"]'::jsonb),
('render-3d','presentazione-valorizzazione','Render 3D','Visualizzazione realistica di ambienti o progetti.','limited','["Render artist", "Architetto", "Interior designer"]'::jsonb),
('home-staging','presentazione-valorizzazione','Home staging','Preparazione fisica degli ambienti per valorizzarli.','limited','["Home stager", "Interior designer"]'::jsonb),
('home-staging-virtuale','presentazione-valorizzazione','Home staging virtuale','Arredo digitale applicato alle fotografie.','limited','["Home stager virtuale", "Render artist"]'::jsonb),
('scrittura-annuncio','presentazione-valorizzazione','Scrittura o revisione annuncio','Testo chiaro e persuasivo per portali e social.','limited','["Copywriter immobiliare", "Agente immobiliare"]'::jsonb),
('traduzione-annuncio','presentazione-valorizzazione','Traduzione annuncio','Adattamento professionale per clienti internazionali.','limited','["Traduttore"]'::jsonb),
('pubblicazione-portali','presentazione-valorizzazione','Pubblicazione e promozione','Gestione della pubblicazione sui canali selezionati.','limited','["Consulente marketing immobiliare", "Agente immobiliare"]'::jsonb),
('brochure-materiali','presentazione-valorizzazione','Brochure e materiali promozionali','Materiali digitali o stampabili per visite e presentazioni.','limited','["Graphic designer", "Copywriter", "Fotografo"]'::jsonb),
('ristrutturazione-completa','lavori-manutenzione','Ristrutturazione completa','Coordinamento e realizzazione di un intervento complessivo.','limited','["Impresa edile", "Architetto", "Geometra"]'::jsonb),
('piccoli-lavori-edili','lavori-manutenzione','Piccoli lavori edili','Riparazioni, muratura e interventi localizzati.','limited','["Impresa edile", "Muratore"]'::jsonb),
('tinteggiatura','lavori-manutenzione','Tinteggiatura','Preparazione e pittura di pareti e soffitti.','limited','["Imbianchino"]'::jsonb),
('impianto-elettrico','lavori-manutenzione','Impianto elettrico','Riparazione, adeguamento o nuova installazione.','limited','["Elettricista abilitato"]'::jsonb),
('impianto-idraulico','lavori-manutenzione','Impianto idraulico','Riparazione, adeguamento o nuova installazione.','limited','["Idraulico abilitato"]'::jsonb),
('climatizzazione-caldaie','lavori-manutenzione','Climatizzazione e caldaie','Installazione, manutenzione e certificazione.','limited','["Termotecnico", "Installatore abilitato"]'::jsonb),
('serramenti-infissi','lavori-manutenzione','Serramenti e infissi','Riparazione o sostituzione di finestre, porte e chiusure.','limited','["Serramentista", "Falegname", "Fabbro"]'::jsonb),
('pavimenti-piastrelle','lavori-manutenzione','Pavimenti e piastrelle','Posa, riparazione o sostituzione.','limited','["Piastrellista", "Impresa edile"]'::jsonb),
('isolamento-impermeabilizzazione','lavori-manutenzione','Isolamento e impermeabilizzazione','Soluzioni per dispersioni, infiltrazioni e coperture.','limited','["Impresa specializzata", "Termotecnico"]'::jsonb),
('muffa-umidita','lavori-manutenzione','Muffa e umidità','Diagnosi della causa e intervento risolutivo.','limited','["Tecnico", "Impresa specializzata"]'::jsonb),
('fotovoltaico-efficienza','lavori-manutenzione','Fotovoltaico ed efficientamento','Valutazione e installazione di soluzioni energetiche.','limited','["Installatore fotovoltaico", "Consulente energetico", "Ingegnere"]'::jsonb),
('giardini-esterni','lavori-manutenzione','Giardini e spazi esterni','Manutenzione, sistemazione e valorizzazione.','limited','["Giardiniere", "Paesaggista", "Impresa"]'::jsonb),
('sistemi-sicurezza','lavori-manutenzione','Sistemi di sicurezza','Allarmi, videosorveglianza e controllo accessi.','limited','["Installatore sistemi di sicurezza"]'::jsonb),
('disinfestazione','lavori-manutenzione','Disinfestazione','Interventi contro infestanti e parassiti.','limited','["Impresa di disinfestazione"]'::jsonb),
('pulizia-fotografie','pulizia-sgombero-trasloco','Pulizia prima delle fotografie','Preparazione accurata prima del servizio fotografico.','active','["Impresa di pulizie"]'::jsonb),
('pulizia-consegna','pulizia-sgombero-trasloco','Pulizia prima della consegna','Pulizia finale per vendita, affitto o riconsegna.','active','["Impresa di pulizie"]'::jsonb),
('pulizia-profonda','pulizia-sgombero-trasloco','Pulizia profonda','Intervento intensivo su tutto l’immobile.','active','["Impresa di pulizie"]'::jsonb),
('pulizia-post-cantiere','pulizia-sgombero-trasloco','Pulizia post-ristrutturazione','Rimozione di polveri e residui dopo i lavori.','limited','["Impresa di pulizie"]'::jsonb),
('sanificazione','pulizia-sgombero-trasloco','Sanificazione','Trattamento specifico degli ambienti.','limited','["Impresa specializzata"]'::jsonb),
('sgombero-immobile','pulizia-sgombero-trasloco','Sgombero immobile','Svuotamento completo o parziale.','limited','["Ditta di sgombero"]'::jsonb),
('smaltimento-mobili','pulizia-sgombero-trasloco','Smaltimento mobili e ingombranti','Ritiro e gestione autorizzata dei materiali.','limited','["Ditta di smaltimento", "Ditta di sgombero"]'::jsonb),
('trasloco','pulizia-sgombero-trasloco','Trasloco','Imballaggio, trasporto e rimontaggio.','limited','["Ditta di traslochi"]'::jsonb),
('deposito-temporaneo','pulizia-sgombero-trasloco','Deposito temporaneo','Custodia di mobili e oggetti per il tempo necessario.','limited','["Deposito", "Ditta di traslochi"]'::jsonb),
('cantine-garage','pulizia-sgombero-trasloco','Svuotamento cantine e garage','Sgombero di spazi accessori e pertinenze.','limited','["Ditta di sgombero"]'::jsonb),
('custodia-chiavi','pulizia-sgombero-trasloco','Custodia delle chiavi','Gestione sicura dell’accesso per visite e interventi.','limited','["Property manager", "Servizio di custodia"]'::jsonb),
('consulenza-mutuo','finanza-assicurazioni-amministrazione','Consulenza mutuo','Analisi delle possibilità e confronto delle soluzioni.','activating','["Mediatore creditizio", "Consulente del credito"]'::jsonb),
('surroga-estinzione','finanza-assicurazioni-amministrazione','Surroga o estinzione','Valutazione e gestione delle alternative sul mutuo.','activating','["Mediatore creditizio", "Consulente bancario"]'::jsonb),
('cancellazione-ipoteca','finanza-assicurazioni-amministrazione','Cancellazione ipoteca','Verifica e gestione degli adempimenti necessari.','activating','["Notaio", "Consulente del credito"]'::jsonb),
('finanziamento-ristrutturazione','finanza-assicurazioni-amministrazione','Finanziamento ristrutturazione','Ricerca della soluzione finanziaria per i lavori.','activating','["Mediatore creditizio", "Consulente del credito"]'::jsonb),
('assicurazione-immobile','finanza-assicurazioni-amministrazione','Assicurazione immobile','Confronto delle coperture per fabbricato e responsabilità.','activating','["Broker assicurativo", "Agente assicurativo"]'::jsonb),
('assicurazione-canone','finanza-assicurazioni-amministrazione','Assicurazione sul canone','Copertura contro morosità e spese legali.','activating','["Broker assicurativo", "Agente assicurativo"]'::jsonb),
('gestione-sinistro','finanza-assicurazioni-amministrazione','Gestione danni e sinistri','Supporto nella documentazione e nella liquidazione.','activating','["Perito assicurativo", "Broker assicurativo"]'::jsonb),
('bonus-incentivi','finanza-assicurazioni-amministrazione','Bonus e incentivi','Analisi dei requisiti e coordinamento delle pratiche.','activating','["Commercialista", "Consulente energetico", "Tecnico"]'::jsonb),
('amministrazione-condominiale','finanza-assicurazioni-amministrazione','Amministrazione condominiale','Ricerca o supporto nella gestione del condominio.','activating','["Amministratore di condominio"]'::jsonb),
('spese-condominiali','finanza-assicurazioni-amministrazione','Verifica spese condominiali','Analisi di bilanci, riparti e situazioni debitorie.','activating','["Amministratore", "Commercialista", "Avvocato"]'::jsonb),
('volture-utenze','finanza-assicurazioni-amministrazione','Volture e utenze','Attivazione, voltura o chiusura delle forniture.','activating','["Consulente amministrativo", "Servizio utenze"]'::jsonb) on conflict(id) do update set category_id=excluded.category_id,name=excluded.name,description=excluded.description,availability_status=excluded.availability_status,eligible_professions=excluded.eligible_professions,updated_at=now();

create or replace function public.accept_professional_quote(p_quote_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_quote public.quotes; v_lead public.lead_requests;
begin
  select * into v_quote from public.quotes where id=p_quote_id for update;
  if v_quote.id is null then raise exception 'Quote not found'; end if;
  select * into v_lead from public.lead_requests where id=v_quote.lead_id for update;
  if v_lead.owner_id<>auth.uid() then raise exception 'Not authorized'; end if;
  update public.quotes set status=case when id=p_quote_id then 'accepted' else 'rejected' end,accepted_at=case when id=p_quote_id then now() else accepted_at end where lead_id=v_quote.lead_id and status in('sent','viewed','accepted');
  update public.lead_requests set status='contacts_unlocked',updated_at=now() where id=v_quote.lead_id;
  insert into public.contact_unlocks(lead_id,quote_id,owner_id,professional_id) values(v_quote.lead_id,v_quote.id,v_lead.owner_id,v_quote.professional_id) on conflict(lead_id) do nothing;
  insert into public.professional_jobs(lead_id,quote_id,owner_id,professional_id) values(v_quote.lead_id,v_quote.id,v_lead.owner_id,v_quote.professional_id) on conflict(lead_id) do nothing;
  insert into public.lead_events(lead_id,actor_id,event_type,payload) values(v_quote.lead_id,auth.uid(),'quote_accepted',jsonb_build_object('quote_id',v_quote.id));
end; $$;

alter table public.professional_categories enable row level security; alter table public.professional_service_catalog enable row level security; alter table public.professional_profiles enable row level security; alter table public.professional_profile_services enable row level security; alter table public.professional_service_areas enable row level security; alter table public.professional_verifications enable row level security; alter table public.lead_requests enable row level security; alter table public.lead_matches enable row level security; alter table public.quotes enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.contact_unlocks enable row level security; alter table public.professional_jobs enable row level security; alter table public.professional_reviews enable row level security; alter table public.lead_events enable row level security;
drop policy if exists catalog_read on public.professional_categories; create policy catalog_read on public.professional_categories for select to authenticated using(is_enabled=true);
drop policy if exists services_read on public.professional_service_catalog; create policy services_read on public.professional_service_catalog for select to authenticated using(is_enabled=true);
drop policy if exists lead_owner_all on public.lead_requests; create policy lead_owner_all on public.lead_requests for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists lead_matched_read on public.lead_requests; create policy lead_matched_read on public.lead_requests for select to authenticated using(exists(select 1 from public.lead_matches lm join public.professional_profiles pp on pp.id=lm.professional_id where lm.lead_id=lead_requests.id and pp.user_id=auth.uid()));
drop policy if exists quote_owner_read on public.quotes; create policy quote_owner_read on public.quotes for select to authenticated using(exists(select 1 from public.lead_requests lr where lr.id=quotes.lead_id and lr.owner_id=auth.uid()));
drop policy if exists quote_professional_all on public.quotes; create policy quote_professional_all on public.quotes for all to authenticated using(exists(select 1 from public.professional_profiles pp where pp.id=quotes.professional_id and pp.user_id=auth.uid())) with check(exists(select 1 from public.professional_profiles pp where pp.id=quotes.professional_id and pp.user_id=auth.uid()));
drop policy if exists reviews_read on public.professional_reviews; create policy reviews_read on public.professional_reviews for select to authenticated using(is_verified=true);
-- Matching automatico, moderazione e analytics aggregate devono usare funzioni server-side; non esporre mai la service role nel browser.
