-- GUIMMIA V76.8 - SALE OPERATIONS & CLOSING LIFECYCLE ENGINE
-- Additive schema. Requires V76.7 installed and verified.
do $$ begin
 if to_regclass('public.guimmia_brain_cases') is null then raise exception 'V76.7 brain cases missing'; end if;
 if to_regclass('public.guimmia_brain_rules') is null then raise exception 'V76.7 brain rules missing'; end if;
 if to_regclass('public.guimmia_brain_technical_snapshots') is null then raise exception 'V76.7 technical snapshots missing'; end if;
 if to_regclass('public.guimmia_transaction_gate_states') is null then raise exception 'V76.7 transaction gates missing'; end if;
 if to_regclass('public.guimmia_case_transaction_profiles') is null then raise exception 'V76.7 transaction routing missing'; end if;
 if to_regprocedure('public.guimmia_set_updated_at()') is null then raise exception 'V76.7 updated_at function missing'; end if;
end $$;
create table if not exists public.guimmia_sale_encumbrance_reviews(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'PENDING',findings jsonb not null default '[]'::jsonb,input_fingerprint text,review_actor_type text check(review_actor_type is null or review_actor_type='PROFESSIONAL'),reviewer_role text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_condominium_reviews(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'PENDING',certificate_ref text,debts jsonb not null default '[]'::jsonb,extraordinary_works jsonb not null default '[]'::jsonb,input_fingerprint text,review_actor_type text check(review_actor_type is null or review_actor_type='PROFESSIONAL'),reviewer_role text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_tax_reviews(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'PENDING',scenarios jsonb not null default '[]'::jsonb,input_fingerprint text,review_actor_type text check(review_actor_type is null or review_actor_type='PROFESSIONAL'),reviewer_role text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_phase05_snapshots(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,technical_snapshot_id uuid not null references public.guimmia_brain_technical_snapshots(id),readiness text not null check(readiness in('READY','REVIEW_REQUIRED','BLOCKED')),snapshot jsonb not null default '{}'::jsonb,input_fingerprint text not null,rules_fingerprint text not null,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_valuation_cases(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'DRAFT',purpose text,method text,min_value numeric(14,2),max_value numeric(14,2),asking_price numeric(14,2),input_fingerprint text,approval_actor_type text check(approval_actor_type is null or approval_actor_type in('HUMAN','PROFESSIONAL')),approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_comparables(id uuid primary key default gen_random_uuid(),valuation_id uuid not null references public.guimmia_sale_valuation_cases(id) on delete cascade,source_ref text,observed_at timestamptz,price numeric(14,2),facts jsonb not null default '{}'::jsonb,evidence jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_valuation_adjustments(id uuid primary key default gen_random_uuid(),valuation_id uuid not null references public.guimmia_sale_valuation_cases(id) on delete cascade,comparable_id uuid references public.guimmia_sale_comparables(id) on delete cascade,adjustment_code text not null,amount numeric(14,2),rationale text,evidence jsonb not null default '[]'::jsonb,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_valuation_snapshots(id uuid primary key default gen_random_uuid(),valuation_id uuid not null references public.guimmia_sale_valuation_cases(id) on delete cascade,case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'DRAFT',snapshot jsonb not null default '{}'::jsonb,input_fingerprint text not null,approval_actor_type text check(approval_actor_type is null or approval_actor_type in('HUMAN','PROFESSIONAL')),approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_listings(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,valuation_snapshot_id uuid references public.guimmia_sale_valuation_snapshots(id),status text not null default 'DRAFT' check(status in('DRAFT','IN_REVIEW','READY','PUBLISHED','PAUSED','ARCHIVED')),asking_price numeric(14,2),master_content jsonb not null default '{}'::jsonb,facts_fingerprint text,approval_actor_type text check(approval_actor_type is null or approval_actor_type='HUMAN'),approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_publication_events(id bigserial primary key,listing_id uuid not null references public.guimmia_sale_listings(id) on delete cascade,channel_code text not null,event_type text not null,actor_type text not null,actor_id uuid,idempotency_key text not null unique,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_leads(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,listing_id uuid references public.guimmia_sale_listings(id) on delete set null,status text not null default 'NEW',contact_fingerprint text,consent_status text not null default 'MISSING',retention_until timestamptz,assigned_to uuid,idempotency_key text not null unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_visits(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,lead_id uuid not null references public.guimmia_sale_leads(id) on delete cascade,status text not null default 'PLANNED',starts_at timestamptz,ends_at timestamptz,privacy_status text not null default 'PENDING',access_authorized boolean not null default false,feedback jsonb not null default '{}'::jsonb,assigned_to uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_negotiation_events(id bigserial primary key,case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,lead_id uuid references public.guimmia_sale_leads(id) on delete set null,event_type text not null,actor_type text not null,actor_id uuid,idempotency_key text not null unique,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_offers(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,lead_id uuid references public.guimmia_sale_leads(id) on delete set null,status text not null default 'DRAFT' check(status in('DRAFT','REVIEWED','SUBMITTED','ACCEPTED','REJECTED','EXPIRED','WITHDRAWN')),price numeric(14,2),terms jsonb not null default '{}'::jsonb,content_hash text,expires_at timestamptz,review_actor_type text check(review_actor_type is null or review_actor_type='HUMAN'),reviewed_by uuid,decision_actor_type text check(decision_actor_type is null or decision_actor_type='HUMAN'),decided_by uuid,decided_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guimmia_sale_offer_events(id bigserial primary key,offer_id uuid not null references public.guimmia_sale_offers(id) on delete cascade,event_type text not null,actor_type text not null,actor_id uuid,idempotency_key text not null unique,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_preliminary_tasks(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,offer_id uuid references public.guimmia_sale_offers(id) on delete set null,task_code text not null,status text not null default 'PENDING',professional_required boolean not null default false,review_actor_type text check(review_actor_type is null or review_actor_type in('HUMAN','PROFESSIONAL')),reviewer_role text,reviewed_by uuid,due_at timestamptz,evidence jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(case_id,task_code));
create table if not exists public.guimmia_sale_closing_tasks(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,task_code text not null,status text not null default 'PENDING',notary_ref text,due_at timestamptz,evidence jsonb not null default '[]'::jsonb,completion_actor_type text check(completion_actor_type is null or completion_actor_type in('HUMAN','PROFESSIONAL')),completed_by uuid,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(case_id,task_code));
create table if not exists public.guimmia_sale_closing_events(id bigserial primary key,case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,event_type text not null,actor_type text not null,actor_id uuid,idempotency_key text not null unique,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.guimmia_sale_archive_records(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,status text not null default 'OPEN',audit_complete boolean not null default false,retention_plan jsonb not null default '{}'::jsonb,final_documents jsonb not null default '[]'::jsonb,closure_actor_type text check(closure_actor_type is null or closure_actor_type='HUMAN'),closed_by uuid,closed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(case_id));
create table if not exists public.guimmia_sale_operational_tasks(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.guimmia_brain_cases(id) on delete cascade,phase_code text not null,task_code text not null,status text not null default 'PENDING',priority text not null default 'NORMAL',due_at timestamptz,assigned_to uuid,evidence jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(case_id,task_code));
create index if not exists idx_guimmia_sale_listing_case_status on public.guimmia_sale_listings(case_id,status);create index if not exists idx_guimmia_sale_leads_case_status on public.guimmia_sale_leads(case_id,status);create index if not exists idx_guimmia_sale_visits_time on public.guimmia_sale_visits(case_id,starts_at);create index if not exists idx_guimmia_sale_tasks_due on public.guimmia_sale_operational_tasks(status,priority,due_at);
do $$ declare t text; begin foreach t in array array['guimmia_sale_encumbrance_reviews','guimmia_sale_condominium_reviews','guimmia_sale_tax_reviews','guimmia_sale_valuation_cases','guimmia_sale_listings','guimmia_sale_leads','guimmia_sale_visits','guimmia_sale_offers','guimmia_sale_preliminary_tasks','guimmia_sale_closing_tasks','guimmia_sale_archive_records','guimmia_sale_operational_tasks'] loop execute format('drop trigger if exists %I on public.%I','trg_'||t||'_updated_at',t);execute format('create trigger %I before update on public.%I for each row execute function public.guimmia_set_updated_at()','trg_'||t||'_updated_at',t);end loop;end $$;
do $$ declare t text; begin foreach t in array array['guimmia_sale_encumbrance_reviews','guimmia_sale_condominium_reviews','guimmia_sale_tax_reviews','guimmia_sale_phase05_snapshots','guimmia_sale_valuation_cases','guimmia_sale_comparables','guimmia_sale_valuation_adjustments','guimmia_sale_valuation_snapshots','guimmia_sale_listings','guimmia_sale_publication_events','guimmia_sale_leads','guimmia_sale_visits','guimmia_sale_negotiation_events','guimmia_sale_offers','guimmia_sale_offer_events','guimmia_sale_preliminary_tasks','guimmia_sale_closing_tasks','guimmia_sale_closing_events','guimmia_sale_archive_records','guimmia_sale_operational_tasks'] loop execute format('alter table public.%I enable row level security',t);end loop;end $$;
