-- Seed catalogo regole P01/P02. Runtime authoritative implementation is mirrored in TypeScript.
with wf as (select id from public.guimmia_brain_workflows where slug='sale-private-apartment' and version=2),
steps as (select id, phase_code from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf))
insert into public.guimmia_brain_rules(code,workflow_id,step_id,module,phase_code,title,description,stability,decision_level,severity,condition_definition,outcome_definition,source_refs,freshness_policy,evidence_policy,version,active)
select 'P01_IDENTITY_NOT_COLLECTED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Identità cliente incompleta','Identità cliente incompleta','INTERNAL','REVIEW','blocking','{"op":"neq","path":"client.identityStatus","value":"COLLECTED"}'::jsonb,'{"code":"IDENTITY_REQUIRED","message":"Completare i dati identificativi.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_IDENTITY_DOCUMENT_EXPIRED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Documento identificativo scaduto','Documento identificativo scaduto','INTERNAL','REVIEW','blocking','{"op":"eq","path":"client.identityDocumentStatus","value":"EXPIRED"}'::jsonb,'{"code":"IDENTITY_DOCUMENT_REFRESH","message":"Richiedere un documento valido o applicare procedura approvata.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_CAPACITY_SPECIAL_CASE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Capacità di agire / rappresentanza speciale','Capacità di agire / rappresentanza speciale','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"in","path":"client.capacityCase","values":["MINOR","SUPPORT_ADMINISTRATION","GUARDIANSHIP","INCAPACITY_OTHER"]}'::jsonb,'{"code":"CAPACITY_PROFESSIONAL_REVIEW","message":"Verificare poteri e autorizzazioni.","blockProgress":true,"escalationTo":"LAWYER"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_REPRESENTATIVE_AUTHORITY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Potere di rappresentanza non verificato','Potere di rappresentanza non verificato','STABLE','AGENT_REQUIRED','blocking','{"op":"all","conditions":[{"op":"eq","path":"client.relationshipToProperty","value":"REPRESENTATIVE"},{"op":"neq","path":"client.authorityStatus","value":"VERIFIED"}]}'::jsonb,'{"code":"AUTHORITY_REVIEW_REQUIRED","message":"Verificare procura o titolo rappresentativo.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_COOWNERSHIP_DECLARED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Comproprietà dichiarata','Comproprietà dichiarata','STABLE','REVIEW','warning','{"op":"eq","path":"property.ownershipClaim","value":"COOWNERSHIP"}'::jsonb,'{"code":"COOWNERSHIP_ROUTE","message":"Raccogliere titolari e quote dichiarate."}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_EXISTING_MANDATE_UNKNOWN_OR_YES',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Possibile incarico preesistente','Possibile incarico preesistente','INTERNAL','AGENT_REQUIRED','blocking','{"op":"in","path":"sale.existingAgencyMandate","values":["YES","UNKNOWN"]}'::jsonb,'{"code":"EXISTING_MANDATE_CHECK","message":"Acquisire e verificare incarico precedente.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_COMPLIANCE_RULESET',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'PRO_COMPLIANCE','PHASE_01_CLIENT_MANDATE','Compliance professionale','Compliance professionale','DYNAMIC','REVIEW','blocking','{"op":"neq","path":"compliance.status","value":"PASSED"}'::jsonb,'{"code":"COMPLIANCE_GATE","message":"Eseguire compliance con ruleset corrente.","blockProgress":true}'::jsonb,'[]'::jsonb,'{"required":true,"maxAgeDays":90,"rulesetKey":"ITALY_AGENCY_COMPLIANCE"}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_SERVICE_PLAN_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Piano servizio mancante','Piano servizio mancante','INTERNAL','REVIEW','blocking','{"op":"not","condition":{"op":"exists","path":"service.plan"}}'::jsonb,'{"code":"SERVICE_SELECTION_REQUIRED","message":"Selezionare piano e pricing version.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_PRICING_VERSION_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Versione tariffaria mancante','Versione tariffaria mancante','INTERNAL','AUTO','blocking','{"op":"not","condition":{"op":"exists","path":"service.pricingVersion"}}'::jsonb,'{"code":"PRICING_VERSION_REQUIRED","message":"Associare una versione tariffaria immutabile.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_CONTRACT_TEMPLATE_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Template contrattuale mancante','Template contrattuale mancante','INTERNAL','AGENT_REQUIRED','blocking','{"op":"not","condition":{"op":"exists","path":"mandate.templateVersion"}}'::jsonb,'{"code":"CONTRACT_TEMPLATE_REQUIRED","message":"Selezionare template approvato/versionato.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_DISTANCE_CONTRACT_HANDLING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'PRO_COMPLIANCE','PHASE_01_CLIENT_MANDATE','Gestione contratto a distanza','Gestione contratto a distanza','DYNAMIC','AGENT_REQUIRED','blocking','{"op":"all","conditions":[{"op":"eq","path":"mandate.channel","value":"ONLINE"},{"op":"neq","path":"mandate.consumerDistanceHandling","value":"PASSED"}]}'::jsonb,'{"code":"DISTANCE_CONTRACT_GATE","message":"Completare adempimenti online correnti.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{"required":true,"maxAgeDays":90,"rulesetKey":"ITALY_DISTANCE_CONTRACTS"}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_MANDATE_UNSIGNED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Mandato non sottoscritto','Mandato non sottoscritto','INTERNAL','REVIEW','blocking','{"op":"neq","path":"mandate.status","value":"SIGNED"}'::jsonb,'{"code":"MANDATE_SIGNATURE_REQUIRED","message":"Completare sottoscrizione.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_AUDIT_TRAIL_INCOMPLETE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'PRO_COMPLIANCE','PHASE_01_CLIENT_MANDATE','Audit trail contrattuale incompleto','Audit trail contrattuale incompleto','INTERNAL','AUTO','blocking','{"op":"all","conditions":[{"op":"eq","path":"mandate.status","value":"SIGNED"},{"op":"neq","path":"mandate.auditStatus","value":"COMPLETE"}]}'::jsonb,'{"code":"CONTRACT_AUDIT_REQUIRED","message":"Persistenza audit incompleta.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P01_PAYMENT_PENDING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P01'),'CLIENT_MANDATE','PHASE_01_CLIENT_MANDATE','Pagamento attivazione pendente','Pagamento attivazione pendente','INTERNAL','AUTO','blocking','{"op":"all","conditions":[{"op":"eq","path":"payment.requiredForActivation","value":true},{"op":"neq","path":"payment.status","value":"PAID"}]}'::jsonb,'{"code":"PAYMENT_GATE","message":"Attendere pagamento richiesto.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_TITLE_DOCUMENT_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Titolo di provenienza mancante','Titolo di provenienza mancante','INTERNAL','REVIEW','blocking','{"op":"neq","path":"ownership.titleDocumentStatus","value":"ACQUIRED"}'::jsonb,'{"code":"TITLE_DOCUMENT_REQUIRED","message":"Acquisire titolo di provenienza.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_HOLDERS_NOT_RECONCILED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Titolari non riconciliati','Titolari non riconciliati','INTERNAL','AGENT_REQUIRED','blocking','{"op":"neq","path":"ownership.holdersStatus","value":"RECONCILED"}'::jsonb,'{"code":"HOLDERS_RECONCILIATION_REQUIRED","message":"Riconciliare titolari, quote e diritti.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_MULTIPLE_HOLDERS_INCOMPLETE',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Comproprietari incompleti','Comproprietari incompleti','STABLE','REVIEW','blocking','{"op":"all","conditions":[{"op":"eq","path":"ownership.multipleHolders","value":true},{"op":"neq","path":"ownership.allHoldersIdentified","value":true}]}'::jsonb,'{"code":"ALL_HOLDERS_REQUIRED","message":"Completare elenco titolari.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_MARITAL_REGIME_UNKNOWN',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Regime patrimoniale da chiarire','Regime patrimoniale da chiarire','STABLE','AGENT_REQUIRED','warning','{"op":"eq","path":"ownership.maritalRegimeRelevance","value":"UNKNOWN"}'::jsonb,'{"code":"MARITAL_REGIME_REVIEW","message":"Chiarire regime patrimoniale.","escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_SPOUSAL_RIGHTS_UNRESOLVED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Rilevanza del coniuge non risolta','Rilevanza del coniuge non risolta','STABLE','AGENT_REQUIRED','blocking','{"op":"eq","path":"ownership.spousalRightsStatus","value":"UNRESOLVED"}'::jsonb,'{"code":"SPOUSAL_RIGHTS_REVIEW","message":"Verificare soggetti necessari.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_USUFRUCT_OR_NAKED_OWNERSHIP',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Usufrutto / nuda proprietà','Usufrutto / nuda proprietà','STABLE','AGENT_REQUIRED','blocking','{"op":"in","path":"ownership.rightType","values":["USUFRUCT","NAKED_OWNERSHIP","MIXED_USUFRUCT_NAKED"]}'::jsonb,'{"code":"REAL_RIGHT_SPLIT_REVIEW","message":"Identificare titolari e oggetto operazione.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_SURFACE_OR_OTHER_REAL_RIGHT',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Diritto reale particolare','Diritto reale particolare','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"in","path":"ownership.rightType","values":["SURFACE","EMPHYTEUSIS","USE","HABITATION","OTHER_REAL_RIGHT"]}'::jsonb,'{"code":"SPECIAL_REAL_RIGHT_REVIEW","message":"Instradare a verifica professionale.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_SUCCESSION_PENDING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Successione non risolta','Successione non risolta','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"all","conditions":[{"op":"eq","path":"ownership.originType","value":"SUCCESSION"},{"op":"neq","path":"ownership.successionStatus","value":"RESOLVED"}]}'::jsonb,'{"code":"SUCCESSION_REVIEW_REQUIRED","message":"Acquisire documenti e verificare con professionista.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_FOREIGN_SUCCESSION',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Successione estera','Successione estera','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"eq","path":"ownership.foreignSuccession","value":true}'::jsonb,'{"code":"FOREIGN_SUCCESSION_ESCALATION","message":"Verifica notarile/legale richiesta.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_DONATION_ORIGIN',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Provenienza da donazione','Provenienza da donazione','STABLE','PROFESSIONAL_REQUIRED','warning','{"op":"eq","path":"ownership.originType","value":"DONATION"}'::jsonb,'{"code":"DONATION_PROVENANCE_REVIEW","message":"Raccogliere atto e richiedere verifica notarile del caso.","escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_USUCAPION_ASSERTED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Usucapione dichiarata','Usucapione dichiarata','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"eq","path":"ownership.originType","value":"USUCAPION"}'::jsonb,'{"code":"USUCAPION_PROFESSIONAL_REVIEW","message":"Acquisire titolo/accertamento e verificare.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_POWER_OF_ATTORNEY_UNRESOLVED',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Procura non risolta','Procura non risolta','STABLE','AGENT_REQUIRED','blocking','{"op":"all","conditions":[{"op":"eq","path":"ownership.representationUsed","value":true},{"op":"neq","path":"ownership.powerOfAttorneyStatus","value":"VERIFIED"}]}'::jsonb,'{"code":"POWER_OF_ATTORNEY_REVIEW","message":"Verificare procura e poteri.","blockProgress":true,"escalationTo":"AGENT"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_COMPANY_SELLER_AUTHORITY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'COMPANIES_COMPLEX','PHASE_02_OWNERSHIP_TITLE','Poteri società non verificati','Poteri società non verificati','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"all","conditions":[{"op":"eq","path":"client.type","value":"LEGAL_ENTITY"},{"op":"neq","path":"ownership.companyAuthorityStatus","value":"VERIFIED"}]}'::jsonb,'{"code":"COMPANY_AUTHORITY_REVIEW","message":"Verificare poteri rappresentativi.","blockProgress":true,"escalationTo":"LAWYER"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_MINOR_OR_PROTECTED_HOLDER',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Titolare protetto','Titolare protetto','STABLE','PROFESSIONAL_REQUIRED','critical','{"op":"eq","path":"ownership.protectedHolderPresent","value":true}'::jsonb,'{"code":"PROTECTED_HOLDER_ESCALATION","message":"Bloccare e verificare poteri/autorizzazioni.","blockProgress":true,"escalationTo":"LAWYER"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_HEREDITARY_SHARE_ONLY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Oggetto vendita non standard','Oggetto vendita non standard','STABLE','PROFESSIONAL_REQUIRED','blocking','{"op":"in","path":"sale.object","values":["HEREDITARY_SHARE","COOWNERSHIP_SHARE","RIGHT_ONLY"]}'::jsonb,'{"code":"NON_STANDARD_SALE_OBJECT","message":"Instradare a percorso speciale.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_TITLE_CHAIN_INCONSISTENCY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Catena provenienza incoerente','Catena provenienza incoerente','INTERNAL','PROFESSIONAL_REQUIRED','critical','{"op":"eq","path":"ownership.titleChainStatus","value":"INCONSISTENT"}'::jsonb,'{"code":"TITLE_CHAIN_INCONSISTENCY","message":"Non dichiarare titolarit\u00e0 verificata; escalation notarile.","blockProgress":true,"escalationTo":"NOTARY"}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_TRANSCRIPTION_REVIEW_MISSING',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'ENCUMBRANCES','PHASE_02_OWNERSHIP_TITLE','Verifica pubblicità immobiliare mancante','Verifica pubblicità immobiliare mancante','INTERNAL','REVIEW','blocking','{"op":"neq","path":"ownership.transcriptionReviewStatus","value":"COMPLETED"}'::jsonb,'{"code":"TRANSCRIPTION_REVIEW_REQUIRED","message":"Completare verifica formalit\u00e0.","blockProgress":true}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
union all
select 'P02_OWNERSHIP_READY',(select id from wf),(select id from public.guimmia_brain_workflow_steps where workflow_id=(select id from wf) and code='P02'),'OWNERSHIP_TITLE','PHASE_02_OWNERSHIP_TITLE','Titolarità pronta','Titolarità pronta','INTERNAL','AUTO','info','{"op":"all","conditions":[{"op":"eq","path":"ownership.titleDocumentStatus","value":"ACQUIRED"},{"op":"eq","path":"ownership.holdersStatus","value":"RECONCILED"},{"op":"eq","path":"ownership.transcriptionReviewStatus","value":"COMPLETED"},{"op":"eq","path":"ownership.specialCaseStatus","value":"RESOLVED_OR_NOT_APPLICABLE"}]}'::jsonb,'{"code":"OWNERSHIP_PHASE_CAN_CLOSE","message":"Gate minimi completati.","blockProgress":false}'::jsonb,'[]'::jsonb,'{}'::jsonb,'{}'::jsonb,1,true
on conflict(code,version) do update set workflow_id=excluded.workflow_id,step_id=excluded.step_id,module=excluded.module,phase_code=excluded.phase_code,title=excluded.title,description=excluded.description,stability=excluded.stability,decision_level=excluded.decision_level,severity=excluded.severity,condition_definition=excluded.condition_definition,outcome_definition=excluded.outcome_definition,freshness_policy=excluded.freshness_policy,active=true,updated_at=now();
