-- V76.3 catalog + requirement definitions

insert into public.guimmia_brain_document_catalog_v2(code,label,category,sensitivity,extraction_profile,description) values
('IDENTITY_DOCUMENT','Documento di identità','IDENTITY','HIGH','identity-v2','Documento identificativo del soggetto.'),
('TAX_CODE_DOCUMENT','Codice fiscale / tessera sanitaria','IDENTITY','HIGH','tax-code-v1','Documento di supporto all''identificazione fiscale quando necessario al processo.'),
('MANDATE','Mandato / incarico','MANDATE','HIGH','contract-v2','Incarico professionale firmato e versionato.'),
('PRIVACY_ACK','Informativa / presa visione privacy','MANDATE','HIGH','privacy-ack-v1','Tracciato di informativa/accettazione secondo policy corrente.'),
('AML_RECORD','Evidenza processo AML','MANDATE','HIGH','aml-record-v1','Evidenza del processo AML separata dai documenti di vendita.'),
('TITLE_DEED','Atto di provenienza','TITLE','HIGH','title-deed-v2','Titolo usato per riconciliare titolari e diritti.'),
('LAND_REGISTRY_INSPECTION','Ispezione / formalità registri immobiliari','REGISTRY','HIGH','land-registry-v1','Evidenza di pubblicità immobiliare/formalità da usare nei moduli dedicati.'),
('CADASTRAL_REPORT','Visura catastale','CADASTRAL','PERSONAL','cadastre-report-v2','Dati catastali dell''unità.'),
('HISTORICAL_CADASTRAL_REPORT','Visura catastale storica','CADASTRAL','PERSONAL','cadastre-history-v1','Storico catastale quando utile al controllo.'),
('CADASTRAL_PLAN','Planimetria catastale','CADASTRAL','PERSONAL','cadastre-plan-v2','Rappresentazione catastale da instradare a P04.'),
('URBAN_ACCESS_REQUEST','Accesso atti / richiesta documenti urbanistici','URBAN','PERSONAL','urban-access-v1','Richiesta/ricevuta di accesso atti quando i titoli non sono disponibili.'),
('URBAN_TITLES','Titoli e pratiche edilizie','URBAN','PERSONAL','urban-title-v2','Documentazione urbanistica disponibile; sufficienza valutata in P04.'),
('AGIBILITY','Agibilità / documentazione collegata','URBAN','PERSONAL','agibility-v2','Documentazione relativa all''agibilità quando presente/rilevante.'),
('TECHNICAL_REPORT','Relazione tecnica','URBAN','PERSONAL','technical-report-v2','Relazione prodotta da tecnico abilitato quando prevista dal processo.'),
('APE','APE','ENERGY','PERSONAL','ape-v2','Attestato energetico quando il ruleset corrente ne determina l''applicabilità.'),
('CONDOMINIUM_ADMIN_CERT','Attestazione / situazione amministratore','CONDOMINIUM','HIGH','condo-admin-v1','Documentazione amministratore relativa a spese/situazione contabile quando acquisita.'),
('CONDOMINIUM_MINUTES','Verbali condominiali','CONDOMINIUM','PERSONAL','condo-minutes-v2','Verbali rilevanti disponibili.'),
('CONDOMINIUM_RULES','Regolamento condominiale','CONDOMINIUM','PERSONAL','condo-rules-v1','Regolamento quando utile alla pratica.'),
('CONDOMINIUM_EXPENSES','Prospetto spese / lavori','CONDOMINIUM','HIGH','condo-expenses-v1','Spese ordinarie/straordinarie e lavori dichiarati/documentati.'),
('LEASE_CONTRACT','Contratto di locazione','LEASE','HIGH','lease-v2','Contratto e allegati se immobile locato.'),
('TENANT_NOTICES','Comunicazioni rilevanti al conduttore','LEASE','HIGH','tenant-notice-v1','Comunicazioni utili al percorso di vendita quando esistono.'),
('MORTGAGE_STATEMENT','Documentazione mutuo / debito residuo','FINANCE','HIGH','mortgage-v2','Documentazione sul finanziamento collegato all''immobile.'),
('MORTGAGE_PAYOFF_QUOTE','Conteggio estintivo / documento banca','FINANCE','HIGH','mortgage-payoff-v1','Documento bancario quando richiesto nel percorso di estinzione.'),
('SUCCESSION_DECLARATION','Documentazione successoria','TITLE','HIGH','succession-v2','Documentazione della provenienza successoria.'),
('SUCCESSION_ACCEPTANCE_EVIDENCE','Accettazione / trascrizione collegata alla successione','REGISTRY','HIGH','succession-acceptance-v1','Evidenza da instradare alla verifica notarile nei casi pertinenti.'),
('DONATION_DEED','Atto di donazione','TITLE','HIGH','donation-v2','Atto di provenienza donativa.'),
('POWER_OF_ATTORNEY','Procura / poteri','TITLE','HIGH','authority-v2','Documento dei poteri di chi agisce per altri.'),
('COMPANY_AUTHORITY_DOCS','Documenti società / poteri','COMPANY','HIGH','company-authority-v2','Documenti della persona giuridica e del rappresentante.'),
('TAX_BONUS_DOCS','Documentazione interventi agevolati','TAX','HIGH','tax-bonus-v2','Documentazione storica che può attivare verifiche fiscali correnti.')
on conflict(code) do update set label=excluded.label,category=excluded.category,sensitivity=excluded.sensitivity,extraction_profile=excluded.extraction_profile,description=excluded.description,active=true,updated_at=now();

insert into public.guimmia_brain_document_requirement_defs_v2(workflow_slug,phase_code,requirement_key,document_code,requirement_level,exit_policy,reason,condition_definition,legal_ruleset_key,professional_type,version) values
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_TITLE_DEED','TITLE_DEED','CORE','RECEIVED','Atto di provenienza necessario come evidenza strutturale del fascicolo.','{}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_CADASTRAL_REPORT','CADASTRAL_REPORT','CORE','ROUTED','Visura da acquisire/instradare prima della fase catastale.','{}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_CADASTRAL_PLAN','CADASTRAL_PLAN','CORE','ROUTED','Planimetria da acquisire/instradare a P04.','{}'::jsonb,null,'TECHNICIAN',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_URBAN_TITLES_OR_ACCESS','URBAN_TITLES','CORE','ROUTED','Titoli disponibili o accesso atti devono essere instradati alla verifica tecnica.','{}'::jsonb,null,'TECHNICIAN',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_LAND_REGISTRY','LAND_REGISTRY_INSPECTION','CORE','ROUTED','Formalità/pubblicità immobiliare devono essere instradate al controllo dedicato.','{}'::jsonb,null,'NOTARY',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_APE','APE','CONDITIONAL','ROUTED','Applicabilità determinata dal ruleset corrente.','{"op": "eq", "path": "documents.apeRequired", "value": true}'::jsonb,'ITALY_APE',null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_CONDO_ADMIN','CONDOMINIUM_ADMIN_CERT','CONDITIONAL','ROUTED','Unità in condominio: instradare documentazione amministratore.','{"op": "eq", "path": "property.isCondominium", "value": true}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_CONDO_MINUTES','CONDOMINIUM_MINUTES','CONDITIONAL','ROUTED','Unità in condominio: raccogliere verbali rilevanti disponibili.','{"op": "eq", "path": "property.isCondominium", "value": true}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_CONDO_EXPENSES','CONDOMINIUM_EXPENSES','CONDITIONAL','ROUTED','Unità in condominio: spese/lavori devono avere una fonte documentale o richiesta aperta.','{"op": "eq", "path": "property.isCondominium", "value": true}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_LEASE','LEASE_CONTRACT','CONDITIONAL','RECEIVED','Immobile locato: contratto necessario per il routing corretto.','{"op": "eq", "path": "property.occupancy", "value": "LEASED"}'::jsonb,null,null,1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_MORTGAGE','MORTGAGE_STATEMENT','CONDITIONAL','ROUTED','Mutuo attivo: raccogliere/instradare documentazione banca.','{"op": "eq", "path": "finance.activeMortgage", "value": true}'::jsonb,null,'BANK',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_MORTGAGE_PAYOFF','MORTGAGE_PAYOFF_QUOTE','CONDITIONAL','ROUTED','Se è previsto percorso di estinzione, instradare il conteggio banca quando richiesto dal workflow.','{"op": "eq", "path": "finance.payoffQuoteRequired", "value": true}'::jsonb,null,'BANK',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_SUCCESSION','SUCCESSION_DECLARATION','CONDITIONAL','RECEIVED','Provenienza successoria: acquisire documentazione di base.','{"op": "eq", "path": "ownership.originType", "value": "SUCCESSION"}'::jsonb,null,'NOTARY',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_SUCCESSION_ACCEPTANCE','SUCCESSION_ACCEPTANCE_EVIDENCE','CONDITIONAL','ROUTED','Nei casi indicati dal professionista/ruleset, instradare evidenza di accettazione/trascrizione.','{"op": "eq", "path": "ownership.successionAcceptanceEvidenceRequired", "value": true}'::jsonb,null,'NOTARY',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_DONATION','DONATION_DEED','CONDITIONAL','RECEIVED','Provenienza donativa: acquisire atto.','{"op": "eq", "path": "ownership.originType", "value": "DONATION"}'::jsonb,null,'NOTARY',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_POA','POWER_OF_ATTORNEY','CONDITIONAL','RECEIVED','Rappresentanza: acquisire evidenza dei poteri.','{"op": "eq", "path": "ownership.representationUsed", "value": true}'::jsonb,null,'AGENT',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_COMPANY_AUTH','COMPANY_AUTHORITY_DOCS','CONDITIONAL','RECEIVED','Venditore società/ente: acquisire documenti e poteri.','{"op": "eq", "path": "client.type", "value": "LEGAL_ENTITY"}'::jsonb,null,'LAWYER',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_TAX_BONUS','TAX_BONUS_DOCS','CONDITIONAL','ROUTED','Storia di interventi agevolati: raccogliere documenti senza derivare fiscalità dal manuale.','{"op": "eq", "path": "tax.superbonusOrArticle119History", "value": true}'::jsonb,'ITALY_REAL_ESTATE_TAX','ACCOUNTANT',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_TECHNICAL_REPORT','TECHNICAL_REPORT','PROFESSIONAL','ROUTED','Se P04 richiede relazione tecnica, aprire routing al professionista.','{"op": "eq", "path": "technical.reportRequired", "value": true}'::jsonb,'ITALY_URBAN_BUILDING','TECHNICIAN',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_TENANT_NOTICE','TENANT_NOTICES','CONDITIONAL','ROUTED','Se il workflow determina una comunicazione rilevante al conduttore, instradarla.','{"op": "eq", "path": "lease.tenantNoticeRequired", "value": true}'::jsonb,'ITALY_REAL_ESTATE_TAX','AGENT',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_HISTORICAL_CADASTRE','HISTORICAL_CADASTRAL_REPORT','CONDITIONAL','ROUTED','Storico catastale quando richiesto dal tecnico/agente per riconciliare variazioni.','{"op": "eq", "path": "technical.historicalCadastreRequired", "value": true}'::jsonb,null,'TECHNICIAN',1),
('sale-private-apartment','PHASE_03_DOCUMENT_DOSSIER','REQ_URBAN_ACCESS','URBAN_ACCESS_REQUEST','CONDITIONAL','ROUTED','Se i titoli non sono nella disponibilità del cliente, tracciare richiesta/accesso atti.','{"op": "eq", "path": "technical.urbanAccessRequired", "value": true}'::jsonb,'ITALY_URBAN_BUILDING','TECHNICIAN',1)
on conflict(workflow_slug,phase_code,requirement_key,version) do update set document_code=excluded.document_code,requirement_level=excluded.requirement_level,exit_policy=excluded.exit_policy,reason=excluded.reason,condition_definition=excluded.condition_definition,legal_ruleset_key=excluded.legal_ruleset_key,professional_type=excluded.professional_type,active=true,updated_at=now();
