-- GUIMMIA V77.0 - hard guards and read models
create or replace function public.guimmia_v770_orchestrator_profile_guard() returns trigger language plpgsql as $$ declare ok boolean;begin select exists(select 1 from public.guimmia_online_agency_profile a where a.id=new.operating_agency_id and a.code='GUIMMIA' and a.singleton_key='GUIMMIA') into ok;if not ok or new.singleton_key<>'GUIMMIA_CENTRAL_ORCHESTRATOR' or new.version<>'77.0.0' then raise exception 'v770_single_guimmia_orchestrator_profile_required';end if;if new.human_authority_policy->>'aiMayApproveOrSign' is distinct from 'false' or new.human_authority_policy->>'aiMaySetPrice' is distinct from 'false' or new.human_authority_policy->>'aiMaySelectCandidate' is distinct from 'false' or new.human_authority_policy->>'unknownActionFailsClosed' is distinct from 'true' or new.human_authority_policy->>'executionRequiresExpectedCaseVersion' is distinct from 'true' then raise exception 'v770_human_authority_policy_cannot_be_weakened';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_orchestrator_profile_guard on public.guimmia_case_orchestrator_profiles;create trigger trg_guimmia_v770_orchestrator_profile_guard before insert or update on public.guimmia_case_orchestrator_profiles for each row execute function public.guimmia_v770_orchestrator_profile_guard();

create or replace function public.guimmia_v770_context_snapshot_guard() returns trigger language plpgsql as $$ declare ok boolean;begin select exists(select 1 from public.guimmia_case_orchestrator_profiles p where p.operating_agency_id=new.operating_agency_id and p.status='ACTIVE') into ok;if not ok then raise exception 'v770_active_guimmia_orchestrator_required';end if;if new.context_data='{}'::jsonb or new.context_fingerprint is null or length(new.context_fingerprint)<8 then raise exception 'v770_context_data_and_fingerprint_required';end if;if new.status='SNAPSHOT_READY' and (new.case_version<1 or new.current_phase is null or new.internal_owner_id is null) then raise exception 'v770_complete_case_snapshot_required';end if;if new.status='SUPERSEDED' and new.superseded_at is null then raise exception 'v770_superseded_timestamp_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_context_snapshot_guard on public.guimmia_case_context_snapshots;create trigger trg_guimmia_v770_context_snapshot_guard before insert or update on public.guimmia_case_context_snapshots for each row execute function public.guimmia_v770_context_snapshot_guard();

create or replace function public.guimmia_v770_fact_observation_guard() returns trigger language plpgsql as $$ begin if new.fact_path is null or new.source_type is null or new.content_hash is null then raise exception 'v770_fact_source_hash_required';end if;if new.status='READY' and (not new.verified or new.source_ref is null) then raise exception 'v770_ready_fact_requires_verified_source';end if;if new.valid_until is not null and new.valid_until<new.observed_at then raise exception 'v770_fact_validity_range_invalid';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_fact_observation_guard on public.guimmia_case_fact_observations;create trigger trg_guimmia_v770_fact_observation_guard before insert or update on public.guimmia_case_fact_observations for each row execute function public.guimmia_v770_fact_observation_guard();

create or replace function public.guimmia_v770_evidence_requirement_guard() returns trigger language plpgsql as $$ declare ready boolean;begin if new.status='READY' then select exists(select 1 from public.guimmia_case_fact_observations o where o.id=new.matched_observation_id and o.case_id=new.case_id and o.status='READY' and o.verified and (o.valid_until is null or o.valid_until>=now())) into ready;if not ready then raise exception 'v770_current_verified_observation_required';end if;end if;if new.status='WAIVED' and (new.waiver_actor_type not in('GUIMMIA','PROFESSIONAL') or new.waiver_actor_id is null or new.waiver_reason is null) then raise exception 'v770_human_evidence_waiver_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_evidence_requirement_guard on public.guimmia_case_evidence_requirements;create trigger trg_guimmia_v770_evidence_requirement_guard before insert or update on public.guimmia_case_evidence_requirements for each row execute function public.guimmia_v770_evidence_requirement_guard();

create or replace function public.guimmia_v770_readiness_guard() returns trigger language plpgsql as $$ begin if new.assessment_fingerprint is null or new.evidence_refs is null then raise exception 'v770_readiness_fingerprint_evidence_required';end if;if new.status='READY' and (new.readiness_score<100 or new.blocking_codes<>'[]'::jsonb) then raise exception 'v770_ready_requires_full_score_without_blocks';end if;if new.status='BLOCKED' and new.blocking_codes='[]'::jsonb then raise exception 'v770_blocked_readiness_reason_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_readiness_guard on public.guimmia_case_readiness_assessments;create trigger trg_guimmia_v770_readiness_guard before insert or update on public.guimmia_case_readiness_assessments for each row execute function public.guimmia_v770_readiness_guard();

create or replace function public.guimmia_v770_decision_run_guard() returns trigger language plpgsql as $$ begin if new.run_key is null or new.input_fingerprint is null then raise exception 'v770_run_key_input_fingerprint_required';end if;if new.status in('DECIDED','BLOCKED','COMMITTED','SUPERSEDED') and new.decided_at is null then raise exception 'v770_decision_timestamp_required';end if;if new.status='COMMITTED' and new.committed_at is null then raise exception 'v770_commit_timestamp_required';end if;if new.status='FAILED' and new.failure_code is null then raise exception 'v770_failure_code_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_decision_run_guard on public.guimmia_case_decision_runs;create trigger trg_guimmia_v770_decision_run_guard before insert or update on public.guimmia_case_decision_runs for each row execute function public.guimmia_v770_decision_run_guard();

create or replace function public.guimmia_v770_decision_input_guard() returns trigger language plpgsql as $$ begin if new.context_fingerprint is null or new.input_hash is null or new.findings is null or new.candidate_actions is null then raise exception 'v770_complete_decision_input_required';end if;if jsonb_typeof(new.findings)<>'array' or jsonb_typeof(new.candidate_actions)<>'array' then raise exception 'v770_decision_input_arrays_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_decision_input_guard on public.guimmia_case_decision_inputs;create trigger trg_guimmia_v770_decision_input_guard before insert or update on public.guimmia_case_decision_inputs for each row execute function public.guimmia_v770_decision_input_guard();

create or replace function public.guimmia_v770_rule_evaluation_guard() returns trigger language plpgsql as $$ begin if new.rule_code is null or new.phase_code is null or new.evaluation_hash is null then raise exception 'v770_rule_evaluation_identity_required';end if;if new.matched and new.reason_codes='[]'::jsonb then raise exception 'v770_matched_rule_reason_required';end if;if new.severity in('blocking','critical') and new.matched and new.evidence_refs='[]'::jsonb then raise exception 'v770_blocking_rule_evidence_reference_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_rule_evaluation_guard on public.guimmia_case_rule_evaluations;create trigger trg_guimmia_v770_rule_evaluation_guard before insert or update on public.guimmia_case_rule_evaluations for each row execute function public.guimmia_v770_rule_evaluation_guard();

create or replace function public.guimmia_v770_decision_output_guard() returns trigger language plpgsql as $$ begin if new.output_hash is null or new.customer_explanation is null or new.internal_explanation is null then raise exception 'v770_explainable_output_required';end if;if new.status='READY' and new.selected_action is null then raise exception 'v770_ready_output_action_required';end if;if new.status in('WAITING_HUMAN','WAITING_PROFESSIONAL') and not new.handoff_required then raise exception 'v770_waiting_authority_handoff_required';end if;if new.ai_execution_allowed and (new.status<>'READY' or new.handoff_required or new.customer_confirmation_required) then raise exception 'v770_ai_execution_state_invalid';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_decision_output_guard on public.guimmia_case_decision_outputs;create trigger trg_guimmia_v770_decision_output_guard before insert or update on public.guimmia_case_decision_outputs for each row execute function public.guimmia_v770_decision_output_guard();

create or replace function public.guimmia_v770_next_action_guard() returns trigger language plpgsql as $$ begin if new.action_fingerprint is null or new.reason_codes='[]'::jsonb then raise exception 'v770_action_fingerprint_reason_required';end if;if new.authority_class='AI_AUTONOMOUS' and new.owner_type<>'AI' then raise exception 'v770_ai_action_owner_mismatch';end if;if new.authority_class='CUSTOMER_CONFIRMATION' and (new.owner_type<>'CUSTOMER' or not new.customer_confirmation_required) then raise exception 'v770_customer_confirmation_action_invalid';end if;if new.status='COMPLETED' and (new.completed_by_actor_type is null or new.completed_by is null or new.completed_at is null) then raise exception 'v770_action_completion_evidence_required';end if;if new.status='COMPLETED' and new.authority_class in('CUSTOMER_CONFIRMATION','GUIMMIA_HUMAN','QUALIFIED_PROFESSIONAL') and new.completed_by_actor_type='AI' then raise exception 'v770_ai_cannot_complete_material_action';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_next_action_guard on public.guimmia_case_next_actions;create trigger trg_guimmia_v770_next_action_guard before insert or update on public.guimmia_case_next_actions for each row execute function public.guimmia_v770_next_action_guard();

create or replace function public.guimmia_v770_handoff_guard() returns trigger language plpgsql as $$ begin if new.reason_codes='[]'::jsonb or new.context_fingerprint is null or new.context_summary='{}'::jsonb then raise exception 'v770_handoff_context_reason_required';end if;if new.authority_class='QUALIFIED_PROFESSIONAL' and new.requested_owner_type<>'PROFESSIONAL' then raise exception 'v770_professional_handoff_owner_required';end if;if new.authority_class='GUIMMIA_HUMAN' and new.requested_owner_type<>'GUIMMIA' then raise exception 'v770_guimmia_handoff_owner_required';end if;if new.status in('ASSIGNED','ACCEPTED','RESOLVED') and new.requested_owner_id is null then raise exception 'v770_handoff_human_owner_required';end if;if new.status='RESOLVED' and (new.resolved_at is null or new.resolution is null) then raise exception 'v770_handoff_resolution_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_handoff_guard on public.guimmia_case_handoff_requests;create trigger trg_guimmia_v770_handoff_guard before insert or update on public.guimmia_case_handoff_requests for each row execute function public.guimmia_v770_handoff_guard();

create or replace function public.guimmia_v770_explanation_guard() returns trigger language plpgsql as $$ begin if new.content_hash is null or length(trim(new.content))<20 then raise exception 'v770_explanation_content_hash_required';end if;if new.audience='CUSTOMER' and (not new.plain_language or not new.redacted) then raise exception 'v770_customer_explanation_plain_and_redacted_required';end if;if new.reason_codes='[]'::jsonb then raise exception 'v770_explanation_reason_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_explanation_guard on public.guimmia_case_explanations;create trigger trg_guimmia_v770_explanation_guard before insert or update on public.guimmia_case_explanations for each row execute function public.guimmia_v770_explanation_guard();

create or replace function public.guimmia_v770_lock_guard() returns trigger language plpgsql as $$ begin if new.lock_token is null or new.owner_instance is null or new.expires_at<=new.locked_at then raise exception 'v770_valid_orchestrator_lock_required';end if;if new.released_at is not null and new.released_at<new.locked_at then raise exception 'v770_lock_release_timestamp_invalid';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_lock_guard on public.guimmia_case_orchestrator_locks;create trigger trg_guimmia_v770_lock_guard before insert or update on public.guimmia_case_orchestrator_locks for each row execute function public.guimmia_v770_lock_guard();

create or replace function public.guimmia_v770_playbook_guard() returns trigger language plpgsql as $$ declare expected_code text;begin expected_code:=case new.operation_type when 'SALE' then 'SALE_V1' when 'RENT_LONG_TERM' then 'RENT_LONG_TERM_V1' when 'RENT_TRANSITORY' then 'RENT_TRANSITORY_V1' when 'RENT_STUDENT' then 'RENT_STUDENT_V1' when 'RENT_TOURIST_SHORT' then 'RENT_TOURIST_SHORT_V1' end;if new.playbook_code is distinct from expected_code or new.playbook_version<>1 then raise exception 'v770_operation_playbook_mismatch';end if;if new.current_stage is null or new.context_fingerprint is null then raise exception 'v770_playbook_stage_context_required';end if;if new.status='COMPLETED' and new.progress_percent<>100 then raise exception 'v770_completed_playbook_requires_full_progress';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_playbook_guard on public.guimmia_case_playbook_instances;create trigger trg_guimmia_v770_playbook_guard before insert or update on public.guimmia_case_playbook_instances for each row execute function public.guimmia_v770_playbook_guard();

create or replace function public.guimmia_v770_stage_transition_guard() returns trigger language plpgsql as $$ begin if new.from_stage=new.to_stage or new.transition_fingerprint is null then raise exception 'v770_distinct_stage_transition_required';end if;if new.status in('VERIFIED','APPLIED') and (new.prerequisites<>'[]'::jsonb or new.evidence_refs='[]'::jsonb or new.verified_at is null) then raise exception 'v770_verified_transition_prerequisites_evidence_required';end if;if new.to_stage in('SELECTION','CONTRACT','CLOSING','CHECK_IN') and new.status='APPLIED' and (new.approved_by_actor_type is null or new.approved_by_actor_id is null) then raise exception 'v770_material_transition_human_approval_required';end if;if new.status='APPLIED' and new.applied_at is null then raise exception 'v770_applied_transition_timestamp_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_stage_transition_guard on public.guimmia_case_stage_transitions;create trigger trg_guimmia_v770_stage_transition_guard before insert or update on public.guimmia_case_stage_transitions for each row execute function public.guimmia_v770_stage_transition_guard();

create or replace function public.guimmia_v770_execution_command_guard() returns trigger language plpgsql as $$ declare latest_version integer;actor_type text;verified boolean;begin select max(case_version) into latest_version from public.guimmia_case_context_snapshots where case_id=new.case_id and status='SNAPSHOT_READY';if latest_version is null or new.expected_case_version<>latest_version then raise exception 'v770_command_expected_case_version_conflict';end if;if new.command_id is null or new.idempotency_key is null or new.input_fingerprint is null then raise exception 'v770_command_identity_required';end if;if new.executable and (new.mode<>'COMMIT' or new.status not in('VALIDATED','EXECUTING')) then raise exception 'v770_executable_command_requires_validated_commit';end if;if new.executable and new.blocked_reason_codes<>'[]'::jsonb then raise exception 'v770_executable_command_cannot_have_blocks';end if;if new.authority_class='AI_AUTONOMOUS' and new.action_type not in('REQUEST_MISSING_INFORMATION','PREPARE_SERVICE_SUMMARY','PREPARE_MANDATE_DRAFT','PREPARE_PROPERTY_DOSSIER','PREPARE_LISTING_DRAFT','QUALIFY_LEAD_DATA','PROPOSE_AVAILABLE_SLOTS','PREPARE_OFFER_SUMMARY','PREPARE_CONTRACT_DRAFT','PREPARE_CLOSING_CHECKLIST','UPDATE_CUSTOMER_PROGRESS','CREATE_REMINDER','SUMMARIZE_CASE','REQUEST_DOCUMENT','PREPARE_SCREENING_SUMMARY','PREPARE_HANDOVER_CHECKLIST','PREPARE_BOOKING_SUMMARY','PREPARE_CHECKIN_CHECKLIST','PREPARE_GUEST_REPORTING_DRAFT','PREPARE_TURNOVER_PLAN','REQUEST_TRANSITORY_REASON','REQUEST_STUDENT_EVIDENCE','REQUEST_TOURIST_COMPLIANCE_EVIDENCE') then raise exception 'v770_unknown_or_nonallowlisted_ai_command_blocked';end if;if new.executable and new.authority_class<>'AI_AUTONOMOUS' then actor_type:=new.authority_evidence->>'actorType';verified:=coalesce((new.authority_evidence->>'verified')::boolean,false);if not verified or new.authority_evidence->>'caseId' is distinct from new.case_id::text or (new.authority_evidence->>'caseVersion')::integer is distinct from new.expected_case_version or new.authority_evidence->>'actionType' is distinct from new.action_type or new.authority_evidence->>'inputFingerprint' is distinct from new.input_fingerprint or (new.authority_evidence->>'decidedAt')::timestamptz>now() or (new.authority_class='CUSTOMER_CONFIRMATION' and actor_type<>'CUSTOMER') or (new.authority_class='GUIMMIA_HUMAN' and actor_type<>'GUIMMIA') or (new.authority_class='QUALIFIED_PROFESSIONAL' and actor_type<>'PROFESSIONAL') then raise exception 'v770_verified_bound_authority_evidence_required';end if;end if;if new.status='SUCCEEDED' and (new.result is null or new.result_hash is null or new.executed_at is null) then raise exception 'v770_success_result_hash_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_execution_command_guard on public.guimmia_case_execution_commands;create trigger trg_guimmia_v770_execution_command_guard before insert or update on public.guimmia_case_execution_commands for each row execute function public.guimmia_v770_execution_command_guard();

create or replace function public.guimmia_v770_question_request_guard() returns trigger language plpgsql as $$ begin if length(trim(new.prompt))<12 or length(trim(new.why_it_matters))<12 then raise exception 'v770_customer_question_plain_prompt_and_why_required';end if;if new.prompt like '%guimmia.orchestrator.%' then raise exception 'v770_customer_question_cannot_expose_internal_fact_path';end if;if new.status='ANSWERED' and (new.response is null or new.answered_by_actor_type is null or new.answered_by_actor_id is null or new.answered_at is null) then raise exception 'v770_question_answer_evidence_required';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_question_request_guard on public.guimmia_case_question_requests;create trigger trg_guimmia_v770_question_request_guard before insert or update on public.guimmia_case_question_requests for each row execute function public.guimmia_v770_question_request_guard();

create or replace function public.guimmia_v770_material_authority_guard() returns trigger language plpgsql as $$ declare action_type text;authority text;begin if new.selected_action is null then return new;end if;action_type:=new.selected_action->>'actionType';authority:=new.selected_action->>'authority';if action_type is null or authority is null then raise exception 'v770_selected_action_type_authority_required';end if;if action_type in('APPROVE_DOCUMENT','SIGN_DOCUMENT','SET_PRICE','COUNTEROFFER','SELECT_CANDIDATE','ACCEPT_OFFER','REJECT_OFFER','APPROVE_LISTING','CLOSE_CASE') and authority is distinct from 'GUIMMIA_HUMAN' then raise exception 'v770_material_action_requires_guimmia_human';end if;if action_type in('ISSUE_LEGAL_CONCLUSION','ISSUE_TAX_CONCLUSION','ISSUE_TECHNICAL_CONCLUSION','CERTIFY_COMPLIANCE') and authority is distinct from 'QUALIFIED_PROFESSIONAL' then raise exception 'v770_professional_conclusion_requires_qualified_professional';end if;if action_type in('BOOK_APPOINTMENT','CONFIRM_APPOINTMENT','SUBMIT_APPLICATION','SEND_OFFER','PUBLISH_LISTING') and authority is distinct from 'CUSTOMER_CONFIRMATION' then raise exception 'v770_customer_confirmation_authority_required';end if;if new.ai_execution_allowed and authority is distinct from 'AI_AUTONOMOUS' then raise exception 'v770_ai_execution_only_for_autonomous_action';end if;if new.ai_execution_allowed and action_type not in('REQUEST_MISSING_INFORMATION','PREPARE_SERVICE_SUMMARY','PREPARE_MANDATE_DRAFT','PREPARE_PROPERTY_DOSSIER','PREPARE_LISTING_DRAFT','QUALIFY_LEAD_DATA','PROPOSE_AVAILABLE_SLOTS','PREPARE_OFFER_SUMMARY','PREPARE_CONTRACT_DRAFT','PREPARE_CLOSING_CHECKLIST','UPDATE_CUSTOMER_PROGRESS','CREATE_REMINDER','SUMMARIZE_CASE','REQUEST_DOCUMENT','PREPARE_SCREENING_SUMMARY','PREPARE_HANDOVER_CHECKLIST','PREPARE_BOOKING_SUMMARY','PREPARE_CHECKIN_CHECKLIST','PREPARE_GUEST_REPORTING_DRAFT','PREPARE_TURNOVER_PLAN','REQUEST_TRANSITORY_REASON','REQUEST_STUDENT_EVIDENCE','REQUEST_TOURIST_COMPLIANCE_EVIDENCE') then raise exception 'v770_unknown_or_nonallowlisted_ai_action_blocked';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_material_authority_guard on public.guimmia_case_decision_outputs;create trigger trg_guimmia_v770_material_authority_guard before insert or update on public.guimmia_case_decision_outputs for each row execute function public.guimmia_v770_material_authority_guard();

create or replace function public.guimmia_v770_event_immutable() returns trigger language plpgsql as $$ declare expected_previous text;begin if tg_op in('UPDATE','DELETE') then raise exception 'V77.0 orchestrator events are immutable; append a compensating event';end if;if new.event_hash is null or new.event_type is null or new.actor_type is null then raise exception 'v770_event_identity_hash_required';end if;if new.actor_type<>'SYSTEM' and new.actor_id is null then raise exception 'v770_event_actor_required';end if;select event_hash into expected_previous from public.guimmia_case_orchestrator_events where case_id=new.case_id order by id desc limit 1;if expected_previous is distinct from new.previous_event_hash then raise exception 'v770_event_chain_broken';end if;return new;end $$;
drop trigger if exists trg_guimmia_v770_event_immutable on public.guimmia_case_orchestrator_events;create trigger trg_guimmia_v770_event_immutable before insert or update or delete on public.guimmia_case_orchestrator_events for each row execute function public.guimmia_v770_event_immutable();

create or replace function public.guimmia_case_orchestrator_summary(p_case_id uuid) returns table(case_id uuid,case_version integer,operation_type text,current_phase text,context_status text,readiness_status text,decision_status text,next_action text,next_action_authority text,handoff_status text,last_decided_at timestamptz) language sql stable security definer set search_path=public as $$ select c.case_id,c.case_version,c.operation_type,c.current_phase,c.status,(select r.status from public.guimmia_case_readiness_assessments r where r.case_id=c.case_id order by r.evaluated_at desc limit 1),(select o.status from public.guimmia_case_decision_outputs o where o.case_id=c.case_id order by o.decided_at desc limit 1),(select a.title from public.guimmia_case_next_actions a where a.case_id=c.case_id and a.status in('PROPOSED','READY','IN_PROGRESS','BLOCKED') order by case a.priority when 'CRITICAL' then 0 when 'HIGH' then 1 when 'NORMAL' then 2 else 3 end,a.due_at nulls last limit 1),(select a.authority_class from public.guimmia_case_next_actions a where a.case_id=c.case_id and a.status in('PROPOSED','READY','IN_PROGRESS','BLOCKED') order by case a.priority when 'CRITICAL' then 0 when 'HIGH' then 1 when 'NORMAL' then 2 else 3 end,a.due_at nulls last limit 1),(select h.status from public.guimmia_case_handoff_requests h where h.case_id=c.case_id and h.status not in('RESOLVED','CANCELLED') order by h.created_at desc limit 1),(select d.decided_at from public.guimmia_case_decision_runs d where d.case_id=c.case_id and d.decided_at is not null order by d.decided_at desc limit 1) from public.guimmia_case_context_snapshots c where c.case_id=p_case_id order by c.case_version desc,c.computed_at desc limit 1;$$;revoke all on function public.guimmia_case_orchestrator_summary(uuid) from public;

create or replace function public.guimmia_case_next_action_queue_v770(p_operating_agency_id uuid default null) returns table(action_id uuid,case_id uuid,title text,priority text,authority_class text,owner_type text,status text,due_at timestamptz,customer_visible boolean) language sql stable security definer set search_path=public as $$ select a.id,a.case_id,a.title,a.priority,a.authority_class,a.owner_type,a.status,a.due_at,a.customer_visible from public.guimmia_case_next_actions a where a.status in('PROPOSED','READY','IN_PROGRESS','BLOCKED') and (p_operating_agency_id is null or a.operating_agency_id=p_operating_agency_id) order by case a.priority when 'CRITICAL' then 0 when 'HIGH' then 1 when 'NORMAL' then 2 else 3 end,a.due_at nulls last;$$;revoke all on function public.guimmia_case_next_action_queue_v770(uuid) from public;

create or replace function public.guimmia_case_handoff_queue_v770(p_operating_agency_id uuid default null) returns table(handoff_id uuid,case_id uuid,authority_class text,requested_owner_type text,requested_owner_id uuid,status text,due_at timestamptz,reason_codes jsonb) language sql stable security definer set search_path=public as $$ select h.id,h.case_id,h.authority_class,h.requested_owner_type,h.requested_owner_id,h.status,h.due_at,h.reason_codes from public.guimmia_case_handoff_requests h where h.status not in('RESOLVED','CANCELLED') and (p_operating_agency_id is null or h.operating_agency_id=p_operating_agency_id) order by h.due_at;$$;revoke all on function public.guimmia_case_handoff_queue_v770(uuid) from public;

create or replace function public.guimmia_customer_case_explanation_v770(p_case_id uuid) returns table(case_id uuid,decision_status text,explanation text,next_action text,customer_confirmation_required boolean,updated_at timestamptz) language sql stable security definer set search_path=public as $$ select o.case_id,o.status,e.content,(o.selected_action->>'title'),o.customer_confirmation_required,o.decided_at from public.guimmia_case_decision_outputs o join public.guimmia_case_explanations e on e.run_id=o.run_id and e.audience='CUSTOMER' where o.case_id=p_case_id order by o.decided_at desc limit 1;$$;revoke all on function public.guimmia_customer_case_explanation_v770(uuid) from public;

create or replace function public.guimmia_case_decision_audit_v770(p_case_id uuid) returns table(run_id uuid,case_id uuid,input_fingerprint text,decision_status text,confidence numeric,reason_codes jsonb,rule_refs jsonb,evidence_refs jsonb,output_hash text,decided_at timestamptz) language sql stable security definer set search_path=public as $$ select d.id,d.case_id,d.input_fingerprint,o.status,d.confidence,o.reason_codes,o.rule_refs,o.evidence_refs,o.output_hash,o.decided_at from public.guimmia_case_decision_runs d join public.guimmia_case_decision_outputs o on o.run_id=d.id where d.case_id=p_case_id order by o.decided_at desc;$$;revoke all on function public.guimmia_case_decision_audit_v770(uuid) from public;

create or replace function public.guimmia_customer_required_questions_v770(p_case_id uuid) returns table(question_code text,prompt text,why_it_matters text,sequence_no integer,status text,created_at timestamptz) language sql stable security definer set search_path=public as $$ select q.question_code,q.prompt,q.why_it_matters,q.sequence_no,q.status,q.created_at from public.guimmia_case_question_requests q where q.case_id=p_case_id and q.status='OPEN' order by q.created_at desc,q.sequence_no limit 3;$$;revoke all on function public.guimmia_customer_required_questions_v770(uuid) from public;

create or replace function public.guimmia_case_playbook_progress_v770(p_case_id uuid) returns table(playbook_code text,operation_type text,current_stage text,status text,progress_percent numeric,stage_started_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path=public as $$ select p.playbook_code,p.operation_type,p.current_stage,p.status,p.progress_percent,p.stage_started_at,p.updated_at from public.guimmia_case_playbook_instances p where p.case_id=p_case_id order by p.updated_at desc limit 1;$$;revoke all on function public.guimmia_case_playbook_progress_v770(uuid) from public;
