export type Operation = "sale" | "rent";
export type ListingMarket = "buy" | "rent" | "room" | "holiday";
export type ListingKind = "whole_property" | "room";
export type RoomType = "single" | "double" | "shared";
export type OccupantProfile = "student" | "worker";

export type AgencyListing = {
  id: string;
  slug: string;
  operation: Operation;
  listing_kind?: ListingKind;
  property_type: string;
  title: string;
  description: string;
  price_cents: number;
  rent_period: string | null;
  city: string;
  province: string | null;
  zone: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  rooms: number | null;
  surface_sqm: number | null;
  room_type?: RoomType | null;
  room_surface_sqm?: number | null;
  private_bathroom?: boolean | null;
  current_roommates_count?: number | null;
  current_household_summary?: string | null;
  accepted_occupant_profiles?: OccupantProfile[];
  available_from?: string | null;
  expenses_included?: boolean | null;
  floor: string | null;
  elevator: boolean | null;
  energy_class: string | null;
  features: string[];
  cover_image_url: string | null;
  visibility_tier: "standard" | "top";
  featured: boolean;
  published_at: string | null;
};
