import type { BrainRule } from "./types";
import { phase01Rules } from "./phases/phase01";
import { phase02Rules } from "./phases/phase02";
import { phase03Rules } from "./phases/phase03";
import { phase04Rules } from "./phases/phase04";
import { phaseR02Rules } from "./phases/phaseR02";
import { phaseR03Rules } from "./phases/phaseR03";
import { phaseR04Rules } from "./phases/phaseR04";
import { phase05Rules } from "./phases/phase05";
import { phaseR06Rules } from "./phases/phaseR06";
import { phaseR07Rules } from "./phases/phaseR07";
import { phaseR08Rules } from "./phases/phaseR08";
import { phaseR09Rules } from "./phases/phaseR09";
import { phaseR10Rules } from "./phases/phaseR10";
import { phaseR11Rules } from "./phases/phaseR11";
import { phaseT06Rules } from "./phases/phaseT06";
import { phaseT07Rules } from "./phases/phaseT07";
import { phaseT08Rules } from "./phases/phaseT08";
import { phaseT09Rules } from "./phases/phaseT09";
import { phaseP05Rules } from "./phases/phaseP05";
import { phaseP06Rules } from "./phases/phaseP06";
import { phaseP07Rules } from "./phases/phaseP07";
import { phaseP08Rules } from "./phases/phaseP08";
import { phaseP09Rules } from "./phases/phaseP09";
import { phaseP10Rules } from "./phases/phaseP10";
import { phaseP11Rules } from "./phases/phaseP11";
import { phaseP12Rules } from "./phases/phaseP12";
import { phaseP13Rules } from "./phases/phaseP13";
import { phaseP14Rules } from "./phases/phaseP14";
import { phaseP15Rules } from "./phases/phaseP15";
import { GUIMMIA_BRAIN_MODULES } from "./data/modules";
import { salePrivateApartmentGoldenPath, rentLongTermGoldenPath, rentTransitoryGoldenPath, rentStudentGoldenPath, rentTouristShortGoldenPath } from "./data/goldenPath";
import { knowledgeCards } from "./data/knowledgeCards";
import { rentalKnowledgeCards } from "./data/rentalKnowledgeCards";
import { operationalKnowledgeCards } from "./data/operationalKnowledgeCards";
import { saleOperationalKnowledgeCards } from "./data/saleOperationalKnowledgeCards";
import { phaseO01Rules } from "./phases/phaseO01";
import { phaseO02Rules } from "./phases/phaseO02";
import { phaseO03Rules } from "./phases/phaseO03";
import { phaseO04Rules } from "./phases/phaseO04";
import { phaseO05Rules } from "./phases/phaseO05";
import { phaseO06Rules } from "./phases/phaseO06";
import { phaseO07Rules } from "./phases/phaseO07";
import { phaseO08Rules } from "./phases/phaseO08";
import { phaseO09Rules } from "./phases/phaseO09";
import { phaseO10Rules } from "./phases/phaseO10";
import { phaseO11Rules } from "./phases/phaseO11";
import { phaseO12Rules } from "./phases/phaseO12";
import { phaseC01Rules } from "./phases/phaseC01";
import { phaseC02Rules } from "./phases/phaseC02";
import { phaseC03Rules } from "./phases/phaseC03";
import { agencyOperationalKnowledgeCards } from "./data/agencyOperationalKnowledgeCards";
import { phaseK01Rules } from "./phases/phaseK01";
import { phaseK02Rules } from "./phases/phaseK02";
import { phaseK03Rules } from "./phases/phaseK03";
import { phaseK04Rules } from "./phases/phaseK04";
import { phaseK05Rules } from "./phases/phaseK05";
import { phaseK06Rules } from "./phases/phaseK06";
import { caseOrchestratorKnowledgeCards } from "./data/caseOrchestratorKnowledgeCards";

export const brainRules: BrainRule[] = [...phase01Rules,...phase02Rules,...phase03Rules,...phase04Rules,...phaseR02Rules,...phaseR03Rules,...phaseR04Rules,...phase05Rules,...phaseR06Rules,...phaseR07Rules,...phaseR08Rules,...phaseR09Rules,...phaseR10Rules,...phaseR11Rules,...phaseT06Rules,...phaseT07Rules,...phaseT08Rules,...phaseT09Rules,...phaseP05Rules,...phaseP06Rules,...phaseP07Rules,...phaseP08Rules,...phaseP09Rules,...phaseP10Rules,...phaseP11Rules,...phaseP12Rules,...phaseP13Rules,...phaseP14Rules,...phaseP15Rules,...phaseO01Rules,...phaseO02Rules,...phaseO03Rules,...phaseO04Rules,...phaseO05Rules,...phaseO06Rules,...phaseO07Rules,...phaseO08Rules,...phaseO09Rules,...phaseO10Rules,...phaseO11Rules,...phaseO12Rules,...phaseC01Rules,...phaseC02Rules,...phaseC03Rules,...phaseK01Rules,...phaseK02Rules,...phaseK03Rules,...phaseK04Rules,...phaseK05Rules,...phaseK06Rules];
export const brainModules = GUIMMIA_BRAIN_MODULES;
export const brainWorkflows = [salePrivateApartmentGoldenPath,rentLongTermGoldenPath,rentTransitoryGoldenPath,rentStudentGoldenPath,rentTouristShortGoldenPath];
export const brainKnowledgeCards = [...knowledgeCards,...rentalKnowledgeCards,...operationalKnowledgeCards,...saleOperationalKnowledgeCards,...agencyOperationalKnowledgeCards,...caseOrchestratorKnowledgeCards];
export function getRulesForPhase(phase:string){return brainRules.filter(r=>r.phase===phase&&r.active)}
export function getKnowledgeByModule(module:string){return brainKnowledgeCards.filter(c=>c.module===module)}
